### ISSUE TITLE
macOS Nethermind.Blockchain.Test errors

### ISSUE THREAD

**Issue by matilote** [NethermindEth/nethermind#1016]
X **After_ending_does_not_update_total_or_current** [978ms]
  Error Message:
     Expected: greater than or equal to 14m
  But was:  9.038376948523430485842888906m

  Stack Trace:
     at Nethermind.Blockchain.Test.Synchronization.MeasuredProgressTests.After_ending_does_not_update_total_or_current() in /Users/runner/runners/2.160.2/work/nethermind/nethermind/src/Nethermind/Nethermind.Blockchain.Test/Synchronization/MeasuredProgressTests.cs:line 140

  X **Update_thrice_result_per_second** [354ms]
  Error Message:
     Expected: greater than or equal to 14m
  But was:  8.490550017830155037443325579m

  Stack Trace:
     at Nethermind.Blockchain.Test.Synchronization.MeasuredProgressTests.Update_thrice_result_per_second() in /Users/runner/runners/2.160.2/work/nethermind/nethermind/src/Nethermind/Nethermind.Blockchain.Test/Synchronization/MeasuredProgressTests.cs:line 118

  X **Update_twice_current_per_second** [120ms]
  Error Message:
     Expected: greater than or equal to 9m
  But was:  8.354847064524483879322589m

  Stack Trace:
     at Nethermind.Blockchain.Test.Synchronization.MeasuredProgressTests.Update_twice_current_per_second() in /Users/runner/runners/2.160.2/work/nethermind/nethermind/src/Nethermind/Nethermind.Blockchain.Test/Synchronization/MeasuredProgressTests.cs:line 93

  X **Update_twice_total_per_second** [143ms]
  Error Message:
     Expected: greater than or equal to 9m
  But was:  6.9963828700561809544465511331m

  Stack Trace:
     at Nethermind.Blockchain.Test.Synchronization.MeasuredProgressTests.Update_twice_total_per_second() in /Users/runner/runners/2.160.2/work/nethermind/nethermind/src/Nethermind/Nethermind.Blockchain.Test/Synchronization/MeasuredProgressTests.cs:line 82

**Comment by tkstanczak** [comment]
fixed / mostly fixed
