### ISSUE TITLE
Linux - Nethermind.Clique.Test errors

### ISSUE THREAD

**Issue by matilote** [NethermindEth/nethermind#1017]
A total of 1 test files matched the specified pattern.
  X **Creates_blocks_without_signals_from_block_tree** [2s 985ms]
  Error Message:
     0x942921b14f1b1c385cd7e0cc2ef7abe5598c8358 head number
  Expected: 1
  But was:  0

  Stack Trace:
     at Nethermind.Clique.Test.CliqueBlockProducerTests.On.AssertHeadBlockIs(PrivateKey nodeKey, Int64 number) in /home/runner/work/nethermind/nethermind/src/Nethermind/Nethermind.Clique.Test/CliqueBlockProducerTests.cs:line 290
   at Nethermind.Clique.Test.CliqueBlockProducerTests.Creates_blocks_without_signals_from_block_tree() in /home/runner/work/nethermind/nethermind/src/Nethermind/Nethermind.Clique.Test/CliqueBlockProducerTests.cs:line 751
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaitable)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

**Comment by tkstanczak** [comment]
fixed / mostly fixed, let us reopen on more issues
