### ISSUE TITLE
Loading receipts from storage - RLP

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1215]
2019-12-31 18:31:03.5994|DEBUG|15|Network.P2P.ZeroNettyP2PHandler|Error in communication with [Node|121.40.86.163:50240|Geth/v1.9.9-stable-01744997/linux-amd64/go1.13.5]: Nethermind.Core.Encoding.RlpException: Unexpected prefix of 130 when decoding Keccak at position 5 in the message of length 267 starting with f9010801825208b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0
   at Nethermind.Core.Encoding.RlpStream.DecodeKeccak() in /root/src/nethermind/src/Nethermind/Nethermind.Core/Encoding/RlpStream.cs:line 626
   at Nethermind.Core.Encoding.ReceiptDecoder.Decode(RlpStream rlpStream, RlpBehaviors rlpBehaviors) in /root/src/nethermind/src/Nethermind/Nethermind.Core/Encoding/ReceiptDecoder.cs:line 46
   at Nethermind.Blockchain.Receipts.PersistentReceiptStorage.Find(Keccak hash) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs:line 53
   at Nethermind.Blockchain.Synchronization.SyncServer.GetReceipts(IList`1 blockHashes) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Synchronization/SyncServer.cs:line 207
   at Nethermind.Network.P2P.Subprotocols.Eth.V63.Eth63ProtocolHandler.Handle(GetReceiptsMessage msg) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandler.cs:line 97
   at Nethermind.Network.P2P.Session.ReceiveMessage(ZeroPacket zeroPacket) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Session.cs:line 187
   at Nethermind.Network.P2P.ZeroNettyP2PHandler.ChannelRead0(IChannelHandlerContext ctx, ZeroPacket input) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/ZeroNettyP2PHandler.cs:line 99
   at DotNetty.Transport.Channels.SimpleChannelInboundHandler`1.ChannelRead(IChannelHandlerContext ctx, Object msg)

**Comment by tkstanczak** [comment]
2019-12-31 18:40:19.0106|DEBUG|15|Network.P2P.ZeroNettyP2PHandler|Error in communication with [Node|206.189.43.146:30303|Parity-Ethereum/v2.5.11-stable-fc129b4-20191205/x86_64-linux-gnu/rustc1.39.0]: Nethermind.Core.Encoding.RlpException: Unexpected prefix of 130 when decoding Keccak at position 5 in the message of length 425 starting with f901a60182cb34b9010000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000001000000000008000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000010010000000000000000000000000000000000000000000000000000000000000000000020000200000000000000000080000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000f89df89b947abc60b3290f68c85f495fd2e0c3bd278837a313f863a0ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3efa00000000000000000000000000861fca546225fbf8806986d211c8398f7457734a0000000000000000000000000c66cb0b6ec63190896a35a4ca45060456c322049a00000000000000000000000000000000000000000000000000009e146af92f500

**Comment by tkstanczak** [comment]
2019-12-31 18:47:42.5119|DEBUG|15|Network.P2P.ZeroNettyP2PHandler|Error in communication with [Node|125.33.48.137:51978|Geth/v1.9.9-stable-599009d2/linux-amd64/go1.13.5]: Nethermind.Core.Encoding.RlpException: Unexpected prefix of 130 when decoding Keccak at position 37 in the message of length 299 starting with f90128a0c48dd2fa7047c42d6f835404c6f598602a92a0ab7515295b17ab116f218d7de0825208b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0
