### ISSUE TITLE
Mark fast synced blocks as main branch

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1216]
2019-12-31 18:40:20.0883|DEBUG|15|Network.P2P.ZeroNettyP2PHandler|Error in communication with [Node|116.62.243.47:30303|Parity-Ethereum/v2.5.11-stable-fc129b4-20191205/x86_64-linux-gnu/rustc1.39.0]: System.InvalidOperationException: Unexpected request by number for a block 9189153 that is not on the main chain and is not the only hash on chain
   at Nethermind.Blockchain.BlockTree.GetBlockHashOnMainOrOnlyHash(Int64 blockNumber) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/BlockTree.cs:line 759
   at Nethermind.Blockchain.BlockTree.FindHeaders(Keccak blockHash, Int32 numberOfBlocks, Int32 skip, Boolean reverse) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/BlockTree.cs:line 724
   at Nethermind.Network.P2P.Subprotocols.Eth.Eth62ProtocolHandler.Handle(GetBlockHeadersMessage getBlockHeadersMessage) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/Eth62ProtocolHandler.cs:line 420
   at Nethermind.Network.P2P.Subprotocols.Eth.V63.Eth63ProtocolHandler.HandleMessage(ZeroPacket message) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandler.cs:line 83
   at Nethermind.Network.P2P.Session.ReceiveMessage(ZeroPacket zeroPacket) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Session.cs:line 187
   at Nethermind.Network.P2P.ZeroNettyP2PHandler.ChannelRead0(IChannelHandlerContext ctx, ZeroPacket input) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/ZeroNettyP2PHandler.cs:line 99
   at DotNetty.Transport.Channels.SimpleChannelInboundHandler`1.ChannelRead(IChannelHandlerContext ctx, Object msg)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRead(Object msg)

**Comment by tkstanczak** [comment]
done
