### ISSUE TITLE
Do not log errors on PeerInfoRefresh timing out

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1217]

**Comment by tkstanczak** [comment]
2019-12-31 18:44:03.7672|DEBUG|50|Blockchain.Synchronization.EthSyncPeerPool|InitPeerInfo failed for node: [Node|157.230.226.110:46906|Geth/v1.9.6-stable-bd059680/linux-amd64/go1.11.5]
System.AggregateException: One or more errors occurred. (Initialized In session 157.230.226.110:46906->localhost:30309 Request timeout in GetBlockHeadersMessage with 1 max headers)
 ---> System.TimeoutException: Initialized In session 157.230.226.110:46906->localhost:30309 Request timeout in GetBlockHeadersMessage with 1 max headers
   at Nethermind.Network.P2P.Subprotocols.Eth.Eth62ProtocolHandler.SendRequest(GetBlockHeadersMessage message, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/Eth62ProtocolHandler.cs:line 562
   at Nethermind.Network.P2P.Subprotocols.Eth.Eth62ProtocolHandler.Nethermind.Blockchain.Synchronization.ISyncPeer.GetHeadBlockHeader(Keccak hash, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/Eth62ProtocolHandler.cs:line 695
   --- End of inner exception stack trace ---
