### ISSUE TITLE
New Ethash approach sometimes throws InvalidState

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1244]
2020-01-08 08:46:06.3390|67|Error when validating headers of Headers [8976769, 8976960](192) [HIGH] [times: S:162ms|R:140ms|V:11ms|W:0ms|H:0ms|A:9958ms, retries 4] min#: 8976960 [Peer|34.83.251.94:30303|9200184|Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0] System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Nethermind.Mining.Ethash.Hashimoto(UInt64 fullSize, IEthashDataSet dataSet, ValueKeccak& headerHash, Keccak expectedMixHash, UInt64 nonce) in /root/src/nethermind/src/Nethermind/Nethermind.Mining/Ethash.cs:line 318
   at Nethermind.Mining.Ethash.Validate(BlockHeader header) in /root/src/nethermind/src/Nethermind/Nethermind.Mining/Ethash.cs:line 208
   at Nethermind.Mining.EthashSealValidator.ValidateSeal(BlockHeader header, Boolean force) in /root/src/nethermind/src/Nethermind/Nethermind.Mining/EthashSealValidator.cs:line 73
   at Nethermind.Blockchain.Synchronization.FastBlocks.FastBlocksDownloader.ValidateHeaders(CancellationToken cancellation, FastBlocksBatch batch) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Synchronization/FastBlocks/FastBlocksDownloader.cs:line 208

**Comment by tkstanczak** [comment]
reverted

**Comment by raymondjacobson** [comment]
Is there any more context on the resolution here? Seeing this bug currently in production on nethermind 1.12.7
