### ISSUE TITLE
When sync and mining is on on Clique the threading issues appear

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1258]
It was not happening before.
To reproduce:

Get a mining goerli validator
Start syncing from 0
It will try to seal blocks but it will keep crashing every 100 blocks or so.
After restart it goes forward.

2020-01-10 16:44:02.5777|66|Sealed block 1976015 (0x1cc66c...d78b84), diff: 1, tx count: 0
2020-01-10 16:44:02.5777|68|BlockchainProcessor encountered an exception. System.InvalidOperationException: Expected checked value 2 to be equal to 3 - 0
   at Nethermind.Store.StateProvider.Commit(IReleaseSpec releaseSpec, IStateTracer stateTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Store/StateProvider.cs:line 484
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean readOnly) in /root/src/nethermind/src/Nethermind/Nethermind.Evm/TransactionProcessor.cs:line 166
   at Nethermind.Blockchain.BlockProcessor.ProcessTransactions(Block block, ProcessingOptions processingOptions, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/BlockProcessor.cs:line 163
   at Nethermind.Blockchain.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/BlockProcessor.cs:line 222
   at Nethermind.Blockchain.BlockProcessor.Process(Keccak branchStateRoot, Block[] suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/BlockProcessor.cs:line 125
   at Nethermind.Blockchain.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/BlockchainProcessor.cs:line 370
   at Nethermind.Blockchain.BlockchainProcessor.RunProcessingLoop() in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/BlockchainProcessor.cs:line 243
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

**Comment by tkstanczak** [comment]
Also conflicts on the tree - probably the same StateProvider was added to the miner and BlockchainProcessor:

2020-01-10 16:47:46.9534|16|Preparing new block on top of 1976729 (0xd177ba...842d75)
2020-01-10 16:47:46.9534|16|Producing out of turn block
2020-01-10 16:47:46.9534|16|Block producer could not produce block on top of 1976729 (0xd177ba...842d75) Nethermind.Store.StateException: Unable to resolve node 0xecbde113c2745de48f40295202f9236c69599ede8088ad30c711a98e58eb092c
 ---> Nethermind.Core.Encoding.RlpException: Expected a sequence prefix to be in the range of <192, 255> and got 61 at position 501 in the message of length 532 starting with f90211a0d7c35e276ed752d6cdd37ab1f5b4df045797f7f580f2035521b47f4a7e4af514a0549ee3dece4c58958cfbdcf3d97c85ff6a3a49aa41e12d21fb3cdd3db7dbf442a0efab4789fc9b5840f3ded6a70b6f9b90a4661f01d41d9a9b33dd9bc2b86c885ba00b19513e2ecd2dffab02a48c6407fbf921e18c83197403004136e6097e68fd3ba03cabd62e4945e6cfd0d4783feb11a691a2163e4e61c485f63616b527cde449e6a017e90ef2edca7ea755885267bca5d30d37a0e7146c8bd5490882f154b9f919e5a07ab7f87ed6513b90c98f6a7ed43d50a25a3f33e53551d196079a26a6631846f4a0affabe5711e87e64a30fa0b845dfc3be24ee3c1d34a55d454e5ff5cdabe4ec25a0ffb1e0182714ec3631f462eb056f3463cc30f3626923e1cb590bef84c38ce21aa03a0dddc8c547f192b43ab7c64bbc9ea8c9108c40acca2a01f2472e4b597a89efa0c3d9e5988f103d094b1ab8731c26bfa80b7cba900ab3fd46556159b0281b5529a051b33c938ca6ab191f7c372b37d4201e80a2d86e168867ab0dbe40ee9ab49152a0e4c62d80eeb83cc342c5cfca5c09d5873181d94e5a988336842c2984b5ab64a9a026eecd26b98d13e1a3e869d5f6b0c1224d9723131ca61ac81e3f1eabaf2d054da0e8a068c3469306a84dea02cb5754ef72a7290e2575fda55a42143da69f776abfa08f3d49657ae65ea46dba6347827716e5735b030136ec6ed60f281d8f51e9a63580
   at Nethermind.Core.Encoding.RlpStream.ReadSequenceLength() in /root/src/nethermind/src/Nethermind/Nethermind.Core/Encoding/RlpStream.cs:line 540
   at Nethermind.Store.TrieNode.ResolveNode(PatriciaTree tree, Boolean allowCaching) in /root/src/nethermind/src/Nethermind/Nethermind.Store/TrieNode.cs:line 213
   --- End of inner exception stack trace ---
   at Nethermind.Store.TrieNode.ResolveNode(PatriciaTree tree, Boolean allowCaching) in /root/src/nethermind/src/Nethermind/Nethermind.Store/TrieNode.cs:line 213
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in /root/src/nethermind/src/Nethermind/Nethermind.Store/PatriciaTree.cs:line 436
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in /root/src/nethermind/src/Nethermind/Nethermind.Store/PatriciaTree.cs:line 322
   at Nethermind.Store.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak rootHash) in /root/src/nethermind/src/Nethermind/Nethermind.Store/PatriciaTree.cs:line 301
   at Nethermind.Store.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /root/src/nethermind/src/Nethermind/Nethermind.Store/PatriciaTree.cs:line 224
   at Nethermind.Store.StateTree.Get(Address address, Keccak rootHash) in /root/src/nethermind/src/Nethermind/Nethermind.Store/StateTree.cs:line 47
   at Nethermind.Store.StateProvider.GetState(Address address) in /root/src/nethermind/src/Nethermind/Nethermind.Store/StateProvider.cs:line 548
   at Nethermind.Store.StateProvider.GetAndAddToCache(Address address) in /root/src/nethermind/src/Nethermind/Nethermind.Store/StateProvider.cs:line 560
   at Nethermind.Store.StateProvider.GetNonce(Address address) in /root/src/nethermind/src/Nethermind/Nethermind.Store/StateProvider.cs:line 113
   at Nethermind.Blockchain.PendingTransactionSelector.SelectTransactions(Int64 gasLimit) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/PendingTransactionSelector.cs:line 82
   at Nethermind.Clique.CliqueBlockProducer.PrepareBlock(Block parentBlock) in /root/src/nethermind/src/Nethermind/Nethermind.Clique/CliqueBlockProducer.cs:line 381
   at Nethermind.Clique.CliqueBlockProducer.ConsumeSignal() in /root/src/nethermind/src/Nethermind/Nethermind.Clique/CliqueBlockProducer.cs:line 227

**Comment by tkstanczak** [comment]
found a fix
