### ISSUE TITLE
nethermind not running on VPS

### ISSUE THREAD

**Issue by makue1105** [NethermindEth/nethermind#1355]
I am trying to run nethermind on a VPS. 
I tried both version 1.4.7 and 1.5.2 and the error is still occuring in both Docker and running it directly on the VPS.

Usually it simply gets stuck at ` Reading config file from /nethermind/configs/mainnet.cfg`

But one time i manged to get an error (see attached log file)
[nethermind.log](https://github.com/NethermindEth/nethermind/files/4121691/nethermind.log)

**Comment by tkstanczak** [comment]
This may be due to permissions:

nethermind_1  | 2020-01-23 09:56:26.7889|Init failed System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
nethermind_1  |  ---> System.TypeInitializationException: The type initializer for 'DotNetty.Transport.Channels.DefaultChannelId' threw an exception.
nethermind_1  |  ---> System.Net.NetworkInformation.NetworkInformationException (2): An error was encountered while querying information from the operating system. ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path '/sys/class/net/eth0/mtu'.) (Could not find a part of the path '/sys/class/net/eth0/mtu'.)
nethermind_1  |  ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/net/eth0/mtu'.
nethermind_1  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
nethermind_1  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
nethermind_1  |    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
nethermind_1  |    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
nethermind_1  |    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
nethermind_1  |    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
nethermind_1  |    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
nethermind_1  |    at System.IO.File.ReadAllText(String path)
nethermind_1  |    at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
nethermind_1  |    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetMtu()
nethermind_1  |    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
nethermind_1  |    at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
nethermind_1  |    at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name, Int32 index)
nethermind_1  |    at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name, Int32 index)
nethermind_1  |    at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
nethermind_1  |    --- End of inner exception stack trace ---
nethermind_1  |  ---> (Inner Exception #1) System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/net/eth0/mtu'.
nethermind_1  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
nethermind_1  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
nethermind_1  |    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
nethermind_1  |    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
nethermind_1  |    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
nethermind_1  |    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
nethermind_1  |    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
nethermind_1  |    at System.IO.File.ReadAllText(String path)
nethermind_1  |    at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
nethermind_1  |    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetMtu()
nethermind_1  |    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
nethermind_1  |    at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
nethermind_1  |    at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name, Int32 index)
nethermind_1  |    at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name, Int32 index)
nethermind_1  |    at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__0(String name, IpAddressInfo* ipAddr, IpAddressInfo* maskAddr)<---
nethermind_1  | 
nethermind_1  |    at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
nethermind_1  |    at DotNetty.Common.Internal.MacAddressUtil.GetBestAvailableMac()
nethermind_1  |    at DotNetty.Common.Internal.DefaultPlatform.DotNetty.Common.Internal.IPlatform.GetDefaultDeviceId()
nethermind_1  |    at DotNetty.Common.Platform.GetDefaultDeviceId()
nethermind_1  |    at DotNetty.Transport.Channels.DefaultChannelId.DefaultMachineId()
nethermind_1  |    at DotNetty.Transport.Channels.DefaultChannelId..cctor()
nethermind_1  |    --- End of inner exception stack trace ---
nethermind_1  |    at DotNetty.Transport.Channels.DefaultChannelId.NewInstance()
nethermind_1  |    at DotNetty.Transport.Channels.AbstractChannel.NewId()
nethermind_1  |    at DotNetty.Transport.Channels.AbstractChannel..ctor(IChannel parent)
nethermind_1  |    at DotNetty.Transport.Channels.Sockets.AbstractSocketChannel..ctor(IChannel parent, Socket socket)
nethermind_1  |    at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel..ctor(Socket socket)
nethermind_1  |    at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel..ctor()

**Comment by tkstanczak** [comment]
Unable to open socket over the network interface

**Comment by tkstanczak** [comment]
/sys/class/net/eth0/mtu'

**Comment by Muhammad-Altabba** [comment]
I am trying with Nethermind according to https://nethermind.readthedocs.io/en/latest/docker.html:

```
    docker run -it --network host --volume /in3/nethermind/mainnet:/data nethermind/nethermind --JsonRpc.Enabled true

    docker run -it --network host --volume /in3/nethermind/goerli:/data nethermind/nethermind --JsonRpc.Enabled true --config goerli
```

And they both just print the following:


> Loading standard NLog.config file from /nethermind/NLog.config.
> 
> Reading config file from /nethermind/configs/goerli.cfg
> 

Not sure where to find the log. 
However, you can reproduce the issue easily with the same docker command that is mentioned in the documentation.
What do you suggest?
Thanks,

**Comment by matilote** [comment]
@Muhammad-Altabba which docker image are you trying to run?

**Comment by matilote** [comment]
@Muhammad-Altabba The data folder is specified for Alpine arm64 image and will be changed soon to default, so logs can be found in `-v /in3/nethermind/goerli:/nethermind/logs/goerli.log.txt`

**Comment by Muhammad-Altabba** [comment]
So, are you able to reproduce the issue and check the logs?

**Comment by matilote** [comment]
I was not able to reproduce the issue, I could find logs at ``/nethermind/logs`` inside the container. Can you please try mapping volumes with below commands?
```
config file:

    -v /home/user/mainnet.cfg:/nethermind/configs/mainnet.cfg

database:

    -v /home/user/nethermind_db:/nethermind/nethermind_db

logs:

    -v /home/user/logs:/nethermind/logs

keystore:

    -v /home/user/keystore:/nethermind/keystore
```

**Comment by matilote** [comment]
@makue1105 Can you paste here an output of ``cat /sys/class/net/eth0/operstate``

**Comment by makue1105** [comment]
The state is `unknown`

**Comment by matilote** [comment]
Unfortunately I cannot reproduce the issue. I am guessing that this can be related to the network drivers, maybe reinstalling will help? As per kernel docs:

`Interface is in unknown state, neither driver nor userspace has set operational state. Interface must be considered for user data as setting operational state has not been implemented in every driver.`

**Comment by Muhammad-Altabba** [comment]
How is the network driver is related when running inside docker? 
Are you able to run it without issues using docker? (as mentioned I am using the docker command mentioned in the documentation https://github.com/NethermindEth/nethermind/issues/1355#issuecomment-581832493)
Thanks,

**Comment by makue1105** [comment]
So i was playing a bit and with the nethermind version 1.6.6 i made nethermind pass the "reading config" state. 

Nevertheless i am still getting errors with the network connection: 
```
2020-02-20 16:39:09.7497|Init failed System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'DotNetty.Transport.Channels.DefaultChannelId' threw an exception.
 ---> System.Net.NetworkInformation.NetworkInformationException (2): An error was encountered while querying information from the operating system. ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path '/sys/class/net/eth0/mtu'.) (Could not find a part of the path '/sys/class/net/eth0/mtu'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/net/eth0/mtu'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetMtu()
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name, Int32 index)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name, Int32 index)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/net/eth0/mtu'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetMtu()
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name, Int32 index)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name, Int32 index)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__0(String name, IpAddressInfo* ipAddr, IpAddressInfo* maskAddr)<---

   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at DotNetty.Common.Internal.MacAddressUtil.GetBestAvailableMac()
   at DotNetty.Common.Internal.DefaultPlatform.DotNetty.Common.Internal.IPlatform.GetDefaultDeviceId()
   at DotNetty.Common.Platform.GetDefaultDeviceId()
   at DotNetty.Transport.Channels.DefaultChannelId.DefaultMachineId()
   at DotNetty.Transport.Channels.DefaultChannelId..cctor()
   --- End of inner exception stack trace ---
   at DotNetty.Transport.Channels.DefaultChannelId.NewInstance()
   at DotNetty.Transport.Channels.AbstractChannel.NewId()
   at DotNetty.Transport.Channels.AbstractChannel..ctor(IChannel parent)
   at DotNetty.Transport.Channels.Sockets.AbstractSocketChannel..ctor(IChannel parent, Socket socket)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel..ctor(Socket socket)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at DotNetty.Transport.Bootstrapping.AbstractBootstrap`2.<>c__10`1.<Channel>b__10_0()
   at DotNetty.Transport.Bootstrapping.AbstractBootstrap`2.InitAndRegisterAsync()
   at DotNetty.Transport.Bootstrapping.AbstractBootstrap`2.DoBindAsync(EndPoint localAddress)
2020-02-20 16:39:09.7612|Init failed. Nethermind.Network.NetworkingException: Failed to initialize _bootstrapChannel
   at Nethermind.Network.Rlpx.RlpxPeer.Init() in /src/Nethermind/Nethermind.Network/Rlpx/RlpxPeer.cs:line 128
```
On my VPS there is no `eth0` thus nethermind is unable to access it.

**Comment by parithosh** [comment]
Is there any update on this issue?

**Comment by tkstanczak** [comment]
I was about to ask the same question @parithosh 
@matilote have you tried this recently?
@Muhammad-Altabba - have you managed to sort it out? if not maybe try to catch me on our Gitter channel so we can try to fix the thing together on Monday?
@makue1105 have you managed to get it resolved? we will have some new joiners soon with a lot of network and systems experience so maybe they will be able to help

**Comment by parithosh** [comment]
I tried it just now with the latest docker version (1.8.4-alpine) and have the exact same error as @makue1105 . I can also confirm that i do not have a eth0 network interface on my server and that would explain why the error ``` ---> (Inner Exception #1) System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/net/eth0/mtu'.``` occurs and causes a failure. Would it be possible to set the network interface identifier via the config file? It could default to use eth0 unless specified in the config file.

**Comment by tkstanczak** [comment]
@parithosh thanks for reporting - I will try to fix it tomorrow

**Comment by thereapman** [comment]
I did some digging into the nethermind code myself and it seems that the DotNetty library is having this behaviour. nethermind works fine on system that don't have an `eth0` either and DotNetty behaves correctly not bothering about `eth0`.

Also it makes no difference if nethermind runs directly on the server or via docker. 

Also to give more insight: The VPS's in question are Strato vServer's using the Virtuozzo Hypervisor. Interestingly they seem to run an approach where they share the kernel between VPS instances.

When it help debugging i could provide you access to my vServer instance.

**Comment by tkstanczak** [comment]
hi @thereapman thanks for the details, I think we will be able to pick it up soon
@matilote would you try to look at it on Monday with Tamas?
@thereapman - it would be great if you could let @matilote access the server in question

**Comment by thereapman** [comment]
sure. he should hit me up on twitter. same handle as here.

**Comment by matilote** [comment]
@parithosh @makue1105 Could you please try running the Nethermind via docker and pass a ``--network host`` argument to the docker command? I managed to get around this issue by doing so.

Example command: 
```
docker run --name nethermind --network host nethermind/nethermind:alpine
```

**Comment by makue1105** [comment]
@matilote Using the `network host` is also working for me and the nethermind is now syncing. 

Thank you!

**Comment by parithosh** [comment]
Yup, seems to work for me as well!

I ran it with docker-compose on my system 
```
nethermind:
        image: nethermind/nethermind:alpine
        command:
        - --JsonRpc.Enabled=true
        - --Network.DiscoveryPort=30312
        - --Network.P2PPort=30312
        ports:
        - 30304:30304
        - 30304:30304/udp
        - 30312:30312
        - 30312:30312/udp
        - 30303:30303
        - 30303:30303/udp
        restart: unless-stopped
        volumes:
        - /nethermind/data/chaindata:/chaindata
        network_mode: host
```
