### ISSUE TITLE
Websocket Exception (ethstats)

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1362]
So my node lost internet for a while (unrelated network issue), and Nethermind just kept dumping out this apparently un-handled exception.

I'm not sure if the intention is to display it like this or not, but it looks messy to dump into the log over and over.

```
2020-01-28 19:57:03.6848|ETH Stats disconnected, reason: Error
2020-01-28 19:57:03.6848|[WEBSOCKET CLIENT] Exception while connecting. Waiting 5 sec before next reconnection try. System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Websocket.Client.WebsocketClient.<>c.<<-ctor>b__17_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Websocket.Client.WebsocketClient.StartClient(Uri uri, CancellationToken token, ReconnectionType type)
```

**Comment by tkstanczak** [comment]
yup need to make it nicer and ethstats is not critical so a short warning would do

**Comment by tkstanczak** [comment]
@SebastianDremo this will be something to add to our test infra - testing behaviour of all modules on connection loss

**Comment by mxmar** [comment]
> Since this issue was most recently commented on, I figured I'd mention here that my Nethermind node connects to ethstats.dev, but it is the only client that does not STAY connected to ethstats.dev
> 
> I look through logs but I never find anything interesting
> 
> ```
> chase@eth02:~$ docker logs nethermind 2>&1 | egrep -i stats
> 20 Jan 17:31:49 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
> 20 Jan 17:31:49 | ETH Stats reconnected, sending 'hello' message...
> 20 Jan 17:51:22 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
> 20 Jan 17:51:23 | ETH Stats reconnected, sending 'hello' message...
> 20 Jan 18:58:10 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
> 20 Jan 18:58:10 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
> 20 Jan 18:58:10 | ETH Stats reconnected, sending 'hello' message...
> ```
> 
> If I restart it connects, and it stays connected for a while but usually within a day it vanishes. I do not have DEBUG logs on though 🤷🏻‍♂️
> 
> Obviously this is a super old issue, and I don't have exceptions anymore, I just can't keep it connected to ethstats for whatever reason.

Same here. After the last log `17 May 04:35:57 | ETH Stats reconnected, sending 'hello' message...`, it doesn't show anything else or try to reconnect to the EthStats service (EthStats API WebSocket connection), but Nethermind keeps running.

<img width="854" height="751" alt="Image" src="https://github.com/user-attachments/assets/46425664-3b29-4ebe-bd43-742f0b674842" />
