### ISSUE TITLE
CLI issues - debug.deleteChainSlice

### ISSUE THREAD

**Issue by matilote** [NethermindEth/nethermind#1466]
input: 
`debug.deleteChainSlice(99000, 100000)`

output: 
```
Request complete in 77439,216μs
SyntaxError: Unexpected token T
null
```

**Comment by matilote** [comment]
sometimes it also produces this error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Blockchain.BlockTree.DeleteChainSlice(Int64& startNumber, Int64& endNumber)
   at Nethermind.Blockchain.BlockTree.Nethermind.Blockchain.IBlockTree.DeleteChainSlice(Int64& startNumber, Int64& endNumber)
   at Nethermind.JsonRpc.Modules.DebugModule.DebugBridge.DeleteChainSlice(Int64 startNumber, Int64 endNumber)
   at Nethermind.JsonRpc.Modules.DebugModule.DebugModule.debug_deleteChainSlice(Int64& startNumber, Int64& endNumber)
   at Nethermind.JsonRpc.Modules.DebugModule.DebugModule.Nethermind.JsonRpc.Modules.DebugModule.IDebugModule.debug_deleteChainSlice(Int64& startNumber, Int64& endNumber) 
```

**Comment by tkstanczak** [comment]
I will remove it from CLI for now
