### ISSUE TITLE
EthStats exception messages when node offline for extended periods

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1567]
With `1.6.30` / Windows

When my node is offline for extended periods of time I eventually get bombarded with these messages:

```
2020-03-21 04:33:29.1161|INFO|5|ETH Stats disconnected, reason: Error 
2020-03-21 04:33:29.1161|ERROR|5|[WEBSOCKET CLIENT] Exception while connecting. Waiting 5 sec before next reconnection try. System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Websocket.Client.WebsocketClient.<>c.<<-ctor>b__17_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Websocket.Client.WebsocketClient.StartClient(Uri uri, CancellationToken token, ReconnectionType type)
```

I reported this once before and you said you were unable to reproduce. Just thought I'd open an issue for tracking because it just happened again this morning when my internet went out for a few hours.

**Comment by LukaszRozmej** [comment]
@tkstanczak would you have anything against using https://github.com/App-vNext/Polly for circuit breaker here?

**Comment by tkstanczak** [comment]
the less dependencies the better - do you think we will have so much of it that is worth to bring some big lib / security risks?

**Comment by tkstanczak** [comment]
@LukaszRozmej if you build a PR we can analyze together - I am mildly skeptical here but also open to discuss
I have seen Polly in some other project and it looked so so

**Comment by tkstanczak** [comment]
@MarekM25 <- if I remember properly, you have fixed this one, can it be closed?

**Comment by MarekM25** [comment]
@tkstanczak  that wasn't the same thing. I fixed replacing https to wss. I think it is something different.
