### ISSUE TITLE
Failing to get IP from checkip.amazonaws.com

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1568]
With: `1.6.31`

I'm getting this every time i start my node:

```
2020-03-21 09:49:11.0010|INFO|1|Using http://checkip.amazonaws.com to get external ip 
2020-03-21 09:49:11.0762|ERROR|1|Error while getting external ip System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at Nethermind.Network.IpResolver.InitializeExternalIp()
```

It then just defaults to 127.0.0.1

Can I suggest maybe a backup method of determining IP too?

**Comment by LukaszRozmej** [comment]
Will be in next release
