### ISSUE TITLE
Error while trying to get trace_replayBlockTransactions

### ISSUE THREAD

**Issue by kwix** [NethermindEth/nethermind#1625]
Nethermind version: v1.7.13-0-fcd450ac3-20200401
Chain: Ethereum mainnet

I'm trying to run `trace_replayBlockTransactions` with the following parameters: `[stateDiff, trace, vmTrace]`. 
Example of blocks where this happened: 
```
9786302
9786305
9786308
9786330
```

This errors pops in the logs:
```
2020-04-01 14:14:54.6939|Connection id "0HLUM64VHMHNV", Request id "0HLUM64VHMHNV:00000005": An unhandled exception was thrown by the application. Newtonsoft.Json.JsonSerializationException: Converter cannot write specified value to JSON. Nethermind.Dirichlet.Numerics.UInt256 is required.
   at Newtonsoft.Json.JsonConverter`1.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Nethermind.JsonRpc.Modules.Trace.ParityAccountStateChangeConverter.WriteChange(JsonWriter writer, ParityStateChange`1 change, JsonSerializer serializer)
   at Nethermind.JsonRpc.Modules.Trace.ParityAccountStateChangeConverter.WriteJson(JsonWriter writer, ParityAccountStateChange value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Nethermind.JsonRpc.Modules.Trace.ParityTxTraceFromReplayConverter.WriteJson(JsonWriter writer, ParityTxTraceFromReplay value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Nethermind.Serialization.Json.EthereumJsonSerializer.Serialize[T](Stream stream, T value, Boolean indented)
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by tkstanczak** [comment]
@kwix fixed but from lack of time for proper testing of Parity behaviour I assume that parity has "*" from: "value" to: null and not "-": value

**Comment by tkstanczak** [comment]
this is now in master

**Comment by kwix** [comment]
Will check as soon as I get the chance. Great job, thank you!
