### ISSUE TITLE
Support larger json rpc requests, when a batch/array of requests is issued. 

### ISSUE THREAD

**Issue by credfeto** [NethermindEth/nethermind#1637]
When I issue a batch of requests that is larger than 4k, I get the following error, which i don't when i issue the same request against geth, parity, infura and alchemy.

Note this is using websockets, but may also be an issue using http

```
2020-04-03 22:44:11.5214|Error during parsing/validation, request: [{"id":"LOCAL:FFMR-02:FULL:79:2020-04-03T21:42:29.4550854Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x7624d523cfa5eb32b3bc3586b708a9e06bad10e33c6eacf4f68a51f33e078e64"]},{"id":"LOCAL:FFMR-02:FULL:80:2020-04-03T21:42:29.4550887Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xe98c32e78489634592fa9934a293c5065697d25a7b2095efd5b575c5ebcf98e9"]},{"id":"LOCAL:FFMR-02:FULL:81:2020-04-03T21:42:29.4550893Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x5e0f67b223d25d0e8de6df908408de5d09f937d7f45993a6dc25da7dfffdaf4c"]},{"id":"LOCAL:FFMR-02:FULL:82:2020-04-03T21:42:29.4550898Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xe1fae5e85de2b96fd616ec5ad1eb9c21499a4ed41747928484beffa1e22ae972"]},{"id":"LOCAL:FFMR-02:FULL:83:2020-04-03T21:42:29.4550904Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x10556625df71d1299369fafa4b309273a7306c901bf2f3ad2a7cf4ee2de153e6"]},{"id":"LOCAL:FFMR-02:FULL:84:2020-04-03T21:42:29.4550909Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x7be0e908597f1f8d9fc9219dd3e110b7674d13ddc37b8d3434268d8cb4a9465d"]},{"id":"LOCAL:FFMR-02:FULL:85:2020-04-03T21:42:29.4550914Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x930182a718579d66db54a69e998976d7e1e5d409c686897541b858b47c1c9272"]},{"id":"LOCAL:FFMR-02:FULL:86:2020-04-03T21:42:29.4550920Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x1aabb145cc1fe35b6d299f7671f403bcd2cd98a007a33a887f8a0245842bc9cc"]},{"id":"LOCAL:FFMR-02:FULL:87:2020-04-03T21:42:29.4550925Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x8cf7551898766b51b58d880b05f8ed9331c19e7f3e52fa6b1755a8abeae36f50"]},{"id":"LOCAL:FFMR-02:FULL:88:2020-04-03T21:42:29.4550930Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x8b16c0d968938aaae7726dcf00c956e118ae95acf1506a6dd982416068a2754d"]},{"id":"LOCAL:FFMR-02:FULL:89:2020-04-03T21:42:29.4550935Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x3ee6207bba64af1402af4028304f92f81af79bcfacca54004ba33d74af0e0a40"]},{"id":"LOCAL:FFMR-02:FULL:90:2020-04-03T21:42:29.4550943Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xe21f2f7026b0965908ef757ab9b9c5e2a78654a540bf105a67a21df63418d1e6"]},{"id":"LOCAL:FFMR-02:FULL:91:2020-04-03T21:42:29.4550949Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x235a58f0db5dd47558854cd7005d0fca8b4996968951b6aedf5fd6eb8ff8c6c4"]},{"id":"LOCAL:FFMR-02:FULL:92:2020-04-03T21:42:29.4550954Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x229a129b1c4f8030b442ff5b81a6cd92c82b74de21003a103f1a69fbd5897a77"]},{"id":"LOCAL:FFMR-02:FULL:93:2020-04-03T21:42:29.4550959Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xaad1b897a9c186566091a45490f11945c192742be16ff2d4653e9f184f6e49d6"]},{"id":"LOCAL:FFMR-02:FULL:94:2020-04-03T21:42:29.4550964Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x211f73492d9eb4a005707c9def5bdec52c6b1aa8c161929367d44bc57173437e"]},{"id":"LOCAL:FFMR-02:FULL:95:2020-04-03T21:42:29.4550969Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x5d875519e5dd97da7ceb966e90e2762d5009e6b3a7b0083142d4d3d524d6ede4"]},{"id":"LOCAL:FFMR-02:FULL:96:2020-04-03T21:42:29.4550975Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x9d1b42280d6693866f9ea1360b16d52e77b2c4cddcec12d87c47dbb260f6ddf7"]},{"id":"LOCAL:FFMR-02:FULL:97:2020-04-03T21:42:29.4550980Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xc4367010d532b5e5f1f23a18e80d1815d044e677ad1dfdf03c4cd711130a53a6"]},{"id":"LOCAL:FFMR-02:FULL:98:2020-04-03T21:42:29.4550985Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x559c1dbfd56bf97b259e7681be0c3a581b50326bd0f4c7a0d6b8c2c12060e946"]},{"id":"LOCAL:FFMR-02:FULL:99:2020-04-03T21:42:29.4550993Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x519453a818d48b19661117925da3aa8a9c58e68d28c6b1ac0a52a8e4d576e741"]},{"id":"LOCAL:FFMR-02:FULL:100:2020-04-03T2 Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '[21].id', line 1, position 4096.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Nethermind.JsonRpc.JsonRpcProcessor.DeserializeObjectOrArray(String json)
   at Nethermind.JsonRpc.JsonRpcProcessor.ProcessAsync(String request)
2020-04-03 22:44:11.5214|Error during parsing/validation, request: 1:42:29.4550999Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xef58c20059d6d44b9f19aaf349cb3b870a24985ff4e227dec4697812a27f5716"]},{"id":"LOCAL:FFMR-02:FULL:101:2020-04-03T21:42:29.4551004Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xab72c6c96b66ea61c75b620e159f889a0f7a40b184ab419211d41005cbe66360"]},{"id":"LOCAL:FFMR-02:FULL:102:2020-04-03T21:42:29.4551010Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x1d6bf2b5ceb90614429bac2d5487513c82b127d4ea19c66e02a70d76edb657fe"]},{"id":"LOCAL:FFMR-02:FULL:103:2020-04-03T21:42:29.4551015Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x2fcf86a21e863600b3818b5e637086e5509a6a0ecb9635224007dcaac4259fc2"]},{"id":"LOCAL:FFMR-02:FULL:104:2020-04-03T21:42:29.4551020Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x9577fa95f77130f911dc9144303df60d5ccdb7bdad10a7373840f729a159a13d"]},{"id":"LOCAL:FFMR-02:FULL:105:2020-04-03T21:42:29.4551025Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x3eb964661614db6bee34ff6db362ffcabb10875d72e4de0c046e042c78458eb4"]},{"id":"LOCAL:FFMR-02:FULL:106:2020-04-03T21:42:29.4551030Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xaacdd9b2eed740a130530ec6d292bf62cd80cbb3449996c33e8dd24c44b89167"]},{"id":"LOCAL:FFMR-02:FULL:107:2020-04-03T21:42:29.4551036Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x496354504400918c2fd4ae875fc43c3417bdf0ac6b99e24a34ba5b3c0c038666"]},{"id":"LOCAL:FFMR-02:FULL:108:2020-04-03T21:42:29.4551041Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x0d5795f19263eaf4cbc9598d187965ff93c98667d4af76a4ae04f0cdea97257c"]},{"id":"LOCAL:FFMR-02:FULL:109:2020-04-03T21:42:29.4551046Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xde77817e50b869941b1cbccbea436cc76a9dabdd4e003c944394687fe028dc93"]},{"id":"LOCAL:FFMR-02:FULL:110:2020-04-03T21:42:29.4551051Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xc8613ce95312c9073a3b9bc8974fadf551ad66801ec65a82f94ea5a48865dcb9"]},{"id":"LOCAL:FFMR-02:FULL:111:2020-04-03T21:42:29.4551056Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x9266b4c03a3918b1565190217c1952307c89569a514cb1e766454c44ddac5cbc"]},{"id":"LOCAL:FFMR-02:FULL:112:2020-04-03T21:42:29.4551062Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x6cfe2c349a60b5cc49522cf216557641138e265bf21a6f0beff02f8009b87db6"]},{"id":"LOCAL:FFMR-02:FULL:113:2020-04-03T21:42:29.4551067Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x77b7062931e3df3ba166faf7c3b874e7ed960a4ae0f5df9866f18ae5ec5c4c38"]},{"id":"LOCAL:FFMR-02:FULL:114:2020-04-03T21:42:29.4551072Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xbeb537c6931346264729d5af044c93fd516384253c1c1599a0b9c4045b9fdd70"]},{"id":"LOCAL:FFMR-02:FULL:115:2020-04-03T21:42:29.4551081Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x8269e4513358a461b854cae96a534815dc4f3b7d334e55167d19b3e1393f3534"]},{"id":"LOCAL:FFMR-02:FULL:116:2020-04-03T21:42:29.4551086Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xbe4a81e276d7146915af483e9d4c0b152deffb6ec44de7736ab3510cd0e458f5"]},{"id":"LOCAL:FFMR-02:FULL:117:2020-04-03T21:42:29.4551091Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x9b6ef6c13ce3d576eca59c220115273e462584185b559f718081b4dd05473858"]},{"id":"LOCAL:FFMR-02:FULL:118:2020-04-03T21:42:29.4551096Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x36837c391f117b5767c4e4a14d264a606a2663d50f06430911bd16dd26474867"]},{"id":"LOCAL:FFMR-02:FULL:119:2020-04-03T21:42:29.4551102Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x160b81f48d2c0fe648a99b4016a1e61d98cc7c53d2302e5c2da236d334412864"]},{"id":"LOCAL:FFMR-02:FULL:120:2020-04-03T21:42:29.4551107Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xc3fbbec93892d7f6aed492dc4c7cb94f44a819063cb442e28d97d8fe650d6a23"]},{"id":"LOCAL:FFMR-02:FULL:121:2020-04-03T21:42:29.4551112Z","jso Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing number: :. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadNumberCharIntoBuffer(Char currentChar, Int32 charPos)
   at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Nethermind.JsonRpc.JsonRpcProcessor.DeserializeObjectOrArray(String json)
   at Nethermind.JsonRpc.JsonRpcProcessor.ProcessAsync(String request)
2020-04-03 22:44:11.5214|Error during parsing/validation, request: nrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x3c4c88c757fd59f9b26abcc3ff476c2f3bf469fb7bc0351d2ecdd357c4a5156a"]},{"id":"LOCAL:FFMR-02:FULL:122:2020-04-03T21:42:29.4551117Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x6e1179b8a94841935152abd7c66f4c7d1f651c3e3f0c6d337af7d168f64d47e4"]},{"id":"LOCAL:FFMR-02:FULL:123:2020-04-03T21:42:29.4551123Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x361de8250546466d669d08db128fd3606b86e48d23d5cd72488dc0aff3437115"]},{"id":"LOCAL:FFMR-02:FULL:124:2020-04-03T21:42:29.4551128Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x391f4042a8cd10a7091f8707638fc9c2b634a6b11aea2911ac92ed4849ce7930"]},{"id":"LOCAL:FFMR-02:FULL:125:2020-04-03T21:42:29.4551133Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x5b17dc6b6c5c3aace20fdc7f7d9c892a8ec30a5313b6279ede4a4852202061b2"]},{"id":"LOCAL:FFMR-02:FULL:126:2020-04-03T21:42:29.4551138Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xa3b263ab4343466186e71dd1c782603b9ccdacbec308b5fa61eb0beda9779b25"]},{"id":"LOCAL:FFMR-02:FULL:127:2020-04-03T21:42:29.4551144Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xf21a94c4fde6ee20205fb53d022717b2279c2f3427510f5d74ab64c8af0b68e3"]},{"id":"LOCAL:FFMR-02:FULL:128:2020-04-03T21:42:29.4551149Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x0f512b1fac679cf508a6c03fb84a46a8779c1c799b89e8d35b74b819cef64211"]},{"id":"LOCAL:FFMR-02:FULL:129:2020-04-03T21:42:29.4551154Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x3fda1b4dd9b3af4e5f9a74edbacab41ba0913eff8b58ac2152a2da43cb0227a9"]},{"id":"LOCAL:FFMR-02:FULL:130:2020-04-03T21:42:29.4551159Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x894099756745f8a47dc60c05ae191bad8ce01ba760a6a25762b5d8264746e6b1"]},{"id":"LOCAL:FFMR-02:FULL:131:2020-04-03T21:42:29.4551168Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xb9f1ac5c2632d001facc5827a1224c2ad429bbba8cb89f4496a59a130075c37d"]},{"id":"LOCAL:FFMR-02:FULL:132:2020-04-03T21:42:29.4551173Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x3789571eefdfe17d77c2593c7af9d9f3bdc33ee81e215e65583fd3407ec6c6c8"]},{"id":"LOCAL:FFMR-02:FULL:133:2020-04-03T21:42:29.4551178Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x33e075d3b4283b9fa78f7e2e05722863ddb15df8584e8594fd7e51920d4e093d"]},{"id":"LOCAL:FFMR-02:FULL:134:2020-04-03T21:42:29.4551183Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x7ebba9ceb3aafecfcbe9ba936fe90ebe8cbe3f3d3d226a977461f2d1d7c5d9a3"]},{"id":"LOCAL:FFMR-02:FULL:135:2020-04-03T21:42:29.4551188Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x888bb1ade54f74cd65b099e1ac7813a3f652cbf099e8f6ba9f83e890ba395589"]},{"id":"LOCAL:FFMR-02:FULL:136:2020-04-03T21:42:29.4551194Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xef5105b90be881564f6e5a60f8d764eec364fe46e2bdd0260d78475c4c39a51d"]},{"id":"LOCAL:FFMR-02:FULL:137:2020-04-03T21:42:29.4551199Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xac44bbf2f64d4efeaea23ae097f1f96fcd7601b1db7b1854b625d445f88ab29d"]},{"id":"LOCAL:FFMR-02:FULL:138:2020-04-03T21:42:29.4551204Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x548916b0b5210d24864751b7da7778a763478983d4926ac134ecf1e34af55235"]},{"id":"LOCAL:FFMR-02:FULL:139:2020-04-03T21:42:29.4551210Z","jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x270f51db2cf3b37bb967f5613efba1dcf6cdc1070b53c52b285d41c07519b7a3"]}] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: n. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Nethermind.JsonRpc.JsonRpcProcessor.DeserializeObjectOrArray(String json)
   at Nethermind.JsonRpc.JsonRpcProcessor.ProcessAsync(String request)
```

Using:

nethermind-windows-amd64-1.7.13-fcd450a on windows 10

**Comment by tkstanczak** [comment]
thanks for reporting @credfeto, checking it

**Comment by tkstanczak** [comment]
works fine on http, checking websockets

![image](https://user-images.githubusercontent.com/498913/78408005-fc66e980-75fd-11ea-93d9-3d6b3f32272a.png)

**Comment by tkstanczak** [comment]
reproduced on WebSockets:

![image](https://user-images.githubusercontent.com/498913/78408547-62a03c00-75ff-11ea-88d9-de8b57bd02b5.png)

**Comment by tkstanczak** [comment]
fixed in latest master
