### ISSUE TITLE
WebSockets errors on closing

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1667]
I opened a bunch of WebSocket connections to my node and then I killed those connections (uncleanly 😄 ). A short while later I closed Nethermind (CTRL+C) and was presented with the following error messages...basically repeating for each of the previously opened WebSocket connections...

```
2020-04-14 14:11:10.6385|ERROR|483|WebSockets error. System.OperationCanceledException: The read was canceled
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Nethermind.WebSockets.Extensions.ReceiveAsync(WebSocket webSocket, IWebSocketsClient client)
   at Nethermind.WebSockets.Extensions.<>c__DisplayClass0_0.<<UseWebSocketsModules>b__0>d.MoveNext()
2020-04-14 14:11:10.6385|ERROR|509|WebSockets error. System.OperationCanceledException: The read was canceled
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Nethermind.WebSockets.Extensions.ReceiveAsync(WebSocket webSocket, IWebSocketsClient client)
   at Nethermind.WebSockets.Extensions.<>c__DisplayClass0_0.<<UseWebSocketsModules>b__0>d.MoveNext()
2020-04-14 14:11:10.6385|INFO|509|Closing WebSockets for client: ''. 
2020-04-14 14:11:10.6385|INFO|483|Closing WebSockets for client: ''. 
```

**Comment by tkstanczak** [comment]
fixed
