### ISSUE TITLE
Nethermind.Trie.TrieException: Node <hash> is missing from the DB

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1691]
`Nethermind/v1.8.1-3-8b8cac252-20200418/X64-Microsoft Windows 10.0.18363/Core3.1.1`

After a seemingly clean shutdown, and then re-starting the node I received the following error, additional logs attached.

[TrieException.txt](https://github.com/NethermindEth/nethermind/files/4497925/TrieException.txt)

```
2020-04-17 12:59:09.5355|ERROR|168|BlockchainProcessor encountered an exception. Nethermind.Trie.TrieException: Node 0xace5924d72ba5f54e3e51530233e27549e669b270f650c5918849f99b1acc169 is missing from the DB
   at Nethermind.Trie.PatriciaTree.GetNode(Keccak keccak, Boolean allowCaching)
   at Nethermind.Trie.TrieNode.ResolveNode(PatriciaTree tree, Boolean allowCaching)
   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak rootHash)
   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash)
   at Nethermind.State.StateTree.Get(Address address, Keccak rootHash)
   at Nethermind.State.StateProvider.GetState(Address address)
   at Nethermind.State.StateProvider.GetAndAddToCache(Address address)
   at Nethermind.State.StateProvider.AccountExists(Address address)
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean isCall)
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer)
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessTransactions(Block block, ProcessingOptions processingOptions, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options)
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak branchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

Node will no longer sync.

**Comment by tkstanczak** [comment]
This is a corrupted db due to fast sync failure :/ We will be able to recover from such cases when beam sync is added. It shouldn't have happened so I will need to analyze it further.

**Comment by tkstanczak** [comment]
fixed, remaining in beam
