### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1702]
When closing my Nethermind node today I caught this. It was 'grey' not 'cyan' like the normal logs.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at RocksDbSharp.Native.rocksdb_get(IntPtr, IntPtr, Byte[], Int64, IntPtr ByRef, RocksDbSharp.ColumnFamilyHandle)
   at RocksDbSharp.Native.rocksdb_get(IntPtr, IntPtr, Byte[], Int64, RocksDbSharp.ColumnFamilyHandle)
   at Nethermind.Db.Rocks.DbOnTheRocks.KeyExists(Byte[])
   at Nethermind.Synchronization.FastSync.StateSyncFeed.AddNode(Nethermind.Synchronization.FastSync.StateSyncItem, DependentItem, System.String, Boolean)
   at Nethermind.Synchronization.FastSync.StateSyncFeed.HandleTrieNode(Nethermind.Synchronization.FastSync.StateSyncItem, Byte[], Int32 ByRef)
   at Nethermind.Synchronization.FastSync.StateSyncFeed.HandleResponse(Nethermind.Synchronization.FastSync.StateSyncBatch)
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1+<>c__DisplayClass18_0[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<Start>b__1(System.Threading.Tasks.Task)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by tkstanczak** [comment]
since we access the database a lot from various threads there are some race conditions when closing - database is already disposed and some threads try to read the data

this has been improved recently but may sometimes occur and should bear no risk

**Comment by MysticRyuujin** [comment]
Not sure if related but I just tried to close my node and it's not closing lol

```
Closing, please wait until all functions are stopped properly...
2020-04-22 11:10:51.3231|Shutting down...
2020-04-22 11:10:51.3231|Stopping session monitor...
2020-04-22 11:10:51.3231|Stopping discovery app...
2020-04-22 11:10:51.3231|Stopping block producer...
2020-04-22 11:10:51.3231|Stopping sync peer pool...
2020-04-22 11:10:51.3527|Stopping peer manager...
2020-04-22 11:10:51.4238|Stopping synchronizer...
2020-04-22 11:10:51.4238|Stopping blockchain processor...
2020-04-22 11:10:51.4414|Stopping rlpx peer...
2020-04-22 11:11:00.0101|Discovered a new block   9923254 11:10:50 (0xab8cd5...71fff4), tx count: 46 mined by 0xd7a15baeb7ea05c9660cbe03fb7999c2c2e57625, sent by 99.80.66.29:30303
2020-04-22 11:11:34.6158|Discovered a new block   9923255 11:11:02 (0x914cb7...a810e2), tx count: 212 mined by Mining Express, sent by 184.73.87.230:30303
2020-04-22 11:11:39.5230|Discovered a new block   9923256 11:11:35 (0x215dce...cd495a), tx count: 149 mined by Spark Pool, sent by 54.174.15.13:30303
2020-04-22 11:11:50.8201|Discovered a new block   9923257 11:11:39 (0x0da19b...7e6a4c), tx count: 140 mined by Spark Pool, sent by 54.174.15.13:30303
```

**Comment by tkstanczak** [comment]
Addressed both in the recent PR

https://github.com/NethermindEth/nethermind/pull/1741
