### ISSUE TITLE
Invalid best state calculation

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1704]
Version: 1.8.5

Been getting few of these in my log lately.

```
2020-04-21 18:28:54.7790|Invalid best state calculation: processed:9918760|beam state:0|state:0|block:9918761|header:9918761|peer block:9918761
2020-04-21 18:28:54.7790|Sync mode update failed System.InvalidOperationException: Invalid best state calculation: processed:9918760|beam state:0|state:0|block:9918761|header:9918761|peer block:9918761
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.VerifySnapshot(Snapshot best)
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.TakeSnapshot(Int64 peerBlock)
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.Update()
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.TimerOnElapsed(Object sender, ElapsedEventArgs e)
```

**Comment by MysticRyuujin** [comment]
Correction, I get this a LOT after closing my node for like 30 minutes, then starting it again.

**Comment by tkstanczak** [comment]
mostly fixed, release coming in 1.8.8

**Comment by tkstanczak** [comment]
this particular issue after restart is fixed for sure

**Comment by tkstanczak** [comment]
fixed
