### ISSUE TITLE
Error during sending message: Type: Ping

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1781]
1.8.25

```
2020-04-27 09:22:00.7258|Fast blocks bodies task completed.
2020-04-27 09:22:01.2294|Waiting for peers... 1s
2020-04-27 09:22:01.2294|Sync peers - Initialized: 0 | All: 0 | Max: 300

2020-04-27 09:22:01.5454|Error during sending message: Type: Ping, FarAddress: [::ffff:13.114.157.223]:53048, FarPublicKey: empty, ExpirationTime: 1587997341, SourceAddress: 192.168.10.50:30305, DestinationAddress: [::ffff:13.114.157.223]:53048, Version: 4, Mdc: empty System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Network.Discovery.DiscoveryManager.SendMessage(DiscoveryMessage discoveryMessage)

2020-04-27 09:22:01.6431|Error during sending message: Type: Ping, FarAddress: [::ffff:134.119.11.28]:54308, FarPublicKey: empty, ExpirationTime: 1587997341, SourceAddress: 192.168.10.50:30305, DestinationAddress: [::ffff:134.119.11.28]:54308, Version: 4, Mdc: empty System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Network.Discovery.DiscoveryManager.SendMessage(DiscoveryMessage discoveryMessage)

2020-04-27 09:22:01.6564|Error during sending message: Type: Ping, FarAddress: [::ffff:54.198.219.25]:46342, FarPublicKey: empty, ExpirationTime: 1587997341, SourceAddress: 192.168.10.50:30305, DestinationAddress: [::ffff:54.198.219.25]:46342, Version: 4, Mdc: empty System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Network.Discovery.DiscoveryManager.SendMessage(DiscoveryMessage discoveryMessage)

2020-04-27 09:22:02.2530|Changing state to FastBlocks, StateNodes, Beam at processed:9951453|beam state:9951453|state:0|block:9955003|header:9955003|peer block:9955021
```

**Comment by tkstanczak** [comment]
thanks, looking into it

**Comment by tkstanczak** [comment]
fixed on a branch

**Comment by tkstanczak** [comment]
1.8.29

**Comment by MysticRyuujin** [comment]
Not fixed

```
2020-04-29 11:11:30.8288|Error during sending message: Type: Ping, FarAddress: [::ffff:35.184.79.2]:42588, FarPublicKey: empty, ExpirationTime: 1588176710, SourceAddress: 47.186.101.185:30305, DestinationAddress: [::ffff:35.184.79.2]:42588, Version: 4, Mdc: empty System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Network.Discovery.DiscoveryManager.SendMessage(DiscoveryMessage discoveryMessage)
2020-04-29 11:11:30.8425|Error during sending message: Type: Ping, FarAddress: [::ffff:52.41.52.35]:14874, FarPublicKey: empty, ExpirationTime: 1588176710, SourceAddress: 47.186.101.185:30305, DestinationAddress: [::ffff:52.41.52.35]:14874, Version: 4, Mdc: empty System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Network.Discovery.DiscoveryManager.SendMessage(DiscoveryMessage discoveryMessage)
```
