### ISSUE TITLE
Sync mode update failed on transition (no impact)

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1790]
2020-04-27 18:21:29.2837|Saving root 0x6caaf362cb11d308291686d7fe39f88a41683b81b321d2c204c9a594d64eabf2 of 2598619
2020-04-27 18:21:29.3849|Changing state to Full at processed:0|state:2598619|block:2598619|header:2598619|peer block:2598619
2020-04-27 18:21:29.3849|Starting the node data sync from the 2598619 (0xfde847...f11dcb) 0x6caaf362cb11d308291686d7fe39f88a41683b81b321d2c204c9a594d64eabf2 root
2020-04-27 18:21:29.3849|Setting state sync state root to 2598619 0x6caaf362cb11d308291686d7fe39f88a41683b81b321d2c204c9a594d64eabf2
2020-04-27 18:21:30.3846|Setting block action to shelving.
2020-04-27 18:21:30.3890|Sync mode update failed System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Nethermind.State.StateProvider.get_StateRoot()
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak branchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Synchronization.BeamSync.BeamBlockchainProcessor.<>c__DisplayClass29_0.<BeamProcess>b__2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

**Comment by tkstanczak** [comment]
This is most likely caused by the cancellation followed by some reads on a temporary beam processor.
It should have no impact at all on the standard processor and is more of an indication that the beam cancellation happened exactly when it shouldhave.

Nonetheless would be nice to handle this exception nicely so it does not scare the users.

This was experienced on the out of the box 1.8.26 Goerli sync

**Comment by tkstanczak** [comment]
1.8.29
