### ISSUE TITLE
BeamSyncDb has already finished and cannot be activated again

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1799]
Error when restarting node `1.8.26-0-8c43ca573-20200428/X64-Microsoft Windows 10.0.18363/Core3.1.1`

```
2020-04-28 08:09:27.8424|Old Headers  9955900 / 9955900 | queue     0 | current     0.00bps | total     0.00bps
2020-04-28 08:09:27.8424|Old Bodies   9955900 / 9955900 | queue     0 | current     0.00bps | total     0.00bps
2020-04-28 08:09:27.8424|Old Receipts 9955900 / 9955900 | queue     0 | current     0.00bps | total     0.00bps
2020-04-28 08:09:27.8424|Waiting for peers... 1s
2020-04-28 08:09:27.8424|Sync peers - Initialized: 0 | All: 0 | Max: 300
2020-04-28 08:09:28.6841|Connected to 0 bootnodes, 356 trusted/persisted nodes
2020-04-28 08:09:29.0502|Initial connection, sending 'hello' message...
2020-04-28 08:09:29.8676|Setting block action to shelving.
2020-04-28 08:09:29.8676|StateSyncDispatcher has finished work.
2020-04-28 08:09:29.8676|Setting block action to standard processing.
2020-04-28 08:09:29.8676|Beam sync completed.
2020-04-28 08:09:29.8889|Building ethash cache for epoch 333
2020-04-28 08:09:29.8889|Building ethash cache for epoch 332
2020-04-28 08:09:31.8823|Processed    9961178 |    5,059ms, mgasps    1.97 total    1.97, tps   40.52 total   40.52, bps    0.00 total    0.00, recv queue 0, proc queue 0
2020-04-28 08:09:33.5721|Cache for epoch 332 with size 60293056 nd seed 2905fd5186c975a16b4c5d157463a325aa73cd8405f0489a0023acf87db18f34 built in 3682ms
2020-04-28 08:09:33.6497|Cache for epoch 333 with size 60423872 nd seed 5d5674707d426883d592850443381021eb4738ee11e242760fcdad8295700bf8 built in 3682ms
2020-04-28 08:09:57.9654|Sync peers 37(40)/300
2020-04-28 08:10:00.0384|Discovered a new block   9961179 08:09:03 (0x823da4...9cc9e5), tx count: 176 mined by Nanopool, sent by [Peer|52.232.78.66:30303|9961179|Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0|eth63]
2020-04-28 08:10:00.1638|BlockchainProcessor encountered an exception. System.InvalidOperationException: BeamSyncDb has already finished and cannot be activated again.
   at Nethermind.Synchronization.ParallelSync.SyncFeed`1.Activate()
   at Nethermind.Synchronization.BeamSync.BeamSyncDb.get_Item(Byte[] key)
   at Nethermind.Db.StateDb.Get(Byte[] key)
   at Nethermind.Db.StateDb.get_Item(Byte[] key)
   at Nethermind.Trie.PatriciaTree.GetNode(Keccak keccak, Boolean allowCaching)
   at Nethermind.Trie.TrieNode.ResolveNode(PatriciaTree tree, Boolean allowCaching)
   at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak rootHash)
   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash)
   at Nethermind.State.StorageTree.Get(UInt256 index)
   at Nethermind.State.StorageProvider.LoadFromTree(StorageCell storageCell)
   at Nethermind.State.StorageProvider.GetCurrentValue(StorageCell storageCell)
   at Nethermind.State.StorageProvider.Get(StorageCell storageCell)
   at Nethermind.Evm.VirtualMachine.ExecuteCall(EvmState vmState, Byte[] previousCallResult, ZeroPaddedSpan previousCallOutput, UInt256& previousCallOutputDestination, IReleaseSpec spec)
   at Nethermind.Evm.VirtualMachine.Run(EvmState state, ITxTracer txTracer)
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean isCall)
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer)
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessTransactions(Block block, ProcessingOptions processingOptions, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options)
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak branchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by tkstanczak** [comment]
already fixed - preparing a release
only affecting beam sync

**Comment by tkstanczak** [comment]
1.8.29
