### ISSUE TITLE
Error when creating data asset

### ISSUE THREAD

**Issue by matilote** [NethermindEth/nethermind#1953]
2020-05-26 10:59:18.5240|WARN|32|Error when handling ID 1, ndm_addDataAsset({
  "name": "ERC20 Stream from Supernode",
  "description": "ERC20 Stream from Mainnet Supernode",
  "unitType": "Unit",
  "queryType": "Stream",
  "unitPrice": "100000000",
  "minUnits": 100000000,
  "maxUnits": 5000000000,
  "termsAndConditions": null,
  "plugin": "erc20-tx-stream",
  "rules": {
    "expiry": {
      "value": "604800"
    }
  }
}) | {"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params"},"id":1}

**Comment by matilote** [comment]
2020-05-26 10:59:18.5178|WARN|32|Error while parsing JSON RPC request parameters Newtonsoft.Json.JsonSerializationException: Error converting value 5000000000 to type 'System.UInt32'. Path 'maxUnits', line 8, position 24.
 ---> System.OverflowException: Value was either too large or too small for a UInt32.
   at System.Convert.ThrowUInt32OverflowException()
   at System.Convert.ToUInt32(Int64 value)
   at System.Int64.System.IConvertible.ToUInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Nethermind.JsonRpc.JsonRpcService.DeserializeParameters(ParameterInfo[] expectedParameters, String[] providedParameters, Int32 missingParamsCount) in /src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs:line 253
