### ISSUE TITLE
Launcher issue remaining

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1984]
ubuntu@ubuntu:~/nether142$ ./Nethermind.Launcher
buffer.js:585
slice: (buf, start, end) => buf.utf8Slice(start, end),
^

RangeError: Index out of range
at Object.slice (buffer.js:585:37)
at Buffer.toString (buffer.js:782:14)
at Object.fs.readFileSync (pkg/prelude/bootstrap.js:703:35)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:992:22)
at Module.load (internal/modules/cjs/loader.js:813:32)
at Function.Module._load (internal/modules/cjs/loader.js:725:14)
at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
at internal/main/run_main_module.js:17:11 {
code: 'ERR_OUT_OF_RANGE'
}

**Comment by matilote** [comment]
Internal node.js issue switched launcher build to the newest node.js version.
