### ISSUE TITLE
estimateGas failing when using Nethermind with Nethereum 

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1995]
HI I am running a full node, my contract code works fine when I call through Infura however when I switch to Nethermind I get the following error: 2020-05-28 08:15:20.7127|ERROR|79|Error during method execution, request: ID 1, eth_estimateGas({}) System.NullReferenceException: Object reference not set to an instance of an object.
at Nethermind.Evm.Precompiles.AddressExtensions.IsPrecompiled(Address address, IReleaseSpec releaseSpec)
at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean isCall)
at Nethermind.Evm.TransactionProcessor.CallAndRestore(Transaction transaction, BlockHeader block, ITxTracer txTracer)
at Nethermind.Facade.BlockchainBridge.CallAndRestore(BlockHeader blockHeader, Transaction transaction, ITxTracer tracer)
at Nethermind.Facade.BlockchainBridge.EstimateGas(BlockHeader header, Transaction tx)
at Nethermind.JsonRpc.Modules.Eth.EthModule.eth_estimateGas(TransactionForRpc transactionCall)
2020-05-28 08:15:20.7216|WARN|79|Error when handling ID 1, eth_estimateGas({}) | {"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error","data":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n at Nethermind.Evm.Precompiles.AddressExtensions.IsPrecompiled(Address address, IReleaseSpec releaseSpec)\r\n at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean isCall)\r\n at Nethermind.Evm.TransactionProcessor.CallAndRestore(Transaction transaction, BlockHeader block, ITxTracer txTracer)\r\n at Nethermind.Facade.BlockchainBridge.CallAndRestore(BlockHeader blockHeader, Transaction transaction, ITxTracer tracer)\r\n at Nethermind.Facade.BlockchainBridge.EstimateGas(BlockHeader header, Transaction tx)\r\n at Nethermind.JsonRpc.Modules.Eth.EthModule.eth_estimateGas(TransactionForRpc transactionCall)"},"id":1}

**Comment by tkstanczak** [comment]
Before starting any work on this issue we should ensure that a PR is requested inside [Nethereum](https://github.com/Nethereum/Nethereum) with Nethermind support on par with `Parity`, `Geth` and `BeSu`.

Then we can use a code sample with `estimate_gas` from Nethereum to explore the issue.
