### ISSUE TITLE
JSON RPC: Unexpected end of request content

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#2074]
`v1.8.54`

I'm not sure what could be causing this?

Possible things making this query:

1. [dshackle](https://github.com/emeraldpay/dshackle) ?
2. [haproxy](http://www.haproxy.org/) health check `HTTP GET /`
3. Weird API calls from someone using our node? 😄 

```
2020-06-30 19:00:32.9794|INFO|137|Executing JSON RPC call eth_blocknumber with params
2020-06-30 19:00:33.1930|INFO|137|Executing JSON RPC call eth_blocknumber with params
2020-06-30 19:00:33.7987|INFO|17|Executing JSON RPC call eth_blocknumber with params
2020-06-30 19:00:35.1426|INFO|7|Executing JSON RPC call eth_blocknumber with params
2020-06-30 19:00:35.1990|ERROR|137|Connection id "0HM0T3HRPOMOH", Request id "0HM0T3HRPOMOH:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-06-30 19:00:35.9757|INFO|7|Executing JSON RPC call eth_blocknumber with params
2020-06-30 19:00:37.2990|INFO|9|Executing JSON RPC call eth_blocknumber with params
2020-06-30 19:00:38.1326|INFO|7|Executing JSON RPC call eth_blocknumber with params
2020-06-30 19:00:39.2073|INFO|17|Executing JSON RPC call eth_blocknumber with params
```

**Comment by MysticRyuujin** [comment]
I turned on debug logging real quick:

[debug.log](https://github.com/NethermindEth/nethermind/files/4853966/debug.log)

**Comment by MysticRyuujin** [comment]
I shutdown `dshackle` and the errors went away, so something about `dshackle` and `nethermind` are not playing nice.
