### ISSUE TITLE
Peer Manager Fails to Start if DNS fails to resolve

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#2197]
If you configure a static peer via `static-node.json` using a DNS name, and that DNS name doesn't resolve you get the following error, and the peer manager fails to start, so you don't peer with anyone.

```
2020-08-10 02:29:28.7989|ERROR|6|Unable to init the peer manager. System.ArgumentException: archive01.archivenode.io is not a proper IP address nor it can be resolved by DNS.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at Nethermind.Config.Enode..ctor(String enodeString)
   --- End of inner exception stack trace ---
   at Nethermind.Config.Enode..ctor(String enodeString)
   at Nethermind.Config.NetworkNode..ctor(String enode)
   at Nethermind.Network.StaticNodes.StaticNodesManager.<>c.<InitAsync>b__12_0(String n)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Nethermind.Network.StaticNodes.StaticNodesManager.InitAsync()
   at Nethermind.Runner.Ethereum.Steps.InitializeNetwork.InitPeer()
2020-08-10 02:29:28.8153|ERROR|11|Unable to start the peer manager. Nethermind.Runner.Ethereum.Steps.StepDependencyException: PeerManager
   at Nethermind.Runner.Ethereum.Steps.InitializeNetwork.StartPeer()
   at Nethermind.Runner.Ethereum.Steps.InitializeNetwork.Initialize(CancellationToken cancellationToken)
2020-08-10 02:29:28.8766|ERROR|9|Error during ethereum runner start System.ArgumentNullException: Value cannot be null. (Parameter 'peerManager')
   at Nethermind.JsonRpc.Modules.Admin.AdminModule..ctor(IBlockTree blockTree, INetworkConfig networkConfig, IPeerManager peerManager, IStaticNodesManager staticNodesManager, IEnode enode, String dataDir)
   at Nethermind.Runner.Ethereum.Steps.RegisterRpcModules.Execute(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.Steps.EthereumStepsManager.RunOneRoundOfInitialization(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken)
```

**Comment by MysticRyuujin** [comment]
This is still a problem :disappointed:
