### ISSUE TITLE
Unexpected end of request content

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#2329]
Recently I've been getting a bunch of errors that look like this:

```
2020-09-22 23:35:16.5956|ERROR|29|Connection id "0HM2VA0GMHQ6L", Request id "0HM2VA0GMHQ6L:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-09-22 23:35:19.5357|ERROR|28|Connection id "0HM2VA0GMHQ6N", Request id "0HM2VA0GMHQ6N:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

But there's not enough details in the request for me to know what's causing it...those connection ID numbers and request ID numbers mean nothing to me... any idea how I might narrow this down?

**Comment by tkstanczak** [comment]
This is an .NET Core issue that we have reported long time ago - it is thrown when client closes connection while server is still responding and should be harmless but it logs the scary messages. Did it cause any of your requests to fail?
Connection ID and Request ID in this case are internal identifiers of .NET Core / Kestrel.

**Comment by tkstanczak** [comment]
.NET 5 will be released in November if everything goes well so I would not chase this further before upgrading to the next version. If causing trouble beyond logs let me know. I think we can disable this in NLog

**Comment by MysticRyuujin** [comment]
I can't say for sure if it's causing requests to fail or not, it's an archive node, I haven't had reports of issues, yet.

**Comment by MysticRyuujin** [comment]
Hmmm it could be related to `dshackle` again...

https://github.com/emeraldpay/dshackle/issues/57

**Comment by tkstanczak** [comment]
@MysticRyuujin would you try with version 1.8.106 - @LukaszRozmej can give you more details on the changes that should improve the throughput

**Comment by MysticRyuujin** [comment]
```
2020-09-29 22:21:40.6194|ERROR|147|Connection id "0HM34OO4KSF4O", Request id "0HM34OO4KSF4O:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-09-29 22:21:42.2255|INFO|29|Processed   10960010 |    7,323ms, mgasps    1.69 total    1.69, tps   21.98 total   21.98, bps    0.00 total    0.00, recv queue 0, proc queue 0 
2020-09-29 22:21:42.9710|ERROR|137|Connection id "0HM34OO4KSF4U", Request id "0HM34OO4KSF4U:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-09-29 22:21:44.9335|ERROR|23|Connection id "0HM34OO4KSF50", Request id "0HM34OO4KSF50:00000003": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-09-29 22:21:46.9327|INFO|30|Discovered new block 10960011 22:21:16 (0x5adea4...dfdfca), tx count: 177 miner 0xd224ca0c819e8e97ba0136b3b95ceff503b79f53, sent by [Peer|eth64|10960011|OpenEthereum/v3.0.1-stable-8ca8089-20200601/x86_64-unknown-linux-gnu/rustc1.45.1|34.234.186.77:30303] 
2020-09-29 22:21:46.9357|ERROR|13|Connection id "0HM34OO4KSF5A", Request id "0HM34OO4KSF5A:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-09-29 22:21:49.3421|INFO|29|Processed   10960011 |    7,117ms, mgasps    3.47 total    2.56, tps   47.49 total   34.56, bps    0.14 total    0.07, recv queue 0, proc queue 0 
2020-09-29 22:21:50.9387|ERROR|25|Connection id "0HM34OO4KSF5L", Request id "0HM34OO4KSF5L:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-09-29 22:21:50.9789|ERROR|25|Connection id "0HM34OO4KSF5J", Request id "0HM34OO4KSF5J:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by MysticRyuujin** [comment]
`Version      : 1.9.7-0-ef11c8d6f-20201010/X64-Linux/Core3.1.5`

```
2020-10-10 14:58:36.5999|ERROR|185|Connection id "0HM3D5JO557VO", Request id "0HM3D5JO557VO:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-10-10 14:58:38.5966|ERROR|25|Connection id "0HM3D5JO557VP", Request id "0HM3D5JO557VP:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-10-10 14:58:41.8604|ERROR|203|Connection id "0HM3D5JO557VH", Request id "0HM3D5JO557VH:00000005": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-10-10 14:58:42.6004|ERROR|179|Connection id "0HM3D5JO557VU", Request id "0HM3D5JO557VU:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-10-10 14:58:44.4404|INFO|33|Discovered new block 11028346 14:58:23 (0xdeeef6...c7e9aa), tx count: 198 miner Spark Pool, sent by [Peer|eth64|11028346|OpenEthereum/v3.0.1-stable-8ca8089-20200601/x86_64-unknown-linux-gnu/rustc1.43.1|95.217.202.171:30303] 
2020-10-10 14:58:44.4982|INFO|33|Discovered new block 11028346 14:58:23 (0x74ca6d...9a92c4), tx count: 197 miner 0x6ebaf477f83e055589c1188bcc6ddccd8c9b131a, sent by [Peer|eth64|11028346|OpenEthereum/v3.0.1-stable-8ca8089-20200601/x86_64-unknown-linux-gnu/rustc1.45.1|34.234.186.77:30303] 
2020-10-10 14:58:44.6062|ERROR|138|Connection id "0HM3D5JO55800", Request id "0HM3D5JO55800:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-10-10 14:58:45.3065|INFO|32|Processed   11028346 |   14,815ms, mgasps    1.68 total    6.45, tps   19.44 total   97.62, bps    0.07 total    0.24, recv queue 0, proc queue 0
```

**Comment by pinghz** [comment]
Solved no？

**Comment by pinghz** [comment]
@MysticRyuujin

**Comment by MysticRyuujin** [comment]
I've not been told there's been any progress on this, I've posted examples of the issue still occuring after it was marked as fixes, so idk

**Comment by MysticRyuujin** [comment]
`Version      : 1.9.14-0-25aab8245-20201103/X64-Linux/Core3.1.5`

```
2020-11-03 15:46:09.5105|ERROR|20|Connection id "0HM401U01FCNB", Request id "0HM401U01FCNB:00000002": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by yorickdowne** [comment]
I've seen this when pointing Lighthouse, a beacon chain client, at Nethermind.

```
eth1_1                      | 2020-11-17 15:33:11.5312|Connection id "0HM4B0PSBUPFD", Request id "0HM4B0PSBUPFD:00000001": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
eth1_1                      |    at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
eth1_1                      |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
eth1_1                      |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
eth1_1                      |    at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
eth1_1                      |    at System.IO.StreamReader.ReadToEndAsyncInternal()
eth1_1                      |    at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__3>d.MoveNext() in /nethermind/src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs:line 151
eth1_1                      | --- End of stack trace from previous location where exception was thrown ---
eth1_1                      |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
eth1_1                      | 2020-11-17 15:33:11.5455|Executing JSON RPC call net_version with params
```

**Comment by MysticRyuujin** [comment]
Is there a way I can just turn these off or something?
![image](https://user-images.githubusercontent.com/8877131/115739130-44fd5c00-a353-11eb-887f-2279e74a5a06.png)
