### ISSUE TITLE
nethtest: System.ArgumentOutOfRangeException when called with invalid input

### ISSUE THREAD

**Issue by MariusVanDerWijden** [NethermindEth/nethermind#2344]
Hey y'all,
I just stumbled upon the following exception when running the nethtest binary on an invalid input.
(file `asdf` is non existent). This should fail gracefully imo with something like "could not find input file" or "input file invalid"
```
> ./nethtest -i asdf
Unhandled exception. System.ArgumentOutOfRangeException: StartIndex cannot be less than zero. (Parameter 'startIndex')
   at System.String.Remove(Int32 startIndex)
   at Ethereum.Test.Base.LoadGeneralStateTestFileStrategy.GetGeneralStateTestsDirectory()
   at Ethereum.Test.Base.LoadGeneralStateTestFileStrategy.Load(String testName, String wildcard)
   at Ethereum.Test.Base.TestsSourceLoader.LoadTests()
   at Nethermind.State.Test.Runner.StateTestsRunner.RunTests()
   at Nethermind.State.Test.Runner.Program.RunSingleTest(String path, Func`2 testRunnerBuilder)
   at Nethermind.State.Test.Runner.Program.Run(Options options)
   at Nethermind.State.Test.Runner.Program.Main(String[] args)
fish: '/home/matematik/ethereum/neth...' terminated by signal SIGABRT (Abort)
```

**Comment by SebastianDremo** [comment]
Thanks for the issue, will take care of it

**Comment by MariusVanDerWijden** [comment]
@SebastianDremo sorry to bother, found another one:
If I call with an existing but empty file I get the following exception:
```
~/ethereum/nethermind/nethtest -m -t -i FuzzyVM-1029641488-461617836.json
Unhandled exception. NUnit.Framework.AssertionException:   test data loading failure
  Expected: null
  But was:  "Failed to load: Object reference not set to an instance of an object."

   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.IsNull(Object anObject, String message, Object[] args)
   at Ethereum.Test.Base.GeneralStateTestBase.RunTest(GeneralStateTest test, ITxTracer txTracer)
   at Nethermind.State.Test.Runner.StateTestsRunner.RunTests()
   at Nethermind.State.Test.Runner.Program.RunSingleTest(String path, Func`2 testRunnerBuilder)
   at Nethermind.State.Test.Runner.Program.Run(Options options)
   at Nethermind.State.Test.Runner.Program.Main(String[] args)
fish: '~/ethereum/nethermind/nethtes...' terminated by signal SIGABRT (Abort)
```

**Comment by tkstanczak** [comment]
@SebastianDremo was it fixed?

**Comment by tkstanczak** [comment]
@MariusVanDerWijden is it still an issue? (I will not be able to check yet, I will discuss with @SebastianDremo on Monday)

**Comment by MarekM25** [comment]
@MariusVanDerWijden I'm closing the issue - feel free to reopen, but I think the problem was solved.
