### ISSUE TITLE
Issue after cache clearing (pruning branch)

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2390]
2020-10-19 02:35:50.3045|TRACE|25|Encountered exception Nethermind.Trie.TrieException: Unexpected number of items = 1 when decoding a node
   at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree, Boolean allowCaching) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 289
   at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 662
   at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 433
   at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 662
   at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 433
   at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 662
   at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 433
   at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 662
   at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 433
   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak startRootHash) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 402
   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 326
   at Nethermind.State.StorageProvider.LoadFromTree(StorageCell storageCell) in /root/src/nethermind/src/Nethermind/Nethermind.State/StorageProvider.cs:line 362
   at Nethermind.State.StorageProvider.GetCurrentValue(StorageCell storageCell) in /root/src/nethermind/src/Nethermind/Nethermind.State/StorageProvider.cs:line 346
   at Nethermind.State.StorageProvider.Get(StorageCell storageCell) in /root/src/nethermind/src/Nethermind/Nethermind.State/StorageProvider.cs:line 73
   at Nethermind.Evm.VirtualMachine.ExecuteCall(EvmState vmState, Byte[] previousCallResult, ZeroPaddedSpan previousCallOutput, UInt256& previousCallOutputDestination, IReleaseSpec spec) in /root/src/nethermind/src/Nethermind/Nethermind.Evm/VirtualMachine.cs:line 1648
   at Nethermind.Evm.VirtualMachine.Run(EvmState state, ITxTracer txTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Evm/VirtualMachine.cs:line 143
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean isCall) in /root/src/nethermind/src/Nethermind/Nethermind.Evm/TransactionProcessor.cs:line 221
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessTransactions(Block block, ProcessingOptions processingOptions, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 189
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 236
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 210
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 101 while processing blocks.

**Comment by tkstanczak** [comment]
Fixed
