### ISSUE TITLE
Cannot run the test runner

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2467]
Unhandled exception. System.ArgumentException: Second path fragment must not be a drive or UNC name. (Parameter 'expression')
   at System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs(String& directory, String& expression, MatchType matchType)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at Ethereum.Test.Base.LoadGeneralStateTestFileStrategy.Load(String testName, String wildcard) in C:\src\nethermind\src\Nethermind\Ethereum.Test.Base\LoadGeneralStateTestFileStrategy.cs:line 23
   at Ethereum.Test.Base.TestsSourceLoader.LoadTests() in C:\src\nethermind\src\Nethermind\Ethereum.Test.Base\TestsSourceLoader.cs:line 40
   at Nethermind.State.Test.Runner.StateTestsRunner.RunTests() in C:\src\nethermind\src\Nethermind\Nethermind.State.Test.Runner\StateTestRunner.cs:line 74
   at Nethermind.State.Test.Runner.Program.RunSingleTest(String path, Func`2 testRunnerBuilder) in C:\src\nethermind\src\Nethermind\Nethermind.State.Test.Runner\Program.cs:line 98
   at Nethermind.State.Test.Runner.Program.Run(Options options) in C:\src\nethermind\src\Nethermind\Nethermind.State.Test.Runner\Program.cs:line 76
   at Nethermind.State.Test.Runner.Program.Main(String[] args) in C:\src\nethermind\src\Nethermind\Nethermind.State.Test.Runner\Program.cs:line 57

**Comment by tkstanczak** [comment]
@SebastianDremo ?

**Comment by SebastianDremo** [comment]
Can you provide more info for me to reproduce this (what parameters are passed to dotnet run on start)? 

Right now I see no behaviour like this on my local machine either with or without giving a test to the runner
![image](https://user-images.githubusercontent.com/33788961/99457066-ab0c3000-292a-11eb-8059-87834672606b.png)
![image](https://user-images.githubusercontent.com/33788961/99457206-e27adc80-292a-11eb-9312-a4e0954ca40c.png)
