### ISSUE TITLE
Warning when running Nethermind.launcher on Windows: "(node:7728) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received 'utf-8'"

### ISSUE THREAD

**Issue by halfalicious** [NethermindEth/nethermind#2472]
Getting the following debug console spew when running nethermind.launcher (version 1.9.22 downloaded from here: https://downloads.nethermind.io/) on Windows 10 in a command prompt during the ethstats registration step: 

```
C:\Users\nilse\Documents\temp>C:\Program" "Files\nethermind\nethermind.launcher
? Start Nethermind Ethereum Node
? Select network Ethereum (mainnet)
? Select sync Fast Sync with Beam
JsonRpc: { Enabled: false, TracerTimeout: 20000, Host: '127.0.0.1', Port: 8545 }
? Would you like to enable web3 / JSON RPC capabilities? (this will expose your node to attacks unless you configured a firewall) Yes
? What should be the JSON RPC Host IP? (this should be the same as your host machine IP address) 127.0.0.1
EthStats: {
  Enabled: false,
  Server: 'wss://ethstats.net/api',
  Name: 'Nethermind',
  Secret: 'secret',
  Contact: 'hello@nethermind.io'
}
? Do you want to configure ethstats registration now? (y/N) (node:7728) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received 'utf-8'
    at maybeCallback (fs.js:148:9)
    at Object.writeFile (fs.js:1298:14)
    at C:\snapshot\nethermind.launcher\index.js
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tkstanczak** [comment]
@halfalicious, thanks for reporting, fixed in the next release
@matilote can you confirm this is the problem with Launcher that has been fixed last Thursday?

**Comment by matilote** [comment]
Yes, I confirm.
