### ISSUE TITLE
Error when running nethermind.launcher on Windows 10: ''Nethermind.Runner.exe' is not recognized as an internal or external command, operable program or batch file.'

### ISSUE THREAD

**Issue by halfalicious** [NethermindEth/nethermind#2473]
Nethermind.launcher tries to launch Nethermind.runner using the current working directory which isn't always the directory containing the binaries. For example, on Windows 10: 

```
C:\Users\nilse\Documents\temp>C:\Program" "Files\nethermind\nethermind.launcher
? Start Nethermind Ethereum Node
? Select network Ethereum (mainnet)
? Select sync Fast Sync with Beam
JsonRpc: { Enabled: false, TracerTimeout: 20000, Host: '127.0.0.1', Port: 8545 }
? Would you like to enable web3 / JSON RPC capabilities? (this will expose your node to attacks unless you configured a firewall) Yes
? What should be the JSON RPC Host IP? (this should be the same as your host machine IP address) 127.0.0.1
EthStats: {
  Enabled: false,
  Server: 'wss://ethstats.net/api',
  Name: 'Nethermind',
  Secret: 'secret',
  Contact: 'hello@nethermind.io'
}
? Do you want to configure ethstats registration now? (y/N) (node:7728) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received 'utf-8'
    at maybeCallback (fs.js:148:9)
    at Object.writeFile (fs.js:1298:14)
    at C:\snapshot\nethermind.launcher\index.js
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
? Do you want to configure ethstats registration now? No
EthStats configuration process will be skipped.
'Nethermind.Runner.exe' is not recognized as an internal or external command,
operable program or batch file.
There was an error when starting ./Nethermind.Runner.exeError: spawn ./Nethermind.Runner.exe ENOENT
```

**Comment by tkstanczak** [comment]
thank you for reporting, investigating

**Comment by tkstanczak** [comment]
@halfalicious for now we do not plan to support these files to be in separate directories. What scenario do you need it in?

**Comment by halfalicious** [comment]
> 
> 
> @halfalicious for now we do not plan to support these files to be in separate directories. What scenario do you need it in?

The scenario is launching nethermind.launcher.exe from a different directory by supplying the full path to the exe, e.g:

C:\Temp>"c:\Program Files\nethermind\Nethermind.Launcher.exe"

Took a closer look at this scenario, the problem arises when you launch nethermind.launcher from a directory other than the one that contains the binaries using the full path to the binary and you haven't added that directory to your path. Adding the dir to your path fixes things...since I think this is an edge case, I'm okay with won't fixing this. 

Thanks for looking at this! 😄

**Comment by tkstanczak** [comment]
I see, ok, this is actually slightly more worrying, will fix it when an opportunity arises. Thanks @halfalicious

**Comment by kamilchodola** [comment]
Interestingly I still reproduce that

```
C:\Users>C:\Users\kamil\Downloads\nethermind-1.30.1-2b75a75a-windows-x64\nethermind-launcher-windows-x64.exe
? Start Nethermind Ethereum Node
? Select network Ethereum (mainnet)
? Select sync Fast sync
2024-12-20 21-52-11.6885|Nethermind starting initialization.
2024-12-20 21-52-11.6986|Client version: Nethermind/v1.29.0+10412d1c/windows-x64/dotnet8.0.8
2024-12-20 21-52-11.7063|Loading embedded plugins
2024-12-20 21-52-11.7065|  Found plugin type Nethermind.Consensus.AuRa.AuRaPlugin
2024-12-20 21-52-11.7066|  Found plugin type Nethermind.Consensus.Clique.CliquePlugin
2024-12-20 21-52-11.7067|  Found plugin type Nethermind.Consensus.Ethash.EthashPlugin
2024-12-20 21-52-11.7068|  Found plugin type Nethermind.Consensus.Ethash.NethDevPlugin
2024-12-20 21-52-11.7069|  Found plugin type Nethermind.Hive.HivePlugin
2024-12-20 21-52-11.7070|  Found plugin type Nethermind.UPnP.Plugin.UPnPPlugin
Resolved executing directory as C:\Users\kamil\AppData\Local\Microsoft\WinGet\Links.
```

Links it with some 1.29.0 version where I run it from within 1.30.1 dir and also last log line here is also a last log - after it it jumps out of process.

@rubo low prio
