### ISSUE TITLE
XDai archive node failure on TxCertifier call

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2504]
v3.0.1-stable-8ca8089-20200601/x86_64-unknown-linux-gnu/rustc1.43.1|167.71.96.6:30303], with AuRa step 321245837
2020-11-24 14:46:25.0923|Call to certifier contract failed. Nethermind.Abi.AbiException: Cannot decode return data for function getAddress(address) for contract 0x6b53721d4f2fb9514b85f5c49b197d857e36cf03.
 ---> System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Nethermind.Core.Extensions.ByteArrayExtensions.Slice(Byte[] bytes, Int32 startIndex, Int32 length) in /root/src/nethermind/src/Nethermind/Nethermind.Core/Extensions/ByteArrayExtensions.cs:line 49
   at Nethermind.Abi.AbiAddress.Decode(Byte[] data, Int32 position, Boolean packed) in /root/src/nethermind/src/Nethermind/Nethermind.Abi/AbiAddress.cs:line 61
   at Nethermind.Abi.AbiEncoder.Decode(AbiEncodingStyle encodingStyle, AbiSignature signature, Byte[] data) in /root/src/nethermind/src/Nethermind/Nethermind.Abi/AbiEncoder.cs:line 89
   at Nethermind.Blockchain.Contracts.Contract.DecodeData(AbiEncodingInfo abiEncodingInfo, Byte[] data) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 187
   --- End of inner exception stack trace ---
   at Nethermind.Blockchain.Contracts.Contract.DecodeData(AbiEncodingInfo abiEncodingInfo, Byte[] data) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 187
   at Nethermind.Consensus.AuRa.Contracts.RegisterContract.GetAddress(BlockHeader header, String key) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/RegisterContract.cs:line 52
   at Nethermind.Consensus.AuRa.Contracts.RegisterBasedContract.GetContractAddress(BlockHeader header) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/RegisterBasedContract.cs:line 70
   at Nethermind.Consensus.AuRa.Contracts.RegisterBasedContract.GenerateTransaction[T](Byte[] transactionData, Address sender, Int64 gasLimit, BlockHeader header) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/RegisterBasedContract.cs:line 44
   at Nethermind.Blockchain.Contracts.Contract.ConstantContract.CallRaw(BlockHeader parentHeader, String functionName, Address sender, Object[] arguments) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.ConstantContract.cs:line 102
   at Nethermind.Consensus.AuRa.Contracts.CertifierContract.Certified(BlockHeader parentHeader, Address sender) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/CertifierContract.cs:line 46
   at Nethermind.Consensus.AuRa.Transactions.TxCertifierFilter.IsCertified(Transaction tx, BlockHeader parentHeader) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TxCertifierFilter.cs:line 73
2020-11-24 14:46:25.1002|Call to certifier contract failed. Nethermind.Abi.AbiException: Cannot decode return data for function getAddress(address) for contract 0x6b53721d4f2fb9514b85f5c49b197d857e36cf03.
 ---> System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Nethermind.Core.Extensions.ByteArrayExtensions.Slice(Byte[] bytes, Int32 startIndex, Int32 length) in /root/src/nethermind/src/Nethermind/Nethermind.Core/Extensions/ByteArrayExtensions.cs:line 49
   at Nethermind.Abi.AbiAddress.Decode(Byte[] data, Int32 position, Boolean packed) in /root/src/nethermind/src/Nethermind/Nethermind.Abi/AbiAddress.cs:line 61
   at Nethermind.Abi.AbiEncoder.Decode(AbiEncodingStyle encodingStyle, AbiSignature signature, Byte[] data) in /root/src/nethermind/src/Nethermind/Nethermind.Abi/AbiEncoder.cs:line 89
   at Nethermind.Blockchain.Contracts.Contract.DecodeData(AbiEncodingInfo abiEncodingInfo, Byte[] data) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 187
   --- End of inner exception stack trace ---
   at Nethermind.Blockchain.Contracts.Contract.DecodeData(AbiEncodingInfo abiEncodingInfo, Byte[] data) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 187
   at Nethermind.Consensus.AuRa.Contracts.RegisterContract.GetAddress(BlockHeader header, String key) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/RegisterContract.cs:line 52
   at Nethermind.Consensus.AuRa.Contracts.RegisterBasedContract.GetContractAddress(BlockHeader header) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/RegisterBasedContract.cs:line 70
   at Nethermind.Consensus.AuRa.Contracts.RegisterBasedContract.GenerateTransaction[T](Byte[] transactionData, Address sender, Int64 gasLimit, BlockHeader header) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/RegisterBasedContract.cs:line 44
   at Nethermind.Blockchain.Contracts.Contract.ConstantContract.CallRaw(BlockHeader parentHeader, String functionName, Address sender, Object[] arguments) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.ConstantContract.cs:line 102
   at Nethermind.Consensus.AuRa.Contracts.CertifierContract.Certified(BlockHeader parentHeader, Address sender) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/CertifierContract.cs:line 46
   at Nethermind.Consensus.AuRa.Transactions.TxCertifierFilter.IsCertified(Transaction tx, BlockHeader parentHeader) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Transac

**Comment by tkstanczak** [comment]
it keeps synchronizing after this:
2020-11-24 14:53:55.1465|Discovered new block 13176995 14:53:55 (0xfb98c1...82cd57), tx count: 6 miner 0x9e41ba620feba8198369c26351063b26ec5b7c9e, sent by [Peer|eth63|13176994|Parity-Ethereum/v2.7.2-posdao-stable-UNKNOWN-UNKNOWN/x86_64-unknown-linux-gnu/rustc1.42.0|157.245.78.43:30303], with AuRa step 321245927
2020-11-24 14:53:55.1634|Call to certifier contract failed. Nethermind.Abi.AbiException: Cannot decode return data for function getAddress(address) for contract 0x6b53721d4f2fb9514b85f5c49b197d857e36cf03.
 ---> System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Nethermind.Core.Extensions.ByteArrayExtensions.Slice(Byte[] bytes, Int32 startIndex, Int32 length) in /root/src/nethermind/src/Nethermind/Nethermind.Core/Extensions/ByteArrayExtensions.cs:line 49
   at Nethermind.Abi.AbiAddress.Decode(Byte[] data, Int32 position, Boolean packed) in /root/src/nethermind/src/Nethermind/Nethermind.Abi/AbiAddress.cs:line 61
   at Nethermind.Abi.AbiEncoder.Decode(AbiEncodingStyle encodingStyle, AbiSignature signature, Byte[] data) in /root/src/nethermind/src/Nethermind/Nethermind.Abi/AbiEncoder.cs:line 89
   at Nethermind.Blockchain.Contracts.Contract.DecodeData(AbiEncodingInfo abiEncodingInfo, Byte[] data) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 187
   --- End of inner exception stack trace ---
   at Nethermind.Blockchain.Contracts.Contract.DecodeData(AbiEncodingInfo abiEncodingInfo, Byte[] data) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 187
   at Nethermind.Consensus.AuRa.Contracts.RegisterContract.GetAddress(BlockHeader header, String key) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/RegisterContract.cs:line 52
   at Nethermind.Consensus.AuRa.Contracts.RegisterBasedContract.GetContractAddress(BlockHeader header) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/RegisterBasedContract.cs:line 70
   at Nethermind.Consensus.AuRa.Contracts.RegisterBasedContract.GenerateTransaction[T](Byte[] transactionData, Address sender, Int64 gasLimit, BlockHeader header) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/RegisterBasedContract.cs:line 44
   at Nethermind.Blockchain.Contracts.Contract.ConstantContract.CallRaw(BlockHeader parentHeader, String functionName, Address sender, Object[] arguments) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.ConstantContract.cs:line 102
   at Nethermind.Consensus.AuRa.Contracts.CertifierContract.Certified(BlockHeader parentHeader, Address sender) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/CertifierContract.cs:line 46
   at Nethermind.Consensus.AuRa.Transactions.TxCertifierFilter.IsCertified(Transaction tx, BlockHeader parentHeader) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TxCertifierFilter.cs:line 73
2020-11-24 14:53:55.2428|Downloaded 4014787 / 13176994 | current  1528.11bps | total   981.77bps
2020-11-24 14:53:56.0685|Processed    3688254 |    1,001ms, mgasps    4.04 total    8.33, tps   37.98 total  111.96, bps 1342.32 total  901.34, recv queue 326065, proc queue 2000
2020-11-24 14:53:56.2441|Downloaded 4016320 / 13176994 | current  1531.11bps | total   981.90bps
2020-11-24 14:53:57.0689|Processed    3689381 |    1,000ms, mgasps   11.01 total    8.33, tps  143.94 total  111.97, bps 1126.54 total  901.40, recv queue 326288, proc queue 2000
2020-11-24 14:53:57.2432|Downloaded 4017853 / 13176994 | current  1534.43bps | total   982.04bps
2020-11-24 14:53:58.0701|Processed    3690551 |    1,001ms, mgasps   17.16 total    8.33, tps  202.76 total  111.99, bps 1168.62 total  901.46, recv queue 326584, proc queue 2000

**Comment by tkstanczak** [comment]
This generally happens tens of times during the archive sync (probably new transactions from the pool are being validated against a not fully synced node)
