### ISSUE TITLE
Error while processing block on xDAI in archive

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2508]
2020-11-24 16:04:41.5735|ERROR|138|BlockchainProcessor encountered an exception. Nethermind.Abi.AbiException: System call to RewardContract.Reward returned an exception 'Expected actual position 3 to be equal to 5 - 1' at block 9190847.
 ---> System.InvalidOperationException: Expected actual position 3 to be equal to 5 - 1
   at Nethermind.State.StateProvider.Restore(Int32 snapshot) in /root/src/nethermind/src/Nethermind/Nethermind.State/StateProvider.cs:line 340
   at Nethermind.Evm.VirtualMachine.Run(EvmState state, ITxTracer txTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Evm/VirtualMachine.cs:line 310
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean isCall) in /root/src/nethermind/src/Nethermind/Nethermind.Evm/TransactionProcessor.cs:line 221
   at Nethermind.Blockchain.Contracts.Contract.CallCore(ITransactionProcessor transactionProcessor, BlockHeader header, String functionName, Transaction transaction, Boolean callAndRestore) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 160
   --- End of inner exception stack trace ---
   at Nethermind.Blockchain.Contracts.Contract.CallCore(ITransactionProcessor transactionProcessor, BlockHeader header, String functionName, Transaction transaction, Boolean callAndRestore) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 160
   at Nethermind.Blockchain.Contracts.CallableContract.Call(BlockHeader header, String functionName, Address sender, Int64 gasLimit, Object[] arguments) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Contracts/CallableContract.cs:line 69
   at Nethermind.Consensus.AuRa.Contracts.RewardContract.Reward(BlockHeader blockHeader, Address[] benefactors, UInt16[] kind) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Contracts/RewardContract.cs:line 77
   at Nethermind.Consensus.AuRa.Rewards.AuRaRewardCalculator.CalculateRewardsWithContract(Block block, IRewardContract contract) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Rewards/AuRaRewardCalculator.cs:line 109
   at Nethermind.Consensus.AuRa.Rewards.AuRaRewardCalculator.CalculateRewards(Block block) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/Rewards/AuRaRewardCalculator.cs:line 78
   at Nethermind.Blockchain.Processing.BlockProcessor.ApplyMinerRewards(Block block, IBlockTracer tracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 299
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 251
   at Nethermind.Consensus.AuRa.AuRaBlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockProcessor.cs:line 79
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 223
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 106
   at Nethermind.Blockchain.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 343
   at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 261
   at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop() in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 227
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

**Comment by tkstanczak** [comment]
on pruning branch (but with master merged)

**Comment by tkstanczak** [comment]
it carries on after restart
