### ISSUE TITLE
Change at current position

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2514]
2020-11-25 18:13:51.7517|BlockchainProcessor encountered an exception. System.InvalidOperationException: Change at current position 0 was null when commiting StateProvider
   at Nethermind.State.StateProvider.Commit(IReleaseSpec releaseSpec, IStateTracer stateTracer) in /root/src/nethermind/src/Nethermind/Nethermind.State/StateProvider.cs:line 407
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 251
   at Nethermind.Consensus.AuRa.AuRaBlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /root/src/nethermind/src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockProcessor.cs:line 79
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 223
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 106
   at Nethermind.Blockchain.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 343
   at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 261
   at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop() in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 227
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

**Comment by tkstanczak** [comment]
2020-11-25 18:13:39.7543|INFO|9|Starting from 9224192 0x44fb007d47e980b44f9140c63870fb9d5a2b75f842c5e5774498f4c3d87f4907
TRIE STATS
  SIZE 108706523 (STATE 13090337, CODE 34571582, STORAGE 61044604)
  ALL NODES 975804 (247216|7539|711686)
  STATE NODES 110883 (29143|1019|80721)
  STORAGE NODES 855558 (218073|6520|630965)
  ACCOUNTS 80721 OF WHICH (9363) ARE CONTRACTS
  MISSING 0 (STATE 0, CODE 0, STORAGE 0)
