### ISSUE TITLE
Pruning failing on collection modified

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2515]
2020-11-25 18:33:48.1725|ERROR|71|BlockchainProcessor encountered an exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Nethermind.Trie.Pruning.TrieStore.PruneCache() in /root/src/nethermind/src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 393
   at Nethermind.Trie.Pruning.TrieStore.Prune() in /root/src/nethermind/src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 312
   at Nethermind.Trie.Pruning.TrieStore.CreateCommitSet(Int64 blockNumber) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 532
   at Nethermind.Trie.Pruning.TrieStore.EnsureCommitSetExistsForBlock(Int64 blockNumber) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 616
   at Nethermind.Trie.Pruning.TrieStore.FinishBlockCommit(TrieType trieType, Int64 blockNumber, TrieNode root) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 194
   at Nethermind.Trie.PatriciaTree.Commit(Int64 blockNumber) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 177
   at Nethermind.State.StateProvider.CommitTree(Int64 blockNumber) in /root/src/nethermind/src/Nethermind/Nethermind.State/StateProvider.cs:line 743
   at Nethermind.Blockchain.Processing.BlockProcessor.PreCommitBlock(Keccak newBranchStateRoot, Int64 blockNumber) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 166
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 111
   at Nethermind.Blockchain.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 343
   at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 287
   at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop() in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 227
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

**Comment by tkstanczak** [comment]
fixed on twocache

**Comment by MysticRyuujin** [comment]
I just got this error and I'm not sure what happened, but I found this issue...looks related.

```
2021-03-12 14:38:35.7586|ERROR|53|BlockchainProcessor encountered an exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at Nethermind.State.Witnesses.WitnessCollector.Persist(Keccak blockHash)
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   ```

**Comment by MysticRyuujin** [comment]
Also see this error:
```
2021-03-12 14:35:17.9793|ERROR|46|BlockchainProcessor encountered an exception. System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
```
