### ISSUE TITLE
Goerli archive pruning EthSyncException

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#2549]
During goerli_archive synchronization, I saw the below error:
`2020-12-03 14:33:12.7253|Processed    1290299 |    1,000ms, mgasps  148.17 total  104.22, tps 1336.93 total  717.23, bps 1848.90 total  731.70, recv queue 668143, proc queue 811
2020-12-03 14:33:12.7547|DEBUG/ERROR Block download from [HBR ][    ][Peer|eth65|3861992|Nethermind/v1.9.45-378-1e31724f1-20201203/X64-Linux/Core3.1.8|94.237.54.114:30313] failed. System.AggregateException: One or more errors occurred. ([HBR ][    ][Peer|eth65|3861992|Nethermind/v1.9.45-378-1e31724f1-20201203/X64-Linux/Core3.1.8|94.237.54.114:30313] sent an empty body for 1959603 (0x426a01...336106).)
 ---> Nethermind.Synchronization.EthSyncException: [HBR ][    ][Peer|eth65|3861992|Nethermind/v1.9.45-378-1e31724f1-20201203/X64-Linux/Core3.1.8|94.237.54.114:30313] sent an empty body for 1959603 (0x426a01...336106).
   at Nethermind.Synchronization.Blocks.BlockDownloadContext.SetBody(Int32 index, BlockBody body) in C:\Users\marek\Desktop\Nethermind\nethermind\src\Nethermind\Nethermind.Synchronization\Blocks\BlockDownloadContext.cs:line 100
   at Nethermind.Synchronization.Blocks.BlockDownloader.RequestBodies(PeerInfo peer, CancellationToken cancellation, BlockDownloadContext context) in C:\Users\marek\Desktop\Nethermind\nethermind\src\Nethermind\Nethermind.Synchronization\Blocks\BlockDownloader.cs:line 423
   at Nethermind.Synchronization.Blocks.BlockDownloader.DownloadBlocks(PeerInfo bestPeer, BlocksRequest blocksRequest, CancellationToken cancellation) in C:\Users\marek\Desktop\Nethermind\nethermind\src\Nethermind\Nethermind.Synchronization\Blocks\BlockDownloader.cs:line 275
   --- End of inner exception stack trace ---`

**Comment by tkstanczak** [comment]
Change this error to DEBUG level.I changed it to Error level by mistake.

**Comment by MarekM25** [comment]
fixed
