### ISSUE TITLE
Non-fatal tx pool handling issue during xDAI fast sync

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2610]
2020-12-29 10:01:30.8538|Old Headers   2768896 / 13560000 | queue  5632 | current 14832.65bps | total  4692.67bps 
2020-12-29 10:01:30.8538|Downloaded 13762610 / 13763425 | current   510.48bps | total   344.37bps 
2020-12-29 10:01:31.7775|Couldn't correctly add or remove transactions from txpool after processing block 13763313 (0x303dea4de7a628081c7cd2cad5462ae926f1c4df14d1607994c64074eb944bfa). System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Nethermind.TxPool.TxPool.RemoveTransaction(Keccak hash, Int64 blockNumber, Boolean removeBelowThisTxNonce)
   at Nethermind.Blockchain.OnChainTxWatcher.ProcessBlock(Block block, Block previousBlock)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2020-12-29 10:01:31.7775|Couldn't correctly add or remove transactions from txpool after processing block 13763318 (0x251395ed48ea6aa3a8e60cda17aa3f9a882418b9f6c01230047dbadcce00ea72). System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Nethermind.TxPool.TxPool.RemoveTransaction(Keccak hash, Int64 blockNumber, Boolean removeBelowThisTxNonce)
   at Nethermind.Blockchain.OnChainTxWatcher.ProcessBlock(Block block, Block previousBlock)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2020-12-29 10:01:31.8545|Peers | with known best block: 12 | all: 15 | 
2020-12-29 10:01:31.8545|Old Headers   2768896 / 13560000 | queue 10240 | current     0.00bps | total  4684.72bps 
2020-12-29 10:01:32.0190|Changing state FastSync, FastHeaders to StateNodes, FastHeaders at processed:0|state:0|block:0|header:13763424|peer block:13763426

**Comment by LukaszRozmej** [comment]
2020-12-29 10:28:19.9733|INFO|16|Discovered new block 13763723 10:28:20 (0x924be7...b9a866), tx count: 11 miner 0x0000999dc55126ca626c20377f0045946db69b6e, sent by [Peer|eth63|13763723|Parity-Ethereum/v2.7.2-posdao-stable-2ea4265-20200226/x86_64-unknown-linux-gnu/rustc1.41.0|64.225.53.25:30303], with AuRa step 321847540
2020-12-29 10:28:19.9766|WARN|16|Reported Benign validator 0x1438087186fdbfd4c256fa2df446921e30e54df8 misbehaviour (cause: SkippedStep) at block 13763723
2020-12-29 10:28:19.9894|ERROR|163|BlockchainProcessor encountered an exception. System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
  at System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
  at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
  at Nethermind.TxPool.TxPool.RemoveTransaction(Keccak hash, Int64 blockNumber, Boolean removeBelowThisTxNonce) in /home/validator/dev/src/nethermind/src/Nethermind/Nethermind.TxPool/TxPool.cs:line 391
  at Nethermind.Blockchain.Processing.BlockProcessor.StoreTxReceipts(Block block, TxReceipt[] txReceipts) in /home/validator/dev/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 271
  at Nethermind.Blockchain.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /home/validator/dev/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 236
  at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /home/validator/dev/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 112
  at Nethermind.Blockchain.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer) in /home/validator/dev/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 343
  at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /home/validator/dev/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 261
  at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop() in /home/validator/dev/src/nethermind/src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 227
  at System.Threading.Tasks.Task.InnerInvoke()
  at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2020-12-29 10:28:25.1722|INFO|16|Discovered new block 13763724 10:28:25 (0xda11ee...651e52), tx count: 2 miner 0x9488f50c33e9616ee3b5b09cd3a9c603a108db4a, sent by [Peer|eth64|13763724|OpenEthereum/v3.0.0-stable-eee06b3-20200521/x86_64-alpine-linux-musl/rustc1.43.1|67.205.176.117:30303], with AuRa step 321847541
2020-12-29 10:28:34.8116|INFO|16|Discovered new block 13763725 10:28:35 (0x30848d...5ff1e0), tx count: 7 miner 0x642c40173134f6e457a62d4c2033259433a53e8c, sent by [Peer|eth64|13763725|OpenEthereum/v3.0.1-stable-8ca8089-20200601/x86_64-unknown-linux-gnu/rustc1.43.1|34.200.219.182:30303], with AuRa step 321847543
