### ISSUE TITLE
CLI Exception at Startup on Windows

### ISSUE THREAD

**Issue by bgausden** [NethermindEth/nethermind#2654]
```
**********************************************

Nethermind CLI -20210113
  https://github.com/NethermindEth/nethermind
  https://nethermind.readthedocs.io/en/latest/

powered by:
  https://github.com/sebastienros/jint
  https://github.com/tomakita/Colorful.Console
  https://github.com/tonerdo/readline

**********************************************

Resolved executing directory as G:\Downloads\nethermind-windows-amd64-1.9.52-cffc0bd.
Type CliModuleBase is a CLI module but is not marked with a CliModuleAttribute
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Nethermind.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Nethermind.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nethermind.Cli.Modules.CliModuleLoader.DiscoverAndLoadModules()
   at Nethermind.Cli.Program.Main()
```

Launching from Explorer on Windows 20H2.

**Comment by yorickdowne** [comment]
Confirmed. Nethermind.Runner.exe works fine; Nethermind.Cli.exe terminates with the errors above.
