### ISSUE TITLE
Large debug_traceTransaction results in Stream too long error

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#2677]
Command:
```
curl -X POST  -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x7a97e47f9399b46c3e8ee444778763a4f331fa182b5c28c1ba98709721f71f7d"],"id":1}'
```

Error:
```
2021-01-22 15:42:29.7416|ERROR|197|Connection id "0HM5UT8QQCL5H", Request id "0HM5UT8QQCL5H:00000001": An unhandled exception was thrown by the application. System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
   at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
   at Nethermind.JsonRpc.Modules.DebugModule.GethLikeTxTraceConverter.WriteEntries(JsonWriter writer, List`1 entries, JsonSerializer serializer)
   at Nethermind.JsonRpc.Modules.DebugModule.GethLikeTxTraceConverter.WriteJson(JsonWriter writer, GethLikeTxTrace value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Nethermind.Serialization.Json.EthereumJsonSerializer.Serialize[T](Stream stream, T value, Boolean indented)
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

The output of this debug is 3.4GB lol

**Comment by LukaszRozmej** [comment]
.net memory limit for streams is currently 2 GB

**Comment by MysticRyuujin** [comment]
Hello, do you guys think it would be possible to impliment `debug_standardTraceBlockToFile` as an alternative here?

I'm asking Turbo-Geth if they will support it, and I'd like to ask you to support it as well so that we can make this project a reality:

https://chasewright.com/ethereum-and-ipfs/

https://github.com/ethereum/go-ethereum/issues/22244#issuecomment-772804809

**Comment by MysticRyuujin** [comment]
#2263

**Comment by LukaszRozmej** [comment]
Yes should be easy to do, added to my TODO list

**Comment by LukaszRozmej** [comment]
Closing issue, works fine without Buffering Responses added docs

**Comment by MysticRyuujin** [comment]
FWIW, I think it's impossible to debug `0xd80a10106f2a8fb76cf6db6b9f7a64f08257b4952c94c888e1ac41ceb80733c9` without this function.
