### ISSUE TITLE
Nethermind generating and unlocking accounts every time in Aura consensus

### ISSUE THREAD

**Issue by kuzdogan** [NethermindEth/nethermind#2733]
I'm setting up Nethermind for an Aura network and every time I see Nethermind generating and unlocking the same accounts on each run. I just want to use an existing address of which I hold the keys.
![image](https://user-images.githubusercontent.com/13069972/106605887-b0f4d300-6561-11eb-9c73-7c787f089958.png)

Still, the authority address is set up correctly as `0x021bc58...` in this case, and I can set its key accordingly as explained in the [docs](https://docs.nethermind.io/nethermind/guides-and-helpers/validator-setup/aura-validator#mining-private-key). The node gets set up to sign keys with `0x021bc58...`.

But why are the other accounts always being generated, and are they of any use? In our case, the existence of multiple keys may cause confusion to the admins running authority nodes.

Thanks

**Comment by tkstanczak** [comment]
@matilote @LukaszRozmej @MarekM25 <- need the KeyStore/AuRa task force to help here

**Comment by LukaszRozmej** [comment]
Hi so there is a separate key used for network communication which needs to be unique. Its completely separate thing from consensus mechanism in AuRa. This key is then used in your public enode for example. You can set it up in KeyStoreConfig in EnodeAccount property: https://docs.nethermind.io/nethermind/ethereum-client/configuration/modules/keystore

**Comment by tkstanczak** [comment]
@LukaszRozmej wy are there three accounts unlocked?
@kuzdogan , does it answer your question?

**Comment by kuzdogan** [comment]
I see. Is there a particular reason not to use the signer account as the network communication account? 

I tried passing `EnodeAccount` and `EnodeKeyFile`. Here are the results.

## Command line options
Also when I'm trying to set `--Keystore.EnodeAccount` or `--Keystore.EnodeKeyFile` as params I am getting errors below that the options are not recognized. 

I have the `nethermind:latest` image `9608489ca2a1`. My running command is as follows in the docker container. 

**EnodeAccount:**
```
./Nethermind.Runner --config  /nethermind/configs/bloxberg.cfg --Network.ExternalIp ${NAT_IP} 
--KeyStore.BlockAuthorAccount ${PUBLIC_ADDRESS} 
--KeyStore.UnlockAccounts ["${PUBLIC_ADDRESS}"] 
--Keystore.EnodeAccount ${PUBLIC_ADDRESS}
```
```
bloxbergValidator-nethermind | =====Starting from the script=====
bloxbergValidator-nethermind | 2021-02-03 12-04-49.4186|Nethermind starting initialization.
bloxbergValidator-nethermind | 2021-02-03 12-04-49.4340|Loading embedded plugins
bloxbergValidator-nethermind | 2021-02-03 12-04-49.4345|  Found plugin type Nethermind.Consensus.Clique.CliquePlugin
bloxbergValidator-nethermind | 2021-02-03 12-04-49.4345|  Found plugin type Nethermind.Consensus.Ethash.EthashPlugin
bloxbergValidator-nethermind | 2021-02-03 12-04-49.4345|  Found plugin type Nethermind.Consensus.Ethash.NethDevPlugin
bloxbergValidator-nethermind | Resolved executing directory as /nethermind.
bloxbergValidator-nethermind | 2021-02-03 12-04-49.5040|Loading 1 assemblies from /nethermind/plugins
bloxbergValidator-nethermind | 2021-02-03 12-04-49.5042|Loading assembly Nethermind.HealthChecks
bloxbergValidator-nethermind | 2021-02-03 12-04-49.5063|  Found plugin type Nethermind.HealthChecks
bloxbergValidator-nethermind | Specify --help for a list of available options and commands.
bloxbergValidator-nethermind | 2021-02-03 12:04:49.8158|Failure Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized option '--Keystore.EnodeAccount'
bloxbergValidator-nethermind |    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
bloxbergValidator-nethermind |    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
bloxbergValidator-nethermind |    at Nethermind.Runner.Program.Run(String[] args) in /src/Nethermind/Nethermind.Runner/Program.cs:line 195
bloxbergValidator-nethermind |    at Nethermind.Runner.Program.Main(String[] args) in /src/Nethermind/Nethermind.Runner/Program.cs:line 73
bloxbergValidator-nethermind exited with code 0
```

**EnodeKeyFile:**
```
./Nethermind.Runner --config  /nethermind/configs/bloxberg.cfg --Network.ExternalIp ${NAT_IP} 
--KeyStore.BlockAuthorAccount ${PUBLIC_ADDRESS} 
--KeyStore.UnlockAccounts ["${PUBLIC_ADDRESS}"] 
--Keystore.EnodeKeyFile /nethermind/keystore/key-021bc580151828bf75c733bd917ffba3230040a7
```
```
bloxbergValidator-nethermind | =====Starting from the script=====
bloxbergValidator-nethermind | 2021-02-03 12-05-45.7530|Nethermind starting initialization.
bloxbergValidator-nethermind | 2021-02-03 12-05-45.7687|Loading embedded plugins
bloxbergValidator-nethermind | 2021-02-03 12-05-45.7691|  Found plugin type Nethermind.Consensus.Clique.CliquePlugin
bloxbergValidator-nethermind | 2021-02-03 12-05-45.7691|  Found plugin type Nethermind.Consensus.Ethash.EthashPlugin
bloxbergValidator-nethermind | 2021-02-03 12-05-45.7691|  Found plugin type Nethermind.Consensus.Ethash.NethDevPlugin
bloxbergValidator-nethermind | Resolved executing directory as /nethermind.
bloxbergValidator-nethermind | 2021-02-03 12-05-45.8389|Loading 1 assemblies from /nethermind/plugins
bloxbergValidator-nethermind | 2021-02-03 12-05-45.8390|Loading assembly Nethermind.HealthChecks
bloxbergValidator-nethermind | 2021-02-03 12-05-45.8411|  Found plugin type Nethermind.HealthChecks
bloxbergValidator-nethermind | Specify --help for a list of available options and commands.
bloxbergValidator-nethermind | 2021-02-03 12:05:46.1477|Failure Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized option '--Keystore.EnodeKeyFile'
bloxbergValidator-nethermind |    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
bloxbergValidator-nethermind |    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
bloxbergValidator-nethermind |    at Nethermind.Runner.Program.Run(String[] args) in /src/Nethermind/Nethermind.Runner/Program.cs:line 195
bloxbergValidator-nethermind |    at Nethermind.Runner.Program.Main(String[] args) in /src/Nethermind/Nethermind.Runner/Program.cs:line 73
bloxbergValidator-nethermind exited with code 0
```

## Config file 

When I set the `Keystore.EnodeAccount` in the config file the accounts are still generated and unlocked but I get the node address as the miner address :heavy_check_mark: :

**EnodeAccount:**
```
"EnodeAccount": "0x021bc580151828bf75c733bd917ffba3230040a7"
```
Output:
```
bloxbergValidator-nethermind | 2021-02-03 10-32-17.1301|Reading config file from /nethermind/configs/bloxberg.cfg
bloxbergValidator-nethermind | 2021-02-03 10-32-17.4843|Configuration initialized.
bloxbergValidator-nethermind | 2021-02-03 10:32:17.7964|Using the external IP override: NetworkConfig.ExternalIp = 141.84.69.88 
bloxbergValidator-nethermind | 2021-02-03 10:32:21.6487|Unlocking account: 0x7e5f4552091a69125d5dfcb7b8c2659029395bdf 
bloxbergValidator-nethermind | 2021-02-03 10:32:25.0648|Unlocking account: 0x2b5ad5c4795c026514f8317c7a215e218dccd6cf 
bloxbergValidator-nethermind | 2021-02-03 10:32:29.1101|Unlocking account: 0x6813eb9362372eef6200f3b1dbc3f819671cba69 
bloxbergValidator-nethermind | 2021-02-03 10:32:29.5266|Block tree initialized, last processed is 0, best queued is 0, best known is 0, lowest inserted header , body  
bloxbergValidator-nethermind | 2021-02-03 10:32:29.5266|Address 0x021bc580151828bf75c733bd917ffba3230040a7 is configured for signing blocks. 
...
bloxbergValidator-nethermind | ======================== Nethermind initialization completed ========================
bloxbergValidator-nethermind | Version      : 1.10.14-0-a6c443fb2-20210203/X64-Linux/5.0.2
bloxbergValidator-nethermind | This node    : enode://683a8ae4b2a4d26f3c0a56bb82cdf47eef6f42366e3b21d6385e5744bcfddf7deab29bab302632a99ad91d6b589680ffc6a97b8bf62c0296abadae6f6a1b0528@141.84.69.88:30303
bloxbergValidator-nethermind | RPC modules  : 
bloxbergValidator-nethermind | Node address : 0x021bc580151828bf75c733bd917ffba3230040a7 (do not use as an account)
bloxbergValidator-nethermind | Mem est tx   :     82MB
bloxbergValidator-nethermind | Mem est DB   :     67MB
bloxbergValidator-nethermind | JSON RPC     : http://127.0.0.1:8545
bloxbergValidator-nethermind | Genesis hash : 0x2b7c083fa74bfc3327bf2510adf0a24452d39cd260bcf11fadbd7274861d0449
bloxbergValidator-nethermind | External IP  : <hiding ip>
bloxbergValidator-nethermind | Ethereum     : tcp://<hiding ip>:30303
bloxbergValidator-nethermind | Discovery    : udp://<hiding ip>:30303
bloxbergValidator-nethermind | Chainspec    : /nethermind/chainspec/bloxberg.json
bloxbergValidator-nethermind | Chain ID     : 8995
bloxbergValidator-nethermind | Chain head   : 0
bloxbergValidator-nethermind | ===================================================================================== 
```
**EnodeKeyFile**
However setting the `EnodeKeyFile` fails and again, generates accounts:
```
"EnodeKeyFile": "/nethermind/keystore/key-021bc580151828bf75c733bd917ffba3230040a7"
```
Output:
```
bloxbergValidator-nethermind | 2021-02-03 12-00-33.3805|Reading config file from /nethermind/configs/bloxberg.cfg
bloxbergValidator-nethermind | 2021-02-03 12-00-33.7335|Configuration initialized.
bloxbergValidator-nethermind | 2021-02-03 12:00:34.0300|Using the external IP override: NetworkConfig.ExternalIp = 141.84.69.88 
bloxbergValidator-nethermind | 2021-02-03 12:00:37.9574|Unlocking account: 0x7e5f4552091a69125d5dfcb7b8c2659029395bdf 
bloxbergValidator-nethermind | 2021-02-03 12:00:41.5052|Unlocking account: 0x2b5ad5c4795c026514f8317c7a215e218dccd6cf 
bloxbergValidator-nethermind | 2021-02-03 12:00:44.7309|Unlocking account: 0x6813eb9362372eef6200f3b1dbc3f819671cba69 
bloxbergValidator-nethermind | 2021-02-03 12:00:44.7362|Step SetupKeyStore            failed after 10519ms System.ArgumentException: PrivateKey should be 32 bytes long (Parameter 'keyBytes')
bloxbergValidator-nethermind |    at Nethermind.Crypto.PrivateKey..ctor(Byte[] keyBytes) in /src/Nethermind/Nethermind.Crypto/PrivateKey.cs:line 55
bloxbergValidator-nethermind |    at Nethermind.Wallet.NodeKeyManager.<LoadNodeKey>g__LoadKeyFromFile|9_0() in /src/Nethermind/Nethermind.Wallet/NodeKeyManager.cs:line 87
bloxbergValidator-nethermind |    at Nethermind.Wallet.NodeKeyManager.LoadNodeKey() in /src/Nethermind/Nethermind.Wallet/NodeKeyManager.cs:line 110
bloxbergValidator-nethermind |    at Nethermind.Runner.Ethereum.Steps.SetupKeyStore.<>c__DisplayClass2_0.<Execute>b__0() in /src/Nethermind/Nethermind.Runner/Ethereum/Steps/SetupKeyStore.cs:line 75
bloxbergValidator-nethermind |    at System.Threading.Tasks.Task.InnerInvoke()
bloxbergValidator-nethermind |    at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
bloxbergValidator-nethermind |    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
bloxbergValidator-nethermind | --- End of stack trace from previous location ---
bloxbergValidator-nethermind |    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
bloxbergValidator-nethermind |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
bloxbergValidator-nethermind | --- End of stack trace from previous location ---
bloxbergValidator-nethermind |    at Nethermind.Runner.Ethereum.Steps.SetupKeyStore.Execute(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Runner/Ethereum/Steps/SetupKeyStore.cs:line 44
bloxbergValidator-nethermind | 2021-02-03 12:00:44.8098|Block tree initialized, last processed is 0, best queued is 0, best known is 0, lowest inserted header , body  
bloxbergValidator-nethermind | 2021-02-03 12:00:44.8098|No address is configured for signing blocks. 
bloxbergValidator-nethermind | 2021-02-03 12:00:44.8175|Initializing 4 plugins 
bloxbergValidator-nethermind | 2021-02-03 12:00:44.8175|  Clique by Nethermind 
bloxbergValidator-nethermind | 2021-02-03 12:00:44.8182|  Clique by Nethermind initialized in 0ms 
bloxbergValidator-nethermind | 2021-02-03 12:00:44.8182|  Ethash by Nethermind 
bloxbergValidator-nethermind | 2021-02-03 12:00:44.8182|  Ethash by Nethermind initialized in 0ms 
bloxbergValidator-nethermind | 2021-02-03 12:00:44.8182|  NethDev by Nethermind 
bloxbergValidator-nethermind | 2021-02-03 12:00:44.8182|  NethDev by Nethermind initialized in 0ms 
bloxbergValidator-nethermind | 2021-02-03 12:00:44.8182|  HealthChecks by Nethermind 
bloxbergValidator-nethermind | 2021-02-03 12:00:44.8182|  HealthChecks by Nethermind initialized in 1ms 
bloxbergValidator-nethermind | 2021-02-03 12:00:45.0109|Found no blocks to load from DB 
bloxbergValidator-nethermind | 2021-02-03 12:00:45.0199|Numbers resolved, level = Max(0, 0), header = Max(0, 0), body = Max(0, 0) 
bloxbergValidator-nethermind | 2021-02-03 12:00:45.0334|Step InitializeNetworkAuRa    failed after 10ms Nethermind.Runner.Ethereum.Steps.StepDependencyException: NodeKey
bloxbergValidator-nethermind |    at Nethermind.Runner.Ethereum.Steps.InitializeNetwork.InitDiscovery() in /src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeNetwork.cs:line 265
bloxbergValidator-nethermind |    at Nethermind.Runner.Ethereum.Steps.InitializeNetwork.Initialize(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeNetwork.cs:line 161
bloxbergValidator-nethermind |    at Nethermind.Runner.Ethereum.Steps.InitializeNetwork.Execute(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeNetwork.cs:line 86
bloxbergValidator-nethermind | 2021-02-03 12:00:45.0826|Step RegisterRpcModules       failed after 45ms Nethermind.Runner.Ethereum.Steps.StepDependencyException: PeerManager
bloxbergValidator-nethermind |    at Nethermind.Runner.Ethereum.Steps.RegisterRpcModules.Execute(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Runner/Ethereum/Steps/RegisterRpcModules.cs:line 152
bloxbergValidator-nethermind | 2021-02-03 12:00:45.0826|Starting AuRa block producer & sealer 
bloxbergValidator-nethermind | 2021-02-03 12:00:45.0906|Starting AuRa block producer & sealer 
bloxbergValidator-nethermind | 2021-02-03 12:00:45.0972|Grafana / Prometheus metrics are disabled in configuration 
bloxbergValidator-nethermind | 2021-02-03 12:00:45.2190|
bloxbergValidator-nethermind | ======================== Nethermind initialization completed ========================
bloxbergValidator-nethermind | Mem est tx   :     82MB
bloxbergValidator-nethermind | Mem est DB   :    100MB
bloxbergValidator-nethermind | JSON RPC     : http://127.0.0.1:8545
bloxbergValidator-nethermind | Genesis hash : 0x2b7c083fa74bfc3327bf2510adf0a24452d39cd260bcf11fadbd7274861d0449
bloxbergValidator-nethermind | External IP  : <hiding ip>
bloxbergValidator-nethermind | Chainspec    : /nethermind/chainspec/bloxberg.json
bloxbergValidator-nethermind | Chain ID     : 8995
bloxbergValidator-nethermind | Chain head   : 0
bloxbergValidator-nethermind | ===================================================================================== 
bloxbergValidator-nethermind | 2021-02-03 12:00:46.0406|Peers | with known best block: 0 | all: 0 | 
bloxbergValidator-nethermind | 2021-02-03 12:00:46.0406|Waiting for peers... 1s 
bloxbergValidator-nethermind | 2021-02-03 12:00:46.0509|Sync peers - Initialized: 0 | All: 0 | Max: 256 
bloxbergValidator-nethermind | 2021-02-03 12:00:47.0525|Waiting for peers... 2s 
...
bloxbergValidator-nethermind | 2021-02-03 12:00:49.0534|Waiting for peers... 15s
``` 

Prior to each run I delete `logs/` `db/` and `UTC-*` keys in the keystore.

I'd say passing the `EnodeAccount` in the config file seems to be working out for us but the errors associated with the command line options are still there and generation of accounts still happens even with `EnodeAccount`.

**Comment by tkstanczak** [comment]
@MarekM25 @LukaszRozmej @matilote 
this spans on all of your areas -> setup docs, keystore, aura setup, would you have a look
I find the keystore setup also a bit confusing now

**Comment by tkstanczak** [comment]
@kuzdogan the three accounts that you see unlocked are due to: 
    "EnableUnsecuredDevWallet": true,

Please set it to false

**Comment by LukaszRozmej** [comment]
@tkstanczak keystore setup mimics OpenEthereum one.
@kuzdogan either you have EnableUnsecuredDevWallet set or those unlocks are from KeystoreConfig.UnlockAccounts

**Comment by kuzdogan** [comment]
Thanks for the responses. 

The first issue about `--Keystore.EnodeAccount` is due to a typo. Must be `--KeyStore.EnodeAccount` :smile: ~~Keystore~~ KeyStore

Setting `EnableUnsecuredDevWallet: false` also solved the account generation issue. It seems I turned it on when I was trying to make the client use an existing key in the `KeyStore.KeyStoreDirectory` as explained [here](https://docs.nethermind.io/nethermind/guides-and-helpers/validator-setup/aura-validator#mining-private-key). My conclusion from the [description](https://docs.nethermind.io/nethermind/ethereum-client/configuration/modules/init) of the property `EnableUnsecuredDevWallet` was that I need to set it to `true` to be able to use the custom `KeyStore.KeyStoreDirectory`:
```
EnableUnsecuredDevWallet |         If 'true' then it enables the wallet / key store in the application.
``` 

Thanks a lot for the support!
