### ISSUE TITLE
DB problem when upgrading from 1.8 to 1.10

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2849]
Mar 05 07:14:03 archivenode101 Nethermind.Runner[25308]: 2021-03-05 07:14:03.5139|Found 11211 blocks to load from DB starting from current head block 11965316 (0xf7e2a2...82b397)
Mar 05 07:14:03 archivenode101 Nethermind.Runner[25308]: 2021-03-05 07:14:03.5654|BlockchainProcessor encountered an exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
Mar 05 07:14:03 archivenode101 Nethermind.Runner[25308]:    at Nethermind.Core.Caching.LruCache`2.NodeRemove(Int32 i, Boolean cleanValues)
Mar 05 07:14:03 archivenode101 Nethermind.Runner[25308]:    at Nethermind.Core.Caching.LruCache`2.Replace(TKey key, TValue value)
Mar 05 07:14:03 archivenode101 Nethermind.Runner[25308]:    at Nethermind.Core.Caching.LruCache`2.Set(TKey key, TValue val)

**Comment by rhaenni** [comment]
I encountered this problem. I have now also tested with 1.10.37 and instead of the LruCache error above I am getting a new error (and node doesn't process blocks):

```
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]: 2021-03-12 15:43:43.7534|Building ethash cache for epoch 401
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]: 2021-03-12 15:43:43.7534|Building ethash cache for epoch 400
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]: 2021-03-12 15:43:43.9737|BlockchainProcessor encountered an exception. System.InvalidOperationException: The LinkedList is empty.
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at System.Collections.Generic.LinkedList`1.RemoveFirst()
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Core.Caching.LruCache`2.Replace(TKey key, TValue value)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Core.Caching.LruCache`2.Set(TKey key, TValue val)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Trie.CachingStore.get_Item(Byte[] key)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak startRootHash)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.State.StateTree.Get(Address address, Keccak rootHash)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.State.StateProvider.GetState(Address address)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.State.StateProvider.GetAndAddToCache(Address address)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.State.StateProvider.AccountExists(Address address)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean isCall)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Blockchain.Processing.BlockProcessor.ProcessTransactions(Block block, ProcessingOptions processingOptions, IBlockTracer blockTracer)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Blockchain.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Blockchain.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Blockchain.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop()
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at System.Threading.Tasks.Task.InnerInvoke()
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]: --- End of stack trace from previous location ---
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 12 15:43:43 archivenode101 Nethermind.Runner[197146]:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by tkstanczak** [comment]
@rhaenni can you check what is your --Init.MemoryHint setting?
(do you keep it default or override it?)

**Comment by rhaenni** [comment]
set in config file as ` "MemoryHint": 58304000000`

**Comment by rhaenni** [comment]
I have tried setting MemoryHint to the default `"MemoryHint": 4096000000` and using 1.10.37 it now works fine! So only when I set MemoryHint to 58GB I am getting the LinkedList error above.

**Comment by nuevoalex** [comment]
This appears to still be an issue. I'm seeing this same error when upgrading from 1.10.46 to 1.10.56 and it is only resolved by dropping the memory hint. Is this on the radar to be addressed? Thanks!

**Comment by tkstanczak** [comment]
Fixed @rhaenni @nuevoalex
