### ISSUE TITLE
[Bug] [1.10.27] Nethermind.Core.Caching.LruCache - Index was outside the bounds of the array

### ISSUE THREAD

**Issue by Texnomic** [NethermindEth/nethermind#2862]
When I increase MemoryHint to 20GB the Blockchain Processor Crashes & Stops Working

```csharp
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Nethermind.Core.Caching.LruCache`2.NodeRemove(Int32 i, Boolean cleanValues)
   at Nethermind.Core.Caching.LruCache`2.Replace(TKey key, TValue value)
   at Nethermind.Core.Caching.LruCache`2.Set(TKey key, TValue val)
   at Nethermind.Trie.CachingStore.get_Item(Byte[] key)
   at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak)
   at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree)
   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak startRootHash)
   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash)
   at Nethermind.State.StateTree.Get(Address address, Keccak rootHash)
   at Nethermind.State.StateProvider.GetState(Address address)
   at Nethermind.State.StateProvider.GetAndAddToCache(Address address)
   at Nethermind.State.StateProvider.AccountExists(Address address)
   at Nethermind.Blockchain.Processing.BlockProcessor.ApplyMinerReward(Block block, BlockReward reward)
   at Nethermind.Blockchain.Processing.BlockProcessor.ApplyMinerRewards(Block block, IBlockTracer tracer)
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options)
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

Once I revert it back to 4GB, it worked normally.

**Comment by tkstanczak** [comment]
Thank you @Texnomic - this has been reported a few times over the weekend. We are working on a fix.

**Comment by jaensen** [comment]
@Texnomic thanks for the workaround :) Wouldn't have guessed that it's the memory limit.
