### ISSUE TITLE
Set Bootnodes using --bootnodes cli flag

### ISSUE THREAD

**Issue by mFarghaly** [NethermindEth/nethermind#3185]
**Is your feature request related to a problem? Please describe.**
We're developing multi-client Ethereum deployer [kotal](https://kotal.co).
All Ethereum clients (geth, open ethereum, and besu) supports passing bootnodes to the node using `--bootnode` flag
There's no way to set bootnodes in Nethermind

**Describe the solution you'd like**
Add a new cli flag `--bootnodes` or `--discovery.bootnodes` that accepts a comma-separated node URLs

**Additional context**
https://discord.com/channels/629004402170134531/629004402170134537/859495946761273345

**Comment by MicahZoltu** [comment]
`dotnet run --configuration Release --Discovery.Bootnodes ""` works while `docker container run --rm -it nethermind/nethermind:1.10.73 --Discovery.Bootnodes ""` yields the following error:
```
Failure Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized option '--Discovery.Bootnodes'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Nethermind.Runner.Program.Run(String[] args) in /src/Nethermind/Nethermind.Runner/Program.cs:line 201
   at Nethermind.Runner.Program.Main(String[] args) in /src/Nethermind/Nethermind.Runner/Program.cs:line 73
```

I have no idea why Docker doesn't like the `Discovery.Bootnodes` option but local run is fine with it.

**Comment by 1swaraj** [comment]
Closing this issue as it is fixed..
