### ISSUE TITLE
'Incorrect message' when calling any JSON-RPC endpoint using Curl

### ISSUE THREAD

**Issue by ruellm** [NethermindEth/nethermind#3219]
**Describe the bug**

**To Reproduce**
1. Cloned nethermind master branch
2. Run Spaceneth local testnet using default config

```
{
    "Init": {
        "WebSocketsEnabled": true,
        "StoreReceipts" : true,
        "EnableUnsecuredDevWallet": true,
        "IsMining": true,
        "ChainSpecPath": "C:/NethermindNodes/genesis/spaceneth.json",
        "BaseDbPath": "nethermind_db/spaceneth",
        "LogFileName": "spaceneth.logs.txt",
        "StaticNodesPath": "C:/NethermindNodes/staticNodes/static-nodes.json"
    },
    "Network": {
        "DiscoveryPort": 30300,
        "P2PPort": 30300,
        "LocalIp": "127.0.0.1",
        "ExternalIp": "127.0.0.1"
    },
    "JsonRpc": {
        "Enabled": true,
        "Host": "127.0.0.1",
        "Port": 8545
    }
}
```
genesis same as here https://docs.nethermind.io/nethermind/ethereum-client/private-networks/how-to-setup-a-nethermind-only-spaceneth-based-chain

3. run **any** RPC API from here https://docs.nethermind.io/nethermind/ethereum-client/json-rpc/eth
```
curl --data '{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```
4. ERROR occured

result from curl
```
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Incorrect message"},"id":null}
```

Display in console of the node
```
2021-07-12 18:52:48.6142|Error during parsing/validation, request: '{method:eth_chainId,params:[],id:1,jsonrpc:2.0}' Newtonsoft.Json.JsonSerializationException: Error converting value "{method:eth_chainId,params:[],id:1,jsonrpc:2.0}" to type 'Nethermind.JsonRpc.JsonRpcRequest'. Path '', line 1, position 49.
 ---> System.ArgumentException: Could not cast or convert from System.String to Nethermind.JsonRpc.JsonRpcRequest.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Nethermind.JsonRpc.JsonRpcProcessor.DeserializeObjectOrArray(String json) in C:\Scopic\workspace\petrachor\nethermind\src\Nethermind\Nethermind.JsonRpc\JsonRpcProcessor.cs:line 98
   at Nethermind.JsonRpc.JsonRpcProcessor.ProcessAsync(String request, JsonRpcContext context) in C:\Scopic\workspace\petrachor\nethermind\src\Nethermind\Nethermind.JsonRpc\JsonRpcProcessor.cs:line 135
```

**Expected behavior**
Should return or recognize the RPC API

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - CURL version: curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL

**Comment by tkstanczak** [comment]
We need to modify the default config for spaceneth to support all JSON RPC out of the box.

**Comment by ruellm** [comment]
> We need to modify the default config for spaceneth to support all JSON RPC out of the box.

Can you teach or guide me how to do it myself? id like to have this working on my side as i have some deadline to deal with

**Comment by MicahZoltu** [comment]
@tkstanczak The `Eth` module should be enabled by default, at least according to the docs.  `eth_chainId` is in the `EthRpcModule`, so this should work out of the box.

I'm not in a position to test this myself at the moment, but it definitely seems like this should work without any additional configuration.

The error message here is a bit weird to me.  It says it is trying to cast a string to a JsonRpcRequest and the string it is trying to convert isn't valid JSON, despite the user sending valid JSON (quoted members).  This is probably just an artifact of the error reporting, but I find it surprising none the less.

**Comment by ruellm** [comment]
> Windows expect different formatting in curl requests. Take a look at the logs:
> `{method:eth_chainId,params:[],id:1,jsonrpc:2.0}`
> @ruellm Try this for example:
> `curl --data {\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1,\"jsonrpc\":\"2.0\"} -H "Content-Type: application/json" -X POST http://127.0.0.1:8545/`

works perfectly, thanks!
