### ISSUE TITLE
IPC RPC request parsing error

### ISSUE THREAD

**Issue by chebykin** [NethermindEth/nethermind#3345]
IPC RPC can't parse two combined requests sent within a single message using web3.js. 

**To Reproduce**

Using web3.js subscribe for updates and specify a block to subscribe from:

```js
const Web3 = require('web3');
const net = require('net');
const web3 = new Web3(new Web3.providers.IpcProvider('/path/to/xdai/ipc/jsonrpc.ipc', net));

(async function () {
  web3.eth
    .subscribe('logs', { fromBlock: '17788909', address: '0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d' })
    .on('data', function (log) {
      console.log('>>>', log.blockNumber, log.transactionHash);
    })
})();
```

JS error:

```js
/home/ubuntu/app/node_modules/web3/node_modules/web3-providers-ipc/lib/index.js:49
        if (!id && result.method.indexOf('_subscription') !== -1) {
                                 ^

TypeError: Cannot read property 'indexOf' of undefined
    at callback (/home/ubuntu/app/node_modules/web3/node_modules/web3-providers-ipc/lib/index.js:49:34)
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/home/ubuntu/app/node_modules/web3/node_modules/web3-providers-ipc/lib/index.js:68:51)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

RPC module log:

```
Aug 27 13:37:19 frontier Nethermind.Runner[22942]: 2021-08-27 13:37:19.9958|Error during parsing/validation, request: {"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"fromBlock":"0x10f6fed","address":"0xe91d153e0b41518a2ce8dd3d7944fa863463a97d","topics":[]}]}{"jsonrpc":"2.0","id":2,"method":"eth_subscribe","params":["logs",{"address":"0xe91d153e0b41518a2ce8dd3d7944fa863463a97d","topics":[]}]} Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: {. Path '', line 1, position 151.
Aug 27 13:37:19 frontier Nethermind.Runner[22942]:    at Newtonsoft.Json.JsonTextReader.Read()
Aug 27 13:37:19 frontier Nethermind.Runner[22942]:    at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
Aug 27 13:37:19 frontier Nethermind.Runner[22942]:    at Nethermind.JsonRpc.JsonRpcProcessor.DeserializeObjectOrArray(String json)
Aug 27 13:37:19 frontier Nethermind.Runner[22942]:    at Nethermind.JsonRpc.JsonRpcProcessor.ProcessAsync(String request, JsonRpcContext context)
```

**Expected behavior**

Parity and Geth work fine with this case.

**Comment by chebykin** [comment]
I want to clarify this a bit more. I was wrong in writing that these `eth_getLogs` and `eth_subscribe` requests were sent within a single socket message. Actually, each of them is sent with separate `net.Socket.write` call [here](https://github.com/ChainSafe/web3.js/blob/c70722b919ac81e45760b9648c4b92fd8d0eeee1/packages/web3-providers-ipc/src/index.js#L212).

Also, the same subscription example above can be handled by Nethermind either correctly, as two distinct requests, or with an error, when it treats these two requests as a single one.

**Comment by dceleda** [comment]
@chebykin could you post here the response you get from Geth ?

**Comment by dceleda** [comment]
https://github.com/ethereum/go-ethereum/issues/23575

**Comment by dceleda** [comment]
It seems Geth handles such scenario differently in WS and in IPC.
https://github.com/ethereum/go-ethereum/issues/23575
