### ISSUE TITLE
[Bug] [1.11.1] [Achieve] Huge Memory Leak Causes OutOfMemoryException

### ISSUE THREAD

**Issue by Texnomic** [NethermindEth/nethermind#3393]
Huge Memory Leak Causes OutOfMemoryException When Running Nethermind in Mainnet Achieve Mode.

This leak consumes over 200 GB of RAM in less than 24 hours.

![image](https://user-images.githubusercontent.com/1648586/132684216-a0194692-ba2c-4244-823d-6fd23df9aba1.png)

![image](https://user-images.githubusercontent.com/1648586/132684398-4499cbe8-ed84-452d-8642-3efe74b5730f.png)

```json
{
  "Init": {
    "WebSocketsEnabled": true,
    "StoreReceipts": true,
    "IsMining": false,
    "ChainSpecPath": "chainspec/foundation.json",
    "GenesisHash": "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
    "BaseDbPath": "nethermind_db/mainnet_archive",
    "LogFileName": "mainnet_archive.logs.txt",
     "MemoryHint": 122880000000
  },
  "Network": {
    "DiscoveryPort": 30303,
    "P2PPort": 30303,
    "ActivePeersMaxCount": 50
  },
  "JsonRpc": {
    "Enabled": true,
    "EnabledModules": "[Admin, Baseline, Clique, Consensus, Db, Debug, Deposit, Erc20, Eth, Evm, Health Mev, NdmConsumer, NdmProvider, Net, Nft, Parity, Personal, Proof, Subscribe, Trace, TxPool, Vault, Web3]",
    "Timeout": 20000,
    "Host": "0.0.0.0",
    "Port": 8545
  },
  "TxPool": {
    "Size": 100000
  },
  "Db": {
    "CacheIndexAndFilterBlocks": false
  },
  "Sync": {
    "DownloadBodiesInFastSync": false,
    "DownloadReceiptsInFastSync": false,
    "UseGethLimitsInFastBlocks": true
  },
  "EthStats": {
    "Enabled": false,
    "Server": "wss://ethstats.net/api",
    "Name": "Nethermind",
    "Secret": "secret",
    "Contact": "hello@nethermind.io"
  },
  "Metrics": {
    "NodeName": "Nethermind",
    "Enabled": true,
    "PushGatewayUrl": "http://10.0.0.33:9091/metrics",
    "IntervalSeconds": 5
  },
  "HealthChecks": {
    "Enabled": true,
    "WebhooksEnabled": false,
    "WebhooksUri": "https://slack.webhook",
    "UIEnabled": true,
    "PollingInterval": 5,
    "Slug": "/api/health",
    "MaxIntervalWithoutProcessedBlock": 15,
    "MaxIntervalWithoutProducedBlock": 45
  }
}
```

```csharp
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.Dictionary`2.Resize(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Nethermind.Core.Caching.LruCache`2.Set(TKey key, TValue val)
   at Nethermind.Trie.CachingStore.get_Item(Byte[] key)
   at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak, IKeyValueStore keyValueStore)
   at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree)
   at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext)
   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak startRootHash)
   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash)
   at Nethermind.State.StorageProvider.LoadFromTree(StorageCell storageCell)
   at Nethermind.State.StorageProvider.GetCurrentValue(StorageCell storageCell)
   at Nethermind.Evm.VirtualMachine.ExecuteCall(EvmState vmState, Byte[] previousCallResult, ZeroPaddedSpan previousCallOutput, UInt256& previousCallOutputDestination, IReleaseSpec spec)
   at Nethermind.Evm.VirtualMachine.Run(EvmState state, ITxTracer txTracer)
   at Nethermind.Evm.TransactionProcessing.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, ExecutionOptions executionOptions)
   at Nethermind.Evm.TransactionProcessing.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer)
   at Nethermind.Blockchain.Processing.TransactionProcessorAdapterExtensions.ProcessTransaction(ITransactionProcessorAdapter transactionProcessor, Block block, Transaction currentTx, BlockReceiptsTracer receiptsTracer, ProcessingOptions processingOptions, IStateProvider stateProvider)
   at Nethermind.Blockchain.Processing.BlockProcessor.BlockValidationTransactionsExecutor.ProcessTransactions(Block block, ProcessingOptions processingOptions, BlockReceiptsTracer receiptsTracer, IReleaseSpec spec)
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options)
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Version Information:**
 - OS: Windows Server 2019 & 2022
 - Browser: Any
 - Version: <= 1.11.1

**Comment by ehabhussein** [comment]
I have the Issue on Ubuntu . but it doesnt throw `OutOfMemoryException` . the node does consume more than the limit i set in the config.

**Comment by ehabhussein** [comment]
On Linux i had to do the following to fix the issue ( this is a hacky work around but the server doesnt suddenly restart anymore) :
```
sysctl -w vm.drop_caches=3
sync
echo 3 | tee /proc/sys/vm/drop_caches
```

**Comment by Texnomic** [comment]
On Windows, I've fixed it by removed `MemoryHint` option to disable built-in memory allocation and manually specify the `Db` options as follows:

```json
"Db": {
    "CacheIndexAndFilterBlocks": true,
    "BlockCacheSize": 81920000000,
    "WriteBufferSize": 51920000000,
    "WriteBufferNumber": 1
  },
```

As a fun fact, the Archive Node performance actually increased from `0.23` bps to `0.94` bps as I expected and reported in #2885
