### ISSUE TITLE
POA Core sync stall / NRE in BlockchainProcessor

### ISSUE THREAD

**Issue by thereapman** [NethermindEth/nethermind#3628]
**Describe the bug**
Experiencing sync stall on POA Core at block 24090739

**To Reproduce**
When running on version 1.11.7 on POA Core it crashes with a NRE inside the `BlockchainProcessor`

**Expected behavior**
Sync should not NRE

**Screenshots**

Log from the console
```
2021-11-20 17:19:52.7496|Processing part of a long blocks branch 0/307091. Block: 24090739 (0xbd654d...92274b)
2021-11-20 17:19:52.7771|BlockchainProcessor encountered an exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Consensus.AuRa.Validators.ContractBasedValidator.LoadValidatorsFromContract(BlockHeader parentHeader) in /src/Nethermind/Nethermind.Consensus.AuRa/Validators/ContractBasedValidator.cs:line 257
   at Nethermind.Consensus.AuRa.Validators.ContractBasedValidator.OnBlockProcessingStart(Block block, ProcessingOptions options) in /src/Nethermind/Nethermind.Consensus.AuRa/Validators/ContractBasedValidator.cs:line 111
   at Nethermind.Consensus.AuRa.Validators.MultiValidator.OnBlockProcessingStart(Block block, ProcessingOptions options) in /src/Nethermind/Nethermind.Consensus.AuRa/Validators/MultiValidator.cs:line 156
   at Nethermind.Consensus.AuRa.AuRaBlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockProcessor.cs:line 89
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 224
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 119
   at Nethermind.Blockchain.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 383
   at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 295
   at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop() in /src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 238
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2021-11-20 17:19:55.3568|Discovered new block 24397955 17:19:55 (0x1cf91a...37d9a3), tx count: 6 miner 0xdc4765d9dabf6c6c4908fe97e649ef1f05cb6252, sent by [Peer|eth66|24397955|OpenEthereum/v
```
**System**
- Nethermind run via Docker

**Comment by LukaszRozmej** [comment]
Hi, this is something unseen before. The only explanation I can find is that it didn't manage to find parent header of the block to be processed.

Can you explain how did you find yourself with a branch of 307091 blocks not processed? This suggest previous issues.

**Comment by thereapman** [comment]
I suspect the host we're running this on might cause this.
We're running on a Contabo VPS and those are known to sometimes throttle I/O pretty hard. 
That could explain the big batch that needs processing. 

Any ideas how to get it out of that hole w/o a resync?

**Comment by LukaszRozmej** [comment]
So the only way this could be NRE is here:

https://github.com/NethermindEth/nethermind/blob/77a5b3ea68287e57a35857d50b30020fdb827877/src/Nethermind/Nethermind.Consensus.AuRa/Validators/ContractBasedValidator.cs#L112

BlockTree.FindParentHeader(block.Header, BlockTreeLookupOptions.None) would have to return null, this would indicate that there is an issue with block tree. 

First can you query eth_getBlockByNumber to get an understanding of the situation?
Even better combite it with [debug.getChainLevel](https://docs.nethermind.io/nethermind/nethermind-utilities/cli/debug#debug.getchainlevel)

Then based on that info we can try [debug_resetHead](https://github.com/NethermindEth/nethermind/blob/8bc2367b60e58ea3f8b6c1b26b7f2ac707925bb8/src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugRpcModule.cs#L37-L40)

**Comment by thereapman** [comment]
K so here the readouts:

*Block #24090739*

```
{
   "jsonrpc":"2.0",
   "result":{
      "author":"0x49bbdebd7f3d39f297135d7af3831ce152a99b67",
      "difficulty":"0xfffffffffffffffffffffffffffffffe",
      "extraData":"0xdb830303008c4f70656e457468657265756d86312e34372e30826c69",
      "gasLimit":"0xe11573",
      "gasUsed":"0x0",
      "hash":"0xbd654d9ca69dea78b21b78b1a94c79628cafb735f6972b0e45ed8145ee92274b",
      "logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "miner":"0x49bbdebd7f3d39f297135d7af3831ce152a99b67",
      "number":"0x16f9873",
      "parentHash":"0x773a38d63347912e5aa509ff2e32d710c743a501dd0e1cb37a63b8af32e7037a",
      "receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      "sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
      "signature":"0x514545f09c6f76ebaaf4987b73bcef4b3f06a214fb51a24bed074ba51b41670529b2ebfc16985eb70ebeb6c723065835925fe244e5a440f73603c83bcb1f4b9a01",
      "size":"0x24b",
      "stateRoot":"0x72d90c089635f5aed58772c64255cf73d63097bdf813310a1600896dee04136f",
      "step":327169440,
      "totalDifficulty":"0x16f9872ffffffffffffffffffffffffeb1231ed",
      "timestamp":"0x61810c20",
      "baseFeePerGas":"0x7",
      "transactions":[
         
      ],
      "transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      "uncles":[
         
      ]
   },
   "id":1
}
```

```
{
   "jsonrpc":"2.0",
   "result":{
      "blockInfos":[
         {
            "blockHash":"0xbd654d9ca69dea78b21b78b1a94c79628cafb735f6972b0e45ed8145ee92274b",
            "totalDifficulty":"0x16f9872ffffffffffffffffffffffffeb1231ed",
            "wasProcessed":false,
            "isFinalized":false
         }
      ],
      "hasBlockOnMainChain":false
   },
   "id":1
}
```

*Block 24090451 (All in between this and the block above are non-existent)* 

```
{
   "jsonrpc":"2.0",
   "result":{
      "author":"0xcf260ea317555637c55f70e55dba8d5ad8414cb0",
      "difficulty":"0xfffffffffffffffffffffffffffffff4",
      "extraData":"0x4e65746865726d696e64",
      "gasLimit":"0x12a388d",
      "gasUsed":"0x186a00",
      "hash":"0x63c6740fd76e0bd74ce1eafa891889cc567ba37daaf625936a3cb4c76cd0d8a6",
      "logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "miner":"0xcf260ea317555637c55f70e55dba8d5ad8414cb0",
      "number":"0x16f9753",
      "parentHash":"0x87b2655b4414aad1ba7fdc9d3b17bd4567402b444422ff8f65021defa6eebc66",
      "receiptsRoot":"0x770afc8e6dd5878db34e137fb505573229abf50d2371df030fd3bdce513a1d94",
      "sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
      "signature":"0xcca51d5972f32aadc5b60faaafc9ab2f0ab985c6f2d9bacd852d456427983a361a447cae60ac924046605893bcfca479ee27c439553ad7808acb989079de465901",
      "size":"0x3ac",
      "stateRoot":"0xc6a6593406f06e3996ebb46850fad9a7bd945503c33a9c78932e5d8f22c28b3a",
      "step":327171592,
      "totalDifficulty":"0x16f9752ffffffffffffffffffffffffeb122aa5",
      "timestamp":"0x61813628",
      "baseFeePerGas":"0x7",
      "transactions":[
         "0xe1b30c7f4a25ff2087246ad16a44b88b6c908a445cbbbd772660bd7a730ca9ec"
      ],
      "transactionsRoot":"0x57004957abefc229161e09833aeb9982f5cd73fbda7e7ce4f04dfc487683e712",
      "uncles":[
         
      ]
   },
   "id":1
}
```

```{
   "jsonrpc":"2.0",
   "result":{
      "blockInfos":[
         {
            "blockHash":"0x63c6740fd76e0bd74ce1eafa891889cc567ba37daaf625936a3cb4c76cd0d8a6",
            "totalDifficulty":"0x16f9752ffffffffffffffffffffffffeb122aa5",
            "wasProcessed":true,
            "isFinalized":false
         }
      ],
      "hasBlockOnMainChain":true
   },
   "id":1
}
```

I guess the next step is to reset head to `24090451`, correct?

**Comment by LukaszRozmej** [comment]
Yes, I don't guarantee it will work, but your block tree already got corrupted somehow

**Comment by LukaszRozmej** [comment]
Waiting for potential feedback.
