### ISSUE TITLE
[1.12.0] Unable to initialize health checks.

### ISSUE THREAD

**Issue by Texnomic** [NethermindEth/nethermind#3640]
Release 1.12.0 Always Crashes due to Health Checks Plugin.

```csharp
System.InvalidOperationException: Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddHealthChecks' inside the call to 'ConfigureServices(...)' in the application startup code.
   at Microsoft.AspNetCore.Builder.HealthCheckEndpointRouteBuilderExtensions.MapHealthChecksCore(IEndpointRouteBuilder endpoints, String pattern, HealthCheckOptions options)
   at Microsoft.AspNetCore.Builder.HealthCheckEndpointRouteBuilderExtensions.MapHealthChecks(IEndpointRouteBuilder endpoints, String pattern, HealthCheckOptions options)
   at Nethermind.Runner.JsonRpc.Startup.<>c__DisplayClass1_0.<Configure>b__3(IEndpointRouteBuilder endpoints)
```

**Comment by LukaszRozmej** [comment]
Hi @Texnomic:
1. Package or docker?
2. Do you have proper Nethermind.HealthChecks.dll in your plugins folder? Its in the released package.
2. If 2nd is yes can you try healthchecks without UI.

**Comment by LukaszRozmej** [comment]
The linked issue fixes CLI and HealthCheckUI in the package. I didn't find that base Healchecks had an issue (but you need proper dll in plugins).

**Comment by Texnomic** [comment]
@LukaszRozmej 

1. Package & Compiling from Source
2. Yes, DLL in Plugin Folder
3. I did, same issue.

**Comment by LukaszRozmej** [comment]
Can you attach all logs from the start to this error?

**Comment by Texnomic** [comment]
I've recompiled from source after #3643 and It is working now

**Comment by LukaszRozmej** [comment]
1.12.1 is out too
