### ISSUE TITLE
Missing Tree node

### ISSUE THREAD

**Issue by nicexe** [NethermindEth/nethermind#3884]
AuRa validator node cannot sync more blocks due to error.

At some point, validator nodes started disconnecting/reporting other validating nodes until each validator node had no more peers to connect to.
I tried to remedy the situation by restarting the nodes in hopes that they connect to each other, reorganize some blocks and continue producing blocks each on their time slot. This worked for a while but then the validator nodes started disconnecting/reporting other validators again.
After a few node restarts I started getting errors like the one shown below.

```
2022-03-17 10:02:03.5812|ERROR|62|BlockchainProcessor encountered an exception. Nethermind.Abi.AbiException: System call to RewardContract.Reward returned an exception 'Failed to load key fcbd49b3a106f7e49c6e147b76ca4682aefd4fe6d07f4368f542751aaf85d596 from root hash 0x51360a56cb5a4d26f340ddb1615eeeb91280f09054e1bce25aa4163c671cdbf7.' at block 257412.
 ---> Nethermind.Trie.TrieException: Failed to load key fcbd49b3a106f7e49c6e147b76ca4682aefd4fe6d07f4368f542751aaf85d596 from root hash 0x51360a56cb5a4d26f340ddb1615eeeb91280f09054e1bce25aa4163c671cdbf7.
 ---> Nethermind.Trie.TrieException: Node 0x51360a56cb5a4d26f340ddb1615eeeb91280f09054e1bce25aa4163c671cdbf7 is missing from the DB
   at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak, IKeyValueStore keyValueStore) in /src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 331
   at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak) in /src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 339
   at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree) in /src/Nethermind/Nethermind.Trie/TrieNode.cs:line 255
   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak startRootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 408
   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 321
   --- End of inner exception stack trace ---
   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 328
   at Nethermind.State.StateTree.Get(Address address, Keccak rootHash) in /src/Nethermind/Nethermind.State/StateTree.cs:line 51
   at Nethermind.State.StateProvider.GetState(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 659
   at Nethermind.State.StateProvider.GetAndAddToCache(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 674
   at Nethermind.State.StateProvider.GetThroughCache(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 695
   at Nethermind.State.StateProvider.GetAccount(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 120
   at Nethermind.Evm.TransactionProcessing.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, ExecutionOptions executionOptions) in /src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs:line 188
   at Nethermind.Evm.TransactionProcessing.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer) in /src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs:line 111
   at Nethermind.Blockchain.Contracts.Contract.CallCore(ITransactionProcessor transactionProcessor, BlockHeader header, String functionName, Transaction transaction, Boolean callAndRestore) in /src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 198
   --- End of inner exception stack trace ---
   at Nethermind.Blockchain.Contracts.Contract.CallCore(ITransactionProcessor transactionProcessor, BlockHeader header, String functionName, Transaction transaction, Boolean callAndRestore) in /src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 205
   at Nethermind.Blockchain.Contracts.CallableContract.Call(BlockHeader header, String functionName, Transaction transaction) in /src/Nethermind/Nethermind.Blockchain/Contracts/CallableContract.cs:line 46
   at Nethermind.Blockchain.Contracts.CallableContract.Call(BlockHeader header, String functionName, Address sender, Int64 gasLimit, Object[] arguments) in /src/Nethermind/Nethermind.Blockchain/Contracts/CallableContract.cs:line 72
   at Nethermind.Consensus.AuRa.Contracts.RewardContract.Reward(BlockHeader blockHeader, Address[] benefactors, UInt16[] kind) in /src/Nethermind/Nethermind.Consensus.AuRa/Contracts/RewardContract.cs:line 79
   at Nethermind.Consensus.AuRa.Rewards.AuRaRewardCalculator.CalculateRewardsWithContract(Block block, IRewardContract contract) in /src/Nethermind/Nethermind.Consensus.AuRa/Rewards/AuRaRewardCalculator.cs:line 110
   at Nethermind.Consensus.AuRa.Rewards.AuRaRewardCalculator.CalculateRewards(Block block) in /src/Nethermind/Nethermind.Consensus.AuRa/Rewards/AuRaRewardCalculator.cs:line 79
   at Nethermind.Blockchain.Processing.BlockProcessor.ApplyMinerRewards(Block block, IBlockTracer tracer, IReleaseSpec spec) in /src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 310
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 258
   at Nethermind.Consensus.AuRa.AuRaBlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockProcessor.cs:line 91
   at Nethermind.Blockchain.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 224
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 119
   at Nethermind.Blockchain.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 383
   at Nethermind.Blockchain.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 295
   at Nethermind.Blockchain.Processing.BlockchainProcessor.RunProcessingLoop() in /src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs:line 238
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

I took a backup of nethermind_db directory and tried the suggestion found here https://github.com/NethermindEth/nethermind/issues/3869#issuecomment-1065067908_ by resetting head to an older block but this didn't work

I restored the backup and tried again but this time using debug_deleteChainSlicem. This also didn't work

If you need the logs for the debug methods I can restore from the backup and try using them again.

**Environment:**
 - Docker host: Ubuntu 20.04
 - Docker container images: [nethermind/nethermind:1.12.5](https://hub.docker.com/layers/nethermind/nethermind/1.12.5/images/sha256-ef0f6e0469425b072a880638b15157730e5fb31f288b0839dedea77dd3fb0533) and [nethermindeth/nethermind:debug_resetHead](https://hub.docker.com/layers/nethermindeth/nethermind/debug_resetHead/images/sha256-5a62c43ed973876ae0d3fcf54cc86cc67aaed18739495d5a11f4f3459d994598)

**Comment by LukaszRozmej** [comment]
Hi @nicexe, at this point of time the best thing is  to resync the node. As this DB/Tree corruption can s ometimes happen, especially on hard restarts we are looking into potential fixes or some healing mechanism.

**Comment by LukaszRozmej** [comment]
One thing you could try, but its not guaranteed to work is setting FastSyncCatchUpHeightDelta in sync module https://docs.nethermind.io/nethermind/ethereum-client/configuration/sync to some low value (like ~100 for example) to trigger FastSync to catch up to chain head.
