### ISSUE TITLE
Calling eth_feeHistory results in a System.FormatException

### ISSUE THREAD

**Issue by FinaChain** [NethermindEth/nethermind#3890]
Metamask calls eth_feeHistory with params [0x400,0x-e3b,[]] and this is the result in version 1.12.6:

2022-03-18 18:55:27.5426|Executing JSON RPC call eth_feeHistory with params [0x400,0x-e3b,[]]
2022-03-18 18:55:27.5426|Error while parsing JSON RPC request parameters System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt64(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int64.Parse(ReadOnlySpan`1 s, NumberStyles style, IFormatProvider provider)
   at Nethermind.Serialization.Json.LongConverter.FromString(String s) in /home/kees/nethermind/src/Nethermind/Nethermind.Serialization.Json/LongConverter.cs:line 85
   at Nethermind.JsonRpc.Data.BlockParameterConverter.GetBlockParameter(String value) in /home/kees/nethermind/src/Nethermind/Nethermind.JsonRpc/Data/BlockParameterConverter.cs:line 149
   at Nethermind.JsonRpc.Data.BlockParameterConverter.ReadJson(JsonReader reader, Type objectType, BlockParameter existingValue, Boolean hasExistingValue, JsonSerializer serializer) in /home/kees/nethermind/src/Nethermind/Nethermind.JsonRpc/Data/BlockParameterConverter.cs:line 130
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Nethermind.JsonRpc.JsonRpcService.DeserializeParameters(ParameterInfo[] expectedParameters, String[] providedParameters, Int32 missingParamsCount) in /home/kees/nethermind/src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs:line 274

**Comment by DockBoss** [comment]
Hello, sorry for the delay.

The issue is that the second parameter(**highest block**) expects a block number. It would have worked fine if the second parameter looked like this `0xe3b`.  Just removing the `-`

You said this is from Metamask, could you elaborate a bit more?

**Comment by LukaszRozmej** [comment]
The 0x-e3b is incorrect parameter in any node implementation and its out of spec, so the behavior looks ok. 

Can you give instructions how to replicate this in MetaMask?

**Comment by LukaszRozmej** [comment]
@FinaChain can you please provide a reproduceable scenario?
