### ISSUE TITLE
Impossible to push a transaction

### ISSUE THREAD

**Issue by cryptoeth1** [NethermindEth/nethermind#3923]
Hello, I'm running a node on Nethermind 1.12.0
Network: xDai, Fast sync, RPC enabled, Ubuntu 18
I connected with metamask (http:127.0.0.1:8545) to my node and tried to send xDai

I constantly get the following error when trying to send:

2022-04-01 20:03:04.5539|Error when handling ID 1092445199633, eth_sendRawTransaction(XXX) | {"jsonrpc":"2.0","error":{"code":-32010,"message":"Filtered"},"id":1092445199633}

When I'm connected to my node I also get many of error messages like this:

30
]] 
2022-04-01 20:43:22.8033|Error while parsing JSON RPC request parameters Newtonsoft.Json.JsonReaderException: Could not convert string to integer: 0x5. Path '', line 1, position 5.
   at Newtonsoft.Json.JsonReader.ReadInt32String(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Nethermind.JsonRpc.JsonRpcService.DeserializeParameters(ParameterInfo[] expectedParameters, String[] providedParameters, Int32 missingParamsCount) 
2022-04-01 20:43:22.8033|Incorrect JSON RPC parameters when calling eth_feeHistory with params [0x5, 0x146c42c, [
  10,
  20,
  30
]] 
2022-04-01 20:43:22.8033|Error when handling ID 2353317747203283, eth_feeHistory(0x5,0x146c42c,[
  10,
  20,
  30
]) | {"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params"},"id":2353317747203283}

**Comment by tkstanczak** [comment]
Thank you, received, the team will triage on Monday.
In the meantime could you change 0x5 in your parameters to 5 in the eth_feeHistory call?

**Comment by cryptoeth1** [comment]
How to change 0x5 in your parameters to 5 in the eth_feeHistory call? This is generated by metamask

**Comment by LukaszRozmej** [comment]
This was fixed in 1.12.2. #3670 #3639
