### ISSUE TITLE
erorr during method execution eth_getBlockByNumber

### ISSUE THREAD

**Issue by unsol** [NethermindEth/nethermind#395]
I am about to be profoundly unhelpful here, so I apologize in advance. I must have seen this error pop up at some point, copy/pasted it, and forgot about it. Feel free to close this issue if you feel there is not enough to act on. I can try and trigger the error again, if you need more info.

So I got Nethermind running (sometime February 20, 2019) with the steps I saved here: https://www.mattbrill.com/2019/02/21/getting-started-with-the-gorli-testnet/#goerliTestnetNethermind

Connected to Goerli.

Then there's this guy. It looks like it may be the same issue as #354.

`2019-02-22 19:21:07.6728|ERROR|7|Error during method execution, request: Id: 171,  JSON RPC: 2.0, Method: eth_getBlockByNumber, Params: System.String[], |System.OverflowException: Value was either too large or too small for a UInt64.
   at System.Numerics.BigInteger.op_Explicit(BigInteger value)
   at Nethermind.Dirichlet.Numerics.UInt256.Create(UInt256& c, BigInteger a) in /home/ubuntu/nethermind/src/Dirichlet/Nethermind.Dirichlet.Numerics/UInt256.cs:line 433
   at Nethermind.Dirichlet.Numerics.UInt256.op_Explicit(BigInteger a) in /home/ubuntu/nethermind/src/Dirichlet/Nethermind.Dirichlet.Numerics/UInt256.cs:line 570
   at Nethermind.JsonRpc.Data.Quantity.AsNumber() in /home/ubuntu/nethermind/src/Nethermind/Nethermind.JsonRpc/Data/Quantity.cs:line 58
   at Nethermind.JsonRpc.Modules.Eth.EthModule.GetBlock(BlockParameter blockParameter) in /home/ubuntu/nethermind/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModule.cs:line 894
   at Nethermind.JsonRpc.Modules.Eth.EthModule.eth_getBlockByNumber(BlockParameter blockParameter, Boolean returnFullTransactionObjects) in /home/ubuntu/nethermind/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModule.cs:line 478`
`2019-02-22 19:21:07.6728|ERROR|7|Failed to respond to eth_getBlockByNumber Internal error|`

**Comment by tkstanczak** [comment]
thank you for reporting!
#354 and this one were considered slightly lower priority as they do not break the block procesing / consensus - I will bump it up in priority in appreciation of the fact that you reported it m, thanks once again, and thanks for setting up the node and writing the walkthrough!

**Comment by tkstanczak** [comment]
And you are very helpful - it is a full stack trace :)!

**Comment by unsol** [comment]
Oh! No need to bump it up in priority, though I do appreciate it. I'm just messing about with Goerli, and saw this popped up. Just wanted to make sure someone knows :)

Thanks again!

**Comment by tkstanczak** [comment]
Seems that it only breaks combined with an incorrect result from eth_syncing.
Modified eth_syncing serialization, fixed the error message to include the actual parameter values. Not fixed yet.

**Comment by tkstanczak** [comment]
2019-03-01 17:34:21.8568|Error during method execution, request: ID 203, version 2.0, eth_getBlockByNumber(0x7b2276616c7565223a22307833366531656430323632633335663466386432643039303532356138373533393066656634356237373265626264376538613234363431616532623764323064222c22626c6f636b4e756d626572223a302c227472616e73616374696f6e496e646578223a302c226c6f67496e646578223a307d,False) System.OverflowException: Value was either too large or too small for a UInt64.

**Comment by unsol** [comment]
Sweet! Thank you for looking in to this so quickly. Much appreciated! I'll keep an eye on future errors, and pass it along to ethstats.

Thanks again!
