### ISSUE TITLE
Error when state stats collector is ON

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#3958]
**Describe the bug**
After setting up a new node on MAINNET and syncing it via Snap Sync there are two issues when we try to run the State Stats Collector:
- it reports some storage nodes missing after a few hours of running
_Collected info from 700000943 nodes. Missing CODE 0 STATE 0 STORAGE 199_
- at some point the client shuts down (memory leak ?)

Config:
_{
  "Init": {
    "ChainSpecPath": "chainspec/foundation.json",
    "GenesisHash": "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
    "BaseDbPath": "/root/db/mainnet",
    "LogFileName": "mainnet.logs.txt",
    "MemoryHint": 2048000000,
    "StoreReceipts": false,
    "DiagnosticMode": 6,
    "ProcessingEnabled": true
  },
  "Network": {
    "ActivePeersMaxCount": 100
  },
  "Sync": {
    "FastSync": true,
    "PivotNumber": 14566000,
    "PivotHash": "0x4ed4a5e2d74631432445dd69cdbfddffbfb4de9c98b6160e5d30f8172d8e6436",
    "PivotTotalDifficulty": "46113308711267016264199",
    "FastBlocks": true,
    "DownloadBodiesInFastSync": false,
    "DownloadReceiptsInFastSync": false,
    "AncientBodiesBarrier": 11052984,
    "AncientReceiptsBarrier": 11052984,
    "WitnessProtocolEnabled": false,
    "SnapSyncProtocolEnabled": false
  },
  "EthStats": {
    "Server": "wss://ethstats.net/api"
  },
  "Metrics": {
    "NodeName": "Mainnet"
  }
}_

**To Reproduce**
1. Sync client via Fast Sync on mainnet
2. Stop it
3. Turn on the stats collector ( "DiagnosticMode": 6 )
4. Start the client again

**Expected behavior**
The stats collector should finish its job without missing nodes.

**Comment by dceleda** [comment]
I've been able to reproduce the issue on Goerli.
At some point there were storage nodes missing:
`Collected info from 68000094 nodes. Missing CODE 0 STATE 0 STORAGE 226 `
A few minutes later there was an exception:

```
2022-05-03 08:54:20.7938|ERROR|14|System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Expected length greater or equal 56 and was {length}) (Expected length greater or equal 56 and was {length}) (One or more errors occurred. (Unexpected prefix of 248 when decoding Keccak at position 77 in the message of length 83 starting with f8518080a07b89c2d99b67e4b846b5e603e92151ae33961e9790b540f809fbfef3eb928cff80808080808080a0bb4e7f8f1151928c12dcc502b4410ee5f59ef3bc605a6ab9a4d98c9ab4013dcc808080808080))
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Nethermind.Serialization.Rlp.RlpStream.ReadByte() in /root/src/nethermind/src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs:line 634
   at Nethermind.Trie.TrieNode.ResolveChild(ITrieNodeResolver tree, Int32 i) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 767
   at Nethermind.Trie.TrieNode.GetChild(ITrieNodeResolver tree, Int32 childIndex) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 445
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 179
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.<>c__DisplayClass85_0.<Accept>b__3(Int32 i) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 119
   at Nethermind.Trie.PatriciaTree.Accept(ITreeVisitor visitor, Keccak rootHash, VisitingOptions visitingOptions) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 1026
   at Nethermind.State.StateProvider.Accept(ITreeVisitor visitor, Keccak stateRoot, VisitingOptions visitingOptions) in /root/src/nethermind/src/Nethermind/Nethermind.State/StateProvider.cs:line 66
   at Nethermind.State.StateProviderExtensions.CollectStats(IStateProvider stateProvider, IKeyValueStore codeStorage, ILogManager logManager) in /root/src/nethermind/src/Nethermind/Nethermind.State/IStateProviderExtensions.cs:line 43
   at Nethermind.Init.Steps.InitializeBlockchain.<>c__DisplayClass4_0.<InitBlockchain>b__0() in /root/src/nethermind/src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs:line 185
 ---> (Inner Exception #1) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Nethermind.Serialization.Rlp.RlpStream.ReadByte() in /root/src/nethermind/src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs:line 634
   at Nethermind.Serialization.Rlp.RlpStream.ReadPrefixAndContentLength() in /root/src/nethermind/src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs:line 554
   at Nethermind.Trie.TrieNode.SeekChild(Int32 itemToSetOn) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 760
   at Nethermind.Trie.TrieNode.ResolveChild(ITrieNodeResolver tree, Int32 i) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 767
   at Nethermind.Trie.TrieNode.GetChild(ITrieNodeResolver tree, Int32 childIndex) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 445
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 179
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.<>c__DisplayClass85_0.<Accept>b__3(Int32 i) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #2) Nethermind.Serialization.Rlp.RlpException: Expected length greater or equal 56 and was {length}
   at Nethermind.Serialization.Rlp.RlpStream.ReadPrefixAndContentLength() in /root/src/nethermind/src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs:line 554
   at Nethermind.Trie.TrieNode.SeekChild(Int32 itemToSetOn) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 760
   at Nethermind.Trie.TrieNode.ResolveChild(ITrieNodeResolver tree, Int32 i) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 767
   at Nethermind.Trie.TrieNode.GetChild(ITrieNodeResolver tree, Int32 childIndex) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 445
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 179
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.<>c__DisplayClass85_0.<Accept>b__3(Int32 i) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #3) Nethermind.Serialization.Rlp.RlpException: Expected length greater or equal 56 and was {length}
   at Nethermind.Serialization.Rlp.RlpStream.ReadPrefixAndContentLength() in /root/src/nethermind/src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs:line 554
   at Nethermind.Trie.TrieNode.SeekChild(Int32 itemToSetOn) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 760
   at Nethermind.Trie.TrieNode.ResolveChild(ITrieNodeResolver tree, Int32 i) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 767
   at Nethermind.Trie.TrieNode.GetChild(ITrieNodeResolver tree, Int32 childIndex) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 445
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 179
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.<>c__DisplayClass85_0.<Accept>b__3(Int32 i) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #4) System.AggregateException: One or more errors occurred. (Unexpected prefix of 248 when decoding Keccak at position 77 in the message of length 83 starting with f8518080a07b89c2d99b67e4b846b5e603e92151ae33961e9790b540f809fbfef3eb928cff80808080808080a0bb4e7f8f1151928c12dcc502b4410ee5f59ef3bc605a6ab9a4d98c9ab4013dcc808080808080)
 ---> Nethermind.Serialization.Rlp.RlpException: Unexpected prefix of 248 when decoding Keccak at position 77 in the message of length 83 starting with f8518080a07b89c2d99b67e4b846b5e603e92151ae33961e9790b540f809fbfef3eb928cff80808080808080a0bb4e7f8f1151928c12dcc502b4410ee5f59ef3bc605a6ab9a4d98c9ab4013dcc808080808080
   at Nethermind.Serialization.Rlp.RlpStream.DecodeKeccak() in /root/src/nethermind/src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs:line 677
   at Nethermind.Trie.TrieNode.ResolveChild(ITrieNodeResolver tree, Int32 i) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 767
   at Nethermind.Trie.TrieNode.GetChild(ITrieNodeResolver tree, Int32 childIndex) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 445
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 179
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.<>c__DisplayClass85_0.<Accept>b__3(Int32 i) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 102
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 119
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.Accept(ITreeVisitor visitor, ITrieNodeResolver nodeResolver, TrieVisitContext trieVisitContext) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 128
   at Nethermind.Trie.TrieNode.<>c__DisplayClass85_0.<Accept>b__3(Int32 i) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```
