### ISSUE TITLE
Too many open files on Discovery commit

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#399]
2019-03-01 14:17:45.9888|Error during discovery commit: System.AggregateException: One or more errors occurred. (Too many open files) ---> System.IO.IOException: Too many open files
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at Nethermind.Db.SimpleFilePublicKeyDb.CommitBatch()
   at Nethermind.Network.NetworkStorage.Commit() in /root/src/nethermind/src/Nethermind/Nethermind.Network/NetworkStorage.cs:line 99
   at Nethermind.Network.Discovery.DiscoveryApp.<RunDiscoveryCommit>b__40_1() in /root/src/nethermind/src/Nethermind/Nethermind.Network/Discovery/DiscoveryApp.cs:line 511
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: Too many open files
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at Nethermind.Db.SimpleFilePublicKeyDb.CommitBatch()
   at Nethermind.Network.NetworkStorage.Commit() in /root/src/nethermind/src/Nethermind/Nethermind.Network/NetworkStorage.cs:line 99
   at Nethermind.Network.Discovery.DiscoveryApp.<RunDiscoveryCommit>b__40_1() in /root/src/nethermind/src/Nethermind/Nethermind.Network/Discovery/DiscoveryApp.cs:line 511
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---

**Comment by Reimdal** [comment]
Most distros do have a limit for open files: https://linux.die.net/man/5/limits.conf

Other clients did have the same problem:
https://github.com/paritytech/parity-ethereum/issues/9831
https://github.com/ethereum/go-ethereum/issues/16006
https://github.com/ethereum/ethereumj/issues/942

**Comment by tkstanczak** [comment]
There are a few options
* limit the number of files open by rocksdb in the rocksdb config
* update the system limits (like in the solutions shown by you)
* check if that was really rocksdb (in our case the issue was on the STreamWrite that should open only 1 file) - not sure if it wasn't some .NET Core 2.2 issue - I experienced it for the first time last week after running full syncs thousands of times...
