### ISSUE TITLE
Can't start Nethermind.Cli on Ubuntu 22.04: Could not load file or assembly 'plugins/Nethermind.Consensus.AuRa.dll'

### ISSUE THREAD

**Issue by c0deright** [NethermindEth/nethermind#4104]
**Describe the bug**

I'm running nethermind 1.13.1 on Ubuntu 22.04 LTS with manually installed `librocksdb6.11` and the [symlink quickfix](https://github.com/NethermindEth/nethermind/issues/4039).

Nethermind is running on `ropsten` testnet and is working fine.

Starting Netzermind.Cli results in an error.

**To Reproduce**
1. Install nethermind 1.13.1 on Ubuntu 22.04 LTS
2. Configure system like shown below
3. Run nethermind
4. Run Nethermind.Cli

**Configuration**
```
% cat /etc/systemd/system/nethermind.service 
[Unit]
Description=Nethermind Node
Documentation=https://docs.nethermind.io
After=network.target

[Service]
User=nethermind
Group=nethermind

WorkingDirectory=/home/nethermind/.nm-data
EnvironmentFile=/home/nethermind/.nm-data/.env
ExecStart=/home/nethermind/nethermind-client/Nethermind.Runner --datadir /home/nethermind/.nm-data
LimitNOFILE=1000000

Restart=always
PrivateTmp=true
TimeoutStopSec=900s
TimeoutStartSec=3s
StartLimitInterval=120s
StartLimitBurst=5

[Install]
WantedBy=default.target
```

```
% ls -ld /home/nethermind/.nm-data /home/nethermind/nethermind-client
drwxrwxr-x 6 nethermind nethermind 101 Jun  3 11:05 /home/nethermind/.nm-data/
lrwxrwxrwx 1 nethermind nethermind  25 Jun  2 15:08 /home/nethermind/nethermind-client -> nethermind-clients/1.13.1/

% ls -l nethermind-clients/1.13.1/plugins/
total 456
drwxr-xr-x 2 nethermind nethermind    200 May 27 14:06 ./
drwxrwxr-x 7 nethermind nethermind    190 Jun  2 15:38 ../
-rw-r--r-- 1 nethermind nethermind 164352 May 27 14:06 Nethermind.AccountAbstraction.dll
-rw-r--r-- 1 nethermind nethermind  51712 May 27 14:16 Nethermind.Api.dll
-rw-r--r-- 1 nethermind nethermind  31744 May 27 14:16 Nethermind.EthStats.dll
-rw-r--r-- 1 nethermind nethermind  20992 May 27 14:16 Nethermind.HealthChecks.dll
-rw-r--r-- 1 nethermind nethermind 105472 May 27 14:16 Nethermind.Merge.Plugin.dll
-rw-r--r-- 1 nethermind nethermind  78848 May 27 14:16 Nethermind.Mev.dll
```

**Expected behavior**

Cli starts

**behaviour instead**

```
% ./nethermind-client/Nethermind.Cli
**********************************************

Nethermind CLI -20220603
  https://github.com/NethermindEth/nethermind
  https://nethermind.readthedocs.io/en/latest/

powered by:
  https://github.com/sebastienros/jint
  https://github.com/tomakita/Colorful.Console
  https://github.com/tonerdo/readline

**********************************************

Resolved executing directory as /home/nethermind/nethermind-clients/1.13.1.
Type CliModuleBase is a CLI module but is not marked with a CliModuleAttribute
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Nethermind.Consensus.AuRa, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Nethermind.Consensus.AuRa, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Could not load file or assembly '/home/nethermind/nethermind-clients/1.13.1/plugins/Nethermind.Consensus.AuRa.dll'. The system cannot find the file specified.

File name: '/home/nethermind/nethermind-clients/1.13.1/plugins/Nethermind.Consensus.AuRa.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Nethermind.Cli.Modules.CliModuleLoader.<>c__DisplayClass12_0.<DiscoverAndLoadModules>b__0(AssemblyLoadContext context, AssemblyName name)
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nethermind.Cli.Modules.CliModuleLoader.DiscoverAndLoadModules()
   at Nethermind.Cli.Program.Main()
```

**Additional context**
* file `Nethermind.Consensus.AuRa.dll` doesn't exist in `plugins` directory.
* same error when starting `/Nethermind.Launcher` and selecting CLI

**Comment by FalcoXYZ** [comment]
I will pick this up, thank you for noticing!

**Comment by FalcoXYZ** [comment]
Should be fixed in next release. :) 
https://github.com/NethermindEth/nethermind/pull/4090
