### ISSUE TITLE
Failure to initialize merge plugin should be a critical error

### ISSUE THREAD

**Issue by dapplion** [NethermindEth/nethermind#4153]
**Describe the bug**

Same story as
- https://github.com/NethermindEth/nethermind/issues/4149
- https://github.com/NethermindEth/nethermind/issues/4150

Nethermind logged

```
el_1  | 2022-06-12 13:09:42.3302|Failed to initialize plugin Merge by Nethermind System.FormatException: One of the identified items was in an invalid format.
el_1  |    at Nethermind.Int256.UInt256.Parse(String value) in /src/int256/src/Nethermind.Int256/UInt256.cs:line 2027
el_1  |    at Nethermind.Merge.Plugin.IMergeConfig.get_TerminalTotalDifficultyParsed() in /src/Nethermind/Nethermind.Merge.Plugin/IMergeConfig.cs:line 45
el_1  |    at Nethermind.Merge.Plugin.PoSSwitcher.Initialize() in /src/Nethermind/Nethermind.Merge.Plugin/PoSSwitcher.cs:line 90
el_1  |    at Nethermind.Merge.Plugin.PoSSwitcher..ctor(IMergeConfig mergeConfig, ISyncConfig syncConfig, IDb metadataDb, IBlockTree blockTree, ISpecProvider specProvider, ILogManager logManager) in /src/Nethermind/Nethermind.Merge.Plugin/PoSSwitcher.cs:line 83
el_1  |    at Nethermind.Merge.Plugin.MergePlugin.Init(INethermindApi nethermindApi) in /src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs:line 84
el_1  |    at Nethermind.Init.Steps.InitializePlugins.Execute(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Init/Steps/InitializePlugins.cs:line 48
```

and continue happily, but the merge plugin was not loaded. So when the CL found the merge block everything errored because:

```
cl_1  | Eph 1/2 5.869[ETH1]             info: Terminal POW block found! hash=0x4ebd4a511161d0ec70c6674395c8b9f06cfce7e120b12379c1ec2640f2fe7384, number=11, totalDifficulty=3743106036130323098097120681749119449189
el_1  | 2022-06-12 13:10:49.9308|Waiting for peers... 7s 
el_1  | 2022-06-12 13:10:50.0061|Sealed block 13 (0x1ffaa0...dbf90b), diff: 340282366920938463463374607431768211454, tx count: 0 
el_1  | 2022-06-12 13:10:50.0094|Processed         13 |        3ms of   5,003ms, mgasps    0.00 total    3.80, tps    0.00 total   14.66, bps  390.53 total   87.95, recv queue 0, proc queue 0 
el_1  | 2022-06-12 13:10:50.2099|Error when handling ID 1, engine_forkchoiceUpdatedV1({
el_1  |   "headBlockHash": "0x4ebd4a511161d0ec70c6674395c8b9f06cfce7e120b12379c1ec2640f2fe7384",
el_1  |   "safeBlockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
el_1  |   "finalizedBlockHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
el_1  | },{
el_1  |   "timestamp": "0x62a5e5da",
el_1  |   "prevRandao": "0x67e28a0a07971c8e85a8e8c6e19f8ef08835aa3cb7409f671915f0b66e6e4ed6",
el_1  |   "suggestedFeeRecipient": "0x0000000000000000000000000000000000000000"
el_1  | }) | {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method engine_forkchoiceUpdatedV1 is not supported"},"id":1} 
```

**To Reproduce**

- Clone https://github.com/dapplion/nethermind-tests/tree/cc1dcb21da9d9b68e991582c6ff9617df0f93e9a/nethermind-lodestar-m3-aura
- Run `docker-compose up`

**Expected behavior**

**Please please please: error immediately for any setup errors** :pray:  :pray:  :pray:

**Comment by tkstanczak** [comment]
@LukaszRozmej how about marking this plugin as critical from inside the app?
