### ISSUE TITLE
Wrong permissions on jwtsecret prevent functional JSON RPC

### ISSUE THREAD

**Issue by dapplion** [NethermindEth/nethermind#4170]
**Describe the bug**

Wrong permissions on jwtsecret cause the error
```
2022-06-17 12:45:24.1563|Step StartRpc                 failed after 16ms System.UnauthorizedAccessException: Access to the path '/jwtsecret' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at Nethermind.Core.Authentication.MicrosoftJwtAuthentication.CreateFromFileOrGenerate(String filePath, IClock clock, ILogger logger) in /src/Nethermind/Nethermind.Core/Authentication/MicrosoftJwtAuthentication.cs:line 61
   at Nethermind.Runner.Ethereum.Steps.StartRpc.Execute(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartRpc.cs:line 61
```

The node does not exit so it appears everything is fine. However, then the beacon node complains that localhost:8545 is not listening

**Expected behavior**

Node should exit 1 if jwtsecret can not be read

**Comment by dceleda** [comment]
@jmederosalvarado can we close that issue?
