### ISSUE TITLE
Bloom index is written to disk with problems on shutdown

### ISSUE THREAD

**Issue by flcl42** [NethermindEth/nethermind#4221]
**Describe the bug**

Bloom index is flushed with problems on shutdown

**To Reproduce**
1. Start the client
2. Wait for a partial synchronization
3. Shutdown gracefully
4. See error:
```
2022-06-27 10:48:01.9368|Disposing DB State0
2022-06-27 10:48:01.9321|Fast blocks headers downloader failed System.InvalidOperationException: Cannot access a closed file. Trying to write bloom index for block 5841146 at bucket 22816
 ---> System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.get_Position()
   at Nethermind.Db.Blooms.FixedSizeFileStore.SeekIndex(Stream file, Int64 index) in /root/src/nethermind/src/Nethermind/Nethermind.Db/Blooms/FixedSizeFileStore.cs:line 103
   at Nethermind.Db.Blooms.FixedSizeFileStore.Write(Int64 index, ReadOnlySpan`1 element) in /root/src/nethermind/src/Nethermind/Nethermind.Db/Blooms/FixedSizeFileStore.cs:line 50
   at Nethermind.Db.Blooms.BloomStorage.BloomStorageLevel.Store(Int64 blockNumber, Bloom bloom) in /root/src/nethermind/src/Nethermind/Nethermind.Db/Blooms/BloomStorage.cs:line 284
   --- End of inner exception stack trace ---
   at Nethermind.Db.Blooms.BloomStorage.BloomStorageLevel.Store(Int64 blockNumber, Bloom bloom) in /root/src/nethermind/src/Nethermind/Nethermind.Db/Blooms/BloomStorage.cs:line 295
   at Nethermind.Db.Blooms.BloomStorage.Store(Int64 blockNumber, Bloom bloom) in /root/src/nethermind/src/Nethermind/Nethermind.Db/Blooms/BloomStorage.cs:line 160
   at Nethermind.Blockchain.BlockTree.Insert(BlockHeader header, BlockTreeInsertOptions options) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/BlockTree.cs:line 567
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.InsertToBlockTree(BlockHeader header) in /root/src/nethermind/src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 556
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.InsertHeader(BlockHeader header) in /root/src/nethermind/src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 551
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.InsertHeaders(HeadersSyncBatch batch) in /root/src/nethermind/src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 471
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.HandleDependentBatches() in /root/src/nethermind/src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 188
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.PrepareRequest() in /root/src/nethermind/src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 195
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.Start(CancellationToken cancellationToken)
2022-06-27 10:48:03.5611|Closing DBs shutdown error. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Attempted to commit a batch on a disposed database State0'.
   at Nethermind.Db.Rocks.DbOnTheRocks.RocksDbBatch.Dispose() in /root/src/nethermind/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 436
   at Nethermind.Db.Rocks.DbOnTheRocks.ReleaseUnmanagedResources() in /root/src/nethermind/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 532
   at Nethermind.Db.Rocks.DbOnTheRocks.Dispose(Boolean disposing) in /root/src/nethermind/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 552
   at Nethermind.Db.Rocks.DbOnTheRocks.Dispose() in /root/src/nethermind/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 562
   at Nethermind.Db.FullPruning.FullPruningDb.Dispose() in /root/src/nethermind/src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs:line 98
   at Nethermind.Db.DbProvider.Dispose() in /root/src/nethermind/src/Nethermind/Nethermind.Db/DbProvider.cs:line 42
   at Nethermind.Runner.Ethereum.EthereumRunner.<StopAsync>b__5_9() in /root/src/nethermind/src/Nethermind/Nethermind.Runner/Ethereum/EthereumRunner.cs:line 97
   at Nethermind.Runner.Ethereum.EthereumRunner.Stop(Action stopAction, String description) in /root/src/nethermind/src/Nethermind/Nethermind.Runner/Ethereum/EthereumRunner.cs:line 109
```

**Expected behavior**

Bloom index is flushed without problems on shutdown

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: master

**Comment by LukaszRozmej** [comment]
HeadersSyncFeed should be properly closed and stop writing blooms
