### ISSUE TITLE
trace_replayBlockTransactions method fails on archive node

### ISSUE THREAD

**Issue by nicexe** [NethermindEth/nethermind#4282]
When calling `trace_replayBlockTransactions("0x8394F", ["trace"])`, nethermind throws an error.

This is on a local testnet and I'm calling the method like so:

```shell
$ curl 127.0.0.1:8545 -X POST -H "Content-Type: application/json" --data '{"method":"trace_replayBlockTransactions","params":["0x8394F",["trace"]],"id":1,"jsonrpc":"2.0"}'`
```

and nethermind replies with:

```json
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error","data":"Nethermind.Trie.TrieException: Failed to load key 2f6a0791cc0675d45262859d32ec96703b4f2e26dffb5effa28482f4d196e26a from root hash 0x60ce3faf21e597574365d2a31d7ab629dd21e4b6a9dc05b2c1ec3a5e188ea2c5.\n ---> Nethermind.Trie.TrieException: Node 0x60ce3faf21e597574365d2a31d7ab629dd21e4b6a9dc05b2c1ec3a5e188ea2c5 is missing from the DB\n   at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak, IKeyValueStore keyValueStore) in /src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 338\n   at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree) in /src/Nethermind/Nethermind.Trie/TrieNode.cs:line 318\n   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak startRootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 399\n   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 328\n   --- End of inner exception stack trace ---\n   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 328\n   at Nethermind.State.StateProvider.GetState(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 659\n   at Nethermind.State.StateProvider.GetAndAddToCache(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 685\n   at Nethermind.State.StateProvider.GetNonce(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 132\n   at Nethermind.Consensus.Processing.BlockProcessor.BlockValidationTransactionsExecutor.ProcessTransactions(Block block, ProcessingOptions processingOptions, BlockReceiptsTracer receiptsTracer, IReleaseSpec spec) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockValidationTransactionsExecutor.cs:line 53\n   at Nethermind.Consensus.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 262\n   at Nethermind.Consensus.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 215\n   at Nethermind.Consensus.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 114\n   at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 475\n   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 299\n   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/OneTimeProcessor.cs:line 58\n   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Tracing/Tracer.cs:line 50\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityTraceTypes traceTypes, TxTraceFilter txTraceFilter) in /src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs:line 248\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes) in /src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs:line 159"},"id":1}
```

Nethermind logs of this instance:

```
2022-07-15 10:00:16.7705|Executing JSON RPC call trace_replayBlockTransactions with params [0x8394F,[
  "trace"
]]
2022-07-15 10:00:16.7705|Error during method execution, request: ID 1, trace_replayBlockTransactions(0x8394F,[
  "trace"
]) Nethermind.Trie.TrieException: Failed to load key 2f6a0791cc0675d45262859d32ec96703b4f2e26dffb5effa28482f4d196e26a from root hash 0x60ce3faf21e597574365d2a31d7ab629dd21e4b6a9dc05b2c1ec3a5e188ea2c5.
 ---> Nethermind.Trie.TrieException: Node 0x60ce3faf21e597574365d2a31d7ab629dd21e4b6a9dc05b2c1ec3a5e188ea2c5 is missing from the DB
   at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak, IKeyValueStore keyValueStore) in /src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 338
   at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree) in /src/Nethermind/Nethermind.Trie/TrieNode.cs:line 318
   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak startRootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 399
   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 328
   --- End of inner exception stack trace ---
   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 328
   at Nethermind.State.StateProvider.GetState(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 659
   at Nethermind.State.StateProvider.GetAndAddToCache(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 685
   at Nethermind.State.StateProvider.GetNonce(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 132
   at Nethermind.Consensus.Processing.BlockProcessor.BlockValidationTransactionsExecutor.ProcessTransactions(Block block, ProcessingOptions processingOptions, BlockReceiptsTracer receiptsTracer, IReleaseSpec spec) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockValidationTransactionsExecutor.cs:line 53
   at Nethermind.Consensus.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 262
   at Nethermind.Consensus.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 215
   at Nethermind.Consensus.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 114
   at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 475
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 299
   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/OneTimeProcessor.cs:line 58
   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Tracing/Tracer.cs:line 50
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityTraceTypes traceTypes, TxTraceFilter txTraceFilter) in /src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs:line 248
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes) in /src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs:line 159
2022-07-15 10:00:16.7705|Error when handling ID 1, trace_replayBlockTransactions(0x8394F,[
  "trace"
]) | {"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error","data":"Nethermind.Trie.TrieException: Failed to load key 2f6a0791cc0675d45262859d32ec96703b4f2e26dffb5effa28482f4d196e26a from root hash 0x60ce3faf21e597574365d2a31d7ab629dd21e4b6a9dc05b2c1ec3a5e188ea2c5.\n ---> Nethermind.Trie.TrieException: Node 0x60ce3faf21e597574365d2a31d7ab629dd21e4b6a9dc05b2c1ec3a5e188ea2c5 is missing from the DB\n   at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak, IKeyValueStore keyValueStore) in /src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 338\n   at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree) in /src/Nethermind/Nethermind.Trie/TrieNode.cs:line 318\n   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak startRootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 399\n   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 328\n   --- End of inner exception stack trace ---\n   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 328\n   at Nethermind.State.StateProvider.GetState(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 659\n   at Nethermind.State.StateProvider.GetAndAddToCache(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 685\n   at Nethermind.State.StateProvider.GetNonce(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 132\n   at Nethermind.Consensus.Processing.BlockProcessor.BlockValidationTransactionsExecutor.ProcessTransactions(Block block, ProcessingOptions processingOptions, BlockReceiptsTracer receiptsTracer, IReleaseSpec spec) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockValidationTransactionsExecutor.cs:line 53\n   at Nethermind.Consensus.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 262\n   at Nethermind.Consensus.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 215\n   at Nethermind.Consensus.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 114\n   at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 475\n   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 299\n   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/OneTimeProcessor.cs:line 58\n   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Tracing/Tracer.cs:line 50\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityTraceTypes traceTypes, TxTraceFilter txTraceFilter) in /src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs:line 248\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes) in /src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs:line 159"},"id":1}
```

Those are the relevant environment variables set for nethermind:

```shell
NETHERMIND_AURACONFIG_ALLOWAURAPRIVATECHAINS=true
NETHERMIND_INITCONFIG_ISMINING=false
NETHERMIND_INITCONFIG_STORERECEIPTS=true
NETHERMIND_INITCONFIG_WEBSOCKETSENABLED=true
NETHERMIND_JSONRPCCONFIG_ENABLED=true
NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES=[Eth,Subscribe,Web3,Net,Parity,Trace]
NETHERMIND_JSONRPCCONFIG_HOST=0.0.0.0
NETHERMIND_JSONRPCCONFIG_PORT=8545
NETHERMIND_JSONRPCCONFIG_WEBSOCKETSPORT=8546
NETHERMIND_SYNCCONFIG_FASTSYNC=false
NETHERMIND_SYNCCONFIG_FASTBLOCKS=false
NETHERMIND_SYNCCONFIG_FASTSYNCCATCHUPHEIGHTDELTA=1000000000
NETHERMIND_SYNCCONFIG_FIXRECEIPTS=true
NETHERMIND_SYNCCONFIG_DOWNLOADBODIESINFASTSYNC=true
NETHERMIND_SYNCCONFIG_DOWNLOADRECEIPTSINFASTSYNC=true
```

**Comment by nicexe** [comment]
I tried an older and an earlier block and both worked.

for block 0x01

```shell
$ curl 127.0.0.1:8545 -X POST -H "Content-Type: application/json" --data '{"method":"trace_replayBlockTransactions","params":["0x01",["trace"]],"id":1,"jsonrpc":"2.0"}'
```

```json
{"jsonrpc":"2.0","result":[{"output":"0x","stateDiff":null,"trace":[{"action":{"callType":"call","from":"0x38670393cfc0c6d6a25917bbf822fd1478c599c6","gas":"0x180b54","input":"0x0b61ba855b102925e09a4a880cac6e3797593245496c5f1ee2458c4d1268cf8b31a71fb50000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000009104d1e51251d31b41a6b52349f521f5b9662fd0f0226ed26b4dd189a5bb17f6655f9418202242c115a819e79a727723ef46911914a479241a0f1d8f8e912db4917110b16e22d78b4e50191f55441f63b03a98070234426741fdd67779a67f09d948dd186bbfd4fa9db5f347039bc1f8a04670eb1c7650dd5cb27ccb61779650393c9785fd8b24aa5e40adb5612ccd9b3fb4000000000000000000000000000000","to":"0x3000000000000000000000000000000000000001","value":"0x0"},"result":{"gasUsed":"0x39657","output":"0x"},"subtraces":1,"traceAddress":[],"type":"call"},{"action":{"callType":"delegatecall","from":"0x3000000000000000000000000000000000000001","gas":"0x1797dc","input":"0x0b61ba855b102925e09a4a880cac6e3797593245496c5f1ee2458c4d1268cf8b31a71fb50000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000009104d1e51251d31b41a6b52349f521f5b9662fd0f0226ed26b4dd189a5bb17f6655f9418202242c115a819e79a727723ef46911914a479241a0f1d8f8e912db4917110b16e22d78b4e50191f55441f63b03a98070234426741fdd67779a67f09d948dd186bbfd4fa9db5f347039bc1f8a04670eb1c7650dd5cb27ccb61779650393c9785fd8b24aa5e40adb5612ccd9b3fb4000000000000000000000000000000","to":"0x3000000000000000000000000000000000000000","value":"0x0"},"result":{"gasUsed":"0x38297","output":"0x"},"subtraces":4,"traceAddress":[0],"type":"call"},{"action":{"callType":"staticcall","from":"0x3000000000000000000000000000000000000001","gas":"0x171aab","input":"0xfacd743b00000000000000000000000038670393cfc0c6d6a25917bbf822fd1478c599c6","to":"0x1000000000000000000000000000000000000001","value":"0x0"},"result":{"gasUsed":"0x261c","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0,0],"type":"call"},{"action":{"callType":"delegatecall","from":"0x1000000000000000000000000000000000000001","gas":"0x16ab1c","input":"0xfacd743b00000000000000000000000038670393cfc0c6d6a25917bbf822fd1478c599c6","to":"0x1000000000000000000000000000000000000000","value":"0x0"},"result":{"gasUsed":"0x1280","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":0,"traceAddress":[0,0,0],"type":"call"},{"action":{"callType":"staticcall","from":"0x3000000000000000000000000000000000000001","gas":"0x16f237","input":"0x2bbb7b7200000000000000000000000038670393cfc0c6d6a25917bbf822fd1478c599c6","to":"0x1000000000000000000000000000000000000001","value":"0x0"},"result":{"gasUsed":"0x3f4","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0,1],"type":"call"},{"action":{"callType":"delegatecall","from":"0x1000000000000000000000000000000000000001","gas":"0x169497","input":"0x2bbb7b7200000000000000000000000038670393cfc0c6d6a25917bbf822fd1478c599c6","to":"0x1000000000000000000000000000000000000000","value":"0x0"},"result":{"gasUsed":"0x1ec","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":0,"traceAddress":[0,1,0],"type":"call"},{"action":{"callType":"staticcall","from":"0x3000000000000000000000000000000000000001","gas":"0x16eacf","input":"0x92d276b4","to":"0x1000000000000000000000000000000000000001","value":"0x0"},"result":{"gasUsed":"0x13e3","output":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[0,2],"type":"call"},{"action":{"callType":"delegatecall","from":"0x1000000000000000000000000000000000000001","gas":"0x168d50","input":"0x92d276b4","to":"0x1000000000000000000000000000000000000000","value":"0x0"},"result":{"gasUsed":"0x11db","output":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"},"subtraces":0,"traceAddress":[0,2,0],"type":"call"},{"action":{"callType":"staticcall","from":"0x3000000000000000000000000000000000000001","gas":"0x16c240","input":"0x2bbb7b7200000000000000000000000038670393cfc0c6d6a25917bbf822fd1478c599c6","to":"0x1000000000000000000000000000000000000001","value":"0x0"},"result":{"gasUsed":"0x3f4","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0,3],"type":"call"},{"action":{"callType":"delegatecall","from":"0x1000000000000000000000000000000000000001","gas":"0x166560","input":"0x2bbb7b7200000000000000000000000038670393cfc0c6d6a25917bbf822fd1478c599c6","to":"0x1000000000000000000000000000000000000000","value":"0x0"},"result":{"gasUsed":"0x1ec","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":0,"traceAddress":[0,3,0],"type":"call"}],"transactionHash":"0x80069e2a7d9fdf07d13423ce763636d47044a128686e67d6e169b073b8b4fb04","vmTrace":null}],"id":1}
```

for block 0x95B76

```shell
$ curl 127.0.0.1:8545 -X POST -H "Content-Type: application/json" --data '{"method":"trace_replayBlockTransactions","params":["0x95B76",["trace"]],"id":1,"jsonrpc":"2.0"}'
```

```json
{"jsonrpc":"2.0","result":[{"output":"0x","stateDiff":null,"trace":[{"action":{"callType":"call","from":"0xad78a5ae1cc885bd3292bf492e61398832bf198d","gas":"0x5c648","input":"0xadc9772e000000000000000000000000ad78a5ae1cc885bd3292bf492e61398832bf198d0000000000000000000000000000000000000000000000000000000000000000","to":"0x1100000000000000000000000000000000000001","value":"0x1043561a8829300000"},"result":{"gasUsed":"0x1ba35","output":"0x"},"subtraces":1,"traceAddress":[],"type":"call"},{"action":{"callType":"delegatecall","from":"0x1100000000000000000000000000000000000001","gas":"0x59c07","input":"0xadc9772e000000000000000000000000ad78a5ae1cc885bd3292bf492e61398832bf198d0000000000000000000000000000000000000000000000000000000000000000","to":"0x1100000000000000000000000000000000000000","value":"0x1043561a8829300000"},"result":{"gasUsed":"0x1a699","output":"0x"},"subtraces":3,"traceAddress":[0],"type":"call"},{"action":{"callType":"staticcall","from":"0x1100000000000000000000000000000000000001","gas":"0x57061","input":"0xa26301f9000000000000000000000000ad78a5ae1cc885bd3292bf492e61398832bf198d","to":"0x1000000000000000000000000000000000000001","value":"0x0"},"result":{"gasUsed":"0x1d9a","output":"0x000000000000000000000000000000000000000000000000000000000000000c"},"subtraces":1,"traceAddress":[0,0],"type":"call"},{"action":{"callType":"delegatecall","from":"0x1000000000000000000000000000000000000001","gas":"0x5477b","input":"0xa26301f9000000000000000000000000ad78a5ae1cc885bd3292bf492e61398832bf198d","to":"0x1000000000000000000000000000000000000000","value":"0x0"},"result":{"gasUsed":"0x9fe","output":"0x000000000000000000000000000000000000000000000000000000000000000c"},"subtraces":0,"traceAddress":[0,0,0],"type":"call"},{"action":{"callType":"staticcall","from":"0x1100000000000000000000000000000000000001","gas":"0x550e8","input":"0x4d04481e000000000000000000000000000000000000000000000000000000000000000c","to":"0x1000000000000000000000000000000000000001","value":"0x0"},"result":{"gasUsed":"0xc26","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[0,1],"type":"call"},{"action":{"callType":"delegatecall","from":"0x1000000000000000000000000000000000000001","gas":"0x539cd","input":"0x4d04481e000000000000000000000000000000000000000000000000000000000000000c","to":"0x1000000000000000000000000000000000000000","value":"0x0"},"result":{"gasUsed":"0xa1e","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":0,"traceAddress":[0,1,0],"type":"call"},{"action":{"callType":"staticcall","from":"0x1100000000000000000000000000000000000001","gas":"0x497a1","input":"0xe717de3a000000000000000000000000000000000000000000000000000000000000000c","to":"0x1000000000000000000000000000000000000001","value":"0x0"},"result":{"gasUsed":"0xbff","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[0,2],"type":"call"},{"action":{"callType":"delegatecall","from":"0x1000000000000000000000000000000000000001","gas":"0x4836b","input":"0xe717de3a000000000000000000000000000000000000000000000000000000000000000c","to":"0x1000000000000000000000000000000000000000","value":"0x0"},"result":{"gasUsed":"0x9f7","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":0,"traceAddress":[0,2,0],"type":"call"}],"transactionHash":"0x8a04009a1cda454a32e059f53f9d4f53dd628b650bd371f93ea1dff81e25774d","vmTrace":null}],"id":1}
```

**Comment by MarekM25** [comment]
HI @nicexe,

Unfortunately, you will need to try resync your node if you want these traces.

Could you try resync your node with --Pruning.Mode None? We changed our default settings for pruning which shouldn't be used for archive node. Of course, we updated all our supported network. However, it is missing custom networks.

**Comment by abcfy2** [comment]
Hi there. I got this error, would you please help ?

```
2023-02-20 18:47:56.6652|ERROR|108|Error during method execution, request: ID 4, trace_replayBlockTransactions(0xFB8354,[
  "trace"
]) System.InvalidOperationException: Block without total difficulty calculated was suggested for processing
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunSimpleChecksAheadOfProcessing(Block suggestedBlock, ProcessingOptions options)
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer)
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityLikeBlockTracer tracer)
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes)
   at InvokeStub_ITraceRpcModule.trace_replayBlockTransactions(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-02-20 18:47:56.6652|INFO|161|Executing JSON RPC call eth_call with params [{
  "data": "0x70a08231000000000000000000000000f89d7b9c864f589bbf53a82105107622b35eaa40",
  "to": "0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce"
}, 0xFE5BF0] 
2023-02-20 18:47:56.6652|WARN|108|Error when handling ID 4, trace_replayBlockTransactions(0xFB8354,[
  "trace"
]) | {"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error","data":"System.InvalidOperationException: Block without total difficulty calculated was suggested for processing\n   at Nethermind.Consensus.Processing.BlockchainProcessor.RunSimpleChecksAheadOfProcessing(Block suggestedBlock, ProcessingOptions options)\n   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityLikeBlockTracer tracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes)\n   at InvokeStub_ITraceRpcModule.trace_replayBlockTransactions(Object, Object, IntPtr*)\n   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)"},"id":4} 
2023-02-20 18:47:56.6652|INFO|108|Executing JSON RPC call trace_replayBlockTransactions with params [0xFE6378, [
  "trace"
]]
```
