### ISSUE TITLE
Multiple errors: Request timeout in GetReceiptsMessage

### ISSUE THREAD

**Issue by MeganerdNL** [NethermindEth/nethermind#4284]
In my log on my fully synced node on mainet the following error is reported multiple times per minute:

```
2022-07-15 11:50:14.3906|Failure when executing request System.AggregateException: One or more errors occurred. ([Session|Out|Initialized|30314->162.55.135.68:30303] Request timeout in GetReceiptsMessage)
 ---> System.TimeoutException: [Session|Out|Initialized|30314->162.55.135.68:30303] Request timeout in GetReceiptsMessage
   at Nethermind.Network.P2P.Subprotocols.Eth.V66.Eth66ProtocolHandler.SendRequest(GetReceiptsMessage message, CancellationToken token) in /src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs:line 368
   at Nethermind.Network.P2P.Subprotocols.Eth.V63.Eth63ProtocolHandler.GetReceipts(IReadOnlyList`1 blockHashes, CancellationToken token) in /src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandler.cs:line 146
   at Nethermind.Synchronization.FastBlocks.ReceiptsSyncDispatcher.Dispatch(PeerInfo peerInfo, ReceiptsSyncBatch batch, CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncDispatcher.cs:line 53
   --- End of inner exception stack trace ---
```

The IP's reported here are everytime different.
Node seems, apart from these errors, fine and stays in sync.

This is on Denian Linux 11
It is running DAppNode with Nethermind 1.13.4
Plenty or memory left and fast SSD with enough space with a gen 11 i5 intel cpu.

Is this a bug or something to worry about? Is there something wrong with my database?

**Comment by MarekM25** [comment]
It is normal thing and just bad logging. We increased the log in the 1.13.4 release. On master, we don't log it by default again, so in next release you shouldn't see this log.
