### ISSUE TITLE
Error "A suitable constructor for type 'Nethermind.HealthChecks.NodeHealthCheck' could not be located"

### ISSUE THREAD

**Issue by ev9173** [NethermindEth/nethermind#4367]
**Describe the bug**
v1.13.5 suddenly got an error and lost all peers: 
"Connection id "0HMJLQ4BBHOBG", Request id "0HMJLQ4BBHOBG:00000015": An unhandled exception was thrown by the application. System.InvalidOperationException: A suitable constructor for type 'Nethermind.HealthChecks.NodeHealthCheck' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided." 

A stack trace is included at the bottom as an 'Additional Context'. @MarekM from the discord suggested to submit this as a potential bug.  

**To Reproduce**
Everything was fine (Nethermind was being used as an Execution Client for my RocketPool native mode validator) until suddenly the error message appeared. Restarted the systemd nethermind service but it kept repeating the same error. Number of peers=0 after restart. It seems like working fine after updating to 1.13.6. 

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
2022-08-03 21:25:04.1508|Waiting for peers... 34s
Aug 03 21:25:05 myserver Nethermind.Runner[1287899]: 2022-08-03 21:25:05.1509|Waiting for peers... 35s
Aug 03 21:25:06 myserver Nethermind.Runner[1287899]: 2022-08-03 21:25:06.1514|Waiting for peers... 36s
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]: 2022-08-03 21:25:07.1286|Connection id "0HMJLQ4BBHOBG", Request id "0HMJLQ4BBHOBG:00000015": An unhandled exception was thrown by the application. System.InvalidOperationException: A suitable constructor for type 'Nethermind.HealthChecks.NodeHealthCheck' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]:    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]:    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]:    at Microsoft.Extensions.DependencyInjection.HealthChecksBuilderAddCheckExtensions.<>c__DisplayClass6_0`1.<AddTypeActivatedCheck>b__0(IServiceProvider s)
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]:    at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(HealthCheckRegistration registration, CancellationToken cancellationToken)
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]:    at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.CheckHealthAsync(Func`2 predicate, CancellationToken cancellationToken)
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]:    at Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware.InvokeAsync(HttpContext httpContext)
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]: 2022-08-03 21:25:07.1286|GetHealthReport threw an exception when trying to get report from http://localhost:8545/health configured with name health. System.InvalidOperationException: Response is null or message can't be deserialized as HealthChecks.UI.Core.UIHealthReport.
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]:    at System.Net.Http.HttpResponseMessageExtensions.As[TContent](HttpResponseMessage response) in /_/src/HealthChecks.UI/Core/Extensions/HttpResponseMessageExtensions.cs:line 27
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]:    at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReportAsync(HealthCheckConfiguration configuration) in /_/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 107
Aug 03 21:25:07 myserver Nethermind.Runner[1287899]: 2022-08-03 21:25:07.1515|Waiting for peers... 37s
Aug 03 21:25:08 myserver Nethermind.Runner[1287899]: 2022-08-03 21:25:08.1515|Waiting for peers... 38s
Aug 03 21:25:09 myserver Nethermind.Runner[1287899]: 2022-08-03 21:25:09.1515|Waiting for peers... 39s
Aug 03 21:25:10 myserver Nethermind.Runner[1287899]: 2022-08-03 21:25:10.1517|Waiting for peers... 40s

**Comment by kamilchodola** [comment]
It was quite a long time since then, noone reported any similar issue afaik and never reproduced it on my end so closing for now.
