### ISSUE TITLE
Error: RocksDB was not found

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4455]
**Describe the bug**
When building and running the node from the source code we can expect following error:

```
2022-08-22 19:43:19.6809|RocksDb was not found, please make sure it is installed on your machine.
 On macOs : 'brew install rocksdb' System.TypeInitializationException: The type initializer for 'RocksDbSharp.Native' threw an exception.
 ---> NativeImport.NativeLoadException: Unable to locate rocksdb native library, either install it, or use RocksDbNative nuget package
Searched:
/root/nethermind_mainnet/runtimes/linux-x64/native/librocksdb-6.29.3.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/runtimes/linux-x64/native/librocksdb-6.29.3.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/runtimes/linux-x64/native/librocksdb-6.29.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/runtimes/linux-x64/native/librocksdb-6.29.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/runtimes/linux-x64/native/librocksdb-6.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/runtimes/linux-x64/native/librocksdb-6.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/runtimes/linux-x64/native/librocksdb.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/runtimes/linux-x64/native/librocksdb.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/native/amd64/librocksdb-6.29.3.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/native/amd64/librocksdb-6.29.3.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/native/amd64/librocksdb-6.29.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/native/amd64/librocksdb-6.29.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/native/amd64/librocksdb-6.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/native/amd64/librocksdb-6.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/native/amd64/librocksdb.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/native/amd64/librocksdb.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/native/librocksdb-6.29.3.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/native/librocksdb-6.29.3.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/native/librocksdb-6.29.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/native/librocksdb-6.29.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/native/librocksdb-6.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/native/librocksdb-6.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/native/librocksdb.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/native/librocksdb.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/amd64/librocksdb-6.29.3.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/amd64/librocksdb-6.29.3.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/amd64/librocksdb-6.29.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/amd64/librocksdb-6.29.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/amd64/librocksdb-6.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/amd64/librocksdb-6.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/amd64/librocksdb.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/amd64/librocksdb.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/librocksdb-6.29.3.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/librocksdb-6.29.3.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/librocksdb-6.29.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/librocksdb-6.29.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/librocksdb-6.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/librocksdb-6.so: cannot open shared object file: No such file or directory
/root/nethermind_mainnet/librocksdb.so: (NativeLoadException) dlopen: /root/nethermind_mainnet/librocksdb.so: cannot open shared object file: No such file or directory
librocksdb-6.29.3.so: (NativeLoadException) dlopen: librocksdb-6.29.3.so: cannot open shared object file: No such file or directory
librocksdb-6.29.so: (NativeLoadException) dlopen: librocksdb-6.29.so: cannot open shared object file: No such file or directory
librocksdb-6.so: (NativeLoadException) dlopen: librocksdb-6.so: cannot open shared object file: No such file or directory
librocksdb.so: (NativeLoadException) dlopen: librocksdb.so: cannot open shared object file: No such file or directory
   at NativeImport.Importers.Import[T](INativeLibImporter importer, String libName, String version, Boolean suppressUnload)
   at NativeImport.Auto.Import[T](String name, String version, Boolean suppressUnload)
   at RocksDbSharp.Native..cctor()
   --- End of inner exception stack trace ---
   at RocksDbSharp.BlockBasedTableOptions..ctor()
   at Nethermind.Db.Rocks.DbOnTheRocks.BuildOptions(IDbConfig dbConfig) in /root/src/nethermind/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 170
   at Nethermind.Db.Rocks.DbOnTheRocks.Init(String basePath, String dbPath, IDbConfig dbConfig, ILogManager logManager, ColumnFamilies columnFamilies, Boolean deleteOnStart) in /root/src/nethermind/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 102
   at Nethermind.Db.Rocks.DbOnTheRocks..ctor(String basePath, RocksDbSettings rocksDbSettings, IDbConfig dbConfig, ILogManager logManager, ColumnFamilies columnFamilies) in /root/src/nethermind/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 75
   at Nethermind.Db.Rocks.RocksDbFactory.CreateDb(RocksDbSettings rocksDbSettings) in /root/src/nethermind/src/Nethermind/Nethermind.Db.Rocks/RocksDbFactory.cs:line 39
   at Nethermind.Db.RocksDbInitializer.CreateDb(RocksDbSettings settings) in /root/src/nethermind/src/Nethermind/Nethermind.Db/RocksDbInitializer.cs:line 60
   at Nethermind.Db.RocksDbInitializer.<>c__DisplayClass12_0.<RegisterDb>b__0() in /root/src/nethermind/src/Nethermind/Nethermind.Db/RocksDbInitializer.cs:line 51
   at Nethermind.Db.RocksDbInitializer.<>c__DisplayClass14_0.<AddRegisterAction>b__0() in /root/src/nethermind/src/Nethermind/Nethermind.Db/RocksDbInitializer.cs:line 57
   at Nethermind.Db.RocksDbInitializer.<>c__DisplayClass18_0.<InitAllAsync>b__0() in /root/src/nethermind/src/Nethermind/Nethermind.Db/RocksDbInitializer.cs:line 78
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Nethermind.Db.RocksDbInitializer.InitAllAsync() in /root/src/nethermind/src/Nethermind/Nethermind.Db/RocksDbInitializer.cs:line 81
   at Nethermind.Db.StandardDbInitializer.InitStandardDbsAsync(Boolean useReceiptsDb) in /root/src/nethermind/src/Nethermind/Nethermind.Db/StandardDbInitializer.cs:line 51
   at Nethermind.Init.Steps.InitDatabase.Execute(CancellationToken _) in /root/src/nethermind/src/Nethermind/Nethermind.Init/Steps/InitDatabase.cs:line 63
2022-08-22 19:43:19.9177|Error during ethereum runner start System.ArgumentException: bloom database has not been registered in DbProvider.
   at Nethermind.Db.DbProvider.GetDb[T](String dbName) in /root/src/nethermind/src/Nethermind/Nethermind.Db/DbProvider.cs:line 50
   at Nethermind.Db.IDbProvider.get_BloomDb() in /root/src/nethermind/src/Nethermind/Nethermind.Db/IDbProvider.cs:line 39
   at Nethermind.Init.Steps.InitializeBlockTree.Execute(CancellationToken cancellationToken) in /root/src/nethermind/src/Nethermind/Nethermind.Init/Steps/InitializeBlockTree.cs:line 54
   at Nethermind.Init.Steps.EthereumStepsManager.RunOneRoundOfInitialization(CancellationToken cancellationToken) in /root/src/nethermind/src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 140
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken) in /root/src/nethermind/src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 108
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken) in /root/src/nethermind/src/Nethermind/Nethermind.Runner/Ethereum/EthereumRunner.cs:line 49
```

**To Reproduce**
1. Build the client from any old source code that included the old RocksDB wrapper - pre-nuget one. (for example from 1.13.5)
2. Run the node.
3. Stop the node
4. Delete the databases but leave the rest
5. Switch branch to master that includes the new nuget wrapper
6. Build the code and run it 

**Workarounds**
- Build and run the code again.
- or delete previous build artifacts before a new build

**Comment by rubo** [comment]
How exactly have you built it?

**Comment by dceleda** [comment]
> How exactly have you built it?

There is a script on some VMs:
```
#! /bin/bash
cd ~/src/nethermind
git stash
git pull
git submodule update
git stash apply
cd ../..
cd ~/src/nethermind/src/Nethermind/Nethermind.Runner
dotnet build -c Release -o ~/nethermind
cp ~/NLog.config ~/nethermind/NLog.config
```

**Comment by rubo** [comment]
@dceleda Have you seen [this](https://github.com/NethermindEth/nethermind/pull/4351#issuecomment-1212596698)?

**Comment by dceleda** [comment]
I think it doesn't matter if one builds from the script or not. Nothing fancy there. 
The problem is related to switching the branches between an old wrapper one and a new nuget one, and building from the code.
In the end, it's not a big problem. Whenever someone builds again the error will disappear and new pulls and builds should be ok.

**Comment by dceleda** [comment]
I think at some point we'll be able to close that issue when all nodes will be 1.14+
Of course with a test of upgrading for example from
1.14.0 to some newer version.
