### ISSUE TITLE
[Restart] After restart on Goerli, Invalid best state calculation exception thrown

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4466]
**Describe the bug**
During testing on goerli testnet I've restarted Nethermind node and changed config in the meantime. After running run command, exceptions started appearing:

```
2022-08-24 15:20:52.1832|Invalid best state calculation: processed:7463862|state:7463862|block:7463850|header:7463850|chain difficulty:10790000|peer block:7463905|peer total difficulty:10790000
2022-08-24 15:20:52.1832|Sync mode update failed System.ComponentModel.InvalidAsynchronousStateException: Invalid best state calculation: processed:7463862|state:
7463862|block:7463850|header:7463850|chain difficulty:10790000|peer block:7463905|peer total difficulty:10790000
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.VerifySnapshot(Snapshot best) in C:\repos\nethermind\src\Nethermind\Nethermind.Synchronization\ParallelSync\MultiSyncModeSelector.cs:line 653
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.TakeSnapshot(UInt256& peerDifficulty, Int64 peerBlock, Boolean inBeaconControl) in C:\repos\nethermind\src\Nethermind\Nethermind.Synchronization\ParallelSync\MultiSyncModeSelector.cs:line 627
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.Update() in C:\repos\nethermind\src\Nethermind\Nethermind.Synchronization\ParallelSync\MultiSyncModeSelector.cs:line 174
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.StartAsync(CancellationToken cancellationToken) in C:\repos\nethermind\src\Nethermind\Nethermind.Synchronization\ParallelSync\MultiSyncModeSelector.cs:line 129
```

**To Reproduce**
This was one time exception - after following restart everything came back to normal.

**Desktop (please complete the following information):**
 - OS: Windows11

**Additional context**
Logs attached

**Comment by kamilchodola** [comment]
[goerli.logs (1).txt](https://github.com/NethermindEth/nethermind/files/9417469/goerli.logs.1.txt)
