### ISSUE TITLE
Nethermind crashes with no error after eating all the RAM

### ISSUE THREAD

**Issue by nazar-kuzo** [NethermindEth/nethermind#4532]
**Describe the bug**
This happened fourth time for the last 2 days during SnapSync (SNAP - progress of State Ranges (Phase 1)).
Application works just fine and utilizing about 6 to 8 gigs of RAM but at some point it starts to output
tremendous amount of logs like:
`2022-09-07 02:12:06.8669|A new block 15438574 (0x85828f...9ad28b) in fast sync transition branch - state not found`
and RAM utilization goes to 100% and it crashes with no error. Last logs before restart:
```2022-09-07 02:12:07.1784|A new block 15438572 (0xa61462...ed613c) in fast sync transition branch - state not found
2022-09-07 02:12:07.4261|A new block 15438571 (0xea034a...62b7a1) in fast sync transition branch - state not found
2022-09-07 02:12:07.6157|A new block 15438570 (0xd31300...cca5e3) in fast sync transition branch - state not found
2022-09-07 02:12:07.7118|A new block 15438569 (0xc85ddd...1298b5) in fast sync transition branch - state not found
2022-09-07 02:12:07.9265|A new block 15438568 (0x7d4fd2...29c393) in fast sync transition branch - state not found
2022-09-07 02:12:08.0205|A new block 15438567 (0x96fa7e...69abf9) in fast sync transition branch - state not found
2022-09-07 02:12:08.0802|Downloaded 15487619 / 15487651 | current     0.00bps | total     0.07bps
2022-09-07 02:12:08.2126|A new block 15438566 (0xe9bc51...b16d06) in fast sync transition branch - state not found
2022-09-07 02:12:12.8184|Downloaded 15487619 / 15487651 | current     0.00bps | total     0.07bps
2022-09-07 02:12:15.6636|Downloaded 15487619 / 15487651 | current     0.00bps | total     0.07bps
2022-09-07 02-12-20.9144|Nethermind starting initialization.
2022-09-07 02-12-21.1753|Loading embedded plugins
2022-09-07 02-12-21.1755|  Found plugin type Nethermind.Consensus.AuRa.AuRaPlugin
2022-09-07 02-12-21.1755|  Found plugin type Nethermind.Consensus.Clique.CliquePlugin
2022-09-07 02-12-21.1755|  Found plugin type Nethermind.Consensus.Ethash.EthashPlugin
2022-09-07 02-12-21.1755|  Found plugin type Nethermind.Consensus.Ethash.NethDevPlugin
2022-09-07 02-12-21.1755|  Found plugin type Nethermind.Hive.HivePlugin```

**To Reproduce**
Steps to reproduce the behavior:
1. Run docker with command:
```sudo docker run -t -d -v $HOME/nethermind:/var/lib/nethermind \
-v $HOME/jwtsecret:/var/lib/jwtsecret \
--network host \
--name nethermind nethermind/nethermind:latest \
--config mainnet \
--datadir /var/lib/nethermind \
--Sync.SnapSync true \
--Sync.AncientBodiesBarrier 11052984 \
--Sync.AncientReceiptsBarrier 11052984 \
--JsonRpc.Enabled true \
--JsonRpc.EngineHost 0.0.0.0 \
--JsonRpc.EnginePort 8551 \
--JsonRpc.JwtSecretFile /var/lib/jwtsecret/jwt.hex \
--JsonRpc.AdditionalRpcUrls "http://localhost:8551|http;ws|net;eth;subscribe;engine;web3;client" \
--Pruning.Mode=Full \
--Merge.Enabled true```

2. Run Prysm Beacon Node and Validator on the same machine:
```sudo docker run -t -d -v $HOME/.eth2:/data \
-v $HOME/jwtsecret:/var/lib/jwtsecret \
--network host \
--name beacon-node gcr.io/prysmaticlabs/prysm/beacon-chain:stable \
--mainnet \
--datadir=/data \
--rpc-host=0.0.0.0 \
--p2p-host-ip={VM_IP} \
--grpc-gateway-host=0.0.0.0 \
--execution-endpoint=http://127.0.0.1:8551 \
--jwt-secret=/var/lib/jwtsecret/jwt.hex \
--suggested-fee-recipient=0xEad087dfBcAd3B48c9B05A9a4e3ff79C88d97340 \
--checkpoint-sync-url={INFURA_URL} \
--genesis-beacon-api-url={INFURA_URL} \
--accept-terms-of-use```

3. Wait around 8 hours
4. See error

**Expected behavior**
RAM utilization should stay around 6 - 8 gigs, SnapSync should continue processing, no restart should happen without an error.

**Screenshots**
Metrics from VM (Network IO/RAM/CPU utilization)
![image](https://user-images.githubusercontent.com/13677730/188796980-3fa5540d-d54c-4ccb-a6f4-ee2aa3b61b32.png)


**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS or Ubuntu 18.04.5 LTS (happened on both)
 - Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
 - Nethermind Image sha256:c35fdbca41ed16d4ff22ed24c668be401e6a58c07f2cdf5402d3d320a1439fbc

**Additional context**
Running in Azure VM (Standard D4as v4 (4 vcpus, 16 GiB memory)), 2048 GiB Premium SSD as OS Disk

**Comment by nazar-kuzo** [comment]
@LukaszRozmej @matilote @MarekM25 sorry for this rude chime-in, but I would like to hear some workaround/config changes to have this SnapSync is done, since it restarts every 8-12 hours and sync starts over, so I feel like I`m in a dead loop here, thank you!

**Comment by MarekM25** [comment]
> @LukaszRozmej @matilote @MarekM25 sorry for this rude chime-in, but I would like to hear some workaround/config changes to have this SnapSync is done, since it restarts every 8-12 hours and sync starts over, so I feel like I`m in a dead loop here, thank you!

Thanks for reporting. It will help us resolve the problem!. It seems that it is connected to this issue: https://github.com/NethermindEth/nethermind/issues/4526
It looks like we have edge case during the sync. If I were you, I would try resync from scratch. Snap Sync is fast, so it shouldn't take long time. Our team will try to resolve root cause in the same time.

**Comment by nazar-kuzo** [comment]
@MarekM25 thanks for the quick reply, when you say  

> I would try resync from scratch

How can I do that? could you please point me to doc where I can prune existing state and start from scratch, thanks!

**Comment by nazar-kuzo** [comment]
@MarekM25 btw, I tried to make a memory dump and it says Process xxx not running compatible .NET runtime. I was installing .net 6, is this the correct one?

**Comment by MarekM25** [comment]
> @MarekM25 thanks for the quick reply, when you say
> 
> > I would try resync from scratch
> 
> How can I do that? could you please point me to doc where I can prune existing state and start from scratch, thanks!

Just close your client and remove your database folder. You can find the default db path here: https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Runner/configs/mainnet.cfg#L5

**Comment by nazar-kuzo** [comment]
@Marek, currently Nethermind is in a almost died state, when it eaten all the memory but still working, do you want me to do something for you in that state?

**Comment by MarekM25** [comment]
> @MarekM25, currently Nethermind is in a almost died state, when it eaten all the memory but still working, do you want me to do something for you in that state?

Thx a lot. It is not needed :) Your bug report helped me understand more about the root cause. I think we can explore this issue without your DB! :) Let me know that fresh sync will work for you.

**Comment by nazar-kuzo** [comment]
ah ok, glad to hear that, good luck then 😉

**Comment by nazar-kuzo** [comment]
@MarekM25  little update after 3 hours of sync I noticed such messages:

```2022-09-07 10:26:55.2956|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:22
2022-09-07 10:26:55.2956|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:27
2022-09-07 10:26:55.3144|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:21
2022-09-07 10:26:55.3144|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:32
2022-09-07 10:26:55.3344|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:41
2022-09-07 10:26:55.3344|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:31
2022-09-07 10:26:55.3384|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:21
2022-09-07 10:26:55.3446|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:42
2022-09-07 10:26:55.3446|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:48
2022-09-07 10:26:55.3446|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:51
2022-09-07 10:26:55.3470|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:52
2022-09-07 10:26:55.3470|A new block 15482897 (0xe6c840...2202c4) in fast sync transition branch - state not found
2022-09-07 10:26:55.3470|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:23:54
2022-09-07 10:26:55.3470|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:24:01
2022-09-07 10:26:55.3470|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:24:02
2022-09-07 10:26:55.3470|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:24:11
2022-09-07 10:26:55.3470|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:24:12
2022-09-07 10:26:55.3470|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:24:15
2022-09-07 10:26:55.3470|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:24:21
2022-09-07 10:26:55.3470|Authentication token is outdated. Now is 09/07/2022 10:26:55 +00:00, token issued at 09/07/2022 10:24:21
2```

than this message 
`2022-09-07 10:26:55.8548|Sync mode changed from FastSync, SnapSync to Disconnected`

after 5 minutes it recovered sync

```2022-09-07 10:30:01.9031|Changing state FastSync, SnapSync to SnapSync at processed:0|state:0|block:15489332|header:15489749|chain difficulty:58160603428264791926830|peer block:15489781|peer total difficulty:58166056879121714677940
2022-09-07 10:30:01.9031|Sync mode changed from FastSync, SnapSync to SnapSync```

then strugged to find peers

`2022-09-07 10:35:06.7110|Waiting for peers... 51s`

then this

```2022-09-07 10:35:07.5014|Changing state Disconnected to None at processed:0|state:0|block:15489332|header:15489757|chain difficulty:58160603428264791926830|peer block:15476000|peer total difficulty:57998979804538619603632
2022-09-07 10:35:07.5014|Sync mode changed from Disconnected to None
2022-09-07 10:35:07.8960|SNAP - progress of State Ranges (Phase 1): 35.546875% [***       ]```

```2022-09-07 10:36:23.5041|Changing state FastSync, SnapSync to SnapSync at processed:0|state:0|block:15489332|header:15489773|chain difficulty:58160603428264791926830|peer block:15489805|peer total difficulty:58166345612168178463864
2022-09-07 10:36:23.5041|Sync mode changed from FastSync, SnapSync to SnapSync```

and now again this

`2022-09-07 10:42:07.1515|Authentication token is outdated. Now is 09/07/2022 10:42:07 +00:00, token issued at 09/07/2022 10:37:51`

```2022-09-07 10:42:41.3397|Executing JSON RPC call eth_getBlockByNumber with params [latest, False]
2022-09-07 10:42:41.8537|Changing state FastSync, SnapSync to SnapSync at processed:0|state:0|block:15489332|header:15489804|chain difficulty:58160603428264791926830|peer block:15489836|peer total difficulty:58166719039747508434997
2022-09-07 10:42:41.8537|Sync mode changed from FastSync, SnapSync to SnapSync
2022-09-07 10:43:37.1522|Changing state SnapSync to FastSync, SnapSync at processed:0|state:0|block:15489332|header:15489804|chain difficulty:58160603428264791926830|peer block:15489837|peer total difficulty:58166706986559964319735
2022-09-07 10:43:37.1522|Sync mode changed from SnapSync to FastSync, SnapSync
2022-09-07 10:43:37.1659|Sync mode changed from FastSync, SnapSync to Disconnected
2022-09-07 10:43:37.1735|Executing JSON RPC call eth_getBlockByNumber with params [latest, False]
2022-09-07 10:43:38.1167|Waiting for peers... 22s
2022-09-07 10:43:38.1220|Changing state Disconnected to None at processed:0|state:0|block:15489332|header:15489804|chain difficulty:58160603428264791926830|peer block:15476000|peer total difficulty:57998979804538619603632
2022-09-07 10:43:38.1220|Sync mode changed from Disconnected to None```

**Comment by nazar-kuzo** [comment]
@MarekM25 and now I get this error as #4514 

```
2022-09-07 10:52:51.5627|Processing part of a long blocks branch 0/13332. Block: 15476001 (0x0046a4...81e9b3)
2022-09-07 10:52:51.5919|Processing loop threw an exception. Block: Nethermind.Consensus.Processing.BlockRef, Exception: Nethermind.Trie.TrieException: Failed to load key 245484f029fd49ff7b7e98c7b19e52409f10cc42e1051170ef64fafcaec26628 from root hash 0xae193f2329b197aa10c9699780d6a963dbda95809d52232f55aebec3858690c0.
 ---> Nethermind.Trie.TrieException: Node 0xae193f2329b197aa10c9699780d6a963dbda95809d52232f55aebec3858690c0 is missing from the DB
   at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak, IKeyValueStore keyValueStore) in /src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 328
   at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak) in /src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 336
   at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree) in /src/Nethermind/Nethermind.Trie/TrieNode.cs:line 318
   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak startRootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 399
   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 328
   --- End of inner exception stack trace ---
   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in /src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 328
   at Nethermind.State.StateProvider.GetState(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 655
   at Nethermind.State.StateProvider.GetAndAddToCache(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 681
   at Nethermind.State.StateProvider.GetAccount(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 116
   at Nethermind.Evm.TransactionProcessing.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, ExecutionOptions executionOptions) in /src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs:line 188
   at Nethermind.Evm.TransactionProcessing.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer) in /src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs:line 111
   at Nethermind.Evm.TransactionProcessing.ExecuteTransactionProcessorAdapter.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer) in /src/Nethermind/Nethermind.Evm/TransactionProcessing/ExecuteTransactionProcessorAdapter.cs:line 33
   at Nethermind.Consensus.Processing.TransactionProcessorAdapterExtensions.ProcessTransaction(ITransactionProcessorAdapter transactionProcessor, Block block, Transaction currentTx, BlockReceiptsTracer receiptsTracer, ProcessingOptions processingOptions, IStateProvider stateProvider) in /src/Nethermind/Nethermind.Consensus/Processing/TransactionProcessorAdapterExtensions.cs:line 40
   at Nethermind.Consensus.Processing.BlockProcessor.BlockValidationTransactionsExecutor.ProcessTransactions(Block block, ProcessingOptions processingOptions, BlockReceiptsTracer receiptsTracer, IReleaseSpec spec) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockValidationTransactionsExecutor.cs:line 53
   at Nethermind.Consensus.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 238
   at Nethermind.Consensus.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 207
   at Nethermind.Consensus.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 115
   at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 458
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 358
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 287
2022-09-07 10:52:51.6934|Changing state SnapSync to FastSync, SnapSync at processed:0|state:0|block:15489332|header:15489845|chain difficulty:58160603428264791926830|peer block:15489878|peer total difficulty:58167214404050342055366
2022-09-07 10:52:51.6934|Sync mode changed from SnapSync to FastSync, SnapSync
2022-09-07 10:52:51.7390|Downloaded 15489845 / 15489877 | current     0.00bps | total     0.94bps
2022-09-07 10:52:52.4008|Discovered new block 15489878 10:52:10 (0xbc4557...6490e3), tx count: 386 miner Ethermine, sent by [Peer|eth66|15489878|  174.75.54.184:36380]
2022-09-07 10:52:52.6915|Changing state FastSync, SnapSync to SnapSync at processed:0|state:0|block:15489332|header:15489846|chain difficulty:58160603428264791926830|peer block:15489878|peer total difficulty:58167226445082929899797
2022-09-07 10:52:52.6915|Sync mode changed from FastSync, SnapSync to SnapSync
2022-09-07 10:52:54.3342|SNAP - progress of State Ranges (Phase 1): 36.71875% [***       ]
```

**Comment by nazar-kuzo** [comment]
Next update:

for last 90 minutes sync progress stays the same with such log output

```
2022-09-07 12:48:51.5767|Downloaded 15489852 / 15489884 | current     0.00bps | total     0.64bps
2022-09-07 12:48:51.8241|SNAP - progress of State Ranges (Phase 1): 42.1875% [****      ]
2022-09-07 12:48:52.3990|SNAP - progress of State Ranges (Phase 1): 42.1875% [****      ]
2022-09-07 12:48:52.5804|Downloaded 15489852 / 15489884 | current     0.00bps | total     0.64bps
2022-09-07 12:48:53.2038|SNAP - progress of State Ranges (Phase 1): 42.1875% [****      ]
2022-09-07 12:48:53.5797|Downloaded 15489852 / 15489884 | current     0.00bps | total     0.64bps
2022-09-07 12:48:54.0202|SNAP - progress of State Ranges (Phase 1): 42.1875% [****      ]
2022-09-07 12:48:54.5799|Downloaded 15489852 / 15489884 | current     0.00bps | total     0.64bps
2022-09-07 12:48:54.7872|SNAP - progress of State Ranges (Phase 1): 42.1875% [****      ]
2022-09-07 12:48:55.5786|Downloaded 15489852 / 15489884 | current     0.00bps | total     0.64bps
2022-09-07 12:48:55.6201|SNAP - progress of State Ranges (Phase 1): 42.1875% [****      ]
2022-09-07 12:48:56.3075|SNAP - progress of State Ranges (Phase 1): 42.1875% [****      ]
2022-09-07 12:48:56.3075|SNAP - (NextSlotRange:1, diff:0) True:0x6c86aeb81e8f19013a95f60bd11cf4928b56c24faa7b13e17ef89257feb3e599 - Requests Account:1 | Storage:1 | Code:0 | Refresh:0 - Queues Slots:0 | Storages:0 | Codes:0 | Refresh:0
2022-09-07 12:48:56.5788|Downloaded 15489852 / 15489884 | current     0.00bps | total     0.64bps
2022-09-07 12:48:57.1470|SNAP - progress of State Ranges (Phase 1): 42.1875% [****      ]
2022-09-07 12:48:57.5795|Downloaded 15489852 / 15489884 | current     0.00bps | total     0.64bps
2022-09-07 12:48:57.9949|SNAP - progress of State Ranges (Phase 1): 42.1875% [****      ]
2022-09-07 12:48:58.5806|Peers | with known best block: 100 | all: 101 |
2022-09-07 12:48:58.5806|Downloaded 15489852 / 15489884 | current     0.00bps | total     0.64bps
2022-09-07 12:48:58.7759|SNAP - progress of State Ranges (Phase 1): 42.1875% [****      ]
```

**Comment by nazar-kuzo** [comment]
@smartprogrammer93 @MarekM25 please tell me what should I do

**Comment by dceleda** [comment]
Related to https://github.com/NethermindEth/nethermind/issues/4502

**Comment by MarekM25** [comment]
@nazar-kuzo I think we can close this issue, right?

**Comment by nazar-kuzo** [comment]
@MarekM25 Yes we can!
