### ISSUE TITLE
Config file being erased

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4613]
**Describe the bug**
The config file is completely erased if the JSON is incorrectly formatted.

**To Reproduce**
1. Broke your config file - for example remove a required comma.
2. Run the node
3. You should get:
```
2022-09-21 17:39:23.7995|Failure System.Configuration.ConfigurationErrorsException: Config is not correctly formed JSon. See inner exception for details.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Nethermind.Config.JsonConfigSource.ApplyJsonConfig(String jsonContent) in /root/src/nethermind/src/Nethermind/Nethermind.Config/JsonConfigSource.cs:line 37
   --- End of inner exception stack trace ---
   at Nethermind.Config.JsonConfigSource.ApplyJsonConfig(String jsonContent) in /root/src/nethermind/src/Nethermind/Nethermind.Config/JsonConfigSource.cs:line 45
   at Nethermind.Config.JsonConfigSource.LoadJsonConfig(String configFilePath) in /root/src/nethermind/src/Nethermind/Nethermind.Config/JsonConfigSource.cs:line 51
   at Nethermind.Config.JsonConfigSource..ctor(String configFilePath) in /root/src/nethermind/src/Nethermind/Nethermind.Config/JsonConfigSource.cs:line 30
   at Nethermind.Runner.Program.BuildConfigProvider(CommandLineApplication app, CommandOption loggerConfigSource, CommandOption logLevelOverride, CommandOption configsDirectory, CommandOption configFile) in /root/src/nethermind/src/Nethermind/Nethermind.Runner/Program.cs:line 401
   at Nethermind.Runner.Program.<>c__DisplayClass10_0.<<Run>b__2>d.MoveNext() in /root/src/nethermind/src/Nethermind/Nethermind.Runner/Program.cs:line 138
```
4. Check if your config file is empty now.

**Comment by deffrian** [comment]
Can't reproduce on Ubuntu 20.04

**Comment by dceleda** [comment]
> Can't reproduce on Ubuntu 20.04

OK, so let's close it.
