### ISSUE TITLE
PushGatewayUrl 

### ISSUE THREAD

**Issue by flcl42** [NethermindEth/nethermind#4736]
**Describe the bug**

**To Reproduce**
1. Enable metrics, without having push receiver up or configured
2. Start the client
3. Exception appears
  ```
Could not reach PushGatewayUrl, Please make sure you have set the correct endpoint in the configurations. System.Net.Http.HttpRequestException: Connection refused (localhost:9091)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Prometheus.MetricPusher.<>c__DisplayClass8_0.<<StartServer>b__0>d.MoveNext()
```

**Expected behavior**
Metrics work without push receiver configured or even when it is set up, but is down

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by kamilchodola** [comment]
@MarekM25 any details? I see this label which gives me a understanding that it was fixed already.

**Comment by stdevMac** [comment]
Closing: fixed — MonitoringService's Pushgateway OnError handler now catches the SocketException and logs 'Cannot reach Pushgateway' instead of crashing. The issue was already labeled fixed-awaiting-release.
