### ISSUE TITLE
Healthchecks-UI flag is throwing an exception

### ISSUE THREAD

**Issue by dharmendrakariya** [NethermindEth/nethermind#4744]
**Describe the bug**

When providing the flag ``` --Metrics.Enabled=true and  --HealthChecks.UIEnabled=true``` We are seeing below errors

```
2022-10-11 11:11:01.7920|Entity Framework Core 6.0.2 initialized 'HealthChecksDb' using provider 'Microsoft.EntityFrameworkCore.InMemory:6.0.2' with options: StoreName=HealthChecksUI  
2022-10-11 11:11:01.7920|Start processing HTTP request GET http://localhost:8545/health 
2022-10-11 11:11:01.7920|Sending HTTP request GET http://localhost:8545/health 
2022-10-11 11:11:01.7920|Request starting HTTP/1.1 GET http://localhost:8545/health - - 
2022-10-11 11:11:01.7920|Request finished HTTP/1.1 GET http://localhost:8545/health - - - 200 - - 0.0596ms 
2022-10-11 11:11:01.7920|Received HTTP response headers after 0.5006ms - 200 
2022-10-11 11:11:01.7920|End processing HTTP request after 0.5342ms - 200 
2022-10-11 11:11:01.7920|GetHealthReport threw an exception when trying to get report from http://localhost:8545/health configured with name health. Newtonsoft.Json.JsonReaderException: Error parsing NaN value. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseNumberNaN(ReadType readType, Boolean matched)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at System.Net.Http.HttpResponseMessageExtensions.As[TContent](HttpResponseMessage response) in /_/src/HealthChecks.UI/Core/Extensions/HttpResponseMessageExtensions.cs:line 28
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReportAsync(HealthCheckConfiguration configuration) in /_/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 107
2022-10-11 11:11:01.7920|Notification is sent on same window time. 
2022-10-11 11:11:01.7920|Saved 1 entities to in-memory store.
```

**To Reproduce**
1. Go to 'https://github.com/gnosischain/nethermind-client/blob/main/docker-compose.yml' and give above two flags
2. Run ```docker-compose up --build -d``` 
3. Check the docker logs

**Expected behavior**

We should be able to see the metrics in push gateway and grafana dashboard but metrics is not being exposed! 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Additional context**

**Comment by deffrian** [comment]
`--HealthChecks.UIEnabled=true` is not enough, you should enable Health Checks by adding `--HealthChecks.Enabled=true`
