### ISSUE TITLE
OOM exception while searching for peers on Rinkeby

### ISSUE THREAD

**Issue by igorbarinov** [NethermindEth/nethermind#493]
After failing to find peers due to a misconfiguration of a security group on AWS (v0.9.9, Ubuntu 18.04) the client had an OOM exception 🤭The security group didn't have port 30303 open and had a custom port for peer discovery inherited from another server.

Here is the log:

```
ueue 2000|
2019-05-21 09:55:11.6234|Sync peers 0(0)/25, searching for peers to sync with...|
2019-05-21 09:55:16.4974|Sync peers 0(0)/25, searching for peers to sync with...|
2019-05-21 09:55:19.4348|Sync peers 0(0)/25, searching for peers to sync with...|
2019-05-21 09:55:22.7463|Sync peers 0(0)/25, searching for peers to sync with...|
2019-05-21 09:55:27.8375|Sync peers 0(0)/25, searching for peers to sync with...|
2019-05-21 09:55:31.2673|Sync peers 0(0)/25, searching for peers to sync with...|
2019-05-21 09:55:33.6046|Sync peers 0(0)/25, searching for peers to sync with...|
2019-05-21 09:55:33.7261|Processed blocks up to    470347 in   24694ms, mgasps    0.00 total   50.80, tps    0.04 total   52.99, bps    0.08 total   86.90, recv queue 305953, proc queue 2000|
2019-05-21 09:55:36.2399|Sync peers 0(0)/25, searching for peers to sync with...|
2019-05-21 09:55:38.7091|Sync peers 0(0)/25, searching for peers to sync with...|
2019-05-21 09:55:41.2058|Sync peers 0(0)/25, searching for peers to sync with...|
2019-05-21 09:55:43.7683|Processed blocks up to    470349 in   10231ms, mgasps    0.00 total   50.13, tps    0.00 total   52.29, bps    0.20 total   85.75, recv queue 305951, proc queue 2000|
2019-05-21 09:55:45.3582|Sync peers 0(0)/25, searching for peers to sync with...|

ubuntu@ip-10-1-4-44:~/nethermind$ 2019-05-21 09:55:46.9494|Sync peers 0(0)/25, searching for peers to sync with...|
2019-05-21 09:55:46.8586|Failure|System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal()
   at System.Threading.Thread.Start(Object parameter)
   at System.ConsolePal.ControlCHandlerRegistrar.OnBreakEvent(CtrlCode ctrlCode)
   at System.ConsolePal.ControlCHandlerRegistrar.<>c.<Register>b__1_0(CtrlCode c)

Unhandled Exception: OutOfMemoryException.
```

**Comment by igorbarinov** [comment]
Host parameters:
t2.medium instance on AWS 2 vCPU, 4Gb RAM

**Comment by tkstanczak** [comment]
@igorbarinov, thank you for reporting this, this a reproducible issue and easily fixable through configuration files.

The node per se is not using too much memory and just allocates too big memory cache sizes to the underlying database.

1) I will send you a config file that sets the memory limits properly for your instance size

2) we have a work item planned to both easily set and easily understand the upper memory usage bound - I will create a GitHub issue to track it

**Comment by tkstanczak** [comment]
@igorbarinov this will be also tracked in #494

**Comment by igorbarinov** [comment]
Thanks, now that server just hanged because of the memory stuff probably 🤔
How to redirect logs to syslog? is there an option for it?

on my foundation archive node memory usage is high but limits are high too
<img width="1277" alt="Screen Shot 2019-05-21 at 12 57 35 PM" src="https://user-images.githubusercontent.com/424628/58090668-0d666200-7bc8-11e9-8e7a-6e822198b6c4.png">

**Comment by tkstanczak** [comment]
We will test adding the new logging target for NLog:
https://github.com/luigiberrettini/NLog.Targets.Syslog

We also have seq integration if you would like to try it (we are planning to merge it with the main branch but haven't seen much interest yet):
https://datalust.co/seq

**Comment by tkstanczak** [comment]
@igorbarinov the foundation archive node that you sent a screenshot of - you mentioned that it hanged - do you mean that the node stopped progressing with blocks processing?

**Comment by tkstanczak** [comment]
Tracking syslog in #495

**Comment by tkstanczak** [comment]
Here is the Rinkeby full archive cfg for your 4GB  machine.
The prepackaged config incorrectly sets the same limits as for the foundation chain (up to 100GB RAM cached)
[rinkeby_archive.zip](https://github.com/NethermindEth/nethermind/files/3203252/rinkeby_archive.zip)

**Comment by tkstanczak** [comment]
@igorbarinov I spoke to @Reimdal and he mentioned that if you launch Nethermind with systemd:
https://nethermind.readthedocs.io/en/latest/download.html

then the logs will be saved at /var/log/syslog and you can access them via journalctl -u nethermind

Would that work for you?
Maybe added some specialized target would be unnecessary.

But in case you need remote syslog then it is all possible via this package: https://github.com/luigiberrettini/NLog.Targets.Syslog that I have already added to the v1.0 dev

**Comment by igorbarinov** [comment]
> @igorbarinov I spoke to @Reimdal and he mentioned that if you launch Nethermind with systemd:
https://nethermind.readthedocs.io/en/latest/download.html

thanks, launched as daemon

> then the logs will be saved at /var/log/syslog and you can access them via journalctl -u nethermind

Yes, it works.

-- 
Regarding the original problem
I applied parameters with 4Gb log.

The node is still hanging and I can't connect to it after some time of application running (before I added it as service)
In AWS console I see 
```
Instance reachability check failed at May 22, 2019 at 12:11:00 AM UTC+2 (11 hours and 2 minutes ago)
```
on archive node of mainnet where I have plenty of RAM I don't have such problem
<img width="1066" alt="Screen Shot 2019-05-22 at 11 15 05 AM" src="https://user-images.githubusercontent.com/424628/58162652-def98d00-7c82-11e9-991f-94fb4bdef35b.png">

I had to restart the node from AWS console.

**Comment by igorbarinov** [comment]
I've added `MemoryLimit=2G` to the nethermind.service. Let's see if it works

**Comment by tkstanczak** [comment]
I will launch the same setup on AWS and check the behaviour.

**Comment by tkstanczak** [comment]
This is a full archive rinkeby, right?

**Comment by igorbarinov** [comment]
Yes, archive Rinkeby

**Comment by igorbarinov** [comment]
`MemoryLimit=2G` or running as a service helped with node hanging. Will comment the `MemoryLimit=2G` parameter in the service config and try again

**Comment by tkstanczak** [comment]
in the end, changing the config solved it - the issue was caused by me not setting CacheIndexAndFilters to true in the config (or at least not warning that this setting at false removes the upper memory bounds)
