### ISSUE TITLE
[Graceful shutdown] When node stopped on OldBodies, exception occurs

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4989]
**To Reproduce**
1. Start syncing Mainnet
2. When node reach OldBodies stage stop a node using CTRL+C

**Actual behavior**
Exception visible:
```
2022-12-08 15:18:36.1745|INFO|220|Peer Manager shutdown complete.. please wait for all components to close
2022-12-08 15:18:36.1745|INFO|220|Stopping synchronizer...
2022-12-08 15:18:36.1774|WARN|220|Failure when executing request System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Nethermind.Network.P2P.ProtocolHandlers.ZeroProtocolHandlerBase.HandleResponse[TRequest,TResponse](Request`2 request, TransferSpeedType speedType, Func`2 describeRequestFunc, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroProtocolHandlerBase.cs:line 82
   at Nethermind.Network.P2P.Subprotocols.Eth.V66.Eth66ProtocolHandler.SendRequestGenericEth66[T66,TRequest,TResponse](MessageDictionary`3 messageQueue, T66 message, TransferSpeedType speedType, Func`2 describeRequestFunc, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs:line 288
   at Nethermind.Network.P2P.Subprotocols.Eth.V66.Eth66ProtocolHandler.SendRequest(GetBlockBodiesMessage message, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs:line 238
   at Nethermind.Network.P2P.ProtocolHandlers.SyncPeerProtocolHandlerBase.Nethermind.Blockchain.Synchronization.ISyncPeer.GetBlockBodies(IReadOnlyList`1 blockHashes, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs:line 84
   at Nethermind.Synchronization.FastBlocks.BodiesSyncDispatcher.Dispatch(PeerInfo peerInfo, BodiesSyncBatch batch, CancellationToken cancellationToken) in /root/src/nethermind/src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncDispatcher.cs:line 54
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.DoDispatch(CancellationToken cancellationToken, PeerInfo allocatedPeer, T request, SyncPeerAllocation allocation) in /root/src/nethermind/src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs:line 159
2022-12-08 15:18:36.1774|WARN|220|Failure when executing request System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Nethermind.Network.P2P.ProtocolHandlers.ZeroProtocolHandlerBase.HandleResponse[TRequest,TResponse](Request`2 request, TransferSpeedType speedType, Func`2 describeRequestFunc, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroProtocolHandlerBase.cs:line 82
   at Nethermind.Network.P2P.Subprotocols.Eth.V66.Eth66ProtocolHandler.SendRequestGenericEth66[T66,TRequest,TResponse](MessageDictionary`3 messageQueue, T66 message, TransferSpeedType speedType, Func`2 describeRequestFunc, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs:line 288
   at Nethermind.Network.P2P.Subprotocols.Eth.V66.Eth66ProtocolHandler.SendRequest(GetBlockBodiesMessage message, CancellationToken token) in /root/src/nethermind/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs:line 238
   at Nethermind.Network.P2P.ProtocolHandlers.SyncPeerProtocolHandlerBase.Nethermind.Blockchain.Synchronization.ISyncPeer.GetBlockBodies(IReadOnlyList`1 blockHashes, CancellationToken token) in
```

**Expected behavior**
Node should be stopped without any issue - to be investigated why is this happening on this stage

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: Nethermind master

**Comment by kamilchodola** [comment]
Got the same exceptions now on ForwardSync

**Comment by smartprogrammer93** [comment]
This does not pose an issue, only needed to handle the exception so it does not produce this ugly message in logs as far as i know

**Comment by smartprogrammer93** [comment]
There is this one as well?
![image (6)](https://user-images.githubusercontent.com/33181301/208291564-297e20f5-836a-450e-810e-574a6e68607e.png)
