### ISSUE TITLE
Database corruption after duplication

### ISSUE THREAD

**Issue by MaxTeiger** [NethermindEth/nethermind#5126]
**Describe the bug**
After using `rsync -ah` to duplicate my archive DB, I tried running Nethermind with the cloned DB but it crashed with this error :
```
Step InitDatabase             failed after 5534ms RocksDbSharp.RocksDbException: Corruption: Corruption: IO error: No such file or directory: While open a file for random read: /nethermind/nethermind_db/poacore_archive/state/0/1289410.ldb: No such file or directory in file /nethermind/nethermind_db/poacore_archive/state/0/MANIFEST-1287230
```

**To Reproduce**
1. Get an archive node on POA in sync and up to date (running using docker)
2. Stop the node (docker stop)
3. Use `rsync -ah --info=progress2 ./data/nethermind_db ./your_duplicate` to duplicate your database
4. Use docker to run an archive node, but using the duplicate DB 

**Expected behavior**
I was expecting to have a second archive node up & running without the need to resync all the blockchain

**Logs**

When I rsync my DB :

```bash
root@POA-CORE-ARCHIVE-2:/# rsync --info=progress2 -ah ./node-setup /mnt/volume_poa_archive_2/
          1.70T  99%  240.00MB/s    1:52:39 (xfr#25743, to-chk=979/26794)  
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287820.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287821.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287822.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287823.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287948.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287949.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287950.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287951.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287952.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287953.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287954.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287955.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1287956.sst"
          1.70T  99%  240.01MB/s    1:52:40 (xfr#25792, to-chk=930/26794)
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288049.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288050.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288051.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288052.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288053.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288054.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288055.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288056.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288057.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288058.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288059.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288060.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288061.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288062.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288063.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288064.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288065.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288066.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288067.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288068.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288069.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288070.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288071.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288072.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288073.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288074.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288079.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288080.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288081.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288082.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288083.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288084.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288085.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288086.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288087.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288088.sst"
          1.70T  99%  240.02MB/s    1:52:42 (xfr#26032, to-chk=690/26794)
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288557.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288558.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288559.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288560.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288561.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288562.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288563.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288564.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288565.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288566.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288567.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288568.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288569.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288570.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288571.sst"
          1.70T  99%  240.02MB/s    1:52:43 (xfr#26115, to-chk=607/26794)
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288642.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288643.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288644.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288645.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288646.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288647.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288648.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288649.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288650.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288651.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288652.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288653.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288654.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288655.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288656.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288657.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288658.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288659.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288660.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288661.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288662.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288663.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288664.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288665.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288666.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288667.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288668.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288669.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288670.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288671.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288672.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288673.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288674.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288675.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288676.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288677.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288678.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288679.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288680.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288681.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288682.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288683.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288684.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288685.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288686.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288687.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288688.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288689.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288690.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288691.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288692.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288693.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288694.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288695.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1288696.sst"
          1.70T  99%  240.03MB/s    1:52:48 (xfr#26510, to-chk=212/26794)
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289141.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289142.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289143.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289145.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289146.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289147.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289148.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289150.sst"
          1.70T  99%  240.07MB/s    1:52:50 (xfr#26692, to-chk=30/26794) 
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289330.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289333.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289335.log"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289336.sst"
file has vanished: "/node-setup/data/nethermind_db/poacore_archive/state/0/1289337.log"
          1.71T 100%  240.11MB/s    1:53:00 (xfr#26722, to-chk=0/26794) 
rsync warning: some files vanished before they could be transferred (code 24) at main.c(1207) [sender=3.1.3]
```

When I start the container using the cloned DB :
```bash
root@POA-CORE-ARCHIVE-2:/node-setup# docker logs -n 25 -f poa-core-archive 
2023-01-11 10-01-47.5815|Loading assembly Nethermind.Consensus.AuRa
2023-01-11 10-01-47.5839|Loading assembly Nethermind.Merge.Plugin
2023-01-11 10-01-47.5861|  Found plugin type Nethermind.Merge.Plugin
2023-01-11 10-01-47.5862|Loading assembly Nethermind.AccountAbstraction
2023-01-11 10-01-47.5885|  Found plugin type Nethermind.AccountAbstraction
2023-01-11 10-01-47.5885|Loading assembly Nethermind.HealthChecks
2023-01-11 10-01-47.5892|  Found plugin type Nethermind.HealthChecks
2023-01-11 10-01-47.5892|Loading assembly Nethermind.Merge.AuRa
2023-01-11 10-01-47.5895|  Found plugin type Nethermind.Merge.AuRa
2023-01-11 10-01-47.6826|Loading standard NLog.config file from /nethermind/NLog.config.
2023-01-11 10-01-47.8563|NLog.config loaded in 173ms.
2023-01-11 10-01-47.8581|Reading config file from /nethermind/configs/poacore_archive.cfg
2023-01-11 10-01-48.1040|Configuration initialized.
2023-01-11 10:01:48.1240|RocksDb Version: 6.29.3 
2023-01-11 10:01:48.1351|ChainSpecPath matched an embedded resource inside the binary. Loading chainspec from embedded resources instead of file! 
2023-01-11 10:01:48.3964|Setting up memory allowances 
2023-01-11 10:01:48.3964|  memory hint:        1024MB 
2023-01-11 10:01:48.3964|  general memory:     32MB 
2023-01-11 10:01:48.3964|  peers memory:       50MB 
2023-01-11 10:01:48.3986|  Netty memory:       134MB 
2023-01-11 10:01:48.3986|  mempool memory:     122MB 
2023-01-11 10:01:48.3986|  fast blocks memory: 0MB 
2023-01-11 10:01:48.3986|  trie memory:        137MB 
2023-01-11 10:01:48.4023|  DB memory:          548MB 
2023-01-11 10:01:48.4023|Using http://ipv4.icanhazip.com to get external ip 
2023-01-11 10:01:53.8997|Step InitDatabase             failed after 5534ms RocksDbSharp.RocksDbException: Corruption: Corruption: IO error: No such file or directory: While open a file for random read: /nethermind/nethermind_db/poacore_archive/state/0/1289410.ldb: No such file or directory in file /nethermind/nethermind_db/poacore_archive/state/0/MANIFEST-1287230
   at RocksDbSharp.Native.rocksdb_open(IntPtr options, String name)
   at RocksDbSharp.RocksDb.Open(OptionsHandle options, String path)
   at Nethermind.Db.Rocks.DbOnTheRocks.<Init>g__Open|24_0(String path, ValueTuple`2 db) in /src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 84
   at Nethermind.Db.Rocks.DbOnTheRocks.<>c.<Init>b__24_1(String s, ValueTuple`2 tuple) in /src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 107
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Nethermind.Db.Rocks.DbOnTheRocks.Init(String basePath, String dbPath, IDbConfig dbConfig, ILogManager logManager, ColumnFamilies columnFamilies, Boolean deleteOnStart) in /src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 107
   at Nethermind.Db.Rocks.DbOnTheRocks..ctor(String basePath, RocksDbSettings rocksDbSettings, IDbConfig dbConfig, ILogManager logManager, ColumnFamilies columnFamilies) in /src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 75
   at Nethermind.Db.Rocks.RocksDbFactory.CreateDb(RocksDbSettings rocksDbSettings) in /src/Nethermind/Nethermind.Db.Rocks/RocksDbFactory.cs:line 39
   at Nethermind.Db.FullPruning.FullPruningInnerDbFactory.CreateDb(RocksDbSettings rocksDbSettings) in /src/Nethermind/Nethermind.Db/FullPruning/FullPruningInnerDbFactory.cs:line 51
   at Nethermind.Db.FullPruning.FullPruningDb.CreateDb(RocksDbSettings settings) in /src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs:line 59
   at Nethermind.Db.FullPruning.FullPruningDb..ctor(RocksDbSettings settings, IRocksDbFactory dbFactory, Action updateDuplicateWriteMetrics) in /src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs:line 56
   at Nethermind.Db.StandardDbInitializer.<>c__DisplayClass5_0.<RegisterAll>b__8() in /src/Nethermind/Nethermind.Db/StandardDbInitializer.cs:line 61
   at Nethermind.Db.RocksDbInitializer.<>c__DisplayClass11_0.<RegisterCustomDb>g__Action|0() in /src/Nethermind/Nethermind.Db/RocksDbInitializer.cs:line 43
   at Nethermind.Db.RocksDbInitializer.<>c__DisplayClass18_0.<InitAllAsync>b__0() in /src/Nethermind/Nethermind.Db/RocksDbInitializer.cs:line 78
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Nethermind.Db.RocksDbInitializer.InitAllAsync() in /src/Nethermind/Nethermind.Db/RocksDbInitializer.cs:line 81
   at Nethermind.Db.StandardDbInitializer.InitStandardDbsAsync(Boolean useReceiptsDb) in /src/Nethermind/Nethermind.Db/StandardDbInitializer.cs:line 51
   at Nethermind.Init.Steps.InitDatabase.Execute(CancellationToken _) in /src/Nethermind/Nethermind.Init/Steps/InitDatabase.cs:line 63
2023-01-11 10:01:53.9484|Start block loaded from reorg boundary - 30734471 - 30734471 (0xf9a6e0...08168d) 
2023-01-11 10:01:53.9502|Loaded LowestInsertedBeaconHeader:  
2023-01-11 10:01:53.9575|Numbers resolved, level = Max(30734471, 30734472), header = Max(30734471, 30734472), body = Max(30734471, 30734472) 
2023-01-11 10:01:53.9588|Beacon Numbers resolved, level = 0, header = 0, body = 0 
2023-01-11 10:01:53.9588|Block tree initialized, last processed is 30734471 (0xf9a6e0...08168d), best queued is 30734472, best known is 30734472, lowest inserted header , body , lowest sync inserted block number  
2023-01-11 10:01:53.9674|Initializing 11 plugins 
2023-01-11 10:01:53.9674|  Clique by Nethermind 
2023-01-11 10:01:53.9674|  Clique by Nethermind initialized in 0ms 
2023-01-11 10:01:53.9674|  AuRa by Nethermind 
2023-01-11 10:01:53.9674|  AuRa by Nethermind initialized in 0ms 
2023-01-11 10:01:53.9674|  Ethash by Nethermind 
2023-01-11 10:01:53.9674|  Ethash by Nethermind initialized in 0ms 
2023-01-11 10:01:53.9674|  NethDev by Nethermind 
2023-01-11 10:01:53.9674|  NethDev by Nethermind initialized in 0ms 
2023-01-11 10:01:53.9674|  Merge by Nethermind 
2023-01-11 10:01:53.9674|  Merge by Nethermind initialized in 0ms 
2023-01-11 10:01:53.9674|  Merge by Nethermind 
2023-01-11 10:01:53.9674|  Merge by Nethermind initialized in 0ms 
2023-01-11 10:01:53.9674|  MEV by Nethermind 
2023-01-11 10:01:53.9704|  MEV by Nethermind initialized in 0ms 
2023-01-11 10:01:53.9704|  HealthChecks by Nethermind 
2023-01-11 10:01:53.9704|  HealthChecks by Nethermind initialized in 0ms 
2023-01-11 10:01:53.9704|  Hive by Nethermind 
2023-01-11 10:01:53.9704|  Hive by Nethermind initialized in 0ms 
2023-01-11 10:01:53.9704|  Account Abstraction by Nethermind 
2023-01-11 10:01:53.9704|  Account Abstraction Plugin: User Operation Mining Disabled 
2023-01-11 10:01:53.9742|  Account Abstraction by Nethermind initialized in 2ms 
2023-01-11 10:01:53.9742|  EthStats by Nethermind 
2023-01-11 10:01:53.9742|  EthStats by Nethermind initialized in 0ms 
2023-01-11 10:01:53.9792|Step InitializeBlockchainAuRa failed after 3ms System.ArgumentException: state database has not been registered in DbProvider.
   at Nethermind.Db.DbProvider.GetDb[T](String dbName) in /src/Nethermind/Nethermind.Db/DbProvider.cs:line 50
   at Nethermind.Db.IDbProvider.get_StateDb() in /src/Nethermind/Nethermind.Db/IDbProvider.cs:line 31
   at Nethermind.Init.Steps.InitializeBlockchain.InitBlockchain() in /src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs:line 113
   at Nethermind.Init.Steps.InitializeBlockchain.Execute(CancellationToken _) in /src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs:line 71
2023-01-11 10:01:53.9861|Error during ethereum runner start Nethermind.Init.Steps.StepDependencyException: BlockchainProcessor
   at Nethermind.Init.Steps.StartBlockProcessor.Execute(CancellationToken _) in /src/Nethermind/Nethermind.Init/Steps/StartBlockProcessor.cs:line 37
   at Nethermind.Init.Steps.EthereumStepsManager.RunOneRoundOfInitialization(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 140
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 108
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Runner/Ethereum/EthereumRunner.cs:line 49
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version [e.g. 22]: 20.04

**Additional context**

**Comment by asdacap** [comment]
Hello, is the original node still working fine?

**Comment by asdacap** [comment]
Did you stop the node when you run rsync?

**Comment by MaxTeiger** [comment]
I first tried with the node running (and stopping during the last 10mn) and then with the node stopped during the whole sync. I got the same errors each time

**Comment by kamilchodola** [comment]
To be checked if still a thing on various chains as it is quite important to have this possibility.

**Comment by kamilchodola** [comment]
Recently tested quite a lot of various copying of DB between locations and it worked well so not an issue anymore 

@MaxTeiger please retest if you still have any possibility to do so after these 2,5 years ;D And reopen if needed.
