### ISSUE TITLE
Block without total difficulty calculated was suggested for processing

### ISSUE THREAD

**Issue by abcfy2** [NethermindEth/nethermind#5238]
**Describe the bug**
I saw this logs when I use blockscout:

```
2023-02-06 08:33:23.7581|INFO|630|Executing JSON RPC call trace_replayBlockTransactions with params [0xFB8354, [
  "trace"
]] 
2023-02-06 08:33:23.7581|ERROR|630|Error during method execution, request: ID 7, trace_replayBlockTransactions(0xFB8354,[
  "trace"
]) System.InvalidOperationException: Block without total difficulty calculated was suggested for processing
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunSimpleChecksAheadOfProcessing(Block suggestedBlock, ProcessingOptions options)
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer)
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityLikeBlockTracer tracer)
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes)
   at InvokeStub_ITraceRpcModule.trace_replayBlockTransactions(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-02-06 08:33:23.7581|WARN|630|Error when handling ID 7, trace_replayBlockTransactions(0xFB8354,[
  "trace"
]) | {"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error","data":"System.InvalidOperationException: Block without total difficulty calculated was suggested for processing\n   at Nethermind.Consensus.Processing.BlockchainProcessor.RunSimpleChecksAheadOfProcessing(Block suggestedBlock, ProcessingOptions options)\n   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityLikeBlockTracer tracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes)\n   at InvokeStub_ITraceRpcModule.trace_replayBlockTransactions(Object, Object, IntPtr*)\n   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)"},"id":7} 
2023-02-06 08:33:23.7581|INFO|630|Executing JSON RPC call trace_replayBlockTransactions with params [0xFCD094, [
  "trace"
]] 
2023-02-06 08:33:23.9376|INFO|612|Executing JSON RPC call trace_replayBlockTransactions with params [0xFB8354, [
  "trace"
]] 
2023-02-06 08:33:23.9376|ERROR|612|Error during method execution, request: ID 4, trace_replayBlockTransactions(0xFB8354,[
  "trace"
]) System.InvalidOperationException: Block without total difficulty calculated was suggested for processing
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunSimpleChecksAheadOfProcessing(Block suggestedBlock, ProcessingOptions options)
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer)
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityLikeBlockTracer tracer)
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes)
   at InvokeStub_ITraceRpcModule.trace_replayBlockTransactions(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-02-06 08:33:23.9376|WARN|612|Error when handling ID 4, trace_replayBlockTransactions(0xFB8354,[
  "trace"
]) | {"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error","data":"System.InvalidOperationException: Block without total difficulty calculated was suggested for processing\n   at Nethermind.Consensus.Processing.BlockchainProcessor.RunSimpleChecksAheadOfProcessing(Block suggestedBlock, ProcessingOptions options)\n   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityLikeBlockTracer tracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes)\n   at InvokeStub_ITraceRpcModule.trace_replayBlockTransactions(Object, Object, IntPtr*)\n   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)"},"id":4} 
2023-02-06 08:33:23.9376|INFO|612|Executing JSON RPC call trace_replayBlockTransactions with params [0xFCD0E1, [
  "trace"
]]
```
And blockscout indexer.log:

```
2023-02-06T08:35:13.951 application=indexer fetcher=internal_transaction count=8 error_count=8 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-06T08:35:14.526 application=indexer fetcher=internal_transaction count=8 error_count=8 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-06T08:35:15.493 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-06T08:35:15.688 application=indexer fetcher=internal_transaction count=8 error_count=8 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-06T08:35:17.259 application=indexer fetcher=internal_transaction count=8 error_count=8 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
2023-02-06T08:35:17.463 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 16483156}, message: "Internal error"}]
```

What's `Block without total difficulty calculated was suggested for processing` mean ? And how could I resolve this issue ?

Thanks.

**Comment by abcfy2** [comment]
Any updates ?

**Comment by kamilchodola** [comment]
@abcfy2 By any chance you know if this is still reproducible?

@brbrr Please try to reproduce on our end.
