### ISSUE TITLE
[HardwareInfo][Arm Linux] Exception on CPU info message

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#5296]
**Describe the bug**
Whenever Nethermind is started on Linux ARM machine, there is a exception on startup:
```
2023-02-16 11:46:56.4912|Step LogHardwareInfo          failed after 476ms System.NullReferenceException: Object reference not set to an instance of an object.
   at HardwareInformation.MachineInformationGatherer.GatherInformation(Boolean skipClockspeedTest, Boolean invalidateCache, ILogger`1 logger)
   at Nethermind.Init.Steps.LogHardwareInfo.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
```
This is a part of a code which reports a CPU details, so seems like library is not working properly on ARM architecture.

Spotted at 1.17.0-unstable version using Launcher.

**Comment by asdacap** [comment]
On an M1 Mac, it shows as `CPU: VirtualApple @ 2.50GHz (8C8T), 0Mhz - 0Mhz`. So need an AWS ARH for this.

**Comment by benaadams** [comment]
Resolved by https://github.com/NethermindEth/nethermind/pull/5547
