### ISSUE TITLE
Occasional problems with CI

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5298]
The failing build run link https://github.com/NethermindEth/nethermind/actions/runs/4818823246/jobs/8581269720

![image](https://user-images.githubusercontent.com/9356351/219372561-933ac29b-4c14-4393-8b5c-52c8987b7ab7.png)

```
Passed!  - Failed:     0, Passed:    29, Skipped:     0, Total:    29, Duration: 26 s - Nethermind.Runner.Test.dll (net7.0)
Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
Error: Process completed with exit code 1.
```

**Comment by benaadams** [comment]
I periodically get something like this locally and have to shut everything down (e.g. VS wait a while for long running processes to quite e.g. compiler) then restart. Also I can use the tests in debug mode for debugging but I cannot get test results in debug mode 🤷‍♂️

**Comment by Scooletz** [comment]
Let me put it on the agenda for the next week then. It's a disgraceful shutdown issue.

**Comment by LukaszRozmej** [comment]
Didn't fix the issue

**Comment by kamilchodola** [comment]
Could be that runner OOMs - but hard to say, not sure if this is still an issue recently.
