### ISSUE TITLE
Block processing exception after forced restart (e.g. power outage)

### ISSUE THREAD

**Issue by damian-orzechowski** [NethermindEth/nethermind#5427]
**Description**
After an enforced shutdown (e.g. power outage), the following exception keeps on reoccurring:
`Processing loop threw an exception. Block: 16789026 (0x12bef8...eb28c6), Exception: System.InvalidOperationException: Attempted to process a blockchain without having starting state
   at Nethermind.Consensus.Processing.BlockchainProcessor.PrepareBlocksToProcess(Block suggestedBlock, ProcessingOptions options, ProcessingBranch processingBranch)
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop()`

**Steps to Reproduce**
1. Enforce shutdown of the node
2. Start again

**Actual behavior**
Exception thrown during block processing.

**Expected behavior**
Any workaround? Can the issue be avoided in case of unexpected shutdown.

**Logs**
Attached
[mainnet.logs.txt](https://github.com/NethermindEth/nethermind/files/10966704/mainnet.logs.txt)

**Comment by MarekM25** [comment]
I'm closing it, I think we solved it
