### ISSUE TITLE
Setup a private-networking failed in docker on Windows 10.

### ISSUE THREAD

**Issue by zydjohnHotmail** [NethermindEth/nethermind#5447]
Hello:
I want to setup a private network in my Windows 10 PC to run nethermind.
I have followed the documents, but the documents seems not talking about where to mount the necessary file systems.
See the following output.
root@a6ce867f9cb5:/usr/share/nethermind# ./Nethermind.Launcher
? Start Nethermind Ethereum Node
? Select network Spaceneth (local developer node)
? Select sync persistent (state is stored in the DB)
2023-03-17 20-14-04.3945|Nethermind starting initialization.
2023-03-17 20-14-04.5114|Loading embedded plugins
2023-03-17 20-14-04.5116|  Found plugin type Nethermind.Consensus.AuRa.AuRaPlugin
2023-03-17 20-14-04.5117|  Found plugin type Nethermind.Consensus.Clique.CliquePlugin
2023-03-17 20-14-04.5117|  Found plugin type Nethermind.Consensus.Ethash.EthashPlugin
2023-03-17 20-14-04.5117|  Found plugin type Nethermind.Consensus.Ethash.NethDevPlugin
2023-03-17 20-14-04.5117|  Found plugin type Nethermind.Hive.HivePlugin
2023-03-17 20-14-04.5117|  Found plugin type Nethermind.UPnP.Plugin.UPnPPlugin
Resolved executing directory as /usr/share/nethermind.
2023-03-17 20-14-04.5352|Loading 10 assemblies from /usr/share/nethermind/plugins
2023-03-17 20-14-04.5354|Loading assembly Nethermind.Api
2023-03-17 20-14-04.5376|Loading assembly Nethermind.Mev
2023-03-17 20-14-04.5411|  Found plugin type Nethermind.Mev
2023-03-17 20-14-04.5411|Loading assembly Nethermind.JsonRpc.TraceStore
2023-03-17 20-14-04.5421|  Found plugin type Nethermind.JsonRpc.TraceStore
2023-03-17 20-14-04.5422|Loading assembly Nethermind.HealthChecks
2023-03-17 20-14-04.5429|  Found plugin type Nethermind.HealthChecks
2023-03-17 20-14-04.5429|Loading assembly Nethermind.Merge.Plugin
2023-03-17 20-14-04.5455|  Found plugin type Nethermind.Merge.Plugin
2023-03-17 20-14-04.5455|Loading assembly Nethermind.EthStats
2023-03-17 20-14-04.5852|  Found plugin type Nethermind.EthStats
2023-03-17 20-14-04.5853|Loading assembly Nethermind.Consensus.AuRa
2023-03-17 20-14-04.5883|Loading assembly Nethermind.Merge.AuRa
2023-03-17 20-14-04.5887|  Found plugin type Nethermind.Merge.AuRa
2023-03-17 20-14-04.5887|Loading assembly Nethermind.AccountAbstraction
2023-03-17 20-14-04.5909|  Found plugin type Nethermind.AccountAbstraction
2023-03-17 20-14-04.5909|Loading assembly Nethermind.Init
2023-03-17 20-14-04.6525|Loading standard NLog.config file from /usr/share/nethermind/NLog.config.
2023-03-17 20-14-04.8168|NLog.config loaded in 164ms.
2023-03-17 20-14-04.8183|Reading config file from /usr/share/nethermind/configs/spaceneth_persistent.cfg
2023-03-17 20-14-04.9456|Incorrect config settings found:
ConfigType:JsonConfigFile|Category:BaselineConfig|Name:Enabled
2023-03-17 20-14-04.9457|Configuration initialized.
2023-03-17 20:14:05.0089|RocksDb Version: 7.7.3
2023-03-17 20:14:05.0198|Loading chainspec from embedded resources: /usr/share/nethermind/chainspec/spaceneth.json
2023-03-17 20:14:05.3273|CPU: AMD Ryzen Threadripper 2950X 16-Core Processor (16C32T), 3500Mhz - 0Mhz
2023-03-17 20:14:05.3473|Setting up memory allowances
2023-03-17 20:14:05.3473|  memory hint:        128MB
2023-03-17 20:14:05.3473|  general memory:     32MB
2023-03-17 20:14:05.3473|  peers memory:       4MB
2023-03-17 20:14:05.3611|  Netty memory:       16MB
2023-03-17 20:14:05.3611|  mempool memory:     8MB
2023-03-17 20:14:05.3611|  fast blocks memory: 0MB
2023-03-17 20:14:05.3611|  trie memory:        13MB
2023-03-17 20:14:05.3668|  DB memory:          53MB
2023-03-17 20:14:05.4051|Using http://ipv4.icanhazip.com to get external ip
2023-03-17 20:14:05.6896|Block tree initialized, last processed is 0, best queued is 0, best known is 0, lowest inserted header , body , lowest sync inserted block number
2023-03-17 20:14:05.6896|Address 0x6f2cf22de4657bae4308e1d7a2543a4ccd5ca9e5 is configured for signing blocks.
2023-03-17 20:14:05.6974|Initializing 13 plugins
2023-03-17 20:14:05.6974|  Clique by Nethermind
2023-03-17 20:14:05.6974|  Clique by Nethermind initialized in 0ms
2023-03-17 20:14:05.6974|  AuRa by Nethermind
2023-03-17 20:14:05.6974|  AuRa by Nethermind initialized in 0ms
2023-03-17 20:14:05.6974|  Ethash by Nethermind
2023-03-17 20:14:05.6974|  Ethash by Nethermind initialized in 0ms
2023-03-17 20:14:05.6974|  NethDev by Nethermind
2023-03-17 20:14:05.6974|  NethDev by Nethermind initialized in 0ms
2023-03-17 20:14:05.6974|  AuRaMerge by Nethermind
2023-03-17 20:14:05.6974|  AuRaMerge by Nethermind initialized in 0ms
2023-03-17 20:14:05.6974|  Merge by Nethermind
2023-03-17 20:14:05.7075|Client started with TTD: , TTD reached: False, Terminal Block Number , FinalTotalDifficulty:
2023-03-17 20:14:05.7075|  Merge by Nethermind initialized in 8ms
2023-03-17 20:14:05.7075|  MEV by Nethermind
2023-03-17 20:14:05.7075|  MEV by Nethermind initialized in 0ms
2023-03-17 20:14:05.7075|  HealthChecks by Nethermind
2023-03-17 20:14:05.7075|  HealthChecks by Nethermind initialized in 0ms
2023-03-17 20:14:05.7075|  Hive by Nethermind
2023-03-17 20:14:05.7075|  Hive by Nethermind initialized in 0ms
2023-03-17 20:14:05.7075|  Account Abstraction by Nethermind
2023-03-17 20:14:05.7075|  Account Abstraction Plugin: User Operation Mining Disabled
2023-03-17 20:14:05.7075|  Account Abstraction by Nethermind initialized in 1ms
2023-03-17 20:14:05.7075|  EthStats by Nethermind
2023-03-17 20:14:05.7075|EthStatsPlugin plugin disabled due to EthStatsConfig settings set to false
2023-03-17 20:14:05.7075|  EthStats by Nethermind initialized in 0ms
2023-03-17 20:14:05.7075|  TraceStore by Nethermind
2023-03-17 20:14:05.7075|  TraceStore by Nethermind initialized in 0ms
2023-03-17 20:14:05.7075|  UPnP by Nethermind
2023-03-17 20:14:05.7075|  UPnP by Nethermind initialized in 0ms
2023-03-17 20:14:05.9056|Loaded Beacon Pivot:
2023-03-17 20:14:05.9965|Init failed System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.DoBind(EndPoint localAddress)
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BindAsync(EndPoint localAddress)
--- End of stack trace from previous location ---
   at DotNetty.Transport.Bootstrapping.AbstractBootstrap`2.DoBindAsync(EndPoint localAddress)
2023-03-17 20:14:06.0048|Init failed. Nethermind.Network.NetworkingException: Failed to initialize _bootstrapChannel
   at Nethermind.Network.Rlpx.RlpxHost.Init()
^C
Any suggestions?
Thanks,

**Comment by zydjohnHotmail** [comment]
Hi, no need for this. 
I am not working on this any more!
