### ISSUE TITLE
It crashes trying to access directory `Nethermind`

### ISSUE THREAD

**Issue by vporton** [NethermindEth/nethermind#5452]
**Description**
It tries to access directory `Nethermind`.

**Steps to Reproduce**
I installed Nethermind to the directory `/usr/share/blockchain-installer`.

```sh
cd /usr/share/blockchain-installer
sudo -u blockchain env DOTNET_BUNDLE_EXTRACT_BASE_DIR=/var/cache/blockchain \
  /usr/share/blockchain-installer/Nethermind.Runner \
  --config config.cfg \
  --datadir /var/lib/blockchain --Init.LogDirectory /var/log/blockchain \
  --KeyStore.KeyStoreDirectory /etc/blockchain-installer/keystore
```

**Actual behavior**
Nethermind crashes trying to access the directory /usr/share/blockchain-installer/Nethermind

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Ubuntu
 - Version: 22.10
 - Installation Method: my own custom `.deb`
 - Consensus Client: not used

**Logs**
```
2023-03-20 00-52-44.1721|Nethermind starting initialization.
2023-03-20 00-52-44.2303|Loading embedded plugins
2023-03-20 00-52-44.2304|  Found plugin type Nethermind.Consensus.AuRa.AuRaPlugin
2023-03-20 00-52-44.2304|  Found plugin type Nethermind.Consensus.Clique.CliquePlugin
2023-03-20 00-52-44.2304|  Found plugin type Nethermind.Consensus.Ethash.EthashPlugin
2023-03-20 00-52-44.2304|  Found plugin type Nethermind.Consensus.Ethash.NethDevPlugin
2023-03-20 00-52-44.2304|  Found plugin type Nethermind.Hive.HivePlugin
2023-03-20 00-52-44.2304|  Found plugin type Nethermind.UPnP.Plugin.UPnPPlugin
Resolved executing directory as /usr/share/blockchain-installer.
2023-03-20 00-52-44.2480|Loading 10 assemblies from /usr/share/blockchain-installer/plugins
2023-03-20 00-52-44.2481|Loading assembly Nethermind.Mev
2023-03-20 00-52-44.2514|  Found plugin type Nethermind.Mev
2023-03-20 00-52-44.2514|Loading assembly Nethermind.AccountAbstraction
2023-03-20 00-52-44.2534|  Found plugin type Nethermind.AccountAbstraction
2023-03-20 00-52-44.2535|Loading assembly Nethermind.Consensus.AuRa
2023-03-20 00-52-44.2554|Loading assembly Nethermind.Merge.AuRa
2023-03-20 00-52-44.2557|  Found plugin type Nethermind.Merge.AuRa
2023-03-20 00-52-44.2557|Loading assembly Nethermind.Init
2023-03-20 00-52-44.2560|Loading assembly Nethermind.JsonRpc.TraceStore
2023-03-20 00-52-44.2563|  Found plugin type Nethermind.JsonRpc.TraceStore
2023-03-20 00-52-44.2563|Loading assembly Nethermind.HealthChecks
2023-03-20 00-52-44.2739|  Found plugin type Nethermind.HealthChecks
2023-03-20 00-52-44.2740|Loading assembly Nethermind.Api
2023-03-20 00-52-44.2743|Loading assembly Nethermind.EthStats
2023-03-20 00-52-44.2746|  Found plugin type Nethermind.EthStats
2023-03-20 00-52-44.2746|Loading assembly Nethermind.Merge.Plugin
2023-03-20 00-52-44.2762|  Found plugin type Nethermind.Merge.Plugin
2023-03-20 00-52-44.3194|Loading standard NLog.config file from /usr/share/blockchain-installer/NLog.config.
2023-03-20 00-52-44.4206|NLog.config loaded in 101ms.
2023-03-20 00-52-44.4215|Reading config file from /usr/share/blockchain-installer/configs/config.cfg
2023-03-20 00-52-44.4989|Configuration initialized.
2023-03-20 00-52-44.5020|Setting BaseDbPath to: /var/lib/blockchain/nethermind_db/spaceneth, from: nethermind_db/spaceneth
2023-03-20 00-52-44.5021|Setting KeyStoreDirectory to: /etc/blockchain-installer/keystore, from: /etc/blockchain-installer/keystore
2023-03-20 00-52-44.5021|Setting LogDirectory to: /var/log/blockchain, from: /var/log/blockchain
2023-03-20 00:52:44.5342|RocksDb Version: 7.7.3 
2023-03-20 00:52:44.5433|Did not find chainspec in embedded resources: ./configs/genesis/spaceneth.json 
2023-03-20 00:52:44.5433|Loading chainspec from file: ./configs/genesis/spaceneth.json 
2023-03-20 00:52:44.9257|CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (4C8T), 4020Mhz - 4700Mhz 
2023-03-20 00:52:44.9302|Using the local IP override: NetworkConfig.LocalIp = 127.0.0.1 
2023-03-20 00:52:44.9302|Using the external IP override: NetworkConfig.ExternalIp = 127.0.0.1 
2023-03-20 00:52:45.8198|Unlocking account: 0x7e5f4552091a69125d5dfcb7b8c2659029395bdf 
2023-03-20 00:52:46.6822|Unlocking account: 0x2b5ad5c4795c026514f8317c7a215e218dccd6cf 
2023-03-20 00:52:47.5103|Unlocking account: 0x6813eb9362372eef6200f3b1dbc3f819671cba69 
2023-03-20 00:52:47.5271|Step SetupKeyStore            failed after 2594ms System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. For more information go to http://aka.ms/dataprotectionwarning
 ---> System.UnauthorizedAccessException: Access to the path '/usr/share/blockchain-installer/Nethermind' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.DirectoryInfo.Create()
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Nethermind.Crypto.ProtectedData.AspNetWrapper.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Nethermind.Crypto.ProtectedData.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Nethermind.Crypto.ProtectedData`1.Protect(Byte[] data)
   at Nethermind.Crypto.ProtectedData`1..ctor(Byte[] data, ICryptoRandom random, ITimestamper timestamper)
   at Nethermind.Crypto.ProtectedPrivateKey..ctor(PrivateKey privateKey, ICryptoRandom random, ITimestamper timestamper)
   at Nethermind.Wallet.NodeKeyManager.<LoadNodeKey>g__LoadKeyFromFile|9_0()
   at Nethermind.Wallet.NodeKeyManager.LoadNodeKey()
   at Nethermind.Init.Steps.SetupKeyStore.<>c__DisplayClass2_0.<Execute>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Nethermind.Init.Steps.SetupKeyStore.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-03-20 00:52:47.5595|Start block loaded from HEAD - 0 (0x9fadec...0b5eb3) 
2023-03-20 00:52:47.5595|Loaded LowestInsertedBeaconHeader:  
2023-03-20 00:52:47.5619|Numbers resolved, level = Max(0, 0), header = Max(0, 0), body = Max(0, 0) 
2023-03-20 00:52:47.5619|Beacon Numbers resolved, level = 0, header = 0, body = 0 
2023-03-20 00:52:47.5619|Block tree initialized, last processed is 0 (0x9fadec...0b5eb3), best queued is 0, best known is 0, lowest inserted header , body , lowest sync inserted block number  
2023-03-20 00:52:47.5619|No address is configured for signing blocks. 
2023-03-20 00:52:47.5673|Initializing 13 plugins 
2023-03-20 00:52:47.5673|  Clique by Nethermind 
2023-03-20 00:52:47.5673|  Clique by Nethermind initialized in 0ms 
2023-03-20 00:52:47.5673|  AuRa by Nethermind 
2023-03-20 00:52:47.5673|  AuRa by Nethermind initialized in 0ms 
2023-03-20 00:52:47.5673|  Ethash by Nethermind 
2023-03-20 00:52:47.5673|  Ethash by Nethermind initialized in 0ms 
2023-03-20 00:52:47.5673|  NethDev by Nethermind 
2023-03-20 00:52:47.5673|  NethDev by Nethermind initialized in 0ms 
2023-03-20 00:52:47.5673|  AuRaMerge by Nethermind 
2023-03-20 00:52:47.5673|  AuRaMerge by Nethermind initialized in 0ms 
2023-03-20 00:52:47.5673|  Merge by Nethermind 
2023-03-20 00:52:47.5736|Client started with TTD: , TTD reached: False, Terminal Block Number , FinalTotalDifficulty:  
2023-03-20 00:52:47.5736|  Merge by Nethermind initialized in 5ms 
2023-03-20 00:52:47.5736|  MEV by Nethermind 
2023-03-20 00:52:47.5736|  MEV by Nethermind initialized in 0ms 
2023-03-20 00:52:47.5736|  HealthChecks by Nethermind 
2023-03-20 00:52:47.5736|  HealthChecks by Nethermind initialized in 0ms 
2023-03-20 00:52:47.5736|  Hive by Nethermind 
2023-03-20 00:52:47.5736|  Hive by Nethermind initialized in 0ms 
2023-03-20 00:52:47.5736|  Account Abstraction by Nethermind 
2023-03-20 00:52:47.5736|  Account Abstraction Plugin: User Operation Mining Disabled 
2023-03-20 00:52:47.5736|  Account Abstraction by Nethermind initialized in 0ms 
2023-03-20 00:52:47.5736|  EthStats by Nethermind 
2023-03-20 00:52:47.5736|EthStatsPlugin plugin disabled due to EthStatsConfig settings set to false 
2023-03-20 00:52:47.5736|  EthStats by Nethermind initialized in 0ms 
2023-03-20 00:52:47.5736|  TraceStore by Nethermind 
2023-03-20 00:52:47.5775|  TraceStore by Nethermind initialized in 0ms 
2023-03-20 00:52:47.5775|  UPnP by Nethermind 
2023-03-20 00:52:47.5775|  UPnP by Nethermind initialized in 0ms 
2023-03-20 00:52:47.6274|Loaded Beacon Pivot:  
2023-03-20 00:52:47.6331|Step InitializeNetwork        failed after 13ms Nethermind.Init.Steps.StepDependencyException: NodeKey
   at Nethermind.Init.Steps.InitializeNetwork.InitDiscovery()
   at Nethermind.Init.Steps.InitializeNetwork.Initialize(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.InitializeNetwork.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-03-20 00:52:47.6375|No block tree levels to review for fixes. All fine. 
2023-03-20 00:52:47.6375|Loaded LowestInsertedBeaconHeader:  
2023-03-20 00:52:47.6375|Numbers resolved, level = Max(0, 0), header = Max(0, 0), body = Max(0, 0) 
2023-03-20 00:52:47.6375|Beacon Numbers resolved, level = 0, header = 0, body = 0 
2023-03-20 00:52:47.6375|Grafana / Prometheus metrics are disabled in configuration 
2023-03-20 00:52:47.6452|Step InitializeBlockProducer  failed after 3ms System.ArgumentNullException: Value cannot be null. (Parameter '_mergeBlockProductionPolicy')
   at Nethermind.Merge.Plugin.MergePlugin.InitBlockProducer(IConsensusPlugin consensusPlugin)
   at Nethermind.Init.Steps.InitializeBlockProducer.BuildProducer()
   at Nethermind.Init.Steps.InitializeBlockProducer.Execute(CancellationToken _)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-03-20 00:52:47.6481|Step RegisterRpcModules       failed after 2ms Nethermind.Init.Steps.StepDependencyException: PeerManager
   at Nethermind.Init.Steps.RegisterRpcModules.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-03-20 00:52:47.6778|Step StartRpc                 failed after 28ms System.ArgumentNullException: Value cannot be null. (Parameter 'implementationInstance')
   at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton[TService](IServiceCollection services, TService implementationInstance)
   at Nethermind.Runner.JsonRpc.Bootstrap.RegisterJsonRpcServices(IServiceCollection services)
   at Nethermind.Runner.JsonRpc.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nethermind.Runner.Ethereum.JsonRpcRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.Steps.StartRpc.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-03-20 00:52:47.6778|Error during ethereum runner start System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. For more information go to http://aka.ms/dataprotectionwarning
 ---> System.UnauthorizedAccessException: Access to the path '/usr/share/blockchain-installer/Nethermind' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.DirectoryInfo.Create()
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Nethermind.Crypto.ProtectedData.AspNetWrapper.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Nethermind.Crypto.ProtectedData.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Nethermind.Crypto.ProtectedData`1.Protect(Byte[] data)
   at Nethermind.Crypto.ProtectedData`1..ctor(Byte[] data, ICryptoRandom random, ITimestamper timestamper)
   at Nethermind.Crypto.ProtectedPrivateKey..ctor(PrivateKey privateKey, ICryptoRandom random, ITimestamper timestamper)
   at Nethermind.Wallet.NodeKeyManager.<LoadNodeKey>g__LoadKeyFromFile|9_0()
   at Nethermind.Wallet.NodeKeyManager.LoadNodeKey()
   at Nethermind.Init.Steps.SetupKeyStore.<>c__DisplayClass2_0.<Execute>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Nethermind.Init.Steps.SetupKeyStore.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Program.<>c__DisplayClass10_0.<<Run>b__1>d.MoveNext()
2023-03-20 00:52:47.6778|Closing, please wait until all functions are stopped properly... 
2023-03-20 00:52:47.6778|Stopping session monitor... 
2023-03-20 00:52:47.6778|Stopping session sync mode selector... 
2023-03-20 00:52:47.6778|Sync mode selector stopped 
2023-03-20 00:52:47.6815|Stopping discovery app... 
2023-03-20 00:52:47.6815|Stopping block producer... 
2023-03-20 00:52:47.6815|Stopping sync peer pool... 
2023-03-20 00:52:47.6883|Stopping peer pool... 
2023-03-20 00:52:47.6883|Stopping peer manager... 
2023-03-20 00:52:47.6883|Stopping synchronizer... 
2023-03-20 00:52:47.6883|Stopping blockchain processor... 
2023-03-20 00:52:47.6900|Stopping rlpx peer... 
2023-03-20 00:52:47.6900|Blockchain Processor shutdown complete.. please wait for all components to close 
2023-03-20 00:52:47.6900|Disposing plugin Clique... 
2023-03-20 00:52:47.6900|Disposing plugin AuRa... 
2023-03-20 00:52:47.6900|Disposing plugin Ethash... 
2023-03-20 00:52:47.6900|Disposing plugin NethDev... 
2023-03-20 00:52:47.6900|Disposing plugin AuRaMerge... 
2023-03-20 00:52:47.6900|Disposing plugin Merge... 
2023-03-20 00:52:47.6900|Disposing plugin MEV... 
2023-03-20 00:52:47.6900|Disposing plugin HealthChecks... 
2023-03-20 00:52:47.6900|Disposing plugin Hive... 
2023-03-20 00:52:47.6900|Disposing plugin Account Abstraction... 
2023-03-20 00:52:47.6900|Disposing plugin EthStats... 
2023-03-20 00:52:47.6900|Disposing plugin TraceStore... 
2023-03-20 00:52:47.6900|Disposing plugin UPnP... 
2023-03-20 00:52:47.6900|Disposing Nethermind.Synchronization.SyncServer... 
2023-03-20 00:52:47.6900|Disposing Nethermind.Merge.Plugin.Synchronization.MergeSynchronizer... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Merge.Plugin.Synchronization.PeerRefresher... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Synchronization.Peers.SyncPeerPool... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Blockchain.FullPruning.FullPruner... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Blockchain.ReceiptCanonicalityMonitor... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Trie.Pruning.TrieStore... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Blockchain.TrieStoreBoundaryWatcher... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Blockchain.FullPruning.PruningTriggerPersistenceStrategy... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Merge.Plugin.InvalidChainTracker.InvalidChainTracker... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Db.Blooms.BloomStorage... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Stats.NodeStatsManager... 
2023-03-20 00:52:47.6936|Disposing Nethermind.Crypto.CryptoRandom... 
2023-03-20 00:52:47.6936|Closing DBs... 
2023-03-20 00:52:47.6936|Disposing DB Blocks 
2023-03-20 00:52:47.6981|Disposing DB Receipts 
2023-03-20 00:52:47.6981|Disposing DB Metadata 
2023-03-20 00:52:47.6981|Disposing DB Code 
2023-03-20 00:52:47.6981|Disposing DB State0 
2023-03-20 00:52:47.6981|Disposing DB Bloom 
2023-03-20 00:52:47.6981|Disposing DB Witness 
2023-03-20 00:52:47.6981|Disposing DB BlockInfos 
2023-03-20 00:52:47.6981|Disposing DB CanonicalHashTrie 
2023-03-20 00:52:47.6981|Disposing DB Headers 
2023-03-20 00:52:47.6981|All DBs closed. 
2023-03-20 00:52:47.6981|Ethereum shutdown complete... please wait for all components to close 
2023-03-20 00:52:47.6981|All done, goodbye!
```

`config.cfg`:
```
{
    "Init": {
        "WebSocketsEnabled": true,
        "StoreReceipts" : true,
        "EnableUnsecuredDevWallet": true,
        "IsMining": true,
        "ChainSpecPath": "./configs/genesis/spaceneth.json",
        "BaseDbPath": "nethermind_db/spaceneth",
        "LogFileName": "spaceneth.logs.txt",
        "StaticNodesPath": "Data/static-nodes.json",
        "ReceiptsMigration": true
    },
    "Mining": {
        "Enabled": true
    },
    "Network": {
        "DiscoveryPort": 30300,
        "P2PPort": 30300,
        "LocalIp": "127.0.0.1",
        "ExternalIp": "127.0.0.1"
    },
    "JsonRpc": {
        "Enabled": true,
        "Host": "127.0.0.1",
        "Port": 8545
    },
    "Blocks": {
        "MinGasPrice": 0
    },
    "Aura": {
        "AllowAuRaPrivateChains": true
    },
    "Sync": {
        "FastSync": true
    }
}
```

**Comment by vporton** [comment]
The same issue as #3510.
