### ISSUE TITLE
[Goerli Archive] Precompiled contract (Nethermind.Evm.Precompiles.ModExpPrecompile) execution exception

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#5626]
**Description**
During goerli_Archive sync with Pruning.Mode=Hybrid I've noticed, that on two nodes in exactly same moment there is a exception 
```
System.OverflowException: Cannot convert UInt256 value to int.
   at Nethermind.Evm.Precompiles.ModExpPrecompile.GetInputLengths(ReadOnlyMemory`1& inputData) in /src/Nethermind/Nethermind.Evm/Precompiles/ModExpPrecompile.cs:line 94
   at Nethermind.Evm.Precompiles.ModExpPrecompile.Run(ReadOnlyMemory`1& inputData, IReleaseSpec releaseSpec) in /src/Nethermind/Nethermind.Evm/Precompiles/ModExpPrecompile.cs:line 146
   at Nethermind.Evm.VirtualMachine.ExecutePrecompile(EvmState state, IReleaseSpec spec) in /src/Nethermind/Nethermind.Evm/VirtualMachine.cs:line 593
```

On both nodes (Teku and Lodestar) it happened in exactly same moment (between processed 8613820 and 8613828):
![image](https://user-images.githubusercontent.com/43241881/235100128-652e8442-02e4-4255-8abd-19ea3108fbd7.png)

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Ubuntu 22.04
 - Version: 1.18.0
 - Installation Method: Sedge
 - Consensus Client: Teku and Lodestar

**Comment by kamilchodola** [comment]
To be retested
@stdevMac can You coordinate with @brbrr to create our own goerli archive node? We can retest that with it and have 24/7 goerli archive.

**Comment by kamilchodola** [comment]
Not to be retested as goerli is not alive anymore and we did not had any similar issue elsewhere
