### ISSUE TITLE
Handle ungraceful JsonRpc disconnetion from remote

### ISSUE THREAD

**Issue by smartprogrammer93** [NethermindEth/nethermind#5640]
Need to handle the following reported by Kamil:
```
2023-05-02 20:39:10.9296|SNAP - progress of State Ranges (Phase 1): 30.405% [***       ]
2023-05-02 20:39:10.9296|SNAP - (NextSlotRange:1200, diff:10) 8 - Requests Account:3 | Storage:71 | Code:1 | Refresh:0 - Queues Slots:0 | Storages:1172 | Codes:35330 | Refresh:0
2023-05-02 20:39:11.8612|Old Headers  10637184 / 17154000 | queue 114067 | current  1199.48bps | total  1889.92bps
2023-05-02 20:39:12.2841|Error during parsing/validation. Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host.
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
   at System.IO.StreamReader.ReadSpan(Span`1 buffer)
   at Nethermind.Serialization.Json.CountingTextReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Nethermind.JsonRpc.Utils.JTokenUtils.ParseMulticontent(TextReader jsonReader)+MoveNext()
   at Nethermind.JsonRpc.JsonRpcProcessor.DeserializeObjectOrArray(TextReader json)+MoveNext()
   at Nethermind.JsonRpc.JsonRpcProcessor.ProcessAsync(TextReader request, JsonRpcContext context)+MoveNext()
2023-05-02 20:39:12.2993|Connection id "0HMQB60QQ1PLC", Request id "0HMQB60QQ1PLC:000000BB": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
 ---> System.InvalidOperationException: Reading is already in progress.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.TryReadInternal(ReadResult& readResult)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()
   --- End of inner exception stack trace ---
```

**Comment by kamilchodola** [comment]
We have much more than this - for example when CL starts to spam with eth_getBlockByNumber and we stop a node in the middle of the batch we have plenty of errors.
