### ISSUE TITLE
CLI: node.switchLocal: System.UriFormatException: Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by Jack-Works** [NethermindEth/nethermind#5650]
**Description**
I'm trying to connect to the engine RPC to run some admin commands.

**Steps to Reproduce**

```
nethermind> node.uri
"http://localhost:8545/"

nethermind> node.switchLocal("http://localhost:8551/")
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at Jint.Runtime.Interop.DelegateWrapper.Call(JsValue thisObject, JsValue[] jsArguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Engine.EvaluateExpression(Expression expression)
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Runtime.StatementInterpreter.ExecuteProgram(Program program)
   at Jint.Engine.Execute(Program program)
   at Jint.Engine.Execute(String source)
   at Nethermind.Cli.CliEngine.Execute(String statement)
```

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Linux
 - Version: Nethermind/v1.18.0+97e80dda/linux-x64/dotnet7.0.5
 - Installation Method: GitHub
 - Consensus Client:

**Comment by deffrian** [comment]
@Jack-Works `node.switchLocal` takes only port, not entire uri. You can use `node.switch` instead. By the way, you can't connect to engine RPC port. It's authenticated and cli does not support connection to authenticated ports. I'm not sure what is your intent, but you can add admin module to 8545 endpoint. 
`--JsonRpc.EnabledModules="[Admin,Eth,Web3,Personal,Health]"`

**Comment by Jack-Works** [comment]
> It's authenticated and cli does not support connection to authenticated ports. I'm not sure what is your intent, but you can add admin module to 8545 endpoint.

Yes. I want to use the CLI to do some management work. Adding it to the public RPC port is unsafe.

**Comment by deffrian** [comment]
@Jack-Works Our CLI communicate with node using RPC. If your `JsonRpc.Host` is localhost it should be safe, as only connections from local network are allowed.
