### ISSUE TITLE
[Nethermind Restart] On restart which is NOT graceful (power outage) peers db contains malformed data

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#5700]
**Description**
According to report by discord user:
"It looks like my client suddenly stopped working (it had previously been running fine on the latest version)."

From logs most important things are:
1. Node was working fine before restart
2. Suddenly node restarted (no dispose logs)
3. After restart exception:
```
Nethermind.Runner[2402093]: 2023-05-15 14:14:53.1194|Unable to init the peer manager. System.IO.InvalidDataException: Malformed data
Nethermind.Runner[2402093]:    at Nethermind.Db.SimpleFilePublicKeyDb.<LoadData>g__ThrowInvalidDataException|36_1()
Nethermind.Runner[2402093]:    at Nethermind.Db.SimpleFilePublicKeyDb.LoadData()
Nethermind.Runner[2402093]:    at Nethermind.Db.SimpleFilePublicKeyDb..ctor(String name, String dbDirectoryPath, ILogManager logManager)
Nethermind.Runner[2402093]:    at Nethermind.Init.Steps.InitializeNetwork.InitPeer()
Nethermind.Runner[2402093]: 2023-05-15 14:14:53.1376|Step InitializeNetwork        failed after 197ms System.NullReferenceException: Object reference not set to an instance of an object.
Nethermind.Runner[2402093]:    at Nethermind.Init.Steps.InitializeNetwork.Initialize(CancellationToken cancellationToken)
Nethermind.Runner[2402093]:    at Nethermind.Init.Steps.InitializeNetwork.Execute(CancellationToken cancellationToken)
Nethermind.Runner[2402093]:    at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)

```

Some more logs:
[NethermindLogs_5-13_and_5-15.zip](https://github.com/NethermindEth/nethermind/files/11481827/NethermindLogs_5-13_and_5-15.zip)

**Comment by rmlcu** [comment]
same here, node suddently stopped working and doesn't start:

`2023-06-06 06:45:26.8645|INFO|305|Received a new payload: 17418831 (0xa5f0d5ee235b94feb9ec57b8a7b9e378005eae274700c70df50789bd9c6e1818)
2023-06-06 06:45:27.8599|INFO|26|Processed   17418831 |      963ms of  23,180ms, mgasps   16.75 total   24.01, tps  186.96 total  237.94, bps    1.04 total    1.58, recv queue 0, proc queue 0

2023-06-06 06:45:27.8599|INFO|26|Valid. Result of a new payload: 17418831 (0xa5f0d5ee235b94feb9ec57b8a7b9e378005eae274700c70df50789bd9c6e1818).
2023-06-06 06:45:27.9339|INFO|112|Executing JSON RPC call eth_getBlockByNumber with params [0x109C249, False]
2023-06-06 06:45:28.6105|INFO|259|Received: ForkchoiceState: (HeadBlockHash: 0xa5f0d5ee235b94feb9ec57b8a7b9e378005eae274700c70df50789bd9c6e1818, SafeBlockHash: 0xf4868efc214862b5f17bc9b368b60a71b002725b676f35972c3122f5f1336fc9, FinalizedBlockHash: 0xb06de66617fbee137157888f30b86e63ba7c6da127092c07a6cb38df45777bed)
2023-06-06 06:45:28.6105|INFO|259|FCU - block 17418831 (0xa5f0d5...6e1818) was processed.
2023-06-06 06:45:28.6192|INFO|259|Block 0xa5f0d5ee235b94feb9ec57b8a7b9e378005eae274700c70df50789bd9c6e1818 was set as head.
2023-06-06 06:45:28.6192|INFO|259|Valid. Request: ForkchoiceState: (HeadBlockHash: 0xa5f0d5ee235b94feb9ec57b8a7b9e378005eae274700c70df50789bd9c6e1818, SafeBlockHash: 0xf4868efc214862b5f17bc9b368b60a71b002725b676f35972c3122f5f1336fc9, FinalizedBlockHash: 0xb06de66617fbee137157888f30b86e63ba7c6da127092c07a6cb38df45777bed) .
2023-06-06 06:45:28.8379|INFO|301|Executing JSON RPC call eth_getBlockByNumber with params [0x109C24A, False]
2023-06-06 06:45:29.0347|INFO|252|Received a new payload: 17418831 (0xa5f0d5ee235b94feb9ec57b8a7b9e378005eae274700c70df50789bd9c6e1818)
2023-06-06 06:45:29.0347|INFO|252|Valid... A new payload ignored. Block 17418831 (0xa5f0d5ee235b94feb9ec57b8a7b9e378005eae274700c70df50789bd9c6e1818) found in main chain.
2023-06-06 06:45:30.3494|INFO|96|Executing JSON RPC call eth_getBlockByNumber with params [0x109C24B, False]
2023-06-06 06:45:31.6352|INFO|271|Received a new payload: 17418832 (0x39312b419289e90c60a5d9f52edfca83641d4fdfbccb84e849f9e7c863f2b533)
2023-06-06 06:45:33.0101|INFO|26|Processed   17418832 |    1,356ms of   5,150ms, mgasps   11.36 total   24.01, tps  113.59 total  237.93, bps    0.74 total    1.58, recv queue 0, proc queue 0

2023-06-06 06:45:33.0467|INFO|26|Valid. Result of a new payload: 17418832 (0x39312b419289e90c60a5d9f52edfca83641d4fdfbccb84e849f9e7c863f2b533).
2023-06-06 06:45:33.0820|INFO|146|Executing JSON RPC call eth_getBlockByNumber with params [0x109C24C, False]
2023-06-06 06:45:33.2553|INFO|146|Peers | with known best block: 255 | all: 255 |
2023-06-06 06:45:54.6644|INFO|1|RocksDb Version: 8.0.0
2023-06-06 06:45:54.6817|INFO|1|Loading chainspec from embedded resources: /srv/nethermind-bin/chainspec/foundation.json
2023-06-06 06:45:55.1733|INFO|8|CPU: Genuine Intel(R) CPU 0000%@ (8C16T)
2023-06-06 06:45:55.2004|INFO|13|Setting up memory allowances
2023-06-06 06:45:55.2004|INFO|13|  memory hint:        4096MB
2023-06-06 06:45:55.2004|INFO|13|  general memory:     32MB
2023-06-06 06:45:55.2004|INFO|13|  peers memory:       256MB
2023-06-06 06:45:55.2123|INFO|6|Using http://ipv4.icanhazip.com to get external ip
2023-06-06 06:45:55.2232|INFO|13|  Netty memory:       268MB
2023-06-06 06:45:55.2232|INFO|13|  mempool memory:     149MB
2023-06-06 06:45:55.2232|INFO|13|  fast blocks memory: 339MB
2023-06-06 06:45:55.2232|INFO|13|  trie memory:        610MB
2023-06-06 06:45:55.2309|INFO|13|  DB memory:          2441MB
2023-06-06 06:46:17.4873|INFO|16|Start block loaded from reorg boundary - 17418768 - 17418768 (0x3172ed...61f7a1)
2023-06-06 06:46:17.6192|INFO|16|Numbers resolved, level = Max(17418768, 17418832), header = Max(17418768, 17418832), body = Max(0, 17418832)
2023-06-06 06:46:17.6388|INFO|16|Beacon Numbers resolved, level = 0, header = 0, body = 0
2023-06-06 06:46:17.6440|INFO|16|Block tree initialized, last processed is 17418768 (0x3172ed...61f7a1), best queued is 17418832, best known is 17418832, lowest inserted header 1, body 11552726, lowest sync inserted block number 17418753
2023-06-06 06:46:17.6527|INFO|16|Initializing 13 plugins
2023-06-06 06:46:17.6527|INFO|16|  Clique by Nethermind
2023-06-06 06:46:17.6541|INFO|16|  Clique by Nethermind initialized in 0ms
...
2023-06-06 06:46:17.7068|INFO|16|  TraceStore by Nethermind initialized in 0ms
2023-06-06 06:46:17.7068|INFO|16|  UPnP by Nethermind
2023-06-06 06:46:17.7068|INFO|16|  UPnP by Nethermind initialized in 0ms
2023-06-06 06:46:18.1320|INFO|9|Loaded 0 static nodes from file: /srv/nethermind-bin/Data/static-nodes.json
2023-06-06 06:46:18.1683|ERROR|16|Unable to init the peer manager. System.IO.InvalidDataException: Malformed data
   at Nethermind.Db.SimpleFilePublicKeyDb.<LoadData>g__ThrowInvalidDataException|36_1()
   at Nethermind.Db.SimpleFilePublicKeyDb.LoadData()
   at Nethermind.Db.SimpleFilePublicKeyDb..ctor(String name, String dbDirectoryPath, ILogManager logManager)
   at Nethermind.Init.Steps.InitializeNetwork.InitPeer()
2023-06-06 06:46:18.1941|ERROR|16|Step InitializeNetwork        failed after 358ms System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Init.Steps.InitializeNetwork.Initialize(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.InitializeNetwork.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-06-06 06:46:18.8737|INFO|8|Peers | with known best block: 0 | all: 0 |
2023-06-06 06:46:18.8744|INFO|8|Waiting for peers... 1s
2023-06-06 06:46:18.8828|INFO|8|Sync peers - Initialized: 0 | All: 0 | Max: 256
2023-06-06 06:46:19.8836|INFO|8|Waiting for peers... 2s
2023-06-06 06:46:20.8836|INFO|8|Waiting for peers... 3s
2023-06-06 06:46:21.8835|INFO|8|Waiting for peers... 4s
2023-06-06 06:46:22.8829|INFO|9|Waiting for peers... 5s
2023-06-06 06:46:23.8833|INFO|9|Waiting for peers... 6s
2023-06-06 06:46:24.8845|INFO|8|Waiting for peers... 7s`

**Comment by kamilchodola** [comment]
@rmlcu 
Can you try removing peers directory in nethermind_db/mainnet?
But if this is possible, can you zip it and send it here?

**Comment by kamilchodola** [comment]
@rmlcu 
Can You also send more logs from this node?

**Comment by rmlcu** [comment]
> @rmlcu Also can you show how static node was added?

```
 cat /srv/nethermind-bin/Data/static-nodes.json
[
  "enode://c1c3a604950119f82d78189792b73f5a96bd09017c77465e3c32fc51c1d758a9a772ffddd58436d465342f2cfa6d4a442a49e526743f4d8354d7c5ce794c3ee5@127.0.0.1:30303",
  "enode://2784b947df025df9911875e68ccfcb0627ad4ae1dfb9f77634435692e8626508d9a6a04adff7719d3d73b25e72cbedee8d8e431492afbbd5fb4082e78c52d934@127.0.0.1:30303"
]
```



> @rmlcu Can you try removing peers directory in nethermind_db/mainnet? But if this is possible, can you zip it and send it here?

sure 

```
ls -al /srv/data/db/peers/
total 1532
drwxr-xr-x  2 nethermind nethermind    4096 Jun  6 06:45 .                                                                                                                                     drwxr-xr-x 14 nethermind nethermind    4096 May  9 11:13 ..
-rw-r--r--  1 nethermind nethermind  548864 Jun  6 06:45 SimpleFileDb.db
-rw-r--r--  1 nethermind nethermind 1010716 Jun  6 06:44 SimpleFileDb.db_b7128302-3c5f-4706-acf8-c393c302f11c
```

modify time indeed correlates with time when node stopped working
[peers.zip](https://github.com/NethermindEth/nethermind/files/11771875/peers.zip)

**Comment by rmlcu** [comment]
> @rmlcu Can you try removing peers directory in nethermind_db/mainnet? But if this is possible, can you zip it and send it here?

@kamilchodola thanks it's helped!
