### ISSUE TITLE
Nethermind.Crypto.SecP256k1 exception in Nethermind 1.19.0-rc when running on Windows 11 Pro

### ISSUE THREAD

**Issue by vadym-voznyuk** [NethermindEth/nethermind#5720]
Windows 11 Pro, fresh install, 6 core AMD Ryzen, 32 GB DDR5 RAM, 2TB Samsung 990 Pro NVMe SSD, all new hardware, tested and rock solid so far. No video card, using integrated Ryzen video instead.

All Windows patches and updates are up to date, all drivers installed, everything is green. Machine is fast and rock stable overall.

Nethermind 1.19.0-rc fresh download.

Starting up first time in a Powershell window, in a new folder to start sync from scratch, here's the full log of the exception that happened:

```
PS C:\nethermind_new> .\Nethermind.Runner.exe
2023-05-22 11-05-55.2212|Nethermind starting initialization.
2023-05-22 11-05-55.2333|Client version: Nethermind/v1.19.0-rc+d8765075/windows-x64/dotnet7.0.5
2023-05-22 11-05-55.2382|Loading embedded plugins
2023-05-22 11-05-55.2382|  Found plugin type Nethermind.Consensus.AuRa.AuRaPlugin
2023-05-22 11-05-55.2383|  Found plugin type Nethermind.Consensus.Clique.CliquePlugin
2023-05-22 11-05-55.2383|  Found plugin type Nethermind.Consensus.Ethash.EthashPlugin
2023-05-22 11-05-55.2383|  Found plugin type Nethermind.Consensus.Ethash.NethDevPlugin
2023-05-22 11-05-55.2384|  Found plugin type Nethermind.Hive.HivePlugin
2023-05-22 11-05-55.2384|  Found plugin type Nethermind.UPnP.Plugin.UPnPPlugin
Resolved executing directory as C:\nethermind_new.
2023-05-22 11-05-55.2446|Loading 10 assemblies from C:\nethermind_new\plugins
2023-05-22 11-05-55.2447|Loading assembly Nethermind.AccountAbstraction
2023-05-22 11-05-55.2507|  Found plugin type Nethermind.AccountAbstraction
2023-05-22 11-05-55.2508|Loading assembly Nethermind.Api
2023-05-22 11-05-55.2523|Loading assembly Nethermind.Consensus.AuRa
2023-05-22 11-05-55.2545|Loading assembly Nethermind.EthStats
2023-05-22 11-05-55.2551|  Found plugin type Nethermind.EthStats
2023-05-22 11-05-55.2551|Loading assembly Nethermind.HealthChecks
2023-05-22 11-05-55.2565|  Found plugin type Nethermind.HealthChecks
2023-05-22 11-05-55.2565|Loading assembly Nethermind.Init
2023-05-22 11-05-55.2570|Loading assembly Nethermind.JsonRpc.TraceStore
2023-05-22 11-05-55.2578|  Found plugin type Nethermind.JsonRpc.TraceStore
2023-05-22 11-05-55.2578|Loading assembly Nethermind.Merge.AuRa
2023-05-22 11-05-55.2588|  Found plugin type Nethermind.Merge.AuRa
2023-05-22 11-05-55.2588|Loading assembly Nethermind.Merge.Plugin
2023-05-22 11-05-55.2605|  Found plugin type Nethermind.Merge.Plugin
2023-05-22 11-05-55.2606|Loading assembly Nethermind.Mev
2023-05-22 11-05-55.2618|  Found plugin type Nethermind.Mev
2023-05-22 11-05-55.3020|Loading standard NLog.config file from C:\nethermind_new\NLog.config.
2023-05-22 11-05-55.4014|NLog.config loaded in 99ms.
2023-05-22 11-05-55.4021|Reading config file from C:\nethermind_new\configs/mainnet.cfg
2023-05-22 11-05-55.4422|Configuration initialized.
2023-05-22 11:05:55.4559|RocksDb Version: 8.0.0
2023-05-22 11:05:55.4628|Loading chainspec from embedded resources: C:\nethermind_new\chainspec/foundation.json
2023-05-22 11:05:55.6671|CPU: AMD Ryzen 5 7600 6-Core Processor (6C12T)
2023-05-22 11:05:55.6671|Using http://ipv4.icanhazip.com to get external ip
2023-05-22 11:05:55.7304|Setting up memory allowances
2023-05-22 11:05:55.7304|  memory hint:        2048MB
2023-05-22 11:05:55.7304|  general memory:     32MB
2023-05-22 11:05:55.7304|  peers memory:       100MB
2023-05-22 11:05:55.7304|  Netty memory:       268MB
2023-05-22 11:05:55.7304|  mempool memory:     149MB
2023-05-22 11:05:55.7304|  fast blocks memory: 149MB
2023-05-22 11:05:55.7304|  trie memory:        269MB
2023-05-22 11:05:55.7304|  DB memory:          1078MB
2023-05-22 11:05:55.7414|Generating private key for the node (no node key in configuration) - stored in plain + key store for JSON RPC unlocking
2023-05-22 11:05:55.7414|Step SetupKeyStore            failed after 8ms System.TypeInitializationException: The type initializer for 'Nethermind.Crypto.SecP256k1' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at Nethermind.Crypto.SecP256k1.LoadLibrary(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Nethermind.Crypto.SecP256k1.secp256k1_context_create(UInt32 flags)
   at Nethermind.Crypto.SecP256k1.CreateContext()
   at Nethermind.Crypto.SecP256k1..cctor()
   --- End of inner exception stack trace ---
   at Nethermind.Crypto.SecP256k1.VerifyPrivateKey(Byte[] privateKey)
   at Nethermind.Crypto.PrivateKeyGenerator.Generate()
   at Nethermind.Wallet.NodeKeyManager.<LoadNodeKey>g__GenerateKeyIfNeeded|9_1(String newFile, String oldFile)
   at Nethermind.Wallet.NodeKeyManager.<LoadNodeKey>g__LoadKeyFromFile|9_0()
   at Nethermind.Wallet.NodeKeyManager.LoadNodeKey()
   at Nethermind.Init.Steps.SetupKeyStore.<>c__DisplayClass2_0.<Execute>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Nethermind.Init.Steps.SetupKeyStore.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-05-22 11:05:55.8591|Error during ethereum runner start System.TypeInitializationException: The type initializer for 'Nethermind.Crypto.SecP256k1' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at Nethermind.Crypto.SecP256k1.LoadLibrary(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Nethermind.Crypto.SecP256k1.secp256k1_context_create(UInt32 flags)
   at Nethermind.Crypto.SecP256k1.CreateContext()
   at Nethermind.Crypto.SecP256k1..cctor()
   --- End of inner exception stack trace ---
   at Nethermind.Crypto.SecP256k1.VerifyPrivateKey(Byte[] privateKey)
   at Nethermind.Crypto.PrivateKeyGenerator.Generate()
   at Nethermind.Wallet.NodeKeyManager.<LoadNodeKey>g__GenerateKeyIfNeeded|9_1(String newFile, String oldFile)
   at Nethermind.Wallet.NodeKeyManager.<LoadNodeKey>g__LoadKeyFromFile|9_0()
   at Nethermind.Wallet.NodeKeyManager.LoadNodeKey()
   at Nethermind.Init.Steps.SetupKeyStore.<>c__DisplayClass2_0.<Execute>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Nethermind.Init.Steps.SetupKeyStore.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ReviewFailedAndThrow()
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Program.<>c__DisplayClass10_0.<<Run>b__1>d.MoveNext()
2023-05-22 11:05:55.8591|Closing, please wait until all functions are stopped properly...
2023-05-22 11:05:55.8591|Stopping session monitor...
2023-05-22 11:05:55.8591|Stopping session sync mode selector...
2023-05-22 11:05:55.8591|Stopping discovery app...
2023-05-22 11:05:55.8591|Stopping block producer...
2023-05-22 11:05:55.8591|Stopping sync peer pool...
2023-05-22 11:05:55.8591|Stopping peer pool...
2023-05-22 11:05:55.8591|Stopping peer manager...
2023-05-22 11:05:55.8591|Stopping synchronizer...
2023-05-22 11:05:55.8591|Stopping blockchain processor...
2023-05-22 11:05:55.8591|Stopping rlpx peer...
2023-05-22 11:05:55.8591|Disposing plugin Clique...
2023-05-22 11:05:55.8591|Disposing plugin AuRa...
2023-05-22 11:05:55.8591|Disposing plugin Ethash...
2023-05-22 11:05:55.8591|Disposing plugin NethDev...
2023-05-22 11:05:55.8591|Disposing plugin AuRaMerge...
2023-05-22 11:05:55.8591|Disposing plugin Merge...
2023-05-22 11:05:55.8591|Disposing plugin MEV...
2023-05-22 11:05:55.8591|Disposing plugin HealthChecks...
2023-05-22 11:05:55.8591|Disposing plugin Hive...
2023-05-22 11:05:55.8591|Disposing plugin Account Abstraction...
2023-05-22 11:05:55.8591|Disposing plugin EthStats...
2023-05-22 11:05:55.8591|Disposing plugin TraceStore...
2023-05-22 11:05:55.8591|Disposing plugin UPnP...
2023-05-22 11:05:55.8591|Disposing Nethermind.Stats.NodeStatsManager...
2023-05-22 11:05:55.8591|Disposing Nethermind.Crypto.CryptoRandom...
2023-05-22 11:05:55.8591|Closing DBs...
2023-05-22 11:05:55.8591|All DBs closed.
2023-05-22 11:05:55.8591|Ethereum shutdown complete... please wait for all components to close
2023-05-22` 11:05:55.8591|All done, goodbye!
```

Please let me know if I can be of any assistance to debug and find the root cause of this.

**Comment by benaadams** [comment]
@rubo

**Comment by rubo** [comment]
@vadym-voznyuk Could you please check whether installing the latest [Microsoft Visual C++ Redistributable](https://aka.ms/vcredist) helps?

**Comment by vadym-voznyuk** [comment]
@rubo works now! thanks a lot!
