### ISSUE TITLE
`trace_filter` returns internal error 'data': "System.ArgumentNullException: Value cannot be null."

### ISSUE THREAD

**Issue by moisses89** [NethermindEth/nethermind#5880]
**Description**
Call `trace_filter` for some blocks returns internal error telling that 'data' cannot be null. 
Log error:
```
Value error retrieving trace_filter results from-block=28742035 to-block=28742035 : {'code': -32603, 'message': 'Internal error', 'data': "System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at Nethermind.State.StateProvider.GetNonce(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 114
   at Nethermind.Consensus.Processing.BlockProcessor.BlockValidationTransactionsExecutor.ProcessTransactions(Block block, ProcessingOptions processingOptions, BlockReceiptsTracer receiptsTracer, IReleaseSpec spec) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockValidationTransactionsExecutor.cs:line 36
   at Nethermind.Consensus.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 226
   at Nethermind.Consensus.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 145
   at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 487
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 321
   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/OneTimeProcessor.cs:line 54
   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Tracing/Tracer.cs:line 42
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityLikeBlockTracer tracer) in /src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs:line 264
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_filter(TraceFilterForRpc traceFilterForRpc) in /src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs:line 199
   at InvokeStub_ITraceRpcModule.trace_filter(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)"}
```

**Steps to Reproduce**
Example request:
```
curl localhost:8545  -X POST \
  -H "Content-Type: application/json"  --data '{"method":"trace_filter","params":[{"fromBlock":"0x1B4E1B2","toBlock":"0x1B4E1B2","fromAddress":["0xfb1bffC9d739B8D520DaF37dF666da4C687191EA", "0x69f4D1788e39c87893C980c06EdF4b7f686e2938", "0x3E5c63644E683549055b9Be8653de26E0B4CD36E", "0x6851D6fDFAfD08c0295C392436245E5bc78B0185", "0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F", "0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552", "0x2CB0ebc503dE87CFD8f0eCEED8197bF7850184ae", "0xb6029EA3B2c51D09a50B53CA8012FeEB05bDa35A"]}],"id":1,"jsonrpc":"2.0"}'
```

**Actual behavior**
Some blocks return the error described, and keeps returning the error more than 19 hours. 

**Expected behavior**
We expect receive the correct result without missing parameters. 

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Version: 1.19.2
 - Installation Method: docker
 - Consensus Client:  Lighthouse v4.2.0

**Additional context**
The error is happening on gnosis chain.

**Comment by Demuirgos** [comment]
Hi, Can you provide the logs around these trace calls ?

**Comment by moisses89** [comment]
I haven't this logs because we are not storing the Nethermind logs (only one hour),  I'm going to provide them when the next issue happen.

**Comment by luarx** [comment]
More logs

```
Problem with payload=`{'id': 0, 'jsonrpc': '2.0', 'method': 'trace_transaction', 'params': ['0x682cb72f0b5eaa22a5655287d05ef153b4e0b4c5fb6e0e9e4e6675b40052db6c']}` result={'jsonrpc': '2.0', 'error': {'code': -32603, 'message': 'Internal error', 'data': "System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at Nethermind.State.StateProvider.GetNonce(Address address) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 119
   at Nethermind.Consensus.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 220
   at Nethermind.Consensus.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 142
   at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 520
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 354
   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/OneTimeProcessor.cs:line 54
   at Nethermind.Consensus.Tracing.Tracer.Process(Block block, IBlockTracer blockTracer, IBlockchainProcessor processor) in /src/Nethermind/Nethermind.Consensus/Tracing/Tracer.cs:line 44
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.ExecuteBlock(Block block, ParityLikeBlockTracer tracer) in /src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs:line 304
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_transaction(Keccak txHash) in /src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs:line 272
   at InvokeStub_ITraceRpcModule.trace_transaction(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)"}, 'id': 0}
```

**Comment by luarx** [comment]
It has happened again
**Nethermind version: 1.20.3**

More logs:
[logs-nethermind-gnosis-chain-archive.txt](https://github.com/NethermindEth/nethermind/files/12790033/logs-nethermind-gnosis-chain-archive.txt)

**Comment by LukaszRozmej** [comment]
Idea for workaround in `fix/sender_recovery_safe`
