### ISSUE TITLE
[Old Headers] Issue "Only one header dependency expected" cause OldHeaders to stop progressing 

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#5928]
**Description**
During a sync of mainnet chain there was a exception:
```
System.InvalidOperationException: Only one header dependency expected (HEADERS [10013980, 10014171](192) [HIGH] [times: S:2ms|R:191ms|V:0ms|W:0ms|H:0ms|A:438ms, retries 2] min#: 10014171 [H   S ][      ][Peer|eth68|17682771|   34.29.26.252:30303| Out])
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.InsertHeaders(HeadersSyncBatch batch) in /src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 472
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.HandleResponse(HeadersSyncBatch batch, PeerInfo peer) in /src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 437
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.DoHandleResponse(T request, PeerInfo allocatedPeer) in /src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs:line 198
```
Then I've noticed that my OldHeaders stopped progressing (error ocured at progress "7,668,288"):
```
13 Jul 2023 08:30:54.588
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,185 Blk/s
13 Jul 2023 08:30:49.589
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,188 Blk/s
13 Jul 2023 08:30:44.589
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,191 Blk/s
13 Jul 2023 08:30:39.589
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,194 Blk/s
13 Jul 2023 08:30:34.588
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,197 Blk/s
13 Jul 2023 08:30:29.589
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,200 Blk/s
13 Jul 2023 08:30:24.590
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,203 Blk/s
13 Jul 2023 08:30:19.589
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,207 Blk/s
13 Jul 2023 08:30:14.588
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,210 Blk/s
13 Jul 2023 08:30:09.590
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,213 Blk/s
13 Jul 2023 08:30:04.590
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,216 Blk/s
13 Jul 2023 08:29:59.590
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,219 Blk/s
13 Jul 2023 08:29:54.588
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,223 Blk/s
13 Jul 2023 08:29:49.588
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,226 Blk/s
13 Jul 2023 08:29:44.589
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,229 Blk/s
13 Jul 2023 08:29:39.589
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,232 Blk/s
13 Jul 2023 08:29:34.584
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,235 Blk/s
13 Jul 2023 08:29:29.589
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,239 Blk/s
13 Jul 2023 08:29:24.588
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,242 Blk/s
13 Jul 2023 08:29:19.584
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,928 | current            0 Blk/s | total        2,245 Blk/s
13 Jul 2023 08:29:14.585
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,785 | current            0 Blk/s | total        2,249 Blk/s
13 Jul 2023 08:29:09.585
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,782 | current            0 Blk/s | total        2,252 Blk/s
13 Jul 2023 08:29:04.584
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,778 | current            0 Blk/s | total        2,255 Blk/s
13 Jul 2023 08:28:59.585
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,776 | current            0 Blk/s | total        2,259 Blk/s
13 Jul 2023 08:28:54.585
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,776 | current            0 Blk/s | total        2,262 Blk/s
13 Jul 2023 08:28:49.583
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,774 | current            0 Blk/s | total        2,265 Blk/s
13 Jul 2023 08:28:44.586
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,771 | current            0 Blk/s | total        2,269 Blk/s
13 Jul 2023 08:28:39.584
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,766 | current            0 Blk/s | total        2,272 Blk/s
13 Jul 2023 08:28:34.583
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,763 | current            0 Blk/s | total        2,275 Blk/s
13 Jul 2023 08:28:29.583
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,760 | current            0 Blk/s | total        2,279 Blk/s
13 Jul 2023 08:28:24.586
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,757 | current            0 Blk/s | total        2,282 Blk/s
13 Jul 2023 08:28:19.586
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,576 | current            0 Blk/s | total        2,285 Blk/s
13 Jul 2023 08:28:14.586
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,569 | current            0 Blk/s | total        2,289 Blk/s
13 Jul 2023 08:28:09.585
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,371 | current            0 Blk/s | total        2,292 Blk/s
13 Jul 2023 08:28:04.585
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,172 | current            0 Blk/s | total        2,296 Blk/s
13 Jul 2023 08:27:59.584
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue   116,165 | current            0 Blk/s | total        2,299 Blk/s
13 Jul 2023 08:27:54.584
 Old Headers   7,668,288 / 17,682,459 ( 43.37 %) | queue    42,240 | current        2,919 Blk/s | total        2,303 Blk/s
13 Jul 2023 08:27:49.584
 Old Headers   7,653,696 / 17,682,459 ( 43.28 %) | queue     3,456 | current        3,956 Blk/s | total        2,302 Blk/s
```

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: ARM Graviton3
 - Version: master branch (commit: 1236aaef)
 - Installation Method: Sedge
 - Consensus Client: Lighthouse

**Comment by asdacap** [comment]
Could be related to #6066

**Comment by kamilchodola** [comment]
Still an issue - it is slowing down a sync and reducing amount of peers.
Recent example:
Basically 2 out of 3 recently started nodes I've noticed are struggling a bit to sync (were slightly slower than the other one) and also had MUCH LESS peers (80 on not affected vs 10-20 on affected ones).
As Ashraf Pointed there was an issue he noticed once locally that when we are receiving `HeaderResponseTooLong` disconnection reason there is some problems with getting more peers because of that (but this is just a observation - it may be something else).
On not affected node there was 0 peers disconnected with that reason where on 2 affected nodes there was 100+ reasons like this.
Also nodes which are having this issue are also having this Exception on logs (screenshot attached).
Simple restart helps but it reduces capability of verifying equally if nodes are syncing faster/slower because this error can affect performance a lot (and now I can't tell if new db schemas are improving sync time or making it worse or not affecting it at all because this issue appeared).

**Comment by kamilchodola** [comment]
@ak88 I think You work on this still, right? Do we have duplicated issues?
