### ISSUE TITLE
WebSockets error Stream was too long

### ISSUE THREAD

**Issue by matyushkins** [NethermindEth/nethermind#5955]
**Description**
Gnosis archive node sync explorer with debug trace block
This is repeated both with WebSockets and with http.
```
debug_traceBlockByHash block 0xeb3f4a6938a880757d0469869303d26fa8636d9dbd0d632bc086268bdbece77f, error websocket: invalid close code
debug_traceBlockByHash block 0x31b5d2874766e1c2023b5d2e1559ca1cc4daa96f0fc6550764cab7702917f2e4, error websocket: invalid close code
```
```
21 Jul 11:40:34 | WebSockets error Stream was too long. System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Nethermind.Serialization.Json.CountingTextWriter.Write(Char value)
   at System.IO.TextWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
   at Newtonsoft.Json.JsonTextWriter.WriteValue(String value)
   at Nethermind.JsonRpc.Modules.DebugModule.GethLikeTxTraceConverter.WriteEntries(JsonWriter writer, List`1 entries, JsonSerializer serializer)
   at Nethermind.JsonRpc.Modules.DebugModule.GethLikeTxTraceConverter.WriteJson(JsonWriter writer, GethLikeTxTrace value, JsonSerializer serializer)
   at Newtonsoft.Json.JsonConverter`1.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Nethermind.Serialization.Json.EthereumJsonSerializer.Serialize[T](Stream stream, T value, Boolean indented)
   at Nethermind.JsonRpc.WebSockets.JsonRpcSocketsClient.SendJsonRpcResultEntry(Entry result, Boolean endOfMessage)
   at Nethermind.JsonRpc.WebSockets.JsonRpcSocketsClient.SendJsonRpcResultEntry(Entry result, Boolean endOfMessage)
   at Nethermind.JsonRpc.WebSockets.JsonRpcSocketsClient.SendJsonRpcResult(JsonRpcResult result)
   at Nethermind.JsonRpc.WebSockets.JsonRpcSocketsClient.ProcessAsync(ArraySegment`1 data)
   at Nethermind.JsonRpc.WebSockets.JsonRpcSocketsClient.ProcessAsync(ArraySegment`1 data)
   at Nethermind.Sockets.SocketClient.ReceiveAsync()
   at Nethermind.Sockets.SocketClient.ReceiveAsync()
   at Nethermind.Sockets.Extensions.<>c__DisplayClass0_0.<<UseWebSocketsModules>b__0>d.MoveNext()

```
**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Linux docker Ubuntu 22.04
 - Version: 1.20.1
 - Consensus Client: lighthouse 4.3.0

**Comment by emlautarom1** [comment]
We're currently trying to reproduce the issue in our machines but we don't currently have a Gnosis archive node. Have you had the same problem with a more recent block?
