### ISSUE TITLE
Can't sync

### ISSUE THREAD

**Issue by jugene** [NethermindEth/nethermind#5983]
Trying to sync for the first time, at the end get continous error like:

   at Nethermind.Consensus.Processing.BlockchainProcessor.PrepareBlocksToProcess(Block suggestedBlock, ProcessingOptions options, ProcessingBranch processingBranch)
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop()
05 Aug 13:23:30 | Processing loop threw an exception. Block: 17840444 (0x3af3c5...79b4d1), Exception: System.InvalidOperationException: Attempted to process a blockchain without having starting state
   at Nethermind.Consensus.Processing.BlockchainProcessor.PrepareBlocksToProcess(Block suggestedBlock, ProcessingOptions options, ProcessingBranch process

**Comment by MarekM25** [comment]
Closing because of no response. @jugene feel free to reopen!
