### ISSUE TITLE
Exception on difficulty calculation when repivoting

### ISSUE THREAD

**Issue by LukaszRozmej** [NethermindEth/nethermind#6125]
**Description**
User issue on startup (after earlier shut down):

```
Sep 23 12:38:15 staker Nethermind.Runner[183650]: 23 Sep 12:38:15 | Waiting for peers... 10s
Sep 23 12:38:15 staker Nethermind.Runner[183650]: 23 Sep 12:38:15 | Changing state Disconnected to FastHeaders, SnapSync at processed:0|state:0|block:0|header:18179255|target block:18179286|peer block:18198570
Sep 23 12:38:15 staker Nethermind.Runner[183650]: 23 Sep 12:38:15 | Sync mode changed from Disconnected to FastHeaders, SnapSync
Sep 23 12:38:15 staker Nethermind.Runner[183650]: 23 Sep 12:38:15 | Sync mode update failed System.ArithmeticException: Underflow in subtraction 1407820785510109 - 1870258756285909
Sep 23 12:38:15 staker Nethermind.Runner[183650]:    at Nethermind.Int256.UInt256.ThrowArithmeticException(UInt256& a, UInt256& b)
Sep 23 12:38:15 staker Nethermind.Runner[183650]:    at Nethermind.Int256.UInt256.op_Subtraction(UInt256& a, UInt256& b)
Sep 23 12:38:15 staker Nethermind.Runner[183650]:    at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.SetExpectedNextHeaderToParent(BlockHeader header)
Sep 23 12:38:15 staker Nethermind.Runner[183650]:    at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.ResetPivot()
Sep 23 12:38:15 staker Nethermind.Runner[183650]:    at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.InitializeFeed()
Sep 23 12:38:15 staker Nethermind.Runner[183650]:    at Nethermind.Synchronization.ParallelSync.ActivatedSyncFeed`1.SyncModeSelectorOnChanged(Object sender, SyncModeChangedEventArgs e)
Sep 23 12:38:15 staker Nethermind.Runner[183650]:    at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.UpdateSyncModes(SyncMode newModes, String reason)
Sep 23 12:38:15 staker Nethermind.Runner[183650]:    at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.Update()
Sep 23 12:38:15 staker Nethermind.Runner[183650]:    at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.StartAsync(CancellationToken cancellationToken)
Sep 23 12:38:16 staker Nethermind.Runner[183650]: 23 Sep 12:38:16 | Sync mode update failed System.ArithmeticException: Underflow in subtraction 1407820785510109 - 1870258756285909
```

[nethermind(1).log](https://github.com/NethermindEth/nethermind/files/12712863/nethermind.1.log)

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: 
 - Version: 1.20
 - Installation Method:
 - Consensus Client:

**Comment by emlautarom1** [comment]
I was unable to reproduce the issue or track down why this is happening. The problematic code is the following:

https://github.com/NethermindEth/nethermind/blob/4dda6d2505323df6c2899cb6a38179a63b0f3d95/src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs#L723

I would expect `TotalDifficulty >= Difficulty` to be an invariant but it looks that at some point, `TotalDifficulty` is less than `Difficulty`. Where exactly this invariant is broken is unknown, due to these being properties that get mutated in so many places (+50).

**Comment by emlautarom1** [comment]
We could wrap `set` operations on the problematic properties in `assert`s to check that the invariant holds, let Nethermind run with a debugger attached and wait until the check fails.

**Comment by LukaszRozmej** [comment]
Where do we get that header from? Maybe we are missing difficulty validation here if it comes from the network and simply the header is invalid?

**Comment by kamilchodola** [comment]
@brbrr 
Can you take a look on that and try to reproduce on master?

**Comment by jmederosalvarado** [comment]
We default to total difficulty being valid when it's null [here](https://github.com/nethermindeth/nethermind/blob/81cb4f5c2e3351b371eb50c942e600704026221b/src/Nethermind/Nethermind.Consensus/Validators/HeaderValidator.cs#L262-L287)

**Comment by LukaszRozmej** [comment]
Header RLP contains only difficulty and not total difficulty

**Comment by kamilchodola** [comment]
@emlautarom1 
Can you check if this was somewhat fixed with the OP related fix? Or this is something else?

**Comment by emlautarom1** [comment]
@kamilchodola Extremely unlikely that the OP fix has anything to do with this issue. OP Holocene changes how fees are calculated.

There were a couple of older issues with `TotalDifficulty` that were fixed for OP but those fixes have been merged for quite some time now.
