### ISSUE TITLE
Genesis load timeout on Holesky

### ISSUE THREAD

**Issue by emlautarom1** [NethermindEth/nethermind#6183]
Nethermind crashes when it gets restarted on Holesky.

**Steps to Reproduce**
1. Run Nethermind and any CL that you want in Holesky.
2. Wait until the node starts syncing and then stop Nethermind and CL.
3. Start Nethermind again with the same config.

**Actual behavior**
Nethermind crashes on startup with the following exception:

```
03 Oct 15:52:19 | Step LoadGenesisBlock         failed after 40056ms Nethermind.Blockchain.BlockchainException: Genesis block processing failure
   at Nethermind.Init.Steps.LoadGenesisBlock.Load() in /src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs:line 87
   at Nethermind.Init.Steps.LoadGenesisBlock.Execute(CancellationToken _) in /src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs:line 42
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 156
   at Nethermind.Init.Steps.EthereumStepsManager.ReviewFailedAndThrow() in /src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 214
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 98
03 Oct 15:52:19 | Error during ethereum runner start Nethermind.Blockchain.BlockchainException: Genesis block processing failure
   at Nethermind.Init.Steps.LoadGenesisBlock.Load() in /src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs:line 87
   at Nethermind.Init.Steps.LoadGenesisBlock.Execute(CancellationToken _) in /src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs:line 42
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 156
   at Nethermind.Init.Steps.EthereumStepsManager.ReviewFailedAndThrow() in /src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 214
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 98
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Runner/Ethereum/EthereumRunner.cs:line 36
   at Nethermind.Runner.Program.<>c__DisplayClass10_0.<<Run>b__1>d.MoveNext() in /src/Nethermind/Nethermind.Runner/Program.cs:line 198
```

**Expected behavior**
Nethermind should be able to start correctly and resume work.

**Desktop:**
 - Operating System: Fedora Workstation 38
 - Version: 1.20.4, master
 - Installation Method: Sedge & directly from source
 - Consensus Client: Lighthouse, Nimbus, Teku

**Additional context**
- Relevant flags are: `--config holesky`
- Nethermind does not crash if you delete the `nethermind_db/holesky` folder before starting up again.

**Logs**

```
2023-10-11 18:06:48.9732|INFO|1|RocksDb Version: 8.0.0 
2023-10-11 18:06:49.0138|INFO|1|ChainSpecPath matched an embedded resource inside the binary. Loading chainspec from embedded resources instead of file! 
2023-10-11 18:06:49.3381|INFO|9|CPU: AMD EPYC 7713 64-Core Processor (8C8T) 
2023-10-11 18:06:49.3528|INFO|9|Using http://ipv4.icanhazip.com to get external ip 
2023-10-11 18:06:49.8741|INFO|16|Numbers resolved, level = Max(0, 85854), header = Max(0, 85854), body = Max(0, 85854) 
2023-10-11 18:06:49.8783|INFO|16|Beacon Numbers resolved, level = 0, header = 0, body = 0 
2023-10-11 18:06:49.8797|INFO|16|Block tree initialized, last processed is 0, best queued is 85854, best known is 85854, lowest inserted header , body 0, lowest sync inserted block number 85776 
2023-10-11 18:06:49.8936|INFO|16|Initializing 13 plugins 
2023-10-11 18:06:49.8936|INFO|16|  Clique by Nethermind 
2023-10-11 18:06:49.8936|INFO|16|  Clique by Nethermind initialized in 0ms 
2023-10-11 18:06:49.8936|INFO|16|  AuRa by Nethermind 
2023-10-11 18:06:49.8936|INFO|16|  AuRa by Nethermind initialized in 0ms 
2023-10-11 18:06:49.8951|INFO|16|  Ethash by Nethermind 
2023-10-11 18:06:49.9033|INFO|16|  Ethash by Nethermind initialized in 8ms 
2023-10-11 18:06:49.9033|INFO|16|  NethDev by Nethermind 
2023-10-11 18:06:49.9033|INFO|16|  NethDev by Nethermind initialized in 0ms 
2023-10-11 18:06:49.9033|INFO|16|  AuRaMerge by Nethermind 
2023-10-11 18:06:49.9033|INFO|16|  AuRaMerge by Nethermind initialized in 0ms 
2023-10-11 18:06:49.9033|INFO|16|  Merge by Nethermind 
2023-10-11 18:06:49.9199|INFO|16|Client started with TTD: 0, TTD reached: True, Terminal Block Number , FinalTotalDifficulty: 0 
2023-10-11 18:06:49.9199|INFO|16|  Merge by Nethermind initialized in 17ms 
2023-10-11 18:06:49.9199|INFO|16|  MEV by Nethermind 
2023-10-11 18:06:49.9199|INFO|16|  MEV by Nethermind initialized in 0ms 
2023-10-11 18:06:49.9199|INFO|16|  HealthChecks by Nethermind 
2023-10-11 18:06:49.9291|INFO|16|  HealthChecks by Nethermind initialized in 6ms 
2023-10-11 18:06:49.9291|INFO|16|  Hive by Nethermind 
2023-10-11 18:06:49.9291|INFO|16|  Hive by Nethermind initialized in 0ms 
2023-10-11 18:06:49.9291|INFO|16|  Account Abstraction by Nethermind 
2023-10-11 18:06:49.9319|INFO|16|  Account Abstraction Plugin: User Operation Mining Disabled 
2023-10-11 18:06:49.9319|INFO|16|  Account Abstraction by Nethermind initialized in 1ms 
2023-10-11 18:06:49.9319|INFO|16|  EthStats by Nethermind 
2023-10-11 18:06:49.9319|INFO|16|  EthStats by Nethermind initialized in 0ms 
2023-10-11 18:06:49.9319|INFO|16|  TraceStore by Nethermind 
2023-10-11 18:06:49.9319|INFO|16|  TraceStore by Nethermind initialized in 0ms 
2023-10-11 18:06:49.9319|INFO|16|  UPnP by Nethermind 
2023-10-11 18:06:49.9319|INFO|16|  UPnP by Nethermind initialized in 0ms 
2023-10-11 18:07:30.1585|ERROR|16|Step LoadGenesisBlock         failed after 40121ms Nethermind.Blockchain.BlockchainException: Genesis block processing failure
   at Nethermind.Init.Steps.LoadGenesisBlock.Load() in /root/development/nethermind/src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs:line 87
   at Nethermind.Init.Steps.LoadGenesisBlock.Execute(CancellationToken _) in /root/development/nethermind/src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs:line 42
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken) in /root/development/nethermind/src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 156
2023-10-11 18:07:30.1691|ERROR|16|Error during ethereum runner start Nethermind.Blockchain.BlockchainException: Genesis block processing failure
   at Nethermind.Init.Steps.LoadGenesisBlock.Load() in /root/development/nethermind/src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs:line 87
   at Nethermind.Init.Steps.LoadGenesisBlock.Execute(CancellationToken _) in /root/development/nethermind/src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs:line 42
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken) in /root/development/nethermind/src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 156
   at Nethermind.Init.Steps.EthereumStepsManager.ReviewFailedAndThrow() in /root/development/nethermind/src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 214
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken) in /root/development/nethermind/src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs:line 98
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken) in /root/development/nethermind/src/Nethermind/Nethermind.Runner/Ethereum/EthereumRunner.cs:line 36
   at Nethermind.Runner.Program.<>c__DisplayClass10_0.<<Run>b__1>d.MoveNext() in /root/development/nethermind/src/Nethermind/Nethermind.Runner/Program.cs:line 198
2023-10-11 18:07:30.1691|INFO|16|Closing, please wait until all functions are stopped properly... 
2023-10-11 18:07:30.1734|INFO|16|Stopping session monitor... 
2023-10-11 18:07:30.1734|INFO|16|Stopping session sync mode selector... 
2023-10-11 18:07:30.1734|INFO|16|Stopping discovery app... 
2023-10-11 18:07:30.1734|INFO|16|Stopping block producer... 
2023-10-11 18:07:30.1751|INFO|16|Stopping sync peer pool... 
2023-10-11 18:07:30.1751|INFO|16|Stopping peer pool... 
2023-10-11 18:07:30.1751|INFO|16|Stopping peer manager... 
2023-10-11 18:07:30.1751|INFO|16|Stopping synchronizer... 
2023-10-11 18:07:30.1751|INFO|16|Stopping blockchain processor... 
2023-10-11 18:07:30.1751|INFO|16|Stopping rlpx peer... 
2023-10-11 18:07:30.1751|INFO|19|Blockchain Processor shutdown complete.. please wait for all components to close 
2023-10-11 18:07:30.1751|INFO|16|Disposing plugin Clique... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin AuRa... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin Ethash... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin NethDev... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin AuRaMerge... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin Merge... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin MEV... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin HealthChecks... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin Hive... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin Account Abstraction... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin EthStats... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin TraceStore... 
2023-10-11 18:07:30.1791|INFO|16|Disposing plugin UPnP... 
2023-10-11 18:07:30.1791|INFO|16|Disposing Nethermind.Blockchain.FullPruning.FullPruner... 
2023-10-11 18:07:30.1844|INFO|16|Disposing Nethermind.Blockchain.ReceiptCanonicalityMonitor... 
2023-10-11 18:07:30.1844|INFO|16|Disposing Nethermind.Trie.Pruning.TrieStore... 
2023-10-11 18:07:30.1875|INFO|16|Disposing Nethermind.Blockchain.TrieStoreBoundaryWatcher... 
2023-10-11 18:07:30.1875|INFO|16|Disposing Nethermind.Blockchain.FullPruning.PruningTriggerPersistenceStrategy... 
2023-10-11 18:07:30.1875|INFO|16|Disposing Nethermind.Merge.Plugin.InvalidChainTracker.InvalidChainTracker... 
2023-10-11 18:07:30.1875|INFO|16|Disposing Nethermind.Db.Blooms.BloomStorage... 
2023-10-11 18:07:30.1875|INFO|16|Disposing Nethermind.Stats.NodeStatsManager... 
2023-10-11 18:07:30.1875|INFO|16|Disposing Nethermind.Crypto.CryptoRandom... 
2023-10-11 18:07:30.1875|INFO|16|Closing DBs... 
2023-10-11 18:07:30.1875|INFO|16|Disposing DB BlockInfos 
2023-10-11 18:07:30.1946|INFO|16|Disposing DB Headers 
2023-10-11 18:07:30.1953|INFO|16|Disposing DB State0 
2023-10-11 18:07:30.2007|INFO|16|Disposing DB Receipts 
2023-10-11 18:07:30.2007|INFO|16|Disposing DB CanonicalHashTrie 
2023-10-11 18:07:30.2007|INFO|16|Disposing DB Witness 
2023-10-11 18:07:30.2007|INFO|16|Disposing DB Blocks 
2023-10-11 18:07:30.2053|INFO|16|Disposing DB Metadata 
2023-10-11 18:07:30.2053|INFO|16|Disposing DB Bloom 
2023-10-11 18:07:30.2053|INFO|16|Disposing DB Code 
2023-10-11 18:07:30.2118|INFO|16|All DBs closed. 
2023-10-11 18:07:30.2118|INFO|16|Ethereum shutdown complete... please wait for all components to close 
2023-10-11 18:07:30.2118|INFO|16|All done, goodbye! 
```

**Comment by jakubgs** [comment]
Seeing the same issue on all Nethermind Holesky nodes in our fleet.

**Comment by carameleon** [comment]
Hi. I also undergo the same behavior on holesky. 
When I update from v1.20.0 to v1.21.1.
Goerli, Sepolia was fine. (from v1.20.3 to v1.21.1)
