### ISSUE TITLE
[1.21.0] Could not load file or assembly 'Microsoft.AspNetCore.Authorization.Policy'

### ISSUE THREAD

**Issue by attila-lendvai** [NethermindEth/nethermind#6195]
**Description**

a new error is thrown after the update from 1.20.4 to 1.21.0.

 - Operating System: [Guix](https://github.com/attila-lendvai/guix-crypto)
 - Version: 1.21.0
 - Installation Method: through the Guix package, which downloads the binary distribution from GitHub.

```
2023-10-15 20:13:53.0910|ERROR|50|Step StartRpc                 failed after 124437ms System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Authorization.Policy, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

**Steps to Reproduce**

i start up the service as before, and when it tries to listen on the RPC port then it crashes with the given error.

**Expected behavior**

the binary distribution is self-contained and does not need any dotnet dependencies? (i don't know whether this is a valid expectation, or not)

**Additional context**

the same setup used to work with with the 1.20.4 release.

this dotnet bug may be relevant: https://github.com/dotnet/extensions/issues/2931

**Logs**

the full backtrace:
```
2023-10-15 20:13:53.0910|ERROR|50|Step StartRpc                 failed after 124437ms System.IO.FileNotFoundException: Could not load file or assembly 'Microso
ft.AspNetCore.Authorization.Policy, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.AspNetCore.Authorization.Policy, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcCoreBuilderExtensions.AddAuthorizationServices(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllers(IServiceCollection services)
   at Nethermind.Runner.JsonRpc.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerC
onfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nethermind.Runner.Ethereum.JsonRpcRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.Steps.StartRpc.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-10-15 20:13:53.1156|ERROR|60|Error during ethereum runner start System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Authorization.Policy, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

**Comment by attila-lendvai** [comment]
err, wait!

1.20.4 is also dying now with all kinds of errors. the variability of the errors suggests that it's either an out of memory error (see the second exception), or maybe running out of file descriptors? what else? any hints?

```
2023-10-15 21:34:02.3649|ERROR|13|Step StartRpc                 failed after 25550ms System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=6.0.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.EntityFrameworkCore, Version=6.0.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Nethermind.HealthChecks.HealthChecksPlugin.AddServices(IServiceCollection service)
   at Nethermind.Runner.Ethereum.JsonRpcRunner.<Start>b__12_0(IServiceCollection s)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nethermind.Runner.Ethereum.JsonRpcRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.Steps.StartRpc.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-10-15 21:34:02.3821|ERROR|13|Error during ethereum runner start System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFramewor
kCore, Version=6.0.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.EntityFrameworkCore, Version=6.0.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Nethermind.HealthChecks.HealthChecksPlugin.AddServices(IServiceCollection service)
   at Nethermind.Runner.Ethereum.JsonRpcRunner.<Start>b__12_0(IServiceCollection s)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nethermind.Runner.Ethereum.JsonRpcRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.Steps.StartRpc.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ReviewFailedAndThrow()
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Program.<>c__DisplayClass10_0.<<Run>b__1>d.MoveNext()
```

and another one that mentions **out of memory?!**. there's 10 GB available RAM, and it fails near the startup. checking the memory usage, it hardly goes up 1.2GB before it dies:

```
2023-10-15 21:33:07.1117|ERROR|6|Step StartRpc                 failed after 24448ms System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Cors, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.AspNetCore.Cors, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nethermind.Runner.Ethereum.JsonRpcRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.Steps.StartRpc.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-10-15 21:33:07.1226|ERROR|6|Error during ethereum runner start System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal(ThreadHandle t, Int32 stackSize, Int32 priority, Char* pThreadName)
   at System.Threading.Thread.StartCore()
   at System.Threading.PortableThreadPool.WaitThread..ctor()
   at System.Threading.PortableThreadPool.RegisterWaitHandle(RegisteredWaitHandle handle)
   at Nethermind.Core.Extensions.WaitHandleExtensions.WaitOneAsync(WaitHandle handle, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ReviewDependencies(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Program.<>c__DisplayClass10_0.<<Run>b__1>d.MoveNext()
```

yet another one:

```
023-10-15 21:32:13.5106|ERROR|15|Step StartRpc                 failed after 45380ms System.IO.FileNotFoundException: Could not load file or assembly 'Promethe
us.AspNetCore, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Prometheus.AspNetCore, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAsse
mbly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.<>c.<GetApplicationPartAssemblies>b__8_0(ApplicationPartAttribute name)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateDefaultParts(String entryAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services, IWebHostEnvironment en
vironment)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllers(IServiceCollection services)
   at Nethermind.Runner.JsonRpc.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerC
onfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nethermind.Runner.Ethereum.JsonRpcRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.Steps.StartRpc.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-10-15 21:32:13.5234|ERROR|15|Error during ethereum runner start System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal(ThreadHandle t, Int32 stackSize, Int32 priority, Char* pThreadName)
   at System.Threading.Thread.StartCore()
   at System.Threading.PortableThreadPool.WaitThread..ctor()
   at System.Threading.PortableThreadPool.RegisterWaitHandle(RegisteredWaitHandle handle)
   at Nethermind.Core.Extensions.WaitHandleExtensions.WaitOneAsync(WaitHandle handle, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ReviewDependencies(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Program.<>c__DisplayClass10_0.<<Run>b__1>d.MoveNext()
```

```
2023-10-15 21:40:19.8941|ERROR|15|Step StartRpc                 failed after 23785ms System.IO.FileNotFoundException: Could not load file or assembly 'Microsof
t.AspNetCore.Mvc, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.AspNetCore.Mvc, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerC
onfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nethermind.Runner.Ethereum.JsonRpcRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.Steps.StartRpc.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-10-15 21:40:19.9061|ERROR|15|Error during ethereum runner start System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal(ThreadHandle t, Int32 stackSize, Int32 priority, Char* pThreadName)
   at System.Threading.Thread.StartCore()
   at System.Threading.PortableThreadPool.WaitThread..ctor()
   at System.Threading.PortableThreadPool.RegisterWaitHandle(RegisteredWaitHandle handle)
   at Nethermind.Core.Extensions.WaitHandleExtensions.WaitOneAsync(WaitHandle handle, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ReviewDependencies(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Program.<>c__DisplayClass10_0.<<Run>b__1>d.MoveNext()
```

another one:

```
2023-10-15 21:43:53.9659|ERROR|14|Step StartRpc                 failed after 23729ms System.IO.FileNotFoundException: Could not load file or assembly 'HealthCh
ecks.UI.InMemory.Storage, Version=6.0.5.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'HealthChecks.UI.InMemory.Storage, Version=6.0.5.0, Culture=neutral, PublicKeyToken=null'
   at Nethermind.HealthChecks.HealthChecksPlugin.AddServices(IServiceCollection service)
   at Nethermind.Runner.Ethereum.JsonRpcRunner.<Start>b__12_0(IServiceCollection s)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nethermind.Runner.Ethereum.JsonRpcRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.Steps.StartRpc.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
2023-10-15 21:43:53.9722|ERROR|14|Error during ethereum runner start System.IO.FileNotFoundException: Could not load file or assembly 'HealthChecks.UI.InMemory
.Storage, Version=6.0.5.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'HealthChecks.UI.InMemory.Storage, Version=6.0.5.0, Culture=neutral, PublicKeyToken=null'
   at Nethermind.HealthChecks.HealthChecksPlugin.AddServices(IServiceCollection service)
   at Nethermind.Runner.Ethereum.JsonRpcRunner.<Start>b__12_0(IServiceCollection s)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nethermind.Runner.Ethereum.JsonRpcRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.Steps.StartRpc.Execute(CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken)
   at Nethermind.Init.Steps.EthereumStepsManager.ReviewFailedAndThrow()
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken)
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken)
   at Nethermind.Runner.Program.<>c__DisplayClass10_0.<<Run>b__1>d.MoveNext()
```

**Comment by attila-lendvai** [comment]
sorry, false alarm: it was happening because `nofiles` was not large enough.
