### ISSUE TITLE
Node fails to start with metrics enabled

### ISSUE THREAD

**Issue by jacquesvcritien** [NethermindEth/nethermind#6544]
**Description**
After upgrading to v1.25.0, the node would not start with metrics enabled

**Steps to Reproduce**
1. Upgrade to v1.25.0
2. Start the node with --Metrics.Enabled=true

**Actual behavior**
Node does not start with
```
Jan 15 13:30:29 nethermind[4032754]: Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
Jan 15 13:30:29 nethermind[4032754]:    at RocksDbSharp.Native.MarshalNullTermAsciiStr(IntPtr nullTermStr)
Jan 15 13:30:29 nethermind[4032754]:    at RocksDbSharp.Native.rocksdb_property_value_string(IntPtr db, String propname)
Jan 15 13:30:29 nethermind[4032754]:    at RocksDbSharp.RocksDb.GetProperty(String propertyName)
Jan 15 13:30:29 nethermind[4032754]:    at Nethermind.Db.Rocks.DbOnTheRocks.GetSize() in /home/node/nethermind/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 241
Jan 15 13:30:29 nethermind[4032754]:    at Nethermind.Db.KeyValueStoreCompressingExtensions.EOACompressingDb.GetSize() in /home/node/nethermind/src/Nethermind/Nethermind.Db/CompressingDb.cs:line 144
Jan 15 13:30:29 nethermind[4032754]:    at Nethermind.Db.FullPruning.FullPruningDb.GetSize() in /home/node/nethermind/src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs:line 118
Jan 15 13:30:29 nethermind[4032754]:    at Nethermind.Init.Steps.StartMonitoring.<SetupMetrics>b__5_0() in /home/node/nethermind/src/Nethermind/Nethermind.Init/Steps/StartMonitoring.cs:line 94
Jan 15 13:30:29 nethermind[4032754]:    at Nethermind.Monitoring.Metrics.MetricsController.UpdateMetrics(Object state) in /home/node/nethermind/src/Nethermind/Nethermind.Monitoring/Metrics/MetricsController.cs:line 200
Jan 15 13:30:29 nethermind[4032754]:    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Expected behavior**
Node should start

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Linux
 - Version: 22.04.3 LTS
 - Installation Method: Github build from source

**Comment by antondlr** [comment]
I experience the same, with the latest release (v1.25.1) installed via PPA. 
This is on gnosis chain btw. 

```
Jan 17 10:52:35 hostname Nethermind.Runner[301869]: Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at RocksDbSharp.Native.MarshalNullTermAsciiStr(IntPtr nullTermStr)
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at Nethermind.Db.Rocks.DbOnTheRocks.GetSize()
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at Nethermind.Db.FullPruning.FullPruningDb.GetSize()
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at Nethermind.Init.Steps.StartMonitoring.<SetupMetrics>b__5_0()
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at Nethermind.Monitoring.Metrics.MetricsController.UpdateMetrics(Object state)
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Jan 17 10:52:35 hostname Nethermind.Runner[301869]: --- End of stack trace from previous location ---
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.TimerQueue.FireNextTimers()
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Jan 17 10:52:35 hostname Nethermind.Runner[301869]: 17 Jan 10:52:35 | Failure System.NullReferenceException: Object reference not set to an instance of an object.
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at RocksDbSharp.Native.MarshalNullTermAsciiStr(IntPtr nullTermStr)
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at Nethermind.Db.Rocks.DbOnTheRocks.GetSize()
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at Nethermind.Db.FullPruning.FullPruningDb.GetSize()
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at Nethermind.Init.Steps.StartMonitoring.<SetupMetrics>b__5_0()
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at Nethermind.Monitoring.Metrics.MetricsController.UpdateMetrics(Object state)
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Jan 17 10:52:35 hostname Nethermind.Runner[301869]: --- End of stack trace from previous location ---
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.TimerQueue.FireNextTimers()
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Jan 17 10:52:35 hostname Nethermind.Runner[301869]:    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by flcl42** [comment]
@jacquesvcritien @antondlr 
Seems like system version of rocksdb is not compatible. You can check if it's installed via:
```sh
apt-cache policy librocksdb-dev
``` 
, and if you remove it the client starts working. Typically it can be done via
```sh
apt remove librocksdb-dev
```

But it may be you need it for some other software, so we are working on making it to prioritize rocksdb version packaged with Nethermind.
