### ISSUE TITLE
`trace_replayBlockTransactions` method sometimes throws `ObjectDisposedException`

### ISSUE THREAD

**Issue by rubo** [NethermindEth/nethermind#6597]
This error has been observed on the Gnosis devnet archive node during `trace_replayBlockTransactions` execution:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Nethermind.Db.Rocks.DbOnTheRocks'.
   at Nethermind.Db.Rocks.DbOnTheRocks.GetSpanWithColumnFamily(ReadOnlySpan`1 key, ColumnFamilyHandle cf) in /_/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 585
   at Nethermind.Serialization.Rlp.KeyValueStoreRlpExtensions.Get[TCacheKey,TItem](IReadOnlyKeyValueStore db, TCacheKey cacheKey, ReadOnlySpan`1 key, IRlpStreamDecoder`1 decoder, LruCache`2 cache, Boolean shouldCache) in /_/src/Nethermind/Nethermind.Serialization.Rlp/KeyValueStoreRlpExtensions.cs:line 45
   at Nethermind.Blockchain.BlockTree.GetBlockHashOnMainOrBestDifficultyHash(Int64 blockNumber) in /_/src/Nethermind/Nethermind.Blockchain/BlockTree.cs:line 665
   at Nethermind.Blockchain.Find.IBlockFinder.FindBlock(BlockParameter blockParameter, Boolean headLimit) in /_/src/Nethermind/Nethermind.Blockchain/Find/IBlockFinder.cs:line 87
   at Nethermind.JsonRpc.Modules.BlockFinderExtensions.SearchForBlock(IBlockFinder blockFinder, BlockParameter blockParameter, Boolean allowNulls) in /_/src/Nethermind/Nethermind.JsonRpc/Modules/BlockFinderExtensions.cs:line 48
   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_replayBlockTransactions(BlockParameter blockParameter, String[] traceTypes) in /_/src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs:line 198
   at InvokeStub_ITraceRpcModule.trace_replayBlockTransactions(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Nethermind v1.25.2+78c7bf5f

**Comment by kamilchodola** [comment]
@rubo Didn't that happen on shutdown?

**Comment by rubo** [comment]
@kamilchodola As far as I recall, no — it was during the `trace_replayBlockTransactions` execution. It was observed a year ago, so if no one else complained, perhaps the error is gone or hasn't caught anyone's attention. With this said, maybe we can close this issue as stale.
