### ISSUE TITLE
BlockProcessingError - Reward returned error 'revert'

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#6638]
```
Processing loop threw an exception. Block: 32184226 (0x6c06e8...66990c), Exception: Nethermind.Abi.AbiException: System call to RewardContract.Reward returned error 'revert' at block 32170447.
   at Nethermind.Blockchain.Contracts.Contract.CallCore(ITransactionProcessor transactionProcessor, BlockHeader header, String functionName, Transaction transaction, Boolean callAndRestore) in /_/src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 197
   at Nethermind.Consensus.AuRa.Rewards.AuRaRewardCalculator.CalculateRewardsWithContract(Block block, IRewardContract contract)
   at Nethermind.Consensus.Processing.BlockProcessor.ApplyMinerRewards(Block block, IBlockTracer tracer, IReleaseSpec spec) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 312
   at Nethermind.Consensus.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 243
   at Nethermind.Consensus.Processing.BlockProcessor.Process(Hash256 newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 108
   at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch& processingBranch, ProcessingOptions options, IBlockTracer tracer) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 488
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 387
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 317
```

**Comment by flcl42** [comment]
Additional context is an earlier message, which tells about db corruption:
```
2024-01-28 13:21:05.5289|WARN|Consensus.Processing.BlockchainProcessor|17|Processing loop threw an exception. Block: 32170447 (0xea67b4...997478), Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Nethermind.Serialization.Rlp.RlpStream.ReadSequenceLength() in /_/src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs:line 731
   at Nethermind.Trie.TrieNode.DecodeRlp(ICappedArrayPool bufferPool, Int32& itemsCount) in /_/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 365
   at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree, ReadFlags readFlags, ICappedArrayPool bufferPool) in /_/src/Nethermind/Nethermind.Trie/TrieNode.cs:line 307
   at Nethermind.Trie.PatriciaTree.ResolveNode(TrieNode node, TraverseContext& traverseContext) in /_/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 464
   at Nethermind.Trie.PatriciaTree.Get(ReadOnlySpan`1 rawKey, Hash256 rootHash) in /_/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 326
   at Nethermind.Synchronization.Trie.HealingStorageTree.Get(ReadOnlySpan`1 rawKey, Hash256 rootHash) in /_/src/Nethermind/Nethermind.Synchronization/Trie/HealingStorageTree.cs:line 33
   at Nethermind.State.PersistentStorageProvider.LoadFromTree(StorageCell& storageCell) in /_/src/Nethermind/Nethermind.State/PersistentStorageProvider.cs:line 239
   at Nethermind.State.PersistentStorageProvider.GetCurrentValue(StorageCell& storageCell) in /_/src/Nethermind/Nethermind.State/PersistentStorageProvider.cs:line 64
   at Nethermind.Evm.VirtualMachine`1.ExecuteCode[TTracingInstructions,TTracingRefunds,TTracingStorage](EvmState vmState, EvmStack`1& stack, Int64 gasAvailable, IReleaseSpec spec) in /_/src/Nethermind/Nethermind.Evm/VirtualMachine.cs:line 773
```
