### ISSUE TITLE
Attempted to process a blockchain without having starting state

### ISSUE THREAD

**Issue by flcl42** [NethermindEth/nethermind#6670]
**Description**
Block processing or recovery after restart leads to broken state, restart helped at least in one case.

**Steps to Reproduce**
Run the node/restart it

**Actual behavior**
Node stucks reporting "Exception: System.InvalidOperationException: Attempted to process a blockchain without having starting state"

**Expected behavior**
Startup recovery and block processing is OK

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Linux x64
 - Version: 1.25.3
 - Installation Method: docker
 - Consensus Client: lighthouse, nimbus

**Additional context**
Please provide any additional context about the problem.

**Logs**

```
nethermind-lh_1        | 04 Feb 00:02:56 | Processed    10480679... 10480680 |  1,167.85 ms  |  slot      1,172 ms | Gas gwei: 0.00 .. 0.00 (0.31) .. 5.00 
nethermind-lh_1        | 04 Feb 00:02:56 | - Blocks 2            3.34 MGas   |     72    txs |  calls    102 (  4) | sload     456 | sstore    128 | create   0 
nethermind-lh_1        | 04 Feb 00:02:56 | - Block throughput    2.86 MGas/s |     61.65 t/s |          1.71 Blk/s | recv        0 | proc       88 
nethermind-lh_1        | 04 Feb 00:02:57 | Processed            10480681     |  1,412.70 ms  |  slot      1,416 ms | Gas gwei: 0.00 .. 0.00 (0.29) .. 18.00 
nethermind-lh_1        | 04 Feb 00:02:57 | - Block               5.04 MGas   |    158    txs |  calls     94 (  2) | sload     317 | sstore     87 | create   0 
nethermind-lh_1        | 04 Feb 00:02:57 | - Block throughput    3.57 MGas/s |    111.84 t/s |          0.71 Blk/s | recv        0 | proc       87 
nethermind-lh_1        | 04 Feb 00:02:59 | Processed            10480682     |  1,558.34 ms  |  slot      1,560 ms | Gas gwei: 0.00 .. 0.00 (0.13) .. 6.00 
nethermind-lh_1        | 04 Feb 00:02:59 | - Block               7.23 MGas   |    183    txs |  calls    216 (  2) | sload     847 | sstore    181 | create   0 
nethermind-lh_1        | 04 Feb 00:02:59 | - Block throughput    4.64 MGas/s |    117.43 t/s |          0.64 Blk/s | recv        0 | proc       86 
nethermind-lh_1        | 04 Feb 00:03:01 | Processed            10480683     |  2,346.91 ms  |  slot      2,348 ms | Gas gwei: 0.00 .. 0.00 (0.07) .. 6.00 
nethermind-lh_1        | 04 Feb 00:03:01 | - Block               9.70 MGas   |    321    txs |  calls     81 (  3) | sload     315 | sstore    109 | create   0 
nethermind-lh_1        | 04 Feb 00:03:01 | - Block throughput    4.13 MGas/s |    136.78 t/s |          0.43 Blk/s | recv        0 | proc       85 
nethermind-lh_1        | 04 Feb 00:03:01 | Received new block:  10480769 (0x3dfba8...22f76e) 
nethermind-lh_1        | 04 Feb 00:03:01 | Processing loop threw an exception. Block: 10480685 (0xdfb77c...a6e7cd), Exception: System.InvalidOperationException: Attempted to process a blockchain without having starting state
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.PrepareBlocksToProcess(Block suggestedBlock, ProcessingOptions options, ProcessingBranch processingBranch) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 576
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 384
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 317 
nethermind-lh_1        | 04 Feb 00:03:01 | Processing loop threw an exception. Block: 10480686 (0xba4ff6...8c2c7e), Exception: System.InvalidOperationException: Attempted to process a blockchain without having starting state
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.PrepareBlocksToProcess(Block suggestedBlock, ProcessingOptions options, ProcessingBranch processingBranch) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 576
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 384
nethermind-lh_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 317
```

another case after restart
```
execution-1  | 05 Feb 10:56:52 | Rerunning block after reorg or pruning: 810888 (0x6ec590...f2c637) 
execution-1  | 05 Feb 10:56:52 | Rerunning block after reorg or pruning: 810889 (0x353973...e6c062) 
execution-1  | 05 Feb 10:56:52 | Rerunning block after reorg or pruning: 810890 (0xb42948...1cd3fc) 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810891 (0x2b9e28...e4d4d2) 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810892 (0xc6b947...4e7d53) 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810893 (0xad0ad5...4300de) 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810894 (0x05aa2f...0b66b7) 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810895 (0x2b941d...07a912) 
execution-1  | 05 Feb 10:56:53 | Processed      810886...   810895 |  1,051.79 ms  |  slot      1,053 ms | Gas gwei: 1.12 .. [97m1.12[37m (1.65) .. 3.00 
execution-1  | 05 Feb 10:56:53 | - Blocks 10         144.39[37m MGas   |    186    txs |  calls  5,089[37m [37m( 17)[37m | sload  12,747 | sstore  7,275[37m | create 1,307[37m[37m(-1,006)[37m 
execution-1  | 05 Feb 10:56:53 | - Block throughput  137.28 MGas/s |    176.84 t/s |          9.51 Blk/s | recv    5,966 | proc    2,000 
execution-1  | 05 Feb 10:56:53 | Rerunning block after reorg or pruning: 810896 (0x673fc3...06478b) 
execution-1  | 05 Feb 10:56:53 | Processing loop threw an exception. Block: 810898 (0xd20dc7...cdc856), Exception: System.InvalidOperationException: Attempted to process a blockchain without having starting state
execution-1  |    at Nethermind.Consensus.Processing.BlockchainProcessor.PrepareBlocksToProcess(Block suggestedBlock, ProcessingOptions options, ProcessingBranch processingBranch) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 576
execution-1  |    at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 384
execution-1  |    at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 317 
```

**Comment by totoCZ** [comment]
```
Dec 19 07:13:05 systemd-nethermind[2527546]: 19 Dec 07:13:05 | Processing loop threw an exception. Block: 21434999 (0x79d895...3bbf3a), Exception: System.InvalidOperationException: Attempted to process a blockchain with missing state root 0x90ef04e2f7e3f1b623e524ce6598fce71ee2f1736b3457ef7080929f01b2c010
Dec 19 07:13:05 systemd-nethermind[2527546]:    at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 319
Dec 19 07:13:05 systemd-nethermind[2527546]:    at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer, String& error) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 393
Dec 19 07:13:05 systemd-nethermind[2527546]:    at Nethermind.Consensus.Processing.BlockchainProcessor.PrepareBlocksToProcess(Block suggestedBlock, ProcessingOptions options, ProcessingBranch processingBranch) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 588
Dec 19 07:13:05 systemd-nethermind[2527546]: 19 Dec 07:13:05 | Processing loop threw an exception. Block: 21434998 (0x10eae8...164985), Exception: System.InvalidOperationException: Attempted to process a blockchain with missing state root 0x90ef04e2f7e3f1b623e524ce6598fce71ee2f1736b3457ef7080929f01b2c010
Dec 19 07:13:05 systemd-nethermind[2527546]: 19 Dec 07:13:05 |  Block throughput       14.82 MGas/s  |      149.9 tps |          0.72 Blk/s | recover     0 | process     6
Dec 19 07:13:05 systemd-nethermind[2527546]: 19 Dec 07:13:05 |  Block mev 0.0459 ETH   20.56 MGas    |      208   txs |  calls  5,030 (107) | sload  16,678 | sstore  6,478 | create   1(-512)
Dec 19 07:13:05 systemd-nethermind[2527546]: 19 Dec 07:13:05 | Processed            21434995         |    1,387.5 ms  |  slot    100,395 ms |<E2> Gas gwei: 10.03 .. 10.91 (12.52) .. 138.79
Dec 19 07:13:03 systemd-nethermind[2527546]: 19 Dec 07:13:03 | Non consecutive block commit. This is likely a reorg. Last block commit: 21434994. New block commit: 21434991.
Dec 19 07:13:03 systemd-nethermind[2527546]: 19 Dec 07:13:03 | Rerunning block after reorg or pruning: 21434994 (0x6a6265...173894)
Dec 19 07:13:03 systemd-nethermind[2527546]: 19 Dec 07:13:03 | Rerunning block after reorg or pruning: 21434993 (0xcfe019...dadb63)
Dec 19 07:13:03 systemd-nethermind[2527546]: 19 Dec 07:13:03 | Rerunning block after reorg or pruning: 21434992 (0xc726c0...fe6ae2)
Dec 19 07:13:03 systemd-nethermind[2527546]: 19 Dec 07:13:03 | Rerunning block after reorg or pruning: 21434991 (0x7f9514...b66733)
Dec 19 07:13:02 systemd-nethermind[2527546]: 19 Dec 07:13:02 | Received ForkChoice: 21435001 (0xd232ac...967aa2), Safe: 21434967 (0x7e42ff...c8a39a), Finalized: 21434935 (0xd72350...d86cbf)

```
