### ISSUE TITLE
Gnosis Fast Sync stuck when no Pivot is defined

### ISSUE THREAD

**Issue by cbermudez97** [NethermindEth/nethermind#6718]
**Description**

I'm syncing Gnosis chain using custom config without specifying Pivot in Sync flags. When doing so the node gets stuck during while syncing Old Headers(happened around block 7000000) and State Sync will also get stuck. The beacon node is synced using checkpoint sync. Also, restarting the Nethermind node after it gets stuck causes it to launch this error after restart:

```
Sync mode update failed System.ArithmeticException: Underflow in subtraction 0 - 340282366920938463463374607431768211454
   at Nethermind.Int256.UInt256.ThrowArithmeticException(UInt256& a, UInt256& b)
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.SetExpectedNextHeaderToParent(BlockHeader header) in /_/src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 716
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.InitializeFeed() in /_/src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 196
   at Nethermind.Synchronization.ParallelSync.ActivatedSyncFeed`1.SyncModeSelectorOnChanged(SyncMode current) in /_/src/Nethermind/Nethermind.Synchronization/ParallelSync/ActivatedSyncFeed.cs:line 30
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.UpdateSyncModes(SyncMode newModes, String reason) in /_/src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs:line 284
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.Update() in /_/src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs:line 246
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.StartAsync(CancellationToken cancellationToken) in /_/src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs:line 1
```

Using provided [config](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Runner/configs/gnosis.cfg) file for Gnosis, which includes a Pivot configuration, works without issues.

**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:
1. Start Nethermind node using flags:
	* `--config=none`. Defaults configs
	* `--Init.ChainSpecPath=<path/to/gnosis-chainspec.json>`. [Used this one](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Chains/gnosis.json)
	* `--Sync.FastSync=true`
	* `--Sync.FastBlocks=true`
	*  Other flags related to JsonRpc, Metrics, ...
2. Sync Gnosis with Beacon node using checkpoint sync.
3. Nethermind will get stuck after some time.

**Actual behavior**
Nethermind gets stuck after some time while syncing old headers and restart causes node to launch exceptions.

**Expected behavior**
Nethermind syncs using Auto Pivot from Beacon node requests.

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Ubuntu
 - Version: 22.04
 - Installation Method: Latest Docker Image
 - Consensus Client: Lighthouse Latest (Reproduced with all CC that supports Gnosis with same results)

**Comment by kamilchodola** [comment]
@cbermudez97 please retest that once more on gnosis and chiado
