### ISSUE TITLE
`Unable to rent an instance of IEthRpcModule`

### ISSUE THREAD

**Issue by SeaMonkey82** [NethermindEth/nethermind#6724]
**Description**
After CL client was offline for a day or two, upon restart, nethermind started throwing this error repeatedly.

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Linux Mint 21.3
 - Version: 1e539c987160e053c27074420d47dd8ad6b7091b
 - Installation Method: GitHub
 - Consensus Client: Lighthouse e7ef2a3a54a871bac30ca1ce8a1382dd567eab8d

**Logs**
```
13 Feb 23:50:30 | Error during method execution, request: Id:1, eth_getLogs([{"address":"0x4242424242424242424242424242424242424242","fromBlock":"0xddfba","toBlock":"0xde3a2","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]) Nethermind.JsonRpc.Exceptions.ModuleRentalTimeoutException: Unable to rent an instance of IEthRpcModule. Too many concurrent requests.
   at Nethermind.JsonRpc.Modules.BoundedModulePool`1.SlowPath() in /home/seamonkey/Downloads/holesky/nethermind/src/Nethermind/Nethermind.JsonRpc/Modules/BoundedModulePool.cs:line 75
   at Nethermind.JsonRpc.Modules.RpcModuleProvider.<>c__DisplayClass17_0`1.<<GetPools>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Nethermind.JsonRpc.JsonRpcService.ExecuteAsync(JsonRpcRequest request, String methodName, ValueTuple`3 method, JsonRpcContext context) in /home/seamonkey/Downloads/holesky/nethermind/src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs:line 162
   at Nethermind.JsonRpc.JsonRpcService.ExecuteRequestAsync(JsonRpcRequest rpcRequest, JsonRpcContext context) in /home/seamonkey/Downloads/holesky/nethermind/src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs:line 86
   at Nethermind.JsonRpc.JsonRpcService.SendRequestAsync(JsonRpcRequest rpcRequest, JsonRpcContext context) in /home/seamonkey/Downloads/holesky/nethermind/src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs:line 49
13 Feb 23:50:30 | Error when handling Id:1, eth_getLogs([{"address":"0x4242424242424242424242424242424242424242","fromBlock":"0xddfba","toBlock":"0xde3a2","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]) | {
  "jsonrpc": "2.0",
  "error": {
    "code": -32017,
    "message": "Timeout",
    "data": "Nethermind.JsonRpc.Exceptions.ModuleRentalTimeoutException: Unable to rent an instance of IEthRpcModule. Too many concurrent requests.\n   at Nethermind.JsonRpc.Modules.BoundedModulePool\u00601.SlowPath() in /home/seamonkey/Downloads/holesky/nethermind/src/Nethermind/Nethermind.JsonRpc/Modules/BoundedModulePool.cs:line 75\n   at Nethermind.JsonRpc.Modules.RpcModuleProvider.\u003C\u003Ec__DisplayClass17_0\u00601.\u003C\u003CGetPools\u003Eb__0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Nethermind.JsonRpc.JsonRpcService.ExecuteAsync(JsonRpcRequest request, String methodName, ValueTuple\u00603 method, JsonRpcContext context) in /home/seamonkey/Downloads/holesky/nethermind/src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs:line 162\n   at Nethermind.JsonRpc.JsonRpcService.ExecuteRequestAsync(JsonRpcRequest rpcRequest, JsonRpcContext context) in /home/seamonkey/Downloads/holesky/nethermind/src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs:line 86\n   at Nethermind.JsonRpc.JsonRpcService.SendRequestAsync(JsonRpcRequest rpcRequest, JsonRpcContext context) in /home/seamonkey/Downloads/holesky/nethermind/src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs:line 49"
  },
  "id": 1
}
```

**Comment by brbrr** [comment]
Got the same issue on windows node running goerli/nimbus

**Comment by asdacap** [comment]
Hi can you provide more logs?

**Comment by brbrr** [comment]
https://seq.nethermind.io/#/events?filter=NodeName%3D%22DailyResync_windows_master_sepolia_nimbus%22

Note, that this node name is reused between runs, so it might be have old or new unrelated entries
