### ISSUE TITLE
On very low disk space (about 3%) OldReceipts sync broke and BlockProcessing stopped working.

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#6733]
**Description**
I have ARM machine which had too small disk to sync full node. Didn't noticed that and started mainnet sync on it.
It reached about 37% of OldReceipts and at this stage last "low disk space" warning reported 30GB left which is about 2,8% of remaining free space (auto shutdown configured to 1%).

On that moment node started misbehaving - Seems that first it lost head of the chain and then it started to throw errors like this:
```
RocksDbSharp.RocksDbException: IO error: No such file or directory: while stat a file for size: /nethermind/data/nethermind_db/mainnet/receipts/052015.sst: No such file or directory
   at Nethermind.Db.Rocks.DbOnTheRocks.SetWithColumnFamily(ReadOnlySpan`1 key, ColumnFamilyHandle cf, ReadOnlySpan`1 value, WriteFlags flags) in /_/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 687
   at Nethermind.Blockchain.Receipts.PersistentReceiptStorage.Insert(Block block, TxReceipt[] txReceipts, Boolean ensureCanonical) in /_/src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs:line 264
   at Nethermind.Synchronization.FastBlocks.ReceiptsSyncFeed.InsertReceipts(ReceiptsSyncBatch batch) in /_/src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs:line 246
   at Nethermind.Synchronization.FastBlocks.ReceiptsSyncFeed.HandleResponse(ReceiptsSyncBatch batch, PeerInfo peer) in /_/src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs:line 160
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.DoHandleResponse(T request, PeerInfo allocatedPeer) in /_/src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs:line 187
```

After that node completly crashed and no new information about low disk space has appeared.

Logs from the moment it happened here (exported from Seq)
[export-8dc2e4394e8cdf3.csv](https://github.com/NethermindEth/nethermind/files/14299531/export-8dc2e4394e8cdf3.csv)

Appeared on master on commit 3d5523d4

**Comment by kamilchodola** [comment]
Something to retest

@dmitriy-b can you check on that at? It is mid prio.

**Comment by dmitriy-b** [comment]
@kamilchodola  I haven't faced with your issue but reached a possible new one. 

My environment was: VM with Windows 11 (ARM version), nethermind v 1.31.1 (x64 binaries, not docker) and the latest lighthouse. I setup the node against virtual nvme with 20 GB, start nethermind and lighthouse with default arguments:

```
.\lighthouse.exe bn --network mainnet --execution-endpoint http://localhost:8551 --execution-jwt "F:\Nethermind\keystore\jwt-secret" --checkpoint-sync-url https://mainnet.checkpoint.sigp.io --http
```
Note that lighthouse DB was located on the drive C, so did not affect the experiment.

So, I started the sync and after some time reached 1 GB of free space on a separate disk F (4% of 20GB), show the warning about running out of free disk space and stop the nethermind process (but not lighthouse). 

Then, I faced with an issue: cannot snap sync during 2 hours: 
```
27 Feb 16:05:31 | No Best Suggested Header available. Snap Sync not started.
```

I have restarted CL and the message disappeared. But during the next 2 hours I was not able to rich less then 4 % on the drive F. 

So, I just copied a few files to reach less then 2%
```
27 Feb 16:31:51 | Running out of free disk space in 'F:\' - only 0.49 GB (2.47%) left!
```
Then I saw the warning
```
27 Feb 16:31:25 | Unable to find beacon header at height 21938139. This is unexpected, forcing a new beacon sync.
```

Finally got
```
Free disk space in 'F:\' is below 1.00% - shutting down...
```
And nethermind has been exited

When started the node again, following error appears
```
Not enough free disk space in 'F:\' to safely run a node - please provide at least 0.50 GB to continue initialization.
```

When I extended the disk size and start the node again, I saw following warning and the sync has been hang
```
27 Feb 16:51:24 | Snap - too many empty responses - Pivot changed from 21938204 to 21938204
```

When I restart CL a few times, above error has disappeared, I saw again
```
27 Feb 17:12:02 | No incoming messages from the consensus client that is required for sync.
``` 
And after the next EL + CL restart I was not managed to start the sync.

So, seems like 1% of free disk is not enough to recover the network. Should we increase auto shutdown?

[mainnet.logs.txt](https://github.com/user-attachments/files/19011744/mainnet.logs.txt)

**Comment by kamilchodola** [comment]
@dmitriy-b Can you recheck both main issue and issue from comments again and leave an update here?
