### ISSUE TITLE
Critical DB corruption error 5 hours after upgrading to 1.25.4

### ISSUE THREAD

**Issue by wga22** [NethermindEth/nethermind#6757]
**Description**
Critical DB corruption error 5 hours after upgrading to 1.25.4.

**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:
1. upgrade to 1.25.4
2. issues after certain time of running

**Actual behavior**
Corrupt DB that requires restart and lengthy repair (which hasnt completed after 20 mins)

**Expected behavior**
No corruption

**Logs**
2024-02-21T21:17:14.314217-05:00 mobius nethermind[1346438]: 21 Feb 21:17:14 | - Block throughput   46.81 MGas/s |    555.51 t/s |          3.00 Blk/s | recv        0 | proc        0
2024-02-21T21:17:14.325425-05:00 mobius nethermind[1346438]: 21 Feb 21:17:14 | Received ForkChoice: Head: 19280132 (0x4446fa...de6945), Safe: 19280073 (0x88e05f...369379), Finalized: 19280041 (0xc706e9...1bf59f)
2024-02-21T21:17:14.325559-05:00 mobius nethermind[1346438]: 21 Feb 21:17:14 | Synced chain Head to 19280132 (0x4446fa...de6945)
2024-02-21T21:17:15.111624-05:00 mobius teku[1346858]: 21:17:15.111 INFO  - #033[37mSlot Event  *** Slot: 8478684, Block: d0da2e8771487c9ff354942207c0f26ad562ed37acbfb7f1c5dada3e2651044d, Justified: 264957, Finalized: 264956, Peers: 100#033[0m
2024-02-21T21:17:21.526043-05:00 mobius nethermind[1346438]: 21 Feb 21:17:21 | Removing 1069 out of 11069 peer candidates (candidates cleanup).
2024-02-21T21:17:24.425324-05:00 mobius nethermind[1346438]: 21 Feb 21:17:24 | Received new block:  19280133 (0x2cfa99...b79839)
2024-02-21T21:17:24.457098-05:00 mobius nethermind[1346438]: 21 Feb 21:17:24 | Corrupted DB detected on path /data/var/lib/nethermind/nethermind_db/mainnet/state/0. Please restart Nethermind to attempt repair.
2024-02-21T21:17:24.461879-05:00 mobius nethermind[1346438]: 21 Feb 21:17:24 | Processing loop threw an exception. Block: 19280133 (0x2cfa99...b79839), Exception: RocksDbSharp.RocksDbException: Corruption: block checksum mismatch: stored = 1449321764, computed = 2313665620, type = 4  in /data/var/lib/nethermind/nethermind_db/mainnet/state/0/093777.sst offset 1076765860 size 3441
2024-02-21T21:17:24.461994-05:00 mobius nethermind[1346438]:    at Nethermind.Db.Rocks.DbOnTheRocks.GetWithColumnFamily(ReadOnlySpan`1 key, ColumnFamilyHandle cf, ManagedIterators readaheadIterators, ReadFlags flags)
2024-02-21T21:17:24.462040-05:00 mobius nethermind[1346438]:    at Nethermind.Synchronization.Trie.HealingTrieStore.LoadRlp(Hash256 keccak, ReadFlags readFlags)
2024-02-21T21:17:24.462084-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree, ReadFlags readFlags, ICappedArrayPool bufferPool)
2024-02-21T21:17:24.462123-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.ResolveNode(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462160-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462200-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462239-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462282-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462329-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462377-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462474-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462519-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462562-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462604-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462641-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462687-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462726-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462760-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.TraverseNode(TrieNode node, TraverseContext& traverseContext)
2024-02-21T21:17:24.462796-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, CappedArray`1 updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Hash256 startRootHash)
2024-02-21T21:17:24.462843-05:00 mobius nethermind[1346438]:    at Nethermind.Trie.PatriciaTree.Get(ReadOnlySpan`1 rawKey, Hash256 rootHash)
2024-02-21T21:17:24.462887-05:00 mobius nethermind[1346438]:    at Nethermind.Synchronization.Trie.HealingStateTree.Get(ReadOnlySpan`1 rawKey, Hash256 rootHash)
2024-02-21T21:17:24.462931-05:00 mobius nethermind[1346438]:    at Nethermind.State.StateProvider.GetAndAddToCache(Address address)
2024-02-21T21:17:24.462974-05:00 mobius nethermind[1346438]:    at Nethermind.Evm.VirtualMachine`1.GetCachedCodeInfo(IWorldState worldState, Address codeSource, IReleaseSpec vmSpec)
2024-02-21T21:17:24.463019-05:00 mobius nethermind[1346438]:    at Nethermind.Evm.TransactionProcessing.TransactionProcessor.BuildExecutionEnvironment(Transaction tx, BlockExecutionContext blCtx, IReleaseSpec spec, UInt256& effectiveGasPrice)
2024-02-21T21:17:24.463062-05:00 mobius nethermind[1346438]:    at Nethermind.Evm.TransactionProcessing.TransactionProcessor.Execute(Transaction tx, BlockExecutionContext blCtx, ITxTracer tracer, ExecutionOptions opts)
2024-02-21T21:17:24.463103-05:00 mobius nethermind[1346438]:    at Nethermind.Consensus.Processing.TransactionProcessorAdapterExtensions.ProcessTransaction(ITransactionProcessorAdapter transactionProcessor, BlockExecutionContext blkCtx, Transaction currentTx, BlockReceiptsTracer receiptsTracer, ProcessingOptions processingOptions, IWorldState stateProvider)
2024-02-21T21:17:24.463185-05:00 mobius nethermind[1346438]:    at Nethermind.Consensus.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options)
2024-02-21T21:17:24.463219-05:00 mobius nethermind[1346438]:    at Nethermind.Consensus.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer)
2024-02-21T21:17:24.463260-05:00 mobius nethermind[1346438]:    at Nethermind.Consensus.Processing.BlockProcessor.Process(Hash256 newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer)
2024-02-21T21:17:24.463296-05:00 mobius nethermind[1346438]:    at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch& processingBranch, ProcessingOptions options, IBlockTracer tracer)
2024-02-21T21:17:24.463327-05:00 mobius nethermind[1346438]:    at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)
2024-02-21T21:17:24.463359-05:00 mobius nethermind[1346438]:    at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop()
2024-02-21T21:17:24.463392-05:00 mobius nethermind[1346438]: 21 Feb 21:17:24 | engine_newPayloadV2 failed: Nethermind.Blockchain.BlockchainException: Block processing threw exception.
2024-02-21T21:17:24.463423-05:00 mobius nethermind[1346438]:  ---> RocksDbSharp.RocksDbException: Corruption: block checksum mismatch: stored = 1449321764, computed = 2313665620, type = 4  in /data/var/lib/nethermind/nethermind_db/mainnet/state/0/093777.sst offset 1076765860 size 3441

**Comment by wga22** [comment]
[6757.log](https://github.com/NethermindEth/nethermind/files/14368509/6757.log)

**Comment by Marchhill** [comment]
Issue resolved on discord
