### ISSUE TITLE
ReceiptsSyncDispatcher throwing object disposed exceptions after finish of OldBodies

### ISSUE THREAD

**Issue by benaadams** [NethermindEth/nethermind#6777]
SyncDispatcher throwing object disposed exceptions after finish of OldBodies

**Logs**

```
24 Feb 05:29:05 | Old Bodies   18,794,150 / 19,291,169 ( 97.42 %) | queue   496,187 | current           26 Blk/s | total        2,216 Blk/s
24 Feb 05:29:10 | Old Bodies   18,794,150 / 19,291,169 ( 97.42 %) | queue   496,891 | current            0 Blk/s | total        2,215 Blk/s
24 Feb 05:29:11 | Received New Block:  19295361 (0x574d57...0d9bf7)
24 Feb 05:29:11 | Processed            19295361     |    190.23 ms  |  slot     12,147 ms |⛽ Gas gwei: 24.27 .. 24.27 (26.13) .. 70.00
24 Feb 05:29:11 | - Block              13.74 MGas   |    170    txs |  calls    554 ( 43) | sload   1,479 | sstore    466 | create   0
24 Feb 05:29:11 | - Block throughput   72.22 MGas/s |    893.67 t/s |          5.26 Blk/s | recv        0 | proc        0
24 Feb 05:29:11 | Received ForkChoice: 19295361 (0x574d57...0d9bf7), Safe: 19295333 (0xcfa0b7...b1863b), Finalized: 19295269 (0x31e956...8d306d)
24 Feb 05:29:11 | Synced Chain Head to 19295361 (0x574d57...0d9bf7)
24 Feb 05:29:14 | Changing state WaitingForBlock, FastBodies to WaitingForBlock, FastReceipts at processed: 19295361 | state: 19295361 | block: 19295361 | header: 19295361 | target block: 19295360 | peer block: 19295360
24 Feb 05:29:14 | Changed pivot in receipts sync. Now using pivot 19291169 and barrier 1
24 Feb 05:29:15 | SyncDispatcher<BodiesSyncBatch> has finished work.
24 Feb 05:29:15 | Fast blocks bodies task completed.
24 Feb 05:29:15 | Sync mode changed from WaitingForBlock, FastBodies to WaitingForBlock, FastReceipts
24 Feb 05:29:15 | Failure when executing request System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ArrayPoolList'.
   at Nethermind.Core.Collections.ArrayPoolList`1.<GuardDispose>g__ThrowObjectDisposed|9_0() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 51
   at Nethermind.Core.Collections.ArrayPoolList`1.get_Count() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 110
   at Nethermind.Core.LatencyAndMessageSizeBasedRequestSizer.<>c__DisplayClass5_0`2.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Nethermind.Core.AdaptiveRequestSizer.Run[TResponse](Func`2 func)
   at Nethermind.Core.LatencyAndMessageSizeBasedRequestSizer.Run[TResponse,TRequest](IReadOnlyList`1 request, Func`2 func)
   at Nethermind.Network.P2P.Subprotocols.Eth.V63.Eth63ProtocolHandler.GetReceipts(IReadOnlyList`1 blockHashes, CancellationToken token) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Network\P2P\Subprotocols\Eth\V63\Eth63ProtocolHandler.cs:line 156
   at Nethermind.Synchronization.FastBlocks.ReceiptsSyncDispatcher.Dispatch(PeerInfo peerInfo, ReceiptsSyncBatch batch, CancellationToken cancellationToken) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Synchronization\FastBlocks\ReceiptsSyncDownloader.cs:line 42
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.DoDispatch(CancellationToken cancellationToken, PeerInfo allocatedPeer, T request, SyncPeerAllocation allocation) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Synchronization\ParallelSync\SyncDispatcher.cs:line 139
24 Feb 05:29:15 | Failure when executing request System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ArrayPoolList'.
   at Nethermind.Core.Collections.ArrayPoolList`1.<GuardDispose>g__ThrowObjectDisposed|9_0() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 51
   at Nethermind.Core.Collections.ArrayPoolList`1.get_Count() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 110
   at Nethermind.Core.LatencyAndMessageSizeBasedRequestSizer.<>c__DisplayClass5_0`2.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Nethermind.Core.AdaptiveRequestSizer.Run[TResponse](Func`2 func)
   at Nethermind.Core.LatencyAndMessageSizeBasedRequestSizer.Run[TResponse,TRequest](IReadOnlyList`1 request, Func`2 func)
   at Nethermind.Network.P2P.Subprotocols.Eth.V63.Eth63ProtocolHandler.GetReceipts(IReadOnlyList`1 blockHashes, CancellationToken token) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Network\P2P\Subprotocols\Eth\V63\Eth63ProtocolHandler.cs:line 156
   at Nethermind.Synchronization.FastBlocks.ReceiptsSyncDispatcher.Dispatch(PeerInfo peerInfo, ReceiptsSyncBatch batch, CancellationToken cancellationToken) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Synchronization\FastBlocks\ReceiptsSyncDownloader.cs:line 42
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.DoDispatch(CancellationToken cancellationToken, PeerInfo allocatedPeer, T request, SyncPeerAllocation allocation) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Synchronization\ParallelSync\SyncDispatcher.cs:line 139
24 Feb 05:29:15 | Failure when executing request System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ArrayPoolList'.
   at Nethermind.Core.Collections.ArrayPoolList`1.<GuardDispose>g__ThrowObjectDisposed|9_0() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 51
   at Nethermind.Core.Collections.ArrayPoolList`1.get_Count() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 110
   at Nethermind.Core.LatencyAndMessageSizeBasedRequestSizer.<>c__DisplayClass5_0`2.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Nethermind.Core.AdaptiveRequestSizer.Run[TResponse](Func`2 func)
   at Nethermind.Core.LatencyAndMessageSizeBasedRequestSizer.Run[TResponse,TRequest](IReadOnlyList`1 request, Func`2 func)
   at Nethermind.Network.P2P.Subprotocols.Eth.V63.Eth63ProtocolHandler.GetReceipts(IReadOnlyList`1 blockHashes, CancellationToken token) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Network\P2P\Subprotocols\Eth\V63\Eth63ProtocolHandler.cs:line 156
   at Nethermind.Synchronization.FastBlocks.ReceiptsSyncDispatcher.Dispatch(PeerInfo peerInfo, ReceiptsSyncBatch batch, CancellationToken cancellationToken) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Synchronization\FastBlocks\ReceiptsSyncDownloader.cs:line 42
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.DoDispatch(CancellationToken cancellationToken, PeerInfo allocatedPeer, T request, SyncPeerAllocation allocation) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Synchronization\ParallelSync\SyncDispatcher.cs:line 139
24 Feb 05:29:15 | Failure when executing request System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ArrayPoolList'.
   at Nethermind.Core.Collections.ArrayPoolList`1.<GuardDispose>g__ThrowObjectDisposed|9_0() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 51
   at Nethermind.Core.Collections.ArrayPoolList`1.get_Count() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 110
   at Nethermind.Core.LatencyAndMessageSizeBasedRequestSizer.<>c__DisplayClass5_0`2.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Nethermind.Core.AdaptiveRequestSizer.Run[TResponse](Func`2 func)
   at Nethermind.Core.LatencyAndMessageSizeBasedRequestSizer.Run[TResponse,TRequest](IReadOnlyList`1 request, Func`2 func)
   at Nethermind.Network.P2P.Subprotocols.Eth.V63.Eth63ProtocolHandler.GetReceipts(IReadOnlyList`1 blockHashes, CancellationToken token) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Network\P2P\Subprotocols\Eth\V63\Eth63ProtocolHandler.cs:line 156
   at Nethermind.Synchronization.FastBlocks.ReceiptsSyncDispatcher.Dispatch(PeerInfo peerInfo, ReceiptsSyncBatch batch, CancellationToken cancellationToken) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Synchronization\FastBlocks\ReceiptsSyncDownloader.cs:line 42
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.DoDispatch(CancellationToken cancellationToken, PeerInfo allocatedPeer, T request, SyncPeerAllocation allocation) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Synchronization\ParallelSync\SyncDispatcher.cs:line 139
```

**Comment by asdacap** [comment]
:disappointed: I suppose all p2p message should be checked for disposability anyway.

**Comment by benaadams** [comment]
Also during startup

```
| Failed to notify [Peer|eth66|19301333|    49.13.55.78:30307| Out] about transactions. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ArrayPoolList'.
   at Nethermind.Core.Collections.ArrayPoolList`1.<GuardDispose>g__ThrowObjectDisposed|9_0() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 51
   at Nethermind.Core.Collections.ArrayPoolList`1.GuardResize(Int32 itemsToAdd) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 154
   at Nethermind.Core.Collections.ArrayPoolList`1.Add(T item) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 59
   at Nethermind.Network.P2P.Subprotocols.Eth.V65.Eth65ProtocolHandler.SendNewTransactionsCore(IEnumerable`1 txs, Boolean sendFullTx) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Network\P2P\Subprotocols\Eth\V65\Eth65ProtocolHandler.cs:line 183
   at Nethermind.Network.P2P.ProtocolHandlers.SyncPeerProtocolHandlerBase.SendNewTransactions(IEnumerable`1 txs, Boolean sendFullTx) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Network\P2P\ProtocolHandlers\SyncPeerProtocolHandlerBase.cs:line 228
   at Nethermind.TxPool.TxBroadcaster.Notify(ITxPoolPeer peer, IEnumerable`1 txs, Boolean sendFullTx) in D:\GitHub\nethermind\src\Nethermind\Nethermind.TxPool\TxBroadcaster.cs:line 317
25 Feb 01:43:07 | Failed to notify [Peer|eth66|19301333|    49.13.55.78:30307| Out] about transactions. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ArrayPoolList'.
   at Nethermind.Core.Collections.ArrayPoolList`1.<GuardDispose>g__ThrowObjectDisposed|9_0() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 51
   at Nethermind.Core.Collections.ArrayPoolList`1.GuardResize(Int32 itemsToAdd) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 154
   at Nethermind.Core.Collections.ArrayPoolList`1.Add(T item) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 59
   at Nethermind.Network.P2P.Subprotocols.Eth.V65.Eth65ProtocolHandler.SendNewTransactionsCore(IEnumerable`1 txs, Boolean sendFullTx) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Network\P2P\Subprotocols\Eth\V65\Eth65ProtocolHandler.cs:line 183
   at Nethermind.Network.P2P.ProtocolHandlers.SyncPeerProtocolHandlerBase.SendNewTransactions(IEnumerable`1 txs, Boolean sendFullTx) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Network\P2P\ProtocolHandlers\SyncPeerProtocolHandlerBase.cs:line 228
   at Nethermind.TxPool.TxBroadcaster.Notify(ITxPoolPeer peer, IEnumerable`1 txs, Boolean sendFullTx) in D:\GitHub\nethermind\src\Nethermind\Nethermind.TxPool\TxBroadcaster.cs:line 317
25 Feb 01:43:07 | Failed to notify [Peer|eth67|19301391|163.114.159.139:40030| Out] about transactions. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ArrayPoolList'.
   at Nethermind.Core.Collections.ArrayPoolList`1.<GuardDispose>g__ThrowObjectDisposed|9_0() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 51
   at Nethermind.Core.Collections.ArrayPoolList`1.GuardResize(Int32 itemsToAdd) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 154
   at Nethermind.Core.Collections.ArrayPoolList`1.Add(T item) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Core\Collections\ArrayPoolList.cs:line 59
   at Nethermind.Network.P2P.Subprotocols.Eth.V65.Eth65ProtocolHandler.SendNewTransactionsCore(IEnumerable`1 txs, Boolean sendFullTx) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Network\P2P\Subprotocols\Eth\V65\Eth65ProtocolHandler.cs:line 183
   at Nethermind.Network.P2P.ProtocolHandlers.SyncPeerProtocolHandlerBase.SendNewTransactions(IEnumerable`1 txs, Boolean sendFullTx) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Network\P2P\ProtocolHandlers\SyncPeerProtocolHandlerBase.cs:line 228
   at Nethermind.TxPool.TxBroadcaster.Notify(ITxPoolPeer peer, IEnumerable`1 txs, Boolean sendFullTx) in D:\GitHub\nethermind\src\Nethermind\Nethermind.TxPool\TxBroadcaster.cs:line 317
```
