### ISSUE TITLE
Goerli node - Failed to notify peer about transactions.

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#6783]
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ArrayPoolList'.
   at Nethermind.Core.Collections.ArrayPoolList`1.<GuardDispose>g__ThrowObjectDisposed|9_0() in /_/src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs:line 51
   at Nethermind.Core.Collections.ArrayPoolList`1.GuardResize(Int32 itemsToAdd) in /_/src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs:line 154
   at Nethermind.Core.Collections.ArrayPoolList`1.Add(T item) in /_/src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs:line 59
   at Nethermind.Network.P2P.Subprotocols.Eth.V65.Eth65ProtocolHandler.SendNewTransactionsCore(IEnumerable`1 txs, Boolean sendFullTx) in /_/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs:line 183
   at Nethermind.TxPool.TxBroadcaster.Notify(ITxPoolPeer peer, IEnumerable`1 txs, Boolean sendFullTx) in /_/src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs:line 313
```

**Comment by MarekM25** [comment]
oh, I think it is related to: https://github.com/NethermindEth/nethermind/pull/6779 cc: @asdacap
