### ISSUE TITLE
[TEST] Access to the path 'Nethermind.Blockchain.dll' is denied

### ISSUE THREAD

**Issue by lazaridiscom** [NethermindEth/nethermind#681]
after build, when running tests:

```sh
P:\nethermind\src\Nethermind>dotnet --version
2.2.108
P:\nethermind\src\Nethermind>dotnet test Nethermind.sln

```

the following error comes up. Is this a know issue?

```sh
Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1,0281 Seconds
SetUp failed for test fixture Nethermind.Overseer.Test.BasicTests
System.TypeInitializationException : The type initializer for 'Nethermind.Overseer.Test.Framework.TestBuilder' threw an exception.
  ----> System.UnauthorizedAccessException : Access to the path 'Nethermind.Blockchain.dll' is denied.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at NUnit.Framework.Internal.Reflect.Construct(Type type, Object[] arguments) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs:line 159
   at NUnit.Framework.Internal.Commands.ConstructFixtureCommand.<.ctor>b__0_0(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\ConstructFixtureCommand.cs:line 51
   at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\BeforeTestCommand.cs:line 50
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp() in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Execution\CompositeWorkItem.cs:line 257
--UnauthorizedAccessException
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Nethermind.Overseer.Test.Framework.TestBuilder..cctor() in P:\nethermind\src\Nethermind\Nethermind.Overseer.Test\Framework\TestBuilder.cs:line 89
SetUp failed for test fixture Nethermind.Overseer.Test.CliqueTests
System.TypeInitializationException : The type initializer for 'Nethermind.Overseer.Test.Framework.TestBuilder' threw an exception.
  ----> System.UnauthorizedAccessException : Access to the path 'Nethermind.Blockchain.dll' is denied.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at NUnit.Framework.Internal.Reflect.Construct(Type type, Object[] arguments) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs:line 159
   at NUnit.Framework.Internal.Commands.ConstructFixtureCommand.<.ctor>b__0_0(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\ConstructFixtureCommand.cs:line 51
   at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\BeforeTestCommand.cs:line 50
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp() in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Execution\CompositeWorkItem.cs:line 257
--UnauthorizedAccessException
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Nethermind.Overseer.Test.Framework.TestBuilder..cctor() in P:\nethermind\src\Nethermind\Nethermind.Overseer.Test\Framework\TestBuilder.cs:line 89
SetUp failed for test fixture Nethermind.Overseer.Test.GoerliTests
System.TypeInitializationException : The type initializer for 'Nethermind.Overseer.Test.Framework.TestBuilder' threw an exception.
  ----> System.UnauthorizedAccessException : Access to the path 'Nethermind.Blockchain.dll' is denied.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at NUnit.Framework.Internal.Reflect.Construct(Type type, Object[] arguments) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs:line 159
   at NUnit.Framework.Internal.Commands.ConstructFixtureCommand.<.ctor>b__0_0(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\ConstructFixtureCommand.cs:line 51
   at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\BeforeTestCommand.cs:line 50
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp() in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Execution\CompositeWorkItem.cs:line 257
--UnauthorizedAccessException
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Nethermind.Overseer.Test.Framework.TestBuilder..cctor() in P:\nethermind\src\Nethermind\Nethermind.Overseer.Test\Framework\TestBuilder.cs:line 89

Total tests: 22. Passed: 22. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 0,8726 Seconds
Failed   Test1
Error Message:
 OneTimeSetUp: System.TypeInitializationException : The type initializer for 'Nethermind.Overseer.Test.Framework.TestBuilder' threw an exception.
  ----> System.UnauthorizedAccessException : Access to the path 'Nethermind.Blockchain.dll' is denied.

Failed   Clique_transaction_broadcast
Skipped  Test
Error Message:
 OneTimeSetUp: System.TypeInitializationException : The type initializer for 'Nethermind.Overseer.Test.Framework.TestBuilder' threw an exception.
  ----> System.UnauthorizedAccessException : Access to the path 'Nethermind.Blockchain.dll' is denied.

Failed   Clique_vote
Error Message:
 OneTimeSetUp: System.TypeInitializationException : The type initializer for 'Nethermind.Overseer.Test.Framework.TestBuilder' threw an exception.
  ----> System.UnauthorizedAccessException : Access to the path 'Nethermind.Blockchain.dll' is denied.

Failed   One_validator
Error Message:
 OneTimeSetUp: System.TypeInitializationException : The type initializer for 'Nethermind.Overseer.Test.Framework.TestBuilder' threw an exception.
  ----> System.UnauthorizedAccessException : Access to the path 'Nethermind.Blockchain.dll' is denied.

Failed   Two_validators
Error Message:
 OneTimeSetUp: System.TypeInitializationException : The type initializer for 'Nethermind.Overseer.Test.Framework.TestBuilder' threw an exception.
  ----> System.UnauthorizedAccessException : Access to the path 'Nethermind.Blockchain.dll' is denied.

Failed   Goerli_initial_voting
Error Message:
 OneTimeSetUp: System.TypeInitializationException : The type initializer for 'Nethermind.Overseer.Test.Framework.TestBuilder' threw an exception.
  ----> System.UnauthorizedAccessException : Access to the path 'Nethermind.Blockchain.dll' is denied.


Total tests: 6. Passed: 0. Failed: 6. Skipped: 0.
Test Run Failed.
Test execution time: 0,8504 Seconds
Skipped  Security_check
Skipped  T_check
Skipped  Serializing_object_int_regression
```

**Comment by lazaridiscom** [comment]
win10pro64

**Comment by tkstanczak** [comment]
Did you run it with the latest codebase? After you mentioned testing I have added an [Explicit] attribute to overseer tests.

    [Explicit]
    public class CliqueTests : TestBuilder

**Comment by tkstanczak** [comment]
These tests are powerful but were not maintained properly so maybe we should remove them or spend time bringing them up to date.

**Comment by lazaridiscom** [comment]
was on latest stable, master seems to skip those tests.

> maybe we should remove them or spend time bringing them up to date.

if the related code is in-repo, then the tests should stay in repo, too (possibly with a remark/open issue)
