### ISSUE TITLE
 Unexpected value '0.0.0.0' for option 'JsonRpc.Host'

### ISSUE THREAD

**Issue by ThomasBlock** [NethermindEth/nethermind#6821]
I am having trouble connecting to nethermind rpc websocket
`2024-03-12T11:37:40.445917Z	FATAL	could not connect to execution client	{"error": "failed to connect to execution client: dial tcp 192.168.131.175:8546: connect: connection refused"}`

so i found the variable `--JsonRpc.Host`.
i tried some variants 
`--JsonRpc.Host=0.0.0.0
--JsonRpc.Host 0.0.0.0
--JsonRpc.Host "0.0.0.0"`
 but it seems not to work as expected?

```
stader_eth1  | 2024-03-12 11-51-50.7067|Nethermind starting initialization.
stader_eth1  | 2024-03-12 11-51-50.7160|Client version: Nethermind/v1.25.4+20b10b35/linux-x64/dotnet8.0.2
stader_eth1  | 2024-03-12 11-51-50.7185|Loading embedded plugins
stader_eth1  | 2024-03-12 11-51-50.7186|  Found plugin type Nethermind.Consensus.AuRa.AuRaPlugin
stader_eth1  | 2024-03-12 11-51-50.7186|  Found plugin type Nethermind.Consensus.Clique.CliquePlugin
stader_eth1  | 2024-03-12 11-51-50.7186|  Found plugin type Nethermind.Consensus.Ethash.EthashPlugin
stader_eth1  | 2024-03-12 11-51-50.7186|  Found plugin type Nethermind.Consensus.Ethash.NethDevPlugin
stader_eth1  | 2024-03-12 11-51-50.7186|  Found plugin type Nethermind.Hive.HivePlugin
stader_eth1  | 2024-03-12 11-51-50.7186|  Found plugin type Nethermind.UPnP.Plugin.UPnPPlugin
stader_eth1  | Resolved executing directory as /nethermind.
stader_eth1  | 2024-03-12 11-51-50.7298|Loading 12 assemblies from /nethermind/plugins
stader_eth1  | 2024-03-12 11-51-50.7298|Loading assembly Nethermind.Api
stader_eth1  | 2024-03-12 11-51-50.7306|Loading assembly Nethermind.HealthChecks
stader_eth1  | 2024-03-12 11-51-50.7314|  Found plugin type Nethermind.HealthChecks
stader_eth1  | 2024-03-12 11-51-50.7315|Loading assembly Nethermind.Mev
stader_eth1  | 2024-03-12 11-51-50.7744|  Found plugin type Nethermind.Mev
stader_eth1  | 2024-03-12 11-51-50.7744|Loading assembly Nethermind.Merge.Plugin
stader_eth1  | 2024-03-12 11-51-50.7764|  Found plugin type Nethermind.Merge.Plugin
stader_eth1  | 2024-03-12 11-51-50.7764|Loading assembly Nethermind.Merge.AuRa
stader_eth1  | 2024-03-12 11-51-50.7768|  Found plugin type Nethermind.Merge.AuRa
stader_eth1  | 2024-03-12 11-51-50.7768|Loading assembly Nethermind.Consensus.AuRa
stader_eth1  | 2024-03-12 11-51-50.7779|Loading assembly Nethermind.EthStats
stader_eth1  | 2024-03-12 11-51-50.7782|  Found plugin type Nethermind.EthStats
stader_eth1  | 2024-03-12 11-51-50.7782|Loading assembly Nethermind.Init
stader_eth1  | 2024-03-12 11-51-50.7785|Loading assembly Nethermind.JsonRpc.TraceStore
stader_eth1  | 2024-03-12 11-51-50.7788|  Found plugin type Nethermind.JsonRpc.TraceStore
stader_eth1  | 2024-03-12 11-51-50.7788|Loading assembly Nethermind.Init.Snapshot
stader_eth1  | 2024-03-12 11-51-50.7791|  Found plugin type Nethermind.Init.Snapshot
stader_eth1  | 2024-03-12 11-51-50.7791|Loading assembly Nethermind.Optimism
stader_eth1  | 2024-03-12 11-51-50.7797|  Found plugin type Nethermind.Optimism
stader_eth1  | 2024-03-12 11-51-50.7797|Loading assembly Nethermind.AccountAbstraction
stader_eth1  | 2024-03-12 11-51-50.7810|  Found plugin type Nethermind.AccountAbstraction
stader_eth1  | Specify --help for a list of available options and commands.
stader_eth1  | 12 Mar 11:51:50 | Failure Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unexpected value '0.0.0.0' for option 'JsonRpc.Host'
stader_eth1  |    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
stader_eth1  |    at Nethermind.Runner.Program.Run(String[] args) in /_/src/Nethermind/Nethermind.Runner/Program.cs:line 230
stader_eth1  |    at Nethermind.Runner.Program.Main(String[] args) in /_/src/Nethermind/Nethermind.Runner/Program.cs:line 80
stader_eth1 exited with code 1
```

**Comment by asdacap** [comment]
HI, can you double check that `--JsonRpc.Host 0.0.0.0` is not set twice?

**Comment by ThomasBlock** [comment]
ah okay that is a good hint. it is a complex docker setup, i just added it. so i probably have to investigate further!
