### ISSUE TITLE
Enable dual stack IPv6

### ISSUE THREAD

**Issue by barnabasbusa** [NethermindEth/nethermind#6822]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to set an IPv4 and an IPv6 advertised p2p address.

Currently, it doesn't seem to be supported:
```sh
Specify --help for a list of available options and commands.
12 Mar 14:52:42 | Failure Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unexpected value '2604:a880:400:d0::2262:9001' for option 'Network.ExternalIp'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Nethermind.Runner.Program.Run(String[] args) in /_/src/Nethermind/Nethermind.Runner/Program.cs:line 230
   at Nethermind.Runner.Program.Main(String[] args) in /_/src/Nethermind/Nethermind.Runner/Program.cs:line 80
```

**Comment by asdacap** [comment]
Hi, can you double check that its not specified twice?

**Comment by barnabasbusa** [comment]
I define it twice, once for ipv4 and once for ipv6. How else should this be done?

**Comment by asdacap** [comment]
Hmm... I'm afraid thats not possible right now.

**Comment by barnabasbusa** [comment]
Yup, thats why this issue is a Feature request.

**Comment by stdevMac** [comment]
Closing as a duplicate of #12309, the better-specified dual-stack tracking issue. The feature itself is still wanted — it is tracked there.
