### ISSUE TITLE
Errors logged - missing DLL 

### ISSUE THREAD

**Issue by duckwifbow** [NethermindEth/nethermind#6826]
**Description**

Noticed below error in logs starting on `2024-03-12 08:00:15`. Error logged repeatedly for about 24 hours until noticed. Consensus client seemed to operate normally during this period.

After restarting Nethermind, haven't seen further errors.

Note the installation uses the single file executable `nethermind.exe`, so there would never be standalone DLLs in the directory the error is indicating.

**Steps to Reproduce**

Nothing known changed configuration at time errors presented.

**Environment**
 - Windows 10
 - Nethermind/v1.25.4+20b10b35/windows-x64/dotnet8.0.2
 - Installation Method: GitHub Release
 - Consensus Client: Teku 24.2.0

**Logs**

```
2024-03-12 08:00:04.9530|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|95|Received ForkChoice: Head: 19419152 (0x800bd5...0294e4), Safe: 19419115 (0x7c1be3...f658d8), Finalized: 19419083 (0x2e8fa5...336b94) 
2024-03-12 08:00:14.5187|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|90|Received ForkChoice: Head: 19419152 (0x800bd5...0294e4), Safe: 19419115 (0x7c1be3...f658d8), Finalized: 19419083 (0x2e8fa5...336b94) 
2024-03-12 08:00:15.4178|ERROR|JsonRpc.JsonRpcService|3|Error during method execution, request: Id:329, eth_getLogs([{"topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"],"fromBlock":"0x127d505","toBlock":"0x127fc15","address":["0x00000000219ab540356cBB839Cbe05303d7705Fa"]}]) System.IO.FileNotFoundException: 
File name: 'System.Linq.Parallel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 ---> System.IO.FileNotFoundException: 
File name: 'D:\Nethermind\System.Linq.Parallel.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyBinder, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Nethermind.Api.Extensions.PluginLoader.<>c__DisplayClass7_0.<Load>b__0(AssemblyLoadContext _, AssemblyName name)
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Nethermind.Blockchain.Find.LogFinder.FilterLogsWithBloomsIndex(LogFilter filter, BlockHeader fromBlock, BlockHeader toBlock, CancellationToken cancellationToken)
   at Nethermind.Blockchain.Find.LogFinder.FindLogs(LogFilter filter, BlockHeader fromBlock, BlockHeader toBlock, CancellationToken cancellationToken)
   at Nethermind.JsonRpc.Modules.Eth.EthRpcModule.eth_getLogs(Filter filter)
   at InvokeStub_IEthRpcModule.eth_getLogs(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-03-12 08:00:15.4367|WARN|JsonRpc.JsonRpcProcessor|3|Error when handling Id:329, eth_getLogs([{"topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"],"fromBlock":"0x127d505","toBlock":"0x127fc15","address":["0x00000000219ab540356cBB839Cbe05303d7705Fa"]}]) | {
  "jsonrpc": "2.0",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "System.IO.FileNotFoundException: \r\nFile name: \u0027System.Linq.Parallel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\u0027\r\n ---\u003E System.IO.FileNotFoundException: \r\nFile name: \u0027D:\\Nethermind\\System.Linq.Parallel.dll\u0027\r\n   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyBinder, String ilPath, String niPath, ObjectHandleOnStack retAssembly)\r\n   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)\r\n   at Nethermind.Api.Extensions.PluginLoader.\u003C\u003Ec__DisplayClass7_0.\u003CLoad\u003Eb__0(AssemblyLoadContext _, AssemblyName name)\r\n   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)\r\n   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)\r\n   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)\r\n   at Nethermind.Blockchain.Find.LogFinder.FilterLogsWithBloomsIndex(LogFilter filter, BlockHeader fromBlock, BlockHeader toBlock, CancellationToken cancellationToken)\r\n   at Nethermind.Blockchain.Find.LogFinder.FindLogs(LogFilter filter, BlockHeader fromBlock, BlockHeader toBlock, CancellationToken cancellationToken)\r\n   at Nethermind.JsonRpc.Modules.Eth.EthRpcModule.eth_getLogs(Filter filter)\r\n   at InvokeStub_IEthRpcModule.eth_getLogs(Object, Span\u00601)\r\n   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)"
  },
  "id": 329
} 
```

**Comment by duckwifbow** [comment]
Likely due to a service wrapper. Will close pending any repro.
