### ISSUE TITLE
Client attemptes to process a blockchain with missing state root

### ISSUE THREAD

**Issue by OwlOfMoistness** [NethermindEth/nethermind#6834]
**Description**
The client attemptes to process a blockchain with missing state root

**Steps to Reproduce**
The client in my current state will keep getting there and restarting the service won't solve the issue

**Actual behavior**
Cannot process the chain and it stuck in a loop

**Expected behavior**
Should sync tot he current state of the chain

**Screenshots**
<img width="1662" alt="image" src="https://github.com/NethermindEth/nethermind/assets/94574404/563e6330-664a-44cf-aee5-c998ab0e889b">

**Logs**
Please include any relevant logs that may help identify the issue.

```
2024-03-15 12:11:12.5893|Received new block:  19440262 (0x52dbf3...054257)
2024-03-15 12:11:12.5893|Syncing... Inserting block 19440262 (0x52dbf3...054257).
2024-03-15 12:11:12.6957|Received ForkChoice: Head: 19440262 (0x52dbf3...054257), Safe: 19440209 (0x354464...a95eb3), Finalized: 19440177 (0xded4ee...8fb648)
2024-03-15 12:11:12.6958|Syncing beacon headers, Request: ForkChoice: Head: 19440262 (0x52dbf3...054257), Safe: 19440209 (0x354464...a95eb3), Finalized: 19440177 (0xded4ee...8fb648)
2024-03-15 12:11:13.2722|Processing loop threw an exception. Block: 19440262 (0x52dbf3...054257), Exception: System.InvalidOperationException: Attempted to process a blockchain with missing state root 0x82e36ebeebc622479216ed732f71da0e25ad44db225f01013c43cfb3e6091af6
   at Nethermind.Consensus.Processing.BlockchainProcessor.PrepareBlocksToProcess(Block suggestedBlock, ProcessingOptions options, ProcessingBranch processingBranch) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 583
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 385
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 318

```

**Comment by odinpodin** [comment]
have the same issue after update

**Comment by mirceanis** [comment]
Same for me. Any workaround?

**Comment by odinpodin** [comment]
> Same for me. Any workaround?

I deleted db and resynced

**Comment by MarekM25** [comment]
Closing, it looks like db corruption. Unfortuntately, resync is required
