### ISSUE TITLE
NullReference during discovery process when syncing

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#6995]
During a SnapSync I noticed this Exception appears on mainnet

```
Error during discovery process: System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Network.Discovery.RoutingTable.NodeTable.ClosestNodesEnumerator.MoveNext() in /_/src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeTable.cs:line 112
   at Nethermind.Network.Discovery.NodesLocator.LocateNodesAsync(Byte[] searchedNodeId, CancellationToken cancellationToken) in /_/src/Nethermind/Nethermind.Network.Discovery/NodesLocator.cs:line 81
   at Nethermind.Network.Discovery.DiscoveryApp.RunDiscoveryProcess() in /_/src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs:line 459
```

Seems like it does not affect sync but not sure how it would affect peers pool.

**Comment by kamilchodola** [comment]
@benaadams Any fix for that? Still happens on master
