### ISSUE TITLE
Early Exception on Holesky about establishing discovery connection

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#7042]
On Holesky already few times I saw that right after startup we have this exception:
```
16 May 19:27:40 | Error when establishing discovery connection System.Net.Sockets.SocketException (22): Invalid argument
Error: Exception found in Docker logs.
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DotNetty.Transport.Channels.Sockets.SocketDatagramChannel.DoBind(EndPoint localAddress)
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BindAsync(EndPoint localAddress)
--- End of stack trace from previous location ---
   at DotNetty.Transport.Bootstrapping.AbstractBootstrap`2.DoBindAsync(EndPoint localAddress)
```

Seems like it does not affect sync process but maybe some of the peers from bootnodes are not capable to connect well and we miss some potential early sync stage peers to speed it up a little.

**Comment by LukaszRozmej** [comment]
What OS was it?

**Comment by LukaszRozmej** [comment]
Can you include new logs from PR when this happens again?

**Comment by kamilchodola** [comment]
Sure

**Comment by kamilchodola** [comment]
Unable to reproduce now for some reason =- will keep the issue to monitor it for a while.
