### ISSUE TITLE
[jsonrpc] An unhandled exception was thrown by the application. System.ArgumentNullException: Value cannot be null. (Parameter 'options')

### ISSUE THREAD

**Issue by Zheaoli** [NethermindEth/nethermind#7145]
Hi guys, I use the v1.26.0 version. I config BufferResponses with true value for jsonrpc . but I get exception when I call rpc method.here's log

```text
06 Jun 13:33:33 | Connection id "0HN465L0KATSV", Request id "0HN465L0KATSV:00000002": An unhandled exception was thrown by the application. System.ArgumentNullException: Value cannot be null. (Parameter 'options')
   at Nethermind.Serialization.Json.CountingStreamPipeWriter..ctor(Stream writingStream, StreamPipeWriterOptions options) in /src/Nethermind/Nethermind.Serialization.Json/StreamPipeWriter.cs:line 89
   at Nethermind.Runner.JsonRpc.Startup.<>c__DisplayClass8_0.<<Configure>b__3>d.MoveNext() in /src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs:line 169
--- End of stack trace from previous location ---
   at Nethermind.Runner.JsonRpc.Startup.<>c__DisplayClass8_0.<<Configure>b__3>d.MoveNext() in /src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs:line 247
--- End of stack trace from previous location ---
   at Nethermind.Runner.JsonRpc.Startup.<>c__DisplayClass8_0.<<Configure>b__3>d.MoveNext() in /src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs:line 164
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
06 Jun 13:33:33 | Connection id "0HN465L0KATT0", Request id "0HN465L0KATT0:00000002": An unhandled exception was thrown by the application. System.ArgumentNullException: Value cannot be null. (Parameter 'options')
```

The config about jsonrpc here

```json
  "JsonRpc": {
    "RequestQueueLimit": 0,
    "BufferResponses": true,
    "Enabled": true,
    "Timeout": 20000,
    "Host": "0.0.0.0",
    "Port": 8545,
    "WebSocketsPort": 8546,
    "EnabledModules": [
      "admin",
      "client",
      "debug",
      "eth",
      "evm",
      "health",
      "net",
      "parity",
      "personal",
      "proof",
      "rpc",
      "subscribe",
      "trace",
      "txpool",
      "web3",
      "pre"
    ],
    "UseMinGasPriceInEstimates": true
   },
```

The bug been here https://github.com/NethermindEth/nethermind/blob/89d9ce4522621a2ed1df89dac92f0dbd1758d1e8/src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs#L168-L169, seems it beacuase we don't pass a option argument

The Bug has been introduced into the codebase in https://github.com/NethermindEth/nethermind/pull/6369/files#diff-598d38fe0d2b6352256df41cf30858eff35472a313c0022f0967db2e28f9d160R172

**Comment by benaadams** [comment]
Resolved in https://github.com/NethermindEth/nethermind/pull/7144 should be in next release

**Comment by Zheaoli** [comment]
The behavior still issue
1. the bootstrap error and 500 error fixed
2. "BufferResponses": true seem not works, the Transfer-Encoding  stiil  chunked

cc @benaadams
