### ISSUE TITLE
Exception: Nethermind.Abi.AbiException: System call to RewardContract.Reward returned error 'revert'

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#7385]
```
2024-09-03 12:28:12.518	
   at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 316 
2024-09-03 12:28:12.518	
   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer, String& error) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 391
2024-09-03 12:28:12.518	
   at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch& processingBranch, ProcessingOptions options, IBlockTracer tracer, String& error)
2024-09-03 12:28:12.518	
   at Nethermind.Consensus.Processing.BlockProcessor.Process(Hash256 newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 94
2024-09-03 12:28:12.518	
   at Nethermind.Consensus.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 272
2024-09-03 12:28:12.518	
   at Nethermind.Consensus.Processing.BlockProcessor.ApplyMinerRewards(Block block, IBlockTracer tracer, IReleaseSpec spec) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 347
2024-09-03 12:28:12.518	
   at Nethermind.Consensus.AuRa.Rewards.AuRaRewardCalculator.CalculateRewardsWithContract(Block block, IRewardContract contract)
2024-09-03 12:28:12.518	
   at Nethermind.Blockchain.Contracts.Contract.CallCore(ITransactionProcessor transactionProcessor, BlockHeader header, String functionName, Transaction transaction, Boolean callAndRestore) in /src/Nethermind/Nethermind.Blockchain/Contracts/Contract.cs:line 197
2024-09-03 12:28:12.509	
03 Sep 12:28:12 | Processing loop threw an exception. Block: 35811530 (0x7e2603...07e92d), Exception: Nethermind.Abi.AbiException: System call to RewardContract.Reward returned error 'revert' at block 35811068.
```

**Comment by Arindam2407** [comment]
Is it because we have not reached block no. 35811068 yet?
