### ISSUE TITLE
Revert precompiled touch

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#749]
Stack Trace:
     at Ethereum.Test.Base.BlockchainTestBase.RunTest(BlockchainTest test, Stopwatch stopwatch) in /home/travis/build/NethermindEth/[secure]/src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs:line 208
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Ethereum.Test.Base.BlockchainTestBase.RunTest(BlockchainTest test, Stopwatch stopwatch)
   at Ethereum.Blockchain.Test.RecursiveCreateTests.Test(BlockchainTest test) in /home/travis/build/NethermindEth/[secure]/src/Nethermind/Ethereum.Blockchain.Test/RecursiveCreateTests.cs:line 31
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Ethereum.Blockchain.Test.RecursiveCreateTests.Test(BlockchainTest test)
  X Test(RevertPrecompiledTouch_storage_d3g0v0_Byzantium) [44ms]
  Error Message:
     differences
  Expected: 0
  But was:  6
  Stack Trace:
     at Ethereum.Test.Base.BlockchainTestBase.RunTest(BlockchainTest test, Stopwatch stopwatch) in /home/travis/build/NethermindEth/[secure]/src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs:line 386
  Standard Output Messages:
 11:33:19 AM [6] ACCOUNT STATE (0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da) HAS DIFFERENCES
 11:33:19 AM [6] ACCOUNT STATE (0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b) HAS DIFFERENCES
 11:33:19 AM [6] Pre state account 0x0000000000000000000000000000000000000003 was not deleted as expected.
 11:33:19 AM [6] 0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da balance exp: 3000000000000098780, actual: , diff: 
 11:33:19 AM [6] 0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da nonce exp: 0, actual: 
 11:33:19 AM [6] 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b balance exp: 999999999999901220, actual: 1000000000000000000, diff: 98780
 11:33:19 AM [6] 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b nonce exp: 2, actual: 1
 11:33:19 AM [6] LAST BLOCK HASH exp: 0x8e1e35eaf6b6f1be3e390494b2e3ffe0b066f999ff0d2565130be0ca56ed247b, actual: 0x3d604db4bb0c5e6366d2489c0c41bf5105d0cd9c37442759626ba0f119424bb7
  X Test(RevertPrecompiledTouch_storage_d3g0v0_Constantinople) [20ms]
  Error Message:
     differences
  Expected: 0
  But was:  6
  Stack Trace:
     at Ethereum.Test.Base.BlockchainTestBase.RunTest(BlockchainTest test, Stopwatch stopwatch) in /home/travis/build/NethermindEth/[secure]/src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs:line 386
  Standard Output Messages:
 11:33:19 AM [55] ACCOUNT STATE (0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da) HAS DIFFERENCES
 11:33:19 AM [55] ACCOUNT STATE (0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b) HAS DIFFERENCES
 11:33:19 AM [55] Pre state account 0x0000000000000000000000000000000000000003 was not deleted as expected.
 11:33:19 AM [55] 0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da balance exp: 2000000000000098780, actual: , diff: 
 11:33:19 AM [55] 0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da nonce exp: 0, actual: 
 11:33:19 AM [55] 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b balance exp: 999999999999901220, actual: 1000000000000000000, diff: 98780
 11:33:19 AM [55] 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b nonce exp: 2, actual: 1
 11:33:19 AM [55] LAST BLOCK HASH exp: 0x23d87b6c0769079c68152b98e53bc810e85933d7427011cccba16460f65cf5eb, actual: 0x3d604db4bb0c5e6366d2489c0c41bf5105d0cd9c37442759626ba0f119424bb7
  X Test(RevertPrecompiledTouch_storage_d3g0v0_ConstantinopleFix) [15ms]
  Error Message:
     differences
  Expected: 0
  But was:  6
  Stack Trace:
     at Ethereum.Test.Base.BlockchainTestBase.RunTest(BlockchainTest test, Stopwatch stopwatch) in /home/travis/build/NethermindEth/[secure]/src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs:line 386
  Standard Output Messages:
 11:33:19 AM [6] ACCOUNT STATE (0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da) HAS DIFFERENCES
 11:33:19 AM [6] ACCOUNT STATE (0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b) HAS DIFFERENCES
 11:33:19 AM [6] Pre state account 0x0000000000000000000000000000000000000003 was not deleted as expected.
 11:33:19 AM [6] 0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da balance exp: 2000000000000098780, actual: , diff: 
 11:33:19 AM [6] 0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da nonce exp: 0, actual: 
 11:33:19 AM [6] 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b balance exp: 999999999999901220, actual: 1000000000000000000, diff: 98780
 11:33:19 AM [6] 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b nonce exp: 2, actual: 1
 11:33:19 AM [6] LAST BLOCK HASH exp: 0x23d87b6c0769079c68152b98e53bc810e85933d7427011cccba16460f65cf5eb, actual: 0x3d604db4bb0c5e6366d2489c0c41bf5105d0cd9c37442759626ba0f119424bb7
  X Test(RevertPrecompiledTouch_d3g0v0_Byzantium) [14ms]
  Error Message:
     differences
  Expected: 0
  But was:  6
  Stack Trace:
     at Ethereum.Test.Base.BlockchainTestBase.RunTest(BlockchainTest test, Stopwatch stopwatch) in /home/travis/build/NethermindEth/[secure]/src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs:line 386
  Standard Output Messages:
 11:33:21 AM [55] ACCOUNT STATE (0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da) HAS DIFFERENCES
 11:33:21 AM [55] ACCOUNT STATE (0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b) HAS DIFFERENCES
 11:33:21 AM [55] Pre state account 0x0000000000000000000000000000000000000003 was not deleted as expected.
 11:33:21 AM [55] 0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da balance exp: 3000000000000098780, actual: , diff: 
 11:33:21 AM [55] 0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da nonce exp: 0, actual: 
 11:33:21 AM [55] 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b balance exp: 999999999999901220, actual: 1000000000000000000, diff: 98780
 11:33:21 AM [55] 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b nonce exp: 2, actual: 1
 11:33:21 AM [55] LAST BLOCK HASH exp: 0x9c9dd8a465b34cce6cca5609e43871685edfd83fff82f240e79095a0f1035ade, actual: 0xe229567dd56b672955b64176eec6df4a57e22df67d02a768e645e32ae1e2bdec
  X Test(RevertPrecompiledTouch_d3g0v0_Constantinople) [11ms]
  Error Message:
     differences
  Expected: 0
  But was:  6
  Stack Trace:
     at Ethereum.Test.Base.BlockchainTestBase.RunTest(BlockchainTest test, Stopwatch stopwatch) in /home/travis/build/NethermindEth/[secure]/src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs:line 386
  Standard Output Messages:
 11:33:21 AM [55] ACCOUNT STATE (0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da) HAS DIFFERENCES
 11:33:21 AM [55] ACCOUNT STATE (0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b) HAS DIFFERENCES
 11:33:21 AM [55] Pre state account 0x0000000000000000000000000000000000000003 was not deleted as expected.
 11:33:21 AM [55] 0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da balance exp: 2000000000000098780, actual: , diff: 
 11:33:21 AM [55] 0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da nonce exp: 0, actual: 
 11:33:21 AM [55] 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b balance exp: 999999999999901220, actual: 1000000000000000000, diff: 98780
 11:33:21 AM [55] 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b nonce exp: 2, actual: 1
 11:33:21 AM [55] LAST BLOCK HASH exp: 0x7240cc040a64903c97188da5a173c728a77e712dbb49cb101295b7474d3d389d, actual: 0xe229567dd56b672955b64176eec6df4a57e22df67d02a768e645e32ae1e2bdec
  X Test(RevertPrecompiledTouch_d3g0v0_ConstantinopleFix) [14ms]
  Error Message:
     differences
  Expected: 0
  But was:  6
  Stack Trace:
     at Ethereum.Test.Base.BlockchainTestBase.RunTest(BlockchainTest test, Stopwatch stopwatch) in /home/travis/build/NethermindEth/[secure]/src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs:line 386
  Standard Output Messages:
 11:33:21 AM [55] ACCOUNT STATE (0x68795c4aa09d6f4ed3e5de

**Comment by tkstanczak** [comment]
might be related:
                            if (_parityTouchBugAccount != null)
                            {
                                _state.AddToBalance(_parityTouchBugAccount, UInt256.Zero, spec);
                                _parityTouchBugAccount = null;
                            }
