### ISSUE TITLE
Block download from Peer failed

### ISSUE THREAD

**Issue by dmitriy-b** [NethermindEth/nethermind#7531]
**Description**
Error message appears in the logs (20-30 times per full sync):

```
DEBUG/ERROR Block download from [HBRN  ][      ][Peer|eth68|20869316|172.234.246.124:|  In] failed. System.AggregateException: One or more errors occurred. ([HBRN  ][      ][Peer|eth68|20869316|172.234.246.124:|  In] Nethermind sent invalid receipts for block 20869285 (0x8ceed3...a620fd).)
 ---> Nethermind.Synchronization.EthSyncException: [HBRN  ][      ][Peer|eth68|20869316|172.234.246.124:|  In] Nethermind sent invalid receipts for block 20869285 (0x8ceed3...a620fd).
   at Nethermind.Synchronization.Blocks.BlockDownloader.RequestReceipts(PeerInfo peer, CancellationToken cancellation, BlockDownloadContext context) in /src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs:line 497
   at Nethermind.Merge.Plugin.Synchronization.MergeBlockDownloader.DownloadBlocks(PeerInfo bestPeer, BlocksRequest blocksRequest, CancellationToken cancellation) in /src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs:line 189
   --- End of inner exception stack trace ---
```

**Steps to Reproduce**
1. Start nethermind client and sync. I used following configuration: 
```
Metrics.Enabled=true#log=DEBUG#Metrics.NodeName=dmytro-b-test-release-full-mainnet-lighthouse#Seq.MinLevel=Info#Seq.ServerUrl=https://seq.nethermind.io#JsonRpc.EnabledModules=[Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin]#Sync.SnapSync=false#Sync.FastSync=true
```
2. Wait some time
3. Check error logs

**Actual behavior**
The synchronization is successful but the error appears periodically 

**Expected behavior**
No errors should appear during the sync

**Desktop:**
 - Operating System: Ubuntu 22.04.5
 - Version: 22.04.5
 - Installation Method: Docker
 - Consensus Client: lighthouse, lodestar, teku, prysm, nimbus
 - Nethermind version: 1.29.0-rc+917f5349

**Additional context**
I run multiple VMs at the same time, with different consensuses 

**Logs**
Example: https://seq.nethermind.io/#/events?filter=NodeName%3D'dmytro-b-test-release-full-mainnet-lighthouse'&signal=signal-m33301

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by kamilchodola** [comment]
@dmitriy-b 
It is debug error which is reported to Seq because of the setup made - and is just an info that some peer sent invalid receipts (Nethermind). 

Also seems like recently we fixed it quite well as such logs were appearing quite often and now are not at all.
