### ISSUE TITLE
Pruning failed with exception. System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by codj0** [NethermindEth/nethermind#7848]
Using v1.29.1 client. Receiving the following error, I think it also existed on previous versions.

```
Pruning failed with exception. System.IO.FileNotFoundException:
File name: 'System.Threading.Tasks.Dataflow, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 ---> System.IO.FileNotFoundException:
File name: 'C:\Ethereum\execution\System.Threading.Tasks.Dataflow.dll'
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr __ptrNativeAssemblyBinder_native, UInt16* __ilPath_native, UInt16* __niPath_native, ObjectHandleOnStack __retAssembly_native)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Nethermind.Api.Extensions.PluginLoader.<>c__DisplayClass7_0.<Load>b__0(AssemblyLoadContext _, AssemblyName name)
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Nethermind.Trie.Pruning.TrieStore.PruneCache(Boolean skipRecalculateMemory, KeyValuePair`2[] allNodes)
   at Nethermind.Trie.Pruning.TrieStore.<Prune>b__49_0()
```
![image](https://github.com/user-attachments/assets/6787987b-dd55-4084-9180-ea08e67f4081)

**Comment by LukaszRozmej** [comment]
Did you build from source or used package/docker?

**Comment by Codj0** [comment]
> Did you build from source or used package/docker?

I downloaded the zip file from Releases: https://github.com/NethermindEth/nethermind/releases/download/1.29.1/nethermind-1.29.1-dfea5240-windows-x64.zip

**Comment by kamilchodola** [comment]
@codj0 Please recheck on latest versions and report back on that.
