### ISSUE TITLE
Missing plugin DLL - Google.Protobuf on fresh Linux install

### ISSUE THREAD

**Issue by quakemmo** [NethermindEth/nethermind#7902]
**Description**
nethermind-cli won't run.

**Steps to Reproduce**
1. Up-to-date Debian 12 server
2. downloaded the latest (1.30.0+7bd28c73) Nethermind amd64 .zip file from the Nethermind web site
3. created nethermind-1.30.1 directory in /home/user
4. unzipped the file into the nethermind-1.30.1 directory
5. cd nethermind-1.30.1
6. ran ./nethermind-cli

**Actual behavior**
nethermind-cli won't start and exits with an error and a backtrace.

**Expected behavior**
nethermind-cli actually starts.

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Debian
 - Version: 12
 - Installation Method: downloaded from https://nethdev.blob.core.windows.net/builds/nethermind-1.30.1-2b75a75a-linux-x64.zip
 - Consensus Client: Prysm

**Logs**
``
**********************************************

Nethermind CLI 1.30.1+2b75a75a
  https://github.com/NethermindEth/nethermind
  https://nethermind.readthedocs.io/en/latest/

powered by:
  https://github.com/sebastienros/jint
  https://github.com/tomakita/Colorful.Console
  https://github.com/tonerdo/readline

**********************************************

Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'Google.Protobuf, Version=3.28.3.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'. The system cannot find the file specified.

File name: 'Google.Protobuf, Version=3.28.3.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'
 ---> System.IO.FileNotFoundException: Could not load file or assembly '/home/user/nethermind-1.30.1/plugins/Google.Protobuf.dll'. The system cannot find the file specified.

File name: '/home/user/nethermind-1.30.1/plugins/Google.Protobuf.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Nethermind.Cli.Modules.CliModuleLoader.<>c__DisplayClass12_0.<DiscoverAndLoadModules>b__0(AssemblyLoadContext context, AssemblyName name)
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nethermind.Cli.Modules.CliModuleLoader.DiscoverAndLoadModules()
   at Nethermind.Cli.Program.<>c__DisplayClass2_0.<Main>b__0(ParseResult parseResult)
   at System.CommandLine.Invocation.AnonymousSynchronousCliAction.Invoke(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
``

**Comment by stdevMac** [comment]
Closing: Nethermind.Cli was removed entirely in #8575, so this no longer applies.
