### ISSUE TITLE
PatriciaTree failure at Ropsten 1695216

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#81]
2018-08-28 11:22:08.2403|ERROR|10|Blockchain.BlockchainProcessor|BlockchainProcessor encountered an exception. System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.) ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Nethermind.Core.Encoding.Rlp.DecoderContext.ReadByte() in C:\src\nethermind\src\Nethermind\Nethermind.Core\Encoding\Rlp.cs:line 870
   at Nethermind.Core.Encoding.Rlp.DecoderContext.ReadSequenceLength() in C:\src\nethermind\src\Nethermind\Nethermind.Core\Encoding\Rlp.cs:line 811
   at Nethermind.Store.TrieNode.ResolveNode(PatriciaTree tree) in C:\src\nethermind\src\Nethermind\Nethermind.Store\TrieNode.cs:line 196
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 463
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 287
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 463
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 287
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 463
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 287
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 463
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 287
   at Nethermind.Store.PatriciaTree.Run(Byte[] updatePath, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 266
   at Nethermind.Store.PatriciaTree.Get(Byte[] rawKey) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 216
   at Nethermind.Store.StorageTree.Get(BigInteger index) in C:\src\nethermind\src\Nethermind\Nethermind.Store\StorageTree.cs:line 65
   at Nethermind.Store.StorageProvider.GetAndAddToCache(StorageAddress storageAddress) in C:\src\nethermind\src\Nethermind\Nethermind.Store\StorageProvider.cs:line 282
   at Nethermind.Store.StorageProvider.GetThroughCache(StorageAddress storageAddress) in C:\src\nethermind\src\Nethermind\Nethermind.Store\StorageProvider.cs:line 268
   at Nethermind.Store.StorageProvider.Get(StorageAddress storageAddress) in C:\src\nethermind\src\Nethermind\Nethermind.Store\StorageProvider.cs:line 60
   at Nethermind.Evm.VirtualMachine.ExecuteCall(EvmState evmState, Byte[] previousCallResult, Byte[] previousCallOutput, UInt256 previousCallOutputDestination, IReleaseSpec spec) in C:\src\nethermind\src\Nethermind\Nethermind.Evm\VirtualMachine.cs:line 1592
   at Nethermind.Evm.VirtualMachine.Run(EvmState state, IReleaseSpec releaseSpec, TransactionTrace trace) in C:\src\nethermind\src\Nethermind\Nethermind.Evm\VirtualMachine.cs:line 136
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block) in C:\src\nethermind\src\Nethermind\Nethermind.Evm\TransactionProcessor.cs:line 238
   at Nethermind.Blockchain.BlockProcessor.ProcessTransactions(Block block, Transaction[] transactions) in C:\src\nethermind\src\Nethermind\Nethermind.Blockchain\BlockProcessor.cs:line 77
   at Nethermind.Blockchain.BlockProcessor.ProcessBlock(Keccak parentHash, UInt256 difficulty, UInt256 number, UInt256 timestamp, Address beneficiary, Int64 gasLimit, Byte[] extraData, Transaction[] transactions, Keccak mixHash, UInt64 nonce, Keccak ommersHash, BlockHeader[] ommers) in C:\src\nethermind\src\Nethermind\Nethermind.Blockchain\BlockProcessor.cs:line 305
   at Nethermind.Blockchain.BlockProcessor.ProcessNonGenesis(Block suggestedBlock, Boolean tryOnly) in C:\src\nethermind\src\Nethermind\Nethermind.Blockchain\BlockProcessor.cs:line 247
   at Nethermind.Blockchain.BlockProcessor.ProcessOne(Block suggestedBlock, Boolean tryOnly) in C:\src\nethermind\src\Nethermind\Nethermind.Blockchain\BlockProcessor.cs:line 204
   at Nethermind.Blockchain.BlockProcessor.Process(Keccak branchStateRoot, Block[] suggestedBlocks, Boolean tryOnly) in C:\src\nethermind\src\Nethermind\Nethermind.Blockchain\BlockProcessor.cs:line 126
   at Nethermind.Blockchain.BlockchainProcessor.Process(Block suggestedBlock, Boolean forMining) in C:\src\nethermind\src\Nethermind\Nethermind.Blockchain\BlockchainProcessor.cs:line 479
   at Nethermind.Blockchain.BlockchainProcessor.Process(Block suggestedBlock) in C:\src\nethermind\src\Nethermind\Nethermind.Blockchain\BlockchainProcessor.cs:line 339
   at Nethermind.Blockchain.BlockchainProcessor.RunProcessingLoop() in C:\src\nethermind\src\Nethermind\Nethermind.Blockchain\BlockchainProcessor.cs:line 225
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---

**Comment by tkstanczak** [comment]
Rlp.DecoderContext context = DecoderContext;
            context.ReadSequenceLength(); (this one passes so the node is not empty)
            int numberOfItems = context.ReadNumberOfItemsRemaining(); <-- here

**Comment by tkstanczak** [comment]
A few things:
* build the newest version of RocksDB (this is covered in another issue)
* fix the app closing - properly close DBs on application exit
* add option to rebuild DB going backwards until the key is found (but need to analyze the sense of doing it) 

as part of the investigation - rebuild until the hash is found:
0x6281e888d37c430fb2fa6a78c0bbfdb3a0668247120346fb2e807a6260ca5efa

**Comment by tkstanczak** [comment]
2018-08-30 11:08:24.3760 INFO [18] Loaded 850000 out of 3938125 blocks from DB into processing queue, waiting for processor before loading more.
2018-08-30 11:08:24.3760 INFO [18] Processed blocks up to    839999 in  13,294ms, tx= 3613 mgas=  618.16, mgasps=  46.50, txps= 271.78, total mgasps= 161.96, queue=7743
2018-08-30 11:08:34.4807 INFO [18] Processed blocks up to    847652 in  10,105ms, tx= 7019 mgas= 1412.43, mgasps= 139.78, txps= 694.63, total mgasps= 161.86, queue=2347
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Nethermind.Core.Encoding.Rlp.DecoderContext.ReadByte() in C:\src\nethermind\src\Nethermind\Nethermind.Core\Encoding\Rlp.cs:line 870
   at Nethermind.Core.Encoding.Rlp.DecoderContext.ReadSequenceLength() in C:\src\nethermind\src\Nethermind\Nethermind.Core\Encoding\Rlp.cs:line 811
   at Nethermind.Store.TrieNode.ResolveNode(PatriciaTree tree) in C:\src\nethermind\src\Nethermind\Nethermind.Store\TrieNode.cs:line 202
2018-08-30 11:08:34.6997 ERROR [10] BlockchainProcessor encountered an exception. System.AggregateException: One or more errors occurred. (Unexpected number of items = 0 when decoding a node) ---> System.InvalidOperationException: Unexpected number of items = 0 when decoding a node
   at Nethermind.Store.TrieNode.ResolveNode(PatriciaTree tree) in C:\src\nethermind\src\Nethermind\Nethermind.Store\TrieNode.cs:line 232
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 472
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 296
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 472
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 296
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 472
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 296
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 472
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext context) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 296
   at Nethermind.Store.PatriciaTree.Run(Byte[] updatePath, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 275
   at Nethermind.Store.PatriciaTree.Get(Byte[] rawKey) in C:\src\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 225
   at Nethermind.Store.StateTree.Get(Address address) in C:\src\nethermind\src\Nethermind\Nethermind.Store\StateTree.cs:line 44

**Comment by tkstanczak** [comment]
2018-08-31 00:01:16.8342 INFO [18] Processed blocks up to    551782 in  10,043ms, tx= 1643 mgas=  753.64, mgasps=  75.04, txps= 163.60, total mgasps= 176.91, queue=8217
2018-08-31 00:01:18.1856 ERROR [11] BlockchainProcessor encountered an exception. System.AggregateException: One or more errors occurred. (HERE WE SAVE 0x854fc926c95d5880bd701b81f1615a4c2a73a2fd8d705974d443b48114f7f696)

**Comment by tkstanczak** [comment]
that was RocksDB, seems ot be resolved after the new RocksDB build
