### ISSUE TITLE
Nethermind node fails to sync to Volta PoA network (AuRa) on startup

### ISSUE THREAD

**Issue by ngyam** [NethermindEth/nethermind#927]
Ubuntu 16.04 LTS
Nethermind client 1.1.2 (downloaded binary from GitHub)
Chain: Volta (AuRa PoA testnet, with reporting enabled, validator set & reward system contracts)

**Problem**: client fails at startup. see details below for logs and reproducibility

Chainspec: https://github.com/energywebfoundation/ewf-chainspec/blob/master/Volta.json

volta.cfg: 
```
{
  "Init": {      
    "WebSocketsEnabled": false,
    "StoreReceipts" : true,
    "IsMining": false,
    "ChainSpecPath": "/home/aznagy/work/ewf/chains/Volta.json",
    "GenesisHash": "0xebd8b413ca7b7f84a8dd20d17519ce2b01954c74d94a0a739a3e416abe0e43e5",
    "BaseDbPath": "nethermind_db/volta",
    "LogFileName": "volta.logs.txt"
  },
  "Network": {
    "DiscoveryPort": 30303,
    "P2PPort": 30303
  },
  "JsonRpc": {
    "Enabled": false,
    "Host": "127.0.0.1",
    "Port": 8545    
  },
  "Db": {
    "WriteBufferSize": 16000000,
    "WriteBufferNumber": 4,
    "BlockCacheSize": 128000000,
    "CacheIndexAndFilterBlocks": true,
    "BlockInfosDbCacheIndexAndFilterBlocks": false
  },
  "Sync": {
    "FastSync": false,
    "FastBlocks" : false,
    "DownloadBodiesInFastSync" : false,
    "DownloadReceiptsInFastSync" : false
  },
  "EthStats": {
    "Enabled": false,
    "Server": "ws://localhost:3000/api",
    "Name": "Nethermind Volta",
    "Secret": "secret",
    "Contact": "hello@nethermind.io"
  },
  "Metrics": {
    "NodeName": "VoltaNode2",
    "Enabled": false,
    "PushGatewayUrl": "http://localhost:9091/metrics",
    "IntervalSeconds": 5
  }
}
```

**Error in the logs:**

```
Redirecting config volta to configs/volta.cfg
Reading config file from configs/volta.cfg
2019-10-22 20:39:17.2692|Nethermind config:
{
  "EnableUnsecuredDevWallet": false,
  "KeepDevWalletInMemory": false,
  "WebSocketsEnabled": false,
  "DiscoveryEnabled": true,
  "SynchronizationEnabled": true,
  "ProcessingEnabled": true,
  "PeerManagerEnabled": true,
  "IsMining": false,
  "ChainSpecPath": "/home/aznagy/work/ewf/chains/Volta.json",
  "ChainSpecFormat": "chainspec",
  "BaseDbPath": "nethermind_db/volta",
  "LogFileName": "volta.logs.txt",
  "GenesisHash": "0xebd8b413ca7b7f84a8dd20d17519ce2b01954c74d94a0a739a3e416abe0e43e5",
  "StaticNodesPath": "Data/static-nodes.json",
  "StoreTraces": false,
  "StoreReceipts": true,
  "EnableRc7Fix": false
}
|
2019-10-22 20:39:17.3256|Using http://checkip.amazonaws.com to get external ip|
2019-10-22 20:39:17.6116|External ip: 96.78.160.67
|
2019-10-22 20:39:17.6455|Loading chain spec from /home/aznagy/work/ewf/chains/Volta.json|
2019-10-22 20:39:17.7585|Using database directory nethermind_db/volta/blocks|
2019-10-22 20:39:17.9272|Using database directory nethermind_db/volta/headers|
2019-10-22 20:39:17.9399|Using database directory nethermind_db/volta/blockInfos|
2019-10-22 20:39:17.9503|Using database directory nethermind_db/volta/state|
2019-10-22 20:39:17.9628|Using database directory nethermind_db/volta/code|
2019-10-22 20:39:17.9759|Using database directory nethermind_db/volta/pendingtxs|
2019-10-22 20:39:17.9848|Using database directory nethermind_db/volta/configs|
2019-10-22 20:39:17.9953|Using database directory nethermind_db/volta/ethRequests|
2019-10-22 20:39:18.0108|Using database directory nethermind_db/volta/receipts|
2019-10-22 20:39:18.0214|Using database directory nethermind_db/volta/trace|
2019-10-22 20:39:18.0565|Block tree initialized, last processed is 0, best queued is 0, best known is 0, lowest inserted header , body |
2019-10-22 20:39:18.1155|Error during ethereum runner start|System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Store.StateProvider.UpdateStorageRoot(Address address, Keccak storageRoot) in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Store/StateProvider.cs:line 201
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean readOnly) in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Evm/TransactionProcessor.cs:line 195
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer) in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Evm/TransactionProcessor.cs:line 61
   at Nethermind.Runner.Runners.EthereumRunner.LoadGenesisBlock(Keccak expectedGenesisHash) in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Runner/Runners/EthereumRunner.cs:line 839
   at Nethermind.Runner.Runners.EthereumRunner.InitBlockchain() in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Runner/Runners/EthereumRunner.cs:line 553
   at Nethermind.Runner.Runners.EthereumRunner.Start() in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Runner/Runners/EthereumRunner.cs:line 220
2019-10-22 20:39:18.1205|Json RPC is disabled|
2019-10-22 20:39:18.1205|Monitoring is disabled|

```

**Comment by ngyam** [comment]
Btw, do you guys have a more detailed specification of AuRa that would make contribution easier?

**Comment by tkstanczak** [comment]
@ngyam, we are looking at it

**Comment by LukaszRozmej** [comment]
@ngyam we merged the fix to master and we will publish new release shortly.

AuRa in Nethermind is currently under development. Currently we are able to sync AuRa chains. I'm currently working on sealing blocks. In next weeks we will also add other functionalities like reporting contract (currently only safe-contract is supported, but contract should also work for syncing), empty steps ect.

As for Aura spec I am using mostly parity specs:
https://wiki.parity.io/Aura
https://wiki.parity.io/Validator-Set
https://wiki.parity.io/Block-Reward-Contract

but to be frank this is not much and the only source of truth is the code, so I am reverse engineering Parity a lot to nail down the details:  https://github.com/paritytech/parity-ethereum

**Comment by tkstanczak** [comment]
https://github.com/NethermindEth/nethermind/releases/tag/1.1.3

**Comment by tkstanczak** [comment]
@ngyam would you check please, I assume that Volta is a private network that we cannot test beyond checking the init correctness

**Comment by ngyam** [comment]
sure sure, thanks for taking time for this issue!

**Comment by ngyam** [comment]
As a first step I just try to sync a non-validating node. With 1.1.3 I now get a bunch of:
```
2019-10-26 16:53:15.0817|Channel is active|DotNetty.Codecs.EncoderException: Exception of type 'DotNetty.Codecs.EncoderException' was thrown.
 ---> System.DllNotFoundException: Unable to load shared library 'snappy' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsnappy: cannot open shared object file: No such file or directory
   at Snappy.Native.snappy_max_compressed_length(UInt32 input_length)
   at Nethermind.Network.Rlpx.ZeroSnappyEncoder.Encode(IChannelHandlerContext context, IByteBuffer input, IByteBuffer output)
   at DotNetty.Codecs.MessageToByteEncoder`1.WriteAsync(IChannelHandlerContext context, Object message)
   --- End of inner exception stack trace ---
```
errors

**Comment by LukaszRozmej** [comment]
Please try from our github Readme:

Linux:
    sudo apt-get update && sudo apt-get install libsnappy-dev libc6-dev libc6

Mac:
    brew install gmp && brew install snappy && brew install lz4

at least the snappy part looks necessary in your situation

**Comment by ngyam** [comment]
nvm installed some packages and the error is gone.
Now the problem seems to be that I get no peers. The 6 bootnodes get recognized according to the logs:
```
2019-10-26 17:03:13.0601|Initializing persisted peers: 0.|
2019-10-26 17:03:13.0601|Bootnode     : enode://59c9250cb805409e84c9cd0038e97d8e5e4605b928663675869ebdfd4c251d80ccad76267a5eb2f4362ddceb5ec671f7595463adfc0a12e9f68dbf233072db41@54.70.158.106:30303|
2019-10-26 17:03:13.0601|Bootnode     : enode://e487ebacbdad3418905d2ed7f009fa5dbd17d73880854884acc604c0afc1a60a396aa90cb2741278c555a4e30ffc6ffc1c29e83840aa22009ec92fe53f81ec04@99.81.92.124:30303|
2019-10-26 17:03:13.0601|Bootnode     : enode://563f12602a117201b39ebeea108185abb15d9286830c074640c9fccbaaaabcc7fe2c95682cc43f95b95059f6d0dc4c9becbc1b2bd78e0c5ef5fddff07d85ba0e@54.201.62.74:30303|
2019-10-26 17:03:13.0601|Bootnode     : enode://5903b3acebdc4a34800f6923e5f3aec3ca7e5d1285bec4adb9f20ebb0f87a3bebdd748b1849ca1108a9f1e37ff9ced0b475292b8effc29e95d49ec438f244b02@3.121.165.10:30303|
2019-10-26 17:03:13.0601|Bootnode     : enode://8f8e35a6dcacfee946f46447b4703c84f4e485e478143997f86b1834e1b0bb78dab363d700dff3147442b9d3e2a1c521f79340c436eb7245a97c7fe385b89a5d@54.93.159.98:30303|
2019-10-26 17:03:13.0601|Bootnode     : enode://bd228aa03cf4a88491c81c5f3ab4a1437df3b463081cc93943c4d3ab37f1e4f8081c6995eca076f717d4fdf9a277c750bd0289477ac151f1e2b024747dcd1747@52.31.129.130:30303|
2019-10-26 17:03:13.0707|Discovery    : udp://198.27.253.194:30303|
2019-10-26 17:03:13.0767|Ethereum     : tcp://198.27.253.194:30303|
2019-10-26 17:03:13.0767|Version      : Nethermind/v1.1.3-/X64-Linux 4.15.0-34-generic/Core3.0.0|
2019-10-26 17:03:13.0790|This node    : enode://fd05f7198533833eaa9137d7d56bd85f695b9a20c6b145f78740d9c8ee980bdde3f33a9a4dcb48b05e1a149400a2886e243f6f067385ce68fb4b24cbbfffe58d@198.27.253.194:30303|
2019-10-26 17:03:13.0790|Node address : 0x6c258ca098e7166fce506707f6949d013baf11d8 (do not use as an account)|
2019-10-26 17:03:13.0832|ETH Stats integration is disabled.|
2019-10-26 17:03:13.0832|Added persisted discovery nodes: 0|
2019-10-26 17:03:13.0832|Json RPC is disabled|
2019-10-26 17:03:13.0832|Monitoring is disabled|
2019-10-26 17:03:13.9727|Sync peers - Initialized: 0 | All: 0 | Max: 50|
2019-10-26 17:03:13.9773|Sync peers 0(0)/50, searching for peers to sync with...|
2019-10-26 17:03:14.1030|Connected to 6 bootnodes, 6 trusted/persisted nodes|
2019-10-26 17:03:14.9655|Sync not started yet... 2s|
2019-10-26 17:03:15.9655|Sync not started yet... 3s|
2019-10-26 17:03:16.9667|Sync not started yet... 4s|
2019-10-26 17:03:17.9663|Sync not started yet... 5s|
2019-10-26 17:03:18.9660|Sync not started yet... 6s|
```
The syncing goes on and on
```
2019-10-26 17:07:13.9650|Sync peers - Initialized: 0 | All: 0 | Max: 50|
2019-10-26 17:07:13.9650|Sync peers 0(0)/50, searching for peers to sync with...|
```

**Comment by tkstanczak** [comment]
Three things for now that can address is without additional logging:

0) upgrade to 1.1.4 (I will deploy the package tomorrow around noon for
1.1.4) as it has a fix to Parity pre-EIP8 handshake format handling which
should improve the nodes connectivity

1) adding static nodes file in the data folder can help

2) letting it run for much longer until it finds volta nodes that are not
busy

---

other possibility is that there is something specifiic in the volta config
that we have missed so far

We can try to build a volta specific AuRa setup locally to check
connections between Parity and Nethermind.

Currently we have Sokol, POA Core and xDai running fine and finding nodes.

**Comment by tkstanczak** [comment]
actually @ngyam 1.1.4 is ready here:
https://github.com/NethermindEth/nethermind/releases/tag/1.1.4

Also before starting again can you delete the whole database folder (nethermind_db) (possibly you still have the corrupted database from before the fix)

**Comment by ngyam** [comment]
thanks, i will try with 1.1.4 and let it run for a few hours

**Comment by LukaszRozmej** [comment]
@ngyam I am trying to sync Volta myself now, my findings:
1. We are finding a lot of nodes with incorrect genesis hash and have a hard time to find correct ones, I've checked and parity has this issue too to some extent but generally its easier there, it managed to find some correct eventually. This took variable amount of time on multiple runs (1-15 min)

2. Please add those parameters to chainspec:

    "eip152Transition": "0xFFFFFFFF",
    "eip1108Transition": "0xFFFFFFFF",
    "eip1344Transition": "0xFFFFFFFF",
    "eip1884Transition": "0xFFFFFFFF",
    "eip2028Transition": "0xFFFFFFFF",
    "eip2200Transition": "0xFFFFFFFF"

This is currently needed to disable Istanbul related Eip's on non-Istanbul chains. Without it we will have some gas spendure conflicts and hash issues.

**Comment by LukaszRozmej** [comment]
I've managed to sync Volta network, so I am closing the issue.

2019-10-27 21:40:26.3695|INFO|15|Discovered a new block   2947763 20:40:25 (21546b...acb864), tx count: 0 sealed by 0x88b20a88a6233d1eacd84fb59a0250f4227b6379, sent by 54.93.159.98:30303 
2019-10-27 21:40:26.3792|INFO|14|DEBUG Full Sync | Processed    2947763 |    5 096ms, mgasps    0,00 total   15,43, tps    0,00 total  160,74, bps    0,20 total   34,96, recv queue 0, proc queue 0 
2019-10-27 21:40:31.3450|INFO|15|Discovered a new block   2947764 20:40:30 (b81334...c0d652), tx count: 0 sealed by 0xd13b66e4027cf454a4a1918394425b9969b99dab, sent by 54.93.159.98:30303 
2019-10-27 21:40:31.3549|INFO|14|DEBUG Full Sync | Processed    2947764 |    4 976ms, mgasps    0,00 total   15,42, tps    0,00 total  160,70, bps    0,20 total   34,96, recv queue 0, proc queue 0
