### ISSUE TITLE
Connection state corruption in Kestrel

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#966]
2019-11-05 22:11:01.8210|75|Connection id "0HLR1EROQTJJG", Request id "0HLR1EROQTJJG:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8247|75|Connection id "0HLR1EROQTJJI", Request id "0HLR1EROQTJJI:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8247|75|Connection id "0HLR1EROQTJJJ", Request id "0HLR1EROQTJJJ:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8247|75|Connection id "0HLR1EROQTJJL", Request id "0HLR1EROQTJJL:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8247|75|Connection id "0HLR1EROQTJJM", Request id "0HLR1EROQTJJM:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8210|42|Connection id "0HLR1EROQTJJH", Request id "0HLR1EROQTJJH:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8294|7|Connection id "0HLR1EROQTJJP", Request id "0HLR1EROQTJJP:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8294|68|Connection id "0HLR1EROQTJJQ", Request id "0HLR1EROQTJJQ:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8294|35|Connection id "0HLR1EROQTJJT", Request id "0HLR1EROQTJJT:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8294|70|Connection id "0HLR1EROQTJJU", Request id "0HLR1EROQTJJU:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8328|47|Connection id "0HLR1EROQTJK1", Request id "0HLR1EROQTJK1:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8328|39|Connection id "0HLR1EROQTJK2", Request id "0HLR1EROQTJK2:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8328|47|Connection id "0HLR1EROQTJK3", Request id "0HLR1EROQTJK3:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8328|39|Connection id "0HLR1EROQTJK4", Request id "0HLR1EROQTJK4:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8328|47|Connection id "0HLR1EROQTJK5", Request id "0HLR1EROQTJK5:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8328|39|Connection id "0HLR1EROQTJK6", Request id "0HLR1EROQTJK6:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8328|49|Connection id "0HLR1EROQTJK9", Request id "0HLR1EROQTJK9:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8367|39|Connection id "0HLR1EROQTJK8", Request id "0HLR1EROQTJK8:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8328|48|Connection id "0HLR1EROQTJKA", Request id "0HLR1EROQTJKA:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8367|68|Connection id "0HLR1EROQTJJS", Request id "0HLR1EROQTJJS:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8367|48|Connection id "0HLR1EROQTJKN", Request id "0HLR1EROQTJKN:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8367|48|Connection id "0HLR1EROQTJKP", Request id "0HLR1EROQTJKP:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8367|49|Connection id "0HLR1EROQTJKL", Request id "0HLR1EROQTJKL:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8367|7|Connection id "0HLR1EROQTJJR", Request id "0HLR1EROQTJJR:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8294|70|Connection id "0HLR1EROQTJJV", Request id "0HLR1EROQTJJV:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8410|70|Connection id "0HLR1EROQTJKT", Request id "0HLR1EROQTJKT:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8410|7|Connection id "0HLR1EROQTJKS", Request id "0HLR1EROQTJKS:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8410|70|Connection id "0HLR1EROQTJKU", Request id "0HLR1EROQTJKU:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8410|7|Connection id "0HLR1EROQTJKV", Request id "0HLR1EROQTJKV:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8410|70|Connection id "0HLR1EROQTJL1", Request id "0HLR1EROQTJL1:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8410|7|Connection id "0HLR1EROQTJL2", Request id "0HLR1EROQTJL2:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8410|70|Connection id "0HLR1EROQTJL3", Request id "0HLR1EROQTJL3:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8367|39|Connection id "0HLR1EROQTJKM", Request id "0HLR1EROQTJKM:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8453|39|Connection id "0HLR1EROQTJL8", Request id "0HLR1EROQTJL8:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8453|47|Connection id "0HLR1EROQTJK7", Request id "0HLR1EROQTJK7:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8453|39|Connection id "0HLR1EROQTJL9", Request id "0HLR1EROQTJL9:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8453|47|Connection id "0HLR1EROQTJLA", Request id "0HLR1EROQTJLA:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8453|39|Connection id "0HLR1EROQTJLB", Request id "0HLR1EROQTJLB:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8453|47|Connection id "0HLR1EROQTJLC", Request id "0HLR1EROQTJLC:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8453|39|Connection id "0HLR1EROQTJLE", Request id "0HLR1EROQTJLE:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.
2019-11-05 22:11:01.8294|35|Connection id "0HLR1EROQTJK0", Request id "0HLR1EROQTJK0:00000001": An unhandled exception was thrown by the application.|Unexpected end of request content.

**Comment by tkstanczak** [comment]
2019-11-08 23:56:11.0407|ERROR|34|JsonWebAPI.Microsoft.AspNetCore.Server.Kestrel|Connection id "0HLR4KO5VLB7R", Request id "0HLR4KO5VLB7R:00000001": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync()
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass2_0.<<Configure>b__2>d.MoveNext() in /root/src/nethermind/src/Nethermind/Nethermind.Runner/Startup.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2019-11-08 23:56:11.0407|ERROR|34|JsonWebAPI.Microsoft.AspNetCore.Server.Kestrel|Connection id "0HLR4KO5VLB7S", Request id "0HLR4KO5VLB7S:00000001": An unhandled exception was thrown by the application. Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync()
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Nethermind.Runner.Startup.<>c__DisplayClass2_0.<<Configure>b__2>d.MoveNext() in /root/src/nethermind/src/Nethermind/Nethermind.Runner/Startup.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
