### ISSUE TITLE
Get_logs failure shortly after restarting the node

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#968]
2019-11-05 22:16:55.0336|7|Error during method execution, request: ID 2635, version 2.0, eth_getLogs({
  "fromBlock": "0x65c64a",
  "toBlock": "0x65c64a",
  "topics": [
    "0x127650bcfb0ba017401abe4931453a405140a8fd36fece67bae2db174d3fdd63"
  ],
  "address": "0x7301cfa0e1756b71869e93d4e4dca5c7d0eb0aa6"
})|Object reference not set to an instance of an object.
2019-11-05 22:16:55.0865|7|Failed to respond to eth_getLogs System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Blockchain.Find.LogFinder.FindLogs(LogFilter filter) in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs:line 45
   at Nethermind.Facade.BlockchainBridge.GetLogs(FilterBlock fromBlock, FilterBlock toBlock, Object address, IEnumerable`1 topics) in /root/src/nethermind/src/Nethermind/Nethermind.Facade/BlockchainBridge.cs:line 269
   at Nethermind.JsonRpc.Modules.Eth.EthModule.eth_getLogs(Filter filter) in /root/src/nethermind/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModule.cs:line 572|

**Comment by tkstanczak** [comment]
the db was lost

**Comment by LukaszRozmej** [comment]
Still maybe we should work on error message?
