### ISSUE TITLE
eth_call() - resolve node issue

### ISSUE THREAD

**Issue by spetz** [NethermindEth/nethermind#978]
```
2019-11-08 10:55:35.5457|Error during method execution, request: ID 0, version 2.0, eth_call({
  "data": "0x70a082310000000000000000000000009045ffa44f37f372e40e3b9a401a663f390622d7",
  "to": "0x225bc3affc1da39bd3cb2100c74a41c62310d1e1"
},0x146627)|System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Store.TrieNode.ResolveNode(PatriciaTree tree, Boolean allowCaching) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\TrieNode.cs:line 215
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 438
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 324
   at Nethermind.Store.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak rootHash) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 303
   at Nethermind.Store.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 226
   at Nethermind.Store.StorageTree.Get(UInt256 index) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\StorageTree.cs:line 78
   at Nethermind.Store.StorageProvider.LoadFromTree(StorageAddress storageAddress) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\StorageProvider.cs:line 386
   at Nethermind.Store.StorageProvider.GetCurrentValue(StorageAddress storageAddress) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\StorageProvider.cs:line 362
   at Nethermind.Store.StorageProvider.Get(StorageAddress storageAddress) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\StorageProvider.cs:line 70
   at Nethermind.Evm.VirtualMachine.ExecuteCall(EvmState evmState, Byte[] previousCallResult, Byte[] previousCallOutput, UInt256& previousCallOutputDestination, IReleaseSpec spec) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Evm\VirtualMachine.cs:line 1848
   at Nethermind.Evm.VirtualMachine.Run(EvmState state, ITxTracer txTracer) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Evm\VirtualMachine.cs:line 147
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean readOnly) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Evm\TransactionProcessor.cs:line 221
   at Nethermind.Evm.TransactionProcessor.CallAndRestore(Transaction transaction, BlockHeader block, ITxTracer txTracer) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Evm\TransactionProcessor.cs:line 56
   at Nethermind.Facade.BlockchainBridge.Call(BlockHeader blockHeader, Transaction transaction) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Facade\BlockchainBridge.cs:line 189
   at Nethermind.JsonRpc.Modules.Eth.EthModule.eth_call(TransactionForRpc transactionCall, BlockParameter blockParameter) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.JsonRpc\Modules\Eth\EthModule.cs:line 297
```

**Comment by spetz** [comment]
```
2019-11-08 10:55:35.5457|Failed to respond to eth_call Nethermind.Store.StateException: Unable to resolve node 0x1a1c7566ee3a929ea8c804f2ddbeee47dd3de930b2781fc10f50ddc9996faafa
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Nethermind.Core.Encoding.RlpStream.ReadByte() in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Core\Encoding\RlpStream.cs:line 567
   at Nethermind.Core.Encoding.RlpStream.DecodeByteArraySpan() in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Core\Encoding\RlpStream.cs:line 901
   at Nethermind.Store.TrieNode.ResolveNode(PatriciaTree tree, Boolean allowCaching) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\TrieNode.cs:line 215
   --- End of inner exception stack trace ---
   at Nethermind.Store.TrieNode.ResolveNode(PatriciaTree tree, Boolean allowCaching) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\TrieNode.cs:line 215
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 438
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 324
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 438
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 324
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 438
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 324
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 438
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 324
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 438
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 324
   at Nethermind.Store.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak rootHash) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 303
   at Nethermind.Store.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 226
   at Nethermind.Store.StateProvider.GetState(Address address) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\StateProvider.cs:line 549
   at Nethermind.Store.StateProvider.GetAndAddToCache(Address address) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\StateProvider.cs:line 568
   at Nethermind.Store.StateProvider.GetCodeHash(Address address) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\StateProvider.cs:line 247
   at Nethermind.Evm.VirtualMachine.GetCachedCodeInfo(Address codeSource) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Evm\VirtualMachine.cs:line 372
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean readOnly) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Evm\TransactionProcessor.cs:line 219
   at Nethermind.Evm.TransactionProcessor.CallAndRestore(Transaction transaction, BlockHeader block, ITxTracer txTracer) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Evm\TransactionProcessor.cs:line 57
   at Nethermind.Facade.BlockchainBridge.Call(BlockHeader blockHeader, Transaction transaction) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Facade\BlockchainBridge.cs:line 190
   at Nethermind.JsonRpc.Modules.Eth.EthModule.eth_call(TransactionForRpc transactionCall, BlockParameter blockParameter) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.JsonRpc\Modules\Eth\EthModule.cs:line 297
```

**Comment by spetz** [comment]
```
2019-11-08 10:55:35.5457|Failed to respond to eth_call Nethermind.Store.StateException: Unable to resolve node 0xcae845ccabdfd51171f6207775b2532b03d660cb92c5d6ea0fbc3c427a4b3d5d
 ---> System.InvalidOperationException: Unexpected number of items = 15 when decoding a node
   at Nethermind.Store.TrieNode.ResolveNode(PatriciaTree tree, Boolean allowCaching) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\TrieNode.cs:line 215
   --- End of inner exception stack trace ---
   at Nethermind.Store.TrieNode.ResolveNode(PatriciaTree tree, Boolean allowCaching) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\TrieNode.cs:line 215
   at Nethermind.Store.PatriciaTree.TraverseBranch(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 438
   at Nethermind.Store.PatriciaTree.TraverseNode(TrieNode node, TraverseContext traverseContext) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 324
   at Nethermind.Store.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak rootHash) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 303
   at Nethermind.Store.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\PatriciaTree.cs:line 226
   at Nethermind.Store.StorageTree.Get(UInt256 index) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\StorageTree.cs:line 78
   at Nethermind.Store.StorageProvider.LoadFromTree(StorageAddress storageAddress) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\StorageProvider.cs:line 386
   at Nethermind.Store.StorageProvider.GetCurrentValue(StorageAddress storageAddress) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\StorageProvider.cs:line 362
   at Nethermind.Store.StorageProvider.Get(StorageAddress storageAddress) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Store\StorageProvider.cs:line 70
   at Nethermind.Evm.VirtualMachine.ExecuteCall(EvmState evmState, Byte[] previousCallResult, Byte[] previousCallOutput, UInt256& previousCallOutputDestination, IReleaseSpec spec) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Evm\VirtualMachine.cs:line 1848
   at Nethermind.Evm.VirtualMachine.Run(EvmState state, ITxTracer txTracer) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Evm\VirtualMachine.cs:line 147
   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean readOnly) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Evm\TransactionProcessor.cs:line 221
   at Nethermind.Evm.TransactionProcessor.CallAndRestore(Transaction transaction, BlockHeader block, ITxTracer txTracer) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Evm\TransactionProcessor.cs:line 57
   at Nethermind.Facade.BlockchainBridge.Call(BlockHeader blockHeader, Transaction transaction) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.Facade\BlockchainBridge.cs:line 190
   at Nethermind.JsonRpc.Modules.Eth.EthModule.eth_call(TransactionForRpc transactionCall, BlockParameter blockParameter) in D:\Workspace\Nethermind\nethermind\src\Nethermind\Nethermind.JsonRpc\Modules\Eth\EthModule.cs:line 297
```
