### ISSUE TITLE
Index out of range on eth_call

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#987]
2019-11-08 23:55:49.6080|ERROR|28|JsonRpc.JsonRpcService|Error while parsing parameters System.IndexOutOfRangeException: Index was outside the bounds of the array.
2019-11-08 23:55:49.6210|ERROR|28|JsonRpc.JsonRpcService|Incorrect JSON RPC parameters when calling eth_call: {
2019-11-08 23:55:49.6210|ERROR|28|JsonRpc.JsonRpcProcessor|Failed to respond to eth_call Incorrect parameters
2019-11-08 23:55:51.2377|ERROR|28|JsonRpc.JsonRpcService|Error while parsing parameters System.IndexOutOfRangeException: Index was outside the bounds of the array.
2019-11-08 23:55:51.2377|ERROR|28|JsonRpc.JsonRpcService|Incorrect JSON RPC parameters when calling eth_call: {
2019-11-08 23:55:51.2377|ERROR|28|JsonRpc.JsonRpcProcessor|Failed to respond to eth_call Incorrect parameters

**Comment by tkstanczak** [comment]
2019-11-08 23:55:51.2377|INFO|28|JsonRpc.JsonRpcService|Executing JSON RPC call eth_call with params {
2019-11-08 23:55:51.2377|ERROR|28|JsonRpc.JsonRpcService|Error while parsing parameters System.IndexOutOfRangeException: Index was outside the bounds of the array.
2019-11-08 23:55:51.2377|ERROR|28|JsonRpc.JsonRpcService|Incorrect JSON RPC parameters when calling eth_call: {
2019-11-08 23:55:51.2377|DEBUG|28|JsonRpc.JsonRpcService|Sending error response, method: eth_call, id: 17, errorType: InvalidParams, message: Incorrect parameters
2019-11-08 23:55:51.2377|ERROR|28|JsonRpc.JsonRpcProcessor|Failed to respond to eth_call Incorrect parameters

**Comment by tkstanczak** [comment]
@matilote any way to find out what was the exact content of the requests?

**Comment by tkstanczak** [comment]
2019-11-08 23:55:51.2377|INFO|28|JsonRpc.JsonRpcService|Executing JSON RPC call eth_call with params {
  "data": "0x313ce567",
  "to": "ethereum"
},latest
2019-11-08 23:55:51.2377|ERROR|28|JsonRpc.JsonRpcService|Error while parsing parameters System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Nethermind.Core.Extensions.Bytes.FromHexString(String hexString) in /root/src/nethermind/src/Nethermind/Nethermind.Core/Extensions/Bytes.cs:line 752
   at Nethermind.Core.Json.AddressConverter.ReadJson(JsonReader reader, Type objectType, Address existingValue, Boolean hasExistingValue, JsonSerializer serializer) in /root/src/nethermind/src/Nethermind/Nethermind.Core/Json/AddressConverter.cs:line 42
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Nethermind.JsonRpc.JsonRpcService.DeserializeParameters(ParameterInfo[] expectedParameters, String[] providedParameters, Int32 missingParamsCount) in /root/src/nethermind/src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs:line 206
2019-11-08 23:55:51.2377|ERROR|28|JsonRpc.JsonRpcService|Incorrect JSON RPC parameters when calling eth_call: {
  "data": "0x313ce567",
  "to": "ethereum"
}, latest

**Comment by tkstanczak** [comment]
to ethereum is definitely incorrect but it would be nicer to send a valid error message saying that parameters were incorrect for Address type?
